---
sidebar: sidebar 
permalink: rhhc/rhhc-pm-solution.html 
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP 
summary:  
---
= マネージドRed Hat OpenShiftコンテナプラットフォームワークロードを使用したNetAppソリューション
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
お客様は、「クラウド生まれ」の場合もあれば、一部のワークロードやすべてのワークロードをデータセンターからクラウドに移行する準備ができた時点で、最新化に向けた取り組みを進めている場合もあります。ワークロードの実行に、プロバイダが管理するOpenShiftコンテナとプロバイダが管理するネットアップストレージをクラウドで使用することもできます。コンテナワークロードに対応した本番環境を成功させるためには、マネージドRed Hat OpenShiftコンテナクラスタを計画し、クラウドに導入する必要があります。NetAppは、業界をリードする3つのパブリッククラウドすべてで、マネージドRed Hatソリューション向けのフルマネージドストレージ製品を提供しています。

* Amazon FSx for NetApp ONTAP（FSx ONTAP）*

FSx ONTAPは、AWSでのコンテナ導入にデータ保護、信頼性、柔軟性を提供します。Tridentは、お客様のステートフルアプリケーション向けに永続的FSx ONTAPストレージを利用するための動的ストレージプロビジョニングツールとして機能します。

ROSAは、コントロールプレーンノードが複数のアベイラビリティゾーンに分散した状態でHAモードで導入できるため、FSx ONTAP は、高可用性を提供し、AZの障害から保護するマルチAZオプションを使用してプロビジョニングすることもできます。

* Google Cloud NetApp Volumes *

Red Hat OpenShift Dedicatedは、ハイブリッドクラウド全体でアプリケーションを迅速に構築、導入、拡張できる、フルマネージドのアプリケーションプラットフォームです。Google Cloud NetApp Volumeは永続ボリュームを提供し、ONTAPのエンタープライズデータ管理機能のフルスイートをGoogle CloudのOpenShift環境に提供します。
