---
sidebar: sidebar 
permalink: rhhc/rhhc-sm-solution.html 
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP 
summary:  
---
= NetApp解決策 とRed Hat OpenShift Containerプラットフォームのワークロードをハイブリッドクラウドで運用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
お客様は、一部のワークロードまたはすべてのワークロードをデータセンターからクラウドに移行する準備が整った時点で、モダナイゼーションに移行する可能性があります。お客様は、さまざまな理由から、クラウドで自己管理型OpenShiftコンテナと自己管理型ネットアップストレージを使用することができます。データセンターからコンテナワークロードを移行するための本番環境向け環境を成功させるには、Red Hat OpenShiftコンテナプラットフォーム（OCP）をクラウドに計画して導入する必要があります。OCPクラスタは、データセンターのVMwareまたはベアメタルに導入し、クラウド環境のAWS、Azure、Google Cloudに導入できます。

NetApp Cloud Volumes ONTAP ストレージは、AWS、Azure、Google Cloudでのコンテナ導入にデータ保護、信頼性、柔軟性を提供します。Astra Tridentは、お客様のステートフルアプリケーション向けに永続的Cloud Volumes ONTAP ストレージを利用するための動的ストレージプロビジョニングツールとして機能します。Astra Control Centerを使用すると、データ保護、移行、ビジネス継続性など、ステートフルアプリケーションに求められる多くのデータ管理要件をオーケストレーションできます。



== Astra Control Centerを使用したハイブリッドクラウドでのOpenShiftコンテナワークロード向けのデータ保護と移行解決策

オンプレミスとAWSのイメージ：：rhhc-self-managed-aws.png[]

オンプレミスとGoogle Cloudのイメージ：：rhhc-self-managed-gcp.png[]

オンプレミスとAzure Cloudのイメージ：：rhhc-self-managed-azure.png[]
