---
sidebar: sidebar 
permalink: rhhc/rhhc-value-prop.html 
keywords: NetApp Solutions, hybrid cloud, container workloads, containers, Red Hat OpenShift, RedHat OpenShift, VMware, ROSA, ACC, Trident Protect, Advanced Cluster Management, ACM, Hub Cluster 
summary:  
---
= Red Hat OpenShift Containerワークロード向けネットアップハイブリッドマルチクラウドソリューションの価値提案
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ほとんどのお客様は、既存のインフラがない状態でKubernetesベースの環境を構築し始めたばかりではありません。おそらく、大規模なVMware環境などで、エンタープライズアプリケーションのほとんどを仮想マシンで実行している従来型のIT環境です。その後、最新のアプリケーション開発チームのニーズを満たすために、小規模なコンテナベースの環境の構築を開始します。これらのイニシアチブは通常、小規模なものから始まり、チームがこれらの新しいテクノロジやスキルを学習し、それらを採用することの多くの利点を認識し始めるにつれて、より普及し始めます。ネットアップなら両方の環境のニーズに対応できるというのは、お客様にとって朗報です。Red Hat OpenShiftを使用したこのハイブリッドマルチクラウド向けソリューションセットは、ネットアップのお客様がインフラや組織全体を刷新することなく、最新のクラウドテクノロジとサービスを採用できるよう支援します。お客様のアプリケーションやデータがオンプレミスでホストされている場合でも、クラウドでホストされている場合でも、仮想マシンで実行されている場合でも、コンテナで実行される場合でも、ネットアップは一貫したデータ管理、保護、セキュリティ、モビリティを提供します。これらの新しいソリューションにより、ネットアップが数十年にわたってオンプレミスのデータセンター環境で提供してきたのと同じ価値を、企業全体のデータホライズン全体で利用できるようになります。ツールの再構築、新しいスキルの習得、新しいチームの構築に多額の投資を行う必要はありません。ネットアップは、お客様がクラウドへの移行のどの段階にいるかにかかわらず、これらのビジネス上の課題を解決できるよう、適切に位置付けられています。

Red Hat OpenShiftを使用したネットアップハイブリッドマルチクラウド：

* ネットアップベースのストレージソリューションでRed Hat OpenShiftを使用する場合に、お客様がデータとアプリケーションを管理、保護、保護、保護、移行するための最良の方法を実証する事前検証済みの設計と手法をお客様に提供します。
* VMware環境、ベアメタルインフラ、またはその両方でネットアップストレージを使用してRed Hat OpenShiftを実行しているお客様向けのベストプラクティスを紹介します。
* オンプレミス環境とクラウド環境、およびその両方を使用するハイブリッド環境の両方について、戦略とオプションを説明する。

