---
sidebar: sidebar 
permalink: xcp/xcp-bp-best-practice-guidelines-and-recommendations.html 
keywords: best practices, guidelines, recommendations, IMT 
summary: ここでは、 NetApp XCP を使用してデータを移行する際のベストプラクティス、ガイドライン、推奨事項について説明します。 
---
= ベストプラクティスのガイドラインと推奨事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
* IMT でサポートされている XCP クライアントオペレーティングシステムを使用します。サポートされている IMT クライアントは、ネットアップで認定されています。
* LinuxオペレーティングシステムでXCPをrootユーザーとして実行して移行を実行します。XCPコマンドはsudoユーザーとして実行できますが、XCPではサポートされていません。
* クライアントごとに 1 つの XCP インスタンスのみを実行します。技術的には、同じホスト上で異なる場所から複数のインスタンスの XCP を実行できますが、これはサポートされていません。実際、多数のインスタンスを実行すると、障害が発生する可能性があります。
* XCP NFSはライブソースデータセットから移行でき、この構成はサポートされています。ライブソースデータセットからのXCP SMB移行はサポートされていないため、失敗する可能性があります。
* 新しい Snapshot は、増分同期ごとに別の名前を使用して作成することを推奨します。これにより、障害発生時に Snapshot 名に基づいて差分移行パスを簡単に作成できます。
* Snapshot ベースのマイグレーションを実行する場合は、カットオーバーまで Snapshot ベースのマイグレーションを続行することを推奨します。
* ファイル数が 1 、 000 万を超え、増分データの変更率が 50% を超える場合は、インストールおよび管理ガイドでの最小推奨値よりもコア数とメモリ容量を増やすことを推奨します。

