---
sidebar: sidebar 
permalink: xcp/xcp-bp-creating-a-csv-file-from-smb-cifs-share.html 
keywords: csv, data dump 
summary: このセクションのコマンドでは、 CSV 形式でデータがダンプされます。サイズ列を合計してデータの合計サイズを確認できます。 
---
= SMB / CIFS 共有からの CSV ファイルの作成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:xcp-bp-specific-date-based-scan-and-copy-of-data.html["Previous ：日付ベースの特定のスキャンとデータのコピー。"]

次に、 CSV 形式でデータをダンプするコマンドを示します。サイズ列を合計してデータの合計サイズを確認できます。

....
xcp scan -match "((now-x.atime) / 3600) > 31*day" -fmt "'{}, {}, {}, {}'.format(relpath, name, strftime(x.atime, '%y-%m-%d-%H:%M:%S'), humanize_size(size))" -preserve-atime  >file.csv
....
次のような出力が表示されます。

....
erase\report_av_fp_cdot_crosstab.csvreport_av_fp_cdot_crosstab.csv20-01-29-10:26:2449.6MiB
....
3 つのサブディレクトリの深さまでスキャンし ' ソート順を指定するには 'XCP -du' コマンドを実行して ' 各ディレクトリ・レベルで 3 つのサブディレクトリの深さまでサイズをダンプします

....
./xcp  scan -du -depth 3 NFS_Server_IP:/source_vol
 
....
ソートするには、情報を CSV ファイルにダンプして情報をソートします。

....
xcp scan -match “type == d” -depth 3 -fmt "'{}, {}, {}, {}'.format(name, relpath, size)" NFS_Server_IP:/share > directory_report.csv
....
これは '-fmt' コマンドを使用するカスタム・レポートですすべてのディレクトリがスキャンされ、ディレクトリの名前、パス、およびサイズが CSV ファイルにダンプされます。サイズ列は、スプレッドシートアプリケーションでソートできます。

link:xcp-bp-data-migration-from-7-mode-to-ontap.html["次のステップ： 7-Mode から ONTAP へのデータ移行"]
