---
sidebar: sidebar 
permalink: xcp/xcp-bp-performance-tuning.html 
keywords: performance, tuning, operations, windows 
summary: ここでは、 XCP 処理のパフォーマンス向上に役立つチューニングパラメータをいくつか紹介します。 
---
= パフォーマンス調整
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションでは、 XCP 処理のパフォーマンスを向上させるために役立つチューニングパラメータをいくつか説明します。

* 拡張性を高め、ワークロードを複数の XCP インスタンスに分散させるには、移行とデータ転送用に各 XCP インスタンスのサブフォルダを分割します。
* XCP では最大 CPU リソースを使用できます。 CPU コア数が多いほど、パフォーマンスが向上します。そのため、 XCP サーバに追加の CPU が必要です。テストでは 128GB の RAM と 48 個のコア CPU を使用し、 8 倍の CPU と 8 GB の RAM に比べてパフォーマンスが向上しました。
* オプションを指定したXCPコピー `-parallel`は、CPUの数に基づいています。ほとんどの XCP データ転送および移行処理には、デフォルトのパラレルスレッド数（ 7 ）で十分な場合があります。XCP Windows のデフォルトでは、並列プロセスの数は CPU の数と同じです。オプションの最大数 `-parallel`は、コア数以下にする必要があります。
* データ転送の開始には 10GbE が適しています。ただし、 25GbE と 100GbE でテストした結果、データ転送が向上し、大容量のファイルサイズのデータ転送に推奨されています。
* Azure NetApp Files の場合、パフォーマンスはサービスレベルによって異なります。詳細については、次の表を参照してください。この表には、 Azure NetApp Files のサービスレベルとパフォーマンスの詳細が表示されます。


|===
| サービスレベル | 標準 | プレミアム | ウルトラ 


| スループット | 1 テラバイトあたり 16mbps | TB あたり 64MBps | TB あたり 128MBps 


| ワークロードのタイプ | 汎用ファイル共有、 E メール、 Web | BMS 、データベース、およびアプリケーション | レイテンシの影響を受けやすいアプリケーション 


| パフォーマンスの説明 | 標準パフォーマンス： 1TB あたり 1 、 000 IOPS （ 16K I/O ）と TB あたり 16mbps | 優れたパフォーマンス– TB あたり 4 、 000 IOPS （ 16 、 000 I/O ）、 TB あたり 64MBps | 卓越したパフォーマンス： TB あたり 8 、 000 IOPS （ 16 、 000 I/O ）、 128MBps / TB 
|===
スループットとワークロードのタイプに基づいて適切なサービスレベルを選択する必要があります。ほとんどのお客様は Premium レベルから始めて、ワークロードに基づいてサービスレベルを変更します。
