---
sidebar: sidebar 
permalink: data-analytics/confluent-kafka-introduction.html 
keywords: tr-4912, tr4912, 4912, introduction, best practices, Kafka, confluent 
summary: このドキュメントでは、ネットアップのストレージコントローラで Kafka を使用する場合のベストプラクティスのガイドラインを説明しています。 
---
= TR-4912 ：『 Best Practices guidelines for ConFluent Kafka Tiered Storage with NetApp 』
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


カーティケヤンナガリングアム、ランケシュクマー

Apache Kafka は、 1 日に数兆ものイベントを処理できる、コミュニティで分散されたイベントストリーミングプラットフォームです。Kafka は、当初はメッセージングキューとして構築され、分散コミットログの抽象化に基づいています。Kafka は、 2011 年に LinkedIn で作成されオープンソースとなって以来、メッセージキューから本格的なイベントストリーミングプラットフォームへと進化してきました。Conluent Platform で Kafka のディストリビューションを提供します。ConFluent Platform は、運用環境の運用者と開発者の両方のストリーミングエクスペリエンスを大規模に向上させるように設計された、追加のコミュニティと商用機能によって Kafka を改善します。

本ドキュメントでは、ネットアップのストレージコントローラで Kafka を使用する場合のベストプラクティスについて、次のコンテンツを提供します。

* Kafka 認定とネットアップのストレージコントローラ– StorageGRID とが競合します
* Kafka のパフォーマンステスト
* ネットアップストレージシステムで Kafka を使用する場合のベストプラクティスのガイドラインを参照してください


link:confluent-kafka-solution.html["次へ：解決策"]
