---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-solution.html 
keywords: solution, architecture, details, hardware, software 
summary: このセクションでは、dremio認証に使用されるハードウェアとソフトウェアについて説明します。この情報は、NetAppストレージを使用したdremioの導入に該当します。 
---
= 解決策の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Hybrid Iceberg Lakehouseソリューションは、データレイクのお客様が直面する課題に対処する独自のメリットを提供します。Dremioの統合されたLakehouseプラットフォームとNetApp ONTAP、StorageGRID、NetAppクラウドソリューションを活用することで、企業はビジネスオペレーションに大きな価値を追加できます。このソリューションは、NetAppソースを含む複数のデータソースへのアクセスを提供するだけでなく、全体的な分析パフォーマンスを向上させ、企業がビジネスの成長につながるビジネスインサイトを促進するのに役立ちます。



== ネットアップの概要

* ONTAPやStorageGRIDなどのNetAppの製品は、ストレージとコンピューティングの分離を可能にし、特定の要件に基づいて最適なリソース使用率を実現します。この柔軟性により、NetAppストレージソリューションを使用してストレージを個別に拡張できます。
* ネットアップのストレージコントローラを活用することで、NFSプロトコルとS3プロトコルを使用してベクトルデータベースに効率的にデータを提供できます。これらのプロトコルを使用すると、顧客データの保存とベクターデータベースインデックスの管理が容易になり、ファイルメソッドやオブジェクトメソッドを使用してデータの複数のコピーにアクセスする必要がなくなります。
* NetApp ONTAPは、AWS、Azure、Google Cloudなどの主要なクラウドサービスプロバイダでNASとオブジェクトストレージをネイティブにサポートします。この広範な互換性により、シームレスな統合が保証され、お客様のデータモビリティ、グローバルなアクセス性、ディザスタリカバリ、動的な拡張性、および高パフォーマンスが実現します。




=== StorageGRID

業界をリードするネットアップのオブジェクトストレージStorageGRIDは、データの自動配置、柔軟な導入オプション、階層型イレイジャーコーディングによる卓越したデータ保持性を実現する強力なポリシーエンジンを提供します。数十億のオブジェクトとペタバイト規模のデータを単一のネームスペースでサポートする拡張性に優れたアーキテクチャを備えています。ハイブリッドクラウドの統合が可能になり、主要なクラウドプラットフォームへのデータ階層化が可能になります。2019年のIDC MarketScape Worldwide Object-Based Vendor Assessmentでリーダーに位置付けられました。

さらに、StorageGRIDは、Software-Definedオブジェクトストレージ、地理的冗長性、マルチサイト機能により、大規模な非構造化データの管理に優れています。ポリシーベースの情報ライフサイクル管理が組み込まれており、ミラーリングや検索などのクラウド統合機能を提供します。Common Criteria、NF203 Digital Safe Component、ISO/IEC 25051、KPMG、Cohasset Compliance Assessmentなど、さまざまな認証を取得しています。

要約すると、NetApp StorageGRIDは、大規模な非構造化データを効率的に管理するための強力な機能、拡張性、ハイブリッドクラウド統合、コンプライアンス認定を提供します。



=== NetApp ONTAP

NetApp ONTAPは、幅広いエンタープライズ機能を提供する堅牢なストレージソリューションです。Snapshotも含まれています。Snapshotを使用すると、アプリケーションと整合性があり、改ざんがない瞬時のバックアップを作成できます。SnapRestoreでは、バックアップをオンデマンドでほぼ瞬時にリストアできます。SnapMirrorには、統合されたリモートバックアップ機能とディザスタリカバリ機能が用意されています。また、Autonomous Ransomware Protection（ARP）も組み込まれているため、複数管理者による検証、FIPS認定による保管データの暗号化、転送中データの暗号化、多要素認証（MFA）、ロールベースアクセス制御（RBAC）などの機能によってデータセキュリティを確保できます。包括的なロギング、監査、オンボードと外部のキー管理、セキュアパージ、複数のテナントのセキュアな管理により、データのセキュリティとコンプライアンスがさらに強化されます。

NetApp ONTAPにはも搭載されています。SnapLockは、高い整合性、パフォーマンス、保持率を維持しながら、総所有コストを抑えながら、規制に準拠したデータ保持を実現します。NetApp ONTAP®9と完全に統合されており、悪意のある行為、不正な管理者、ランサムウェアからの保護を提供します。

このソリューションには、転送中データと保管データの暗号化、多要素管理アクセス、複数管理者検証のためのNSE / NVE暗号化が含まれています。Active IQは、AIに基づく予測分析と修正措置を提供すると同時に、QoSによってQuality of Service（QoS；サービス品質）ワークロードを管理します。管理と自動化の統合は、sysmgr /gui/cli/apiを通じて直感的に実行できます。FabricPoolはデータの自動階層化を可能にし、インラインデータ圧縮、重複排除、コンパクションによる効率化を実現します。NetAppでは、ワークロード効率化目標の達成をお客様に無償で保証します。

NetApp ONTAPは、NVMe/FC、FC、NVMe/TCP、iSCSI、NFS、SMB、S3などのさまざまなプロトコルをサポートし、ユニファイドストレージソリューションです。全体的に、NetApp ONTAPは広範なエンタープライズ機能、堅牢なセキュリティ、コンプライアンス、効率性、汎用性を提供し、多様なストレージニーズに対応します。



== Dremioの概要

Dremioは、セルフサービス分析とAIのための統合されたLakehouseプラットフォームです。Dremio統合分析プラットフォームは、従来のデータウェアハウスソリューションの数分の1のコストで、Lakehouseの柔軟性、拡張性、パフォーマンスにより、ユーザーをデータに近づけることができます。Dremioは「シフトレフト」分析を可能にし、複雑でコストのかかるデータ統合とETLを排除し、データを移動することなくシームレスなエンタープライズ規模の分析を実現します。Dremioには次の機能もあります。

* 汎用性に優れたセマンティックレイヤと、緊密に統合されたハイパフォーマンスなSQLクエリエンジンによって実現される使いやすいセルフサービス分析により、クラウドとオンプレミスの両方で、すべてのデータを簡単に接続、管理、分析できます。
* DremioのApache IcebergネイティブのLakehouse管理機能は、データ検出を簡素化し、データの最適化を自動化して、Gitにインスパイアされたデータバージョン管理を使用したハイパフォーマンス分析を実現します。
* オープンソースとオープンスタンダードに基づいて構築されたDremioは、企業がロックインを回避し、イノベーションのための地位を維持できるようにします。大企業は、すべてのワークロードで最高のコストパフォーマンスを発揮する、使いやすいLakehouseプラットフォームとしてDremioを信頼しています。




== DremioおよびNetAppハイブリッドアイスバーグレイクハウスソリューションはどのような価値をお客様に提供しますか？

* *データ管理とアクセシビリティの向上*: Dremioは、データレイクからデータを高速で直接クエリできるデータレイクハウスプラットフォームでよく知られています。一方、NetAppは、クラウドデータサービスとデータストレージソリューションの業界をリードするプロバイダです。この共同サービスは、企業データを効率的かつ効率的に保存、管理、アクセス、分析するための包括的なソリューションをお客様に提供します。
* *パフォーマンスの最適化*：データストレージに関するNetAppの専門知識と、Data Processingとデータ最適化に関するDremioの能力を活用して、このパートナーシップは、データ運用のパフォーマンスを向上させ、レイテンシを低減し、ビジネスインサイトを高速化するソリューションを提供します。Dremioは、NetAppの社内IT分析インフラストラクチャにもパフォーマンス上のメリットをもたらしました。
* *拡張性*: DremioとNetAppはどちらも、拡張性に優れたソリューションを提供します。この共同ソリューションは、拡張性に優れたデータストレージ、データ管理、分析環境をお客様に提供します。Hybrid Iceberg Lakehouse環境では、Dremio SQLクエリエンジンをNetApp StorageGRIDと組み合わせることで、あらゆるビジネスの分析ニーズに対応できる、比類のない拡張性、同時実行性、クエリパフォーマンスを実現します。
* *データセキュリティとガバナンス*:両社はデータセキュリティとガバナンスに重点を置いています。堅牢なセキュリティ機能とデータガバナンス機能を組み合わせることで、データを確実に保護し、データガバナンス要件を満たすことができます。ロールベースおよびきめ細かなアクセス制御、包括的な監査、エンドツーエンドのデータリネージ、統合されたアイデンティティ管理、広範なコンプライアンスおよびセキュリティフレームワークを備えたSSOなどの機能により、企業の分析データ環境の安全性と管理性が確保されます。
* *コスト効率*: DremioのデータレイクエンジンとNetAppのストレージソリューションを統合することで、データ管理とデータ移動に関連するコストを削減できます。また、従来のデータレイク環境から、NetAppとDremioで構成される最新のLakehouseソリューションに移行することもできます。このHybrid Iceberg Lakehouseソリューションは、高速クエリパフォーマンスと市場をリードするクエリの同時実行性を実現し、TCOを削減し、ビジネスインサイトを得るまでの時間を短縮します。

