---
sidebar: sidebar 
permalink: data-analytics/hdcs-sh-conclusion.html 
keywords: conclusion, summary, data protection, hadoop, more information, Acknowledgements 
summary: このセクションでは、ネットアップが提供するさまざまな Hadoop データ保護要件を満たすユースケースとソリューションの概要を説明します。 
---
= まとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションでは、ネットアップが提供するさまざまな Hadoop データ保護要件を満たすユースケースとソリューションの概要を説明します。ネットアップのデータファブリックを使用することで、お客様は次のことが可能になります。

* ネットアップの充実したデータ管理機能と Hadoop ネイティブワークフローとの統合により、適切なデータ保護ソリューションを柔軟に選択できます。
* Hadoop クラスタのバックアップ時間を約 70% 短縮します。
* Hadoop クラスタのバックアップによるパフォーマンスへの影響を排除します。
* 異なるクラウドプロバイダからのマルチクラウドデータ保護とデータアクセスを、単一の分析データソースに同時に提供できます。
* FlexClone テクノロジを使用すると、スペース効率に優れた高速な Hadoop クラスタコピーを作成できます。




== 詳細情報の入手方法

このドキュメントに記載されている情報の詳細については、次のドキュメントやWebサイトを参照してください。

* ネットアップのビッグデータ分析ソリューション
+
https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx["https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx"^]

* ネットアップストレージを使用した Apache Spark ワークロード
+
https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf["https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf"^]

* ネットアップの Apache Spark 向けストレージソリューション
+
https://www.netapp.com/media/16864-tr-4570.pdf["https://www.netapp.com/media/16864-tr-4570.pdf"^]

* ネットアップが有効にしたデータファブリック上の Apache Hadoop
+
https://www.netapp.com/media/16877-tr-4529.pdf["https://www.netapp.com/media/16877-tr-4529.pdf"^]





== 謝辞

* ネットアップ、 ANZ 地域セールス担当、 Paul Burland 氏
* ネットアップ、ビジネス開発マネージャー、 Hoseb Dermanilian 氏
* ネットアップ、 MPSG ディレクター、 Lee Dorrior 氏
* ネットアップ、 ANZ ビクトリア地区 SE 、システムエンジニア David Thiessen 氏




== バージョン履歴

|===
| バージョン | 日付 | ドキュメントのバージョン履歴 


| バージョン1.0 | 2018年1月 | 初版リリース 


| バージョン2.0 | 2021年10月 | ユースケース 5 ：分析ワークロードの高速化を更新 


| バージョン3.0 | 2023年11月 | 削除されたNIPAMの詳細 
|===