---
sidebar: sidebar 
permalink: data-analytics/hdcs-sh-overview-of-hadoop-data-protection-use-cases.html 
keywords: summary, overview, backup, devtest, data protection 
summary: このセクションでは、データ保護のユースケースの概要を概要で説明します。これが、本ドキュメントで重要となるのです。以降のセクションでは、それぞれのユースケースについて、お客様の問題（シナリオ）、要件と課題、ソリューションなどの詳細を説明します。 
---
= Hadoop のデータ保護のユースケースの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
このセクションでは、データ保護のユースケースの概要を概要で説明します。これが、本ドキュメントで重要となるのです。以降のセクションでは、それぞれのユースケースについて、お客様の問題（シナリオ）、要件と課題、ソリューションなどの詳細を説明します。



== 使用事例 1 ： Hadoop データのバックアップ

このユースケースでは、NetApp NFSボリュームを使用することで、大規模な金融機関では、長いバックアップウィンドウ時間を24時間以上からわずか数時間に短縮することができました。



== ユースケース 2 ：クラウドからオンプレミスへのバックアップとディザスタリカバリ

大規模な放送会社では、ネットアップのデータファブリックをビルディングブロックとして使用することで、オンデマンド、瞬時、データ転送などのさまざまなデータ転送モードに応じて、クラウドデータをオンプレミスのデータセンターにバックアップするという要件を満たすことができました。 または、 Hadoop / Spark のクラスタの負荷に基づいて計算されました。



== ユースケース 3 ：既存の Hadoop データに対して DevTest を有効化

ネットアップのソリューションは、オンラインの音楽配信企業が、スペース効率に優れた複数の Hadoop クラスタをさまざまなブランチオフィスに迅速に構築し、レポートを作成したり、定期的なポリシーを使用して日々の DevTest タスクを実行したりできるよう支援しました



== ユースケース 4 ：データ保護とマルチクラウド接続

ある大手サービスプロバイダは、ネットアップのデータファブリックを使用して、さまざまなクラウドインスタンスからお客様にマルチクラウド分析を提供していました。



== ユースケース 5 ：分析ワークロードを高速化

最大規模の金融サービスおよび投資銀行の 1 つは、ネットアップのネットワーク接続型ストレージ解決策を使用して、 I/O 待ち時間を短縮し、定量的な金融分析プラットフォームを高速化しました。
