---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-conclusion.html 
keywords: conclusion, references, history 
summary: Splunk Enterpriseは、セキュリティ、IT、DevOpsの各チームの成果を高める、市場をリードするSIEM解決策 です。Splunkの使用率は、お客様の組織全体で大幅に増加しています。そのため、データソースをさらに追加し、そのデータを長期間保持して、Splunkインフラに重点を置く必要があります。 
---
= まとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:stgr-splunkss-single-site-smartstore-performance.html["前のバージョン：単一サイトのSmartStoreのパフォーマンス。"]

[role="lead"]
Splunk Enterpriseは、セキュリティ、IT、DevOpsの各チームの成果を高める、市場をリードするSIEM解決策 です。Splunkの使用率は、お客様の組織全体で大幅に増加しています。そのため、データソースをさらに追加し、そのデータを長期間保持して、Splunkインフラに重点を置く必要があります。

Splunk SmartStoreとNetApp StorageGRID を組み合わせることで、SmartStoreとStorageGRID オブジェクトストレージにより取り込みパフォーマンスを向上させ、複数の地域にわたるSplunk環境の拡張性を高める、拡張性に優れたアーキテクチャを実現できます。



== 追加情報の参照先

このドキュメントに記載されている情報の詳細については、以下のドキュメントや Web サイトを参照してください。

* NetApp StorageGRID のドキュメントリソース
+
https://["https://www.netapp.com/data-storage/storagegrid/documentation/"^]

* ネットアップの製品マニュアル
+
https://["https://docs.netapp.com"^]

* Splunk Enterpriseに関するドキュメント
+
https://["https://docs.splunk.com/Documentation/Splunk"^]

* SmartStore向けSplunk Enterprise
+
https://["https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/AboutSmartStore"^]

* Splunk Enterprise Distributed Deployment Manual』を参照してください
+
https://["https://docs.splunk.com/Documentation/Splunk/8.0.6/Deploy/Distributedoverview"^]

* Splunk Enterpriseインデクサとインデクサのクラスタを管理しています
+
https://["https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/Aboutindexesandindexers"^]





== バージョン履歴

|===
| バージョン | 日付 | ドキュメントのバージョン履歴 


| 1.0 | 2022年7月 | 初版リリース 
|===