---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-solution-benefits.html 
keywords: benefits, performance, multi-site, scalability, capacity, availability, cache 
summary: このソリューションにより、コンピューティング、ホット ストレージ、または S3 リソースを追加して、単一サイトおよび複数サイトの展開全体でのユーザー数や取り込み速度に関する需要の増大に対応できます。 
---
= この解決策 の利点
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このソリューションにより、コンピューティング、ホット ストレージ、または S3 リソースを追加して、単一サイトおよび複数サイトの展開全体でのユーザー数や取り込み速度に関する需要の増大に対応できます。

* *パフォーマンス。*Splunk SmartStoreとNetApp StorageGRIDを組み合わせることで、オブジェクトストレージを使用してホットバケットとウォームバケットの間でデータを迅速に移行できます。StorageGRID は、大規模なオブジェクトワークロードに高速なパフォーマンスを提供することで、移行プロセスを大幅に高速化します。
* *マルチサイト対応*StorageGRIDの分散アーキテクチャにより、単一のグローバルネームスペースを使用して、単一のサイトと複数のサイトにまたがる環境を拡張できます。データの保存場所に関係なく、任意のサイトからデータにアクセスできます。
* *拡張性の向上*Splunk環境の変化するニーズやニーズに合わせて、コンピューティングリソースとは別にストレージリソースを拡張できるため、TCOが向上します。
* *容量*StorageGRIDを使用してグローバルネームスペースを560PB超に拡張すれば、Splunk環境で急増するボリュームに対応できます。
* *データの可用性*データのビジネスバリューの変化に応じて動的に調整できるメタデータベースのポリシーで、データの可用性、パフォーマンス、地理的な分散、保持、保護、ストレージコストを最適化します。


SmartStoreキャッシュは、ローカル（ホット）ストレージとリモート（ウォーム）ストレージ間のバケットコピーの転送を処理するインデクサのコンポーネントである。このソリューションのSplunkのサイジングは、に基づいて行われます https://docs.splunk.com/Documentation/Splunk/8.0.5/Capacity/Summaryofperformancerecommendations["Splunkから提供されるガイドライン"^]。このソリューションにより、コンピューティング、ホット ストレージ、または S3 リソースを追加して、単一サイトおよび複数サイトの展開全体でのユーザー数や取り込み速度に関する需要の増大に対応できます。
