---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-benefits-of-this-solution.html 
keywords: benefits, performance, multisite, scalability, capacity, availability, cache 
summary: 解決策 を使用すると、コンピューティング、ホットストレージ、またはS3リソースを追加して、ユーザ数や単一のマルチサイト環境全体での取り込み速度の増加に対応することができます。 
---
= この解決策 の利点
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:stgr-splunkss-introduction.html["前へ：はじめに。"]

[role="lead"]
* *パフォーマンス*。Splunk SmartStoreとNetApp StorageGRID を組み合わせることで、オブジェクトストレージを使用して、ホットバケットとウォームバケット間でデータを迅速に移行できます。StorageGRID は、大規模なオブジェクトワークロードに高速なパフォーマンスを提供することで、移行プロセスを大幅に高速化します。
* *マルチサイト対応。* StorageGRID 分散アーキテクチャにより、Splunk SmartStoreは単一のグローバルネームスペースを介して単一サイトと複数サイトに展開を拡張でき、データの場所に関係なく、あらゆるサイトからデータにアクセスできます。
* *拡張性の向上。* Splunk環境のニーズやニーズの変化に合わせて、コンピューティングリソースから独立してストレージリソースを拡張できるため、TCOが削減されます。
* *容量*。StorageGRID を使用して、1つのネームスペースを560PB以上に拡張することで、Splunk環境の急速に拡大しているボリュームに対応できます。
* *データの可用性。*データの可用性、パフォーマンス、地理的な分散、保持、保護、 また、データのビジネスバリューの変化に応じて動的に調整できるメタデータベースのポリシーに基づくストレージコストも発生します。


SmartStoreキャッシュは、ローカル（ホット）ストレージとリモート（ウォーム）ストレージ間のバケットコピーの転送を処理するインデクサのコンポーネントである。この解決策 のSplunkのサイジングは、に基づいています https://docs.splunk.com/Documentation/Splunk/8.0.5/Capacity/Summaryofperformancerecommendations["Splunkから提供されるガイドライン"^]。解決策 を使用すると、コンピューティング、ホットストレージ、またはS3リソースを追加して、ユーザ数や単一のマルチサイト環境全体での取り込み速度の増加に対応することができます。

link:stgr-splunkss-intelligent-tiering-and-cost-savings.html["次のステップ：インテリジェントな階層化とコスト削減。"]
