---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-solution-overview.html 
keywords: storagegrid, splunk enterprise, smartstore, object storage, machine data 
summary: このページでは、NetApp StorageGRID 、Splunk Enterprise、Splunk SmartStoreなど、解決策 の設定に使用するコンポーネントについて説明します。 
---
= 解決策の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:stgr-splunkss-intelligent-tiering-and-cost-savings.html["従来：インテリジェントな階層化とコスト削減を実現"]



== NetApp StorageGRID

NetApp StorageGRID は、高性能で対費用効果の高いオブジェクトストレージプラットフォームです。ノードベースの分散グリッドアーキテクチャを使用して、インテリジェントなポリシーベースのグローバルデータ管理を実現します。数ペタバイトの非構造化データと数十億のオブジェクトを、ユビキタスなグローバルオブジェクトネームスペースと高度なデータ管理機能を組み合わせることでシンプルに管理できます。単一コールのオブジェクトアクセスはサイト間を拡張し、高可用性アーキテクチャを簡素化しながら、サイトやインフラストラクチャの停止に関係なく、オブジェクトへの継続的なアクセスを保証します。

マルチテナンシーを使用すると、複数のクラウドやエンタープライズ非構造化データアプリケーションを同じグリッド内で安全に処理できるため、StorageGRID のROIとユースケースが向上します。メタデータベースのオブジェクトライフサイクルポリシーを使用して複数のサービスレベルを作成し、複数の地域にわたってデータの保持、保護、パフォーマンス、ローカリティを最適化できます。ユーザは、要件の変化に応じて、ポリシーを調整し、システムを停止せずにデータの再配置を行うことができます。

SmartStoreはStorageGRID をリモートストレージ階層として活用し、地理的に分散した複数のサイトを展開して、単一のオブジェクトネームスペースとして提供される堅牢な可用性と耐久性を実現します。これにより、Splunk SmartStoreは、StorageGRID の高パフォーマンス、高密度の容量、および単一のURLを使用して複数の物理サイトにまたがる数百のノードに拡張可能な機能を活用し、オブジェクトとやり取りできます。また、 1 つの URL だけで、ストレージの拡張、アップグレード、修復を、 1 つのサイトだけでなく無停止で実行することもできます。StorageGRID 独自のデータ管理ポリシーエンジンにより、最適なレベルのパフォーマンスと耐久性が実現し、データローカリティ要件への準拠が実現します。



== Splunk Enterpriseの

Splunkは、マシン生成データの収集と分析を行うリーダーであり、運用分析機能を通じてITを簡易化、刷新します。また、ビジネス分析、セキュリティ、IoTのユースケースにも対応します。Splunkソフトウェアを適切に導入するためには、ストレージが欠かせません。

マシン生成データは、最も急速に増加しているビッグデータのタイプです。フォーマットは予測不能であり、多くの異なるソースから得られます。多くの場合、高レートで大量に発生します。このようなワークロード特性は、一般にデジタルエキゾーストと呼ばれます。Splunk SmartStoreを使用すると、こうしたデータを把握し、最もコスト効率の高いストレージ階層にホットデータとウォームデータを最適な場所に配置できるように、スマートなデータ階層化を実現できます。



== Splunk SmartStoreからダウンロードできます

Splunk SmartStoreは、StorageGRID などのオブジェクトストレージ（リモートストレージまたはリモートストレージ階層とも呼ばれます）を使用して、S3プロトコルを使用してウォームデータを格納するインデクサ機能です。

導入のデータボリュームが増加すると、ストレージの需要がコンピュータリソースの需要を上回ってしまうことがよくあります。SmartStoreでは、コンピューティングとストレージを個別に拡張することにより、インデックスサーバのストレージリソースとコンピューティングリソースをコスト効率よく管理できます。

SmartStoreでは、S3プロトコルとキャッシュマネージャを使用して、リモートストレージ層を導入しています。これらの機能を使用すると、インデックスサーバー上またはリモートストレージ上にデータをローカルに配置できます。インデクサに常駐するキャッシュマネージャは'インデクサとリモートストレージ階層の間のデータ移動を管理しますデータはバケットメタデータと一緒にバケットに（ホットおよびウォーム）格納されます。

SmartStoreを使用すると、ほとんどのデータがリモートストレージ階層に存在するため、インデクサのストレージ設置面積を最小に抑え、I/O最適化コンピューティングリソースを選択できます。インデクサは、要求され予測された結果を返すために必要な最小限のデータ量を表すローカルキャッシュを維持します。ローカルキャッシュには、ホットバケット、アクティブまたは最新の検索に使用されるウォームバケットのコピー、およびバケットメタデータが格納されます。

StorageGRID を搭載したSplunk SmartStoreを使用すると、高パフォーマンスでコスト効率の高いリモートストレージを使用して環境を段階的に拡張でき、解決策 全体にも高い柔軟性を提供できます。これにより、お客様は任意の量のコンポーネント（ホットストレージやウォームS3ストレージ）をいつでも追加でき、インデックスの追加、データの保持の変更、システム停止なしの取り込み速度の向上が可能です。

link:stgr-splunkss-flexible-storagegrid-features-for-splunk-smartstore.html["次に、Splunk SmartStore向けの柔軟なStorageGRID 機能を紹介します。"]
