---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization, overview 
summary: 解決策には、Hyper-VをNetAppストレージに導入するために必要な手順が記載されている 
---
= NetAppストレージへのMicrosoft Hyper-Vの導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Windows Serverプラットフォームは、Hyper-Vの役割を使用して仮想化テクノロジを提供します。Hyper-Vは、Windows Serverで提供される多くのオプションの役割の1つです。



== 概要

Hyper-Vの役割により、Windows Serverに組み込まれている仮想化テクノロジを使用して、仮想化コンピューティング環境を作成および管理できます。Hyper-Vテクノロジは、ハードウェアを仮想化して、1台の物理コンピュータ上で複数のオペレーティングシステムを同時に実行できる環境を提供します。Hyper-Vでは、仮想マシンとそのリソースを作成および管理できます。各仮想マシンは、独立した仮想化されたコンピュータシステムであり、独自のオペレーティングシステムを実行できます。Hyper-Vは、効率の向上とコスト削減を目的としたさまざまなビジネス目標をサポートするアプリケーションとワークロードを仮想化するためのインフラストラクチャを提供します。これは、VMware®vSphereの最適な代替手段です。特に、現在の市場状況において、複数のハイパーバイザの共存を求める組織に適しています。



== 対象読者

このドキュメントでは、NetApp ONTAPシステムを使用するHyper-Vクラスタ構成のアーキテクチャと導入手順について説明します。このドキュメントの対象読者は、セールスエンジニア、フィールドコンサルタント、プロフェッショナルサービス、ITマネージャー、パートナーエンジニア、 また、プライマリまたは代替のハイパーバイザーとしてHyper-Vを導入したいと考えているお客様もいます。



== アーキテクチャ

本ドキュメントで説明するアーキテクチャには、特にMicrosoft®Windows Server®2022とHyper-V®仮想化が含まれています。NetAppでは、すべての導入に仮想化ソフトウェアとインフラ管理ソフトウェアを使用することを強く推奨しています。この構成では、各コンポーネントのベストプラクティスを使用して、信頼性の高いエンタープライズクラスのインフラを実現します。



== ユースケースの概要

本ドキュメントでは、NetAppオールフラッシュFASおよびASAアレイモデルを使用して、Microsoft Windows Server 2022でワークロードとして最適なパフォーマンスを発揮するようにHyper-Vクラスタをセットアップするための導入手順とベストプラクティスについて説明します。サーバのオペレーティングシステム/ハイパーバイザーはMicrosoft Windows Server 2022です。このガイダンスでは、Storage Area Network（SAN；ストレージエリアネットワーク）プロトコルとNetwork-Attached Storage（NAS；ネットワーク接続型ストレージ）プロトコルでデータを提供するNetAppストレージシステムを対象としています。
