---
sidebar: sidebar 
permalink: ent-apps-db/awx_automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: このページでは、 NetApp ONTAP ストレージ上に Oracle19c を導入するための自動化方式について説明します。 
---
= ステップバイステップの導入手順
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== AWX/Tower の導入 Oracle 19C データベース



=== 1. 環境のインベントリ、グループ、ホスト、およびクレデンシャルを作成します

このセクションでは、ネットアップの自動化ソリューションを使用する環境を準備するための AWX/Ansible タワーでのインベントリ、グループ、ホスト、アクセスクレデンシャルのセットアップについて説明します。

. インベントリを設定します。
+
.. リソース→インベントリ→追加と進み、インベントリの追加をクリックします。
.. 名前と組織の詳細を入力し、 [ 保存 ] をクリックします。
.. インベントリページで、作成されたインベントリをクリックします。
.. インベントリ変数がある場合は、その変数を変数フィールドに貼り付けます。
.. [ グループ ] サブメニューに移動し、 [ 追加 ] をクリックします。
.. ONTAP のグループの名前を入力し、グループ変数（ある場合）を貼り付けて、 [ 保存 ] をクリックします。
.. Oracle の別のグループに対してこの手順を繰り返します。
.. 作成した ONTAP グループを選択し、 Hosts サブメニューに移動して、 Add New Host をクリックします。
.. ONTAP クラスタ管理 IP の IP アドレスを入力し、ホスト変数（存在する場合）を貼り付けて、 [ 保存 ] をクリックします。
.. このプロセスは、 Oracle グループおよび Oracle ホストの管理 IP / ホスト名に対して繰り返す必要があります。


. クレデンシャルタイプを作成する。ONTAP を使用するソリューションでは、ユーザ名とパスワードのエントリを照合するようにクレデンシャルタイプを設定する必要があります。
+
.. [ 管理 ] → [ 資格情報の種類 ] に移動し、 [ 追加 ] をクリックします。
.. 名前と概要を指定します。
.. 入力構成に次の内容を貼り付けます。
+
[source, cli]
----
fields:
  - id: username
    type: string
    label: Username
  - id: password
    type: string
    label: Password
    secret: true
  - id: vsadmin_password
    type: string
    label: vsadmin_password
    secret: true
----
.. 次の内容をインジェクター設定に貼り付けます。
+
[source, cli]
----
extra_vars:
  password: '{{ password }}'
  username: '{{ username }}'
  vsadmin_password: '{{ vsadmin_password }}'
----


. クレデンシャルを設定します。
+
.. [ リソース ] → [ 資格情報 ] に移動し、 [ 追加 ] をクリックします。
.. ONTAP の名前と組織の詳細を入力します。
.. ONTAP 用に作成したカスタム資格情報タイプを選択します。
.. [ タイプの詳細 ] で、ユーザー名、パスワード、および vsadmin-readonly を入力します。
.. [ 資格情報に戻る ] をクリックし、 [ 追加 ] をクリックします
.. Oracle の名前と組織の詳細を入力します。
.. マシンクレデンシャルタイプを選択します。
.. Type Details （タイプの詳細）に、 Oracle ホストのユーザー名とパスワードを入力します。
.. 適切な特権昇格方式を選択し、ユーザ名とパスワードを入力します。






=== 2. プロジェクトを作成します

. [ リソース ] → [ プロジェクト ] に移動し、 [ 追加 ] をクリックします。
+
.. 名前と組織の詳細を入力します
.. Source Control Credential Type フィールドで Git を選択します。
.. 入力するコマンド <https://github.com/NetApp-Automation/na_oracle19c_deploy.git>[""] をソース管理 URL として指定します。
.. [ 保存 ] をクリックします .
.. ソースコードが変更されたときに、プロジェクトの同期が必要になることがあります。






=== 3. Oracle host_vars を設定します

このセクションで定義した変数は、個々の Oracle サーバとデータベースに適用されます。

. 次の組み込み Oracle ホスト変数または host_vars フォームに、環境固有のパラメータを入力します。



NOTE: 青の項目は、環境に合わせて変更する必要があります。



=== ホスト VAR 構成


. 青のフィールドにすべての変数を入力します。
. 変数の入力が完了したら、フォームの [ コピー ] ボタンをクリックして、 AWX またはタワーに転送されるすべての変数をコピーします。
. AWX またはタワーに戻って、 Resources （リソース）→ Hosts （ホスト）に移動し、 Oracle サーバ設定ページを選択して開きます。
. [ 詳細 ] タブで、編集をクリックし、コピーした変数を手順 1 から YAML タブの [ 変数 ] フィールドに貼り付けます。
. [ 保存 ] をクリックします .
. システム内の他の Oracle サーバについても、この手順を繰り返します。




=== 4. グローバル変数を設定します

このセクションで定義する変数は、すべての Oracle ホスト、データベース、および ONTAP クラスタに適用されます。

. 次の組み込みグローバル変数または変数フォームに環境固有のパラメータを入力します。
+

NOTE: 青の項目は、環境に合わせて変更する必要があります。





=== VAR


. すべての変数を青のフィールドに入力します。
. 変数の入力が完了したら、フォームの [ コピー ] ボタンをクリックして、 AWX またはタワーに転送されるすべての変数を次のジョブテンプレートにコピーします。




=== 5. ジョブテンプレートを設定して起動します。

. ジョブテンプレートを作成します。
+
.. [ リソース ] → [ テンプレート ] → [ 追加 ] に移動し、 [ ジョブテンプレートの追加 ] をクリックします。
.. 名前と概要を入力します
.. ジョブタイプを選択します。 Run は、プレイブックに基づいてシステムを設定します。 Check は、実際にシステムを設定することなく、プレイブックの事前チェックを実行します。
.. 対応するインベントリ、プロジェクト、プレイブック、およびクレデンシャルを選択します。
.. 実行するデフォルトのプレイブックとして、 all_cplaybook.yml を選択します。
.. 手順 4 からコピーしたグローバル変数を YAML タブの Template Variables フィールドに貼り付けます。
.. [ ジョブタグ ] フィールドの [ 起動時にプロンプトを表示する ] チェックボックスをオンにします。
.. [ 保存 ] をクリックします .


. ジョブテンプレートを起動します。
+
.. [ リソース ] → [ テンプレート ] に移動します。
.. 目的のテンプレートをクリックし、 [ 起動 ] をクリックします。
.. ジョブタグの起動時にプロンプトが表示されたら、 requires_config と入力します。requires_config の下にある Create Job Tag 行をクリックして、ジョブタグを入力する必要がある場合があります。
+

NOTE: requireation_config により、他のロールを実行するための正しいライブラリが確保されます。

.. [ 次へ ] をクリックし、 [ 起動 ] をクリックしてジョブを開始します。
.. ジョブの出力と進行状況を監視するには、表示→ジョブをクリックします。
.. ジョブタグの起動を求めるプロンプトが表示されたら、「 ONTAP_config 」と入力します。ジョブタグを入力するには、 ONTAP_config の下にある「ジョブタグの作成」行をクリックする必要があります。
.. [ 次へ ] をクリックし、 [ 起動 ] をクリックしてジョブを開始します。
.. ジョブ出力およびを監視するには、表示→ジョブをクリックします 進捗状況
.. ONTAP_CONFIG ロールの完了後、 linux_config のプロセスを再度実行します。
.. [ リソース ] → [ テンプレート ] に移動します。
.. 目的のテンプレートを選択し、 [ 起動 ] をクリックします。
.. linux_config でジョブタグタイプの起動時にプロンプトが表示されたら、 linux_config のすぐ下にある「ジョブタグの作成」行を選択して、ジョブタグを入力する必要があります。
.. [ 次へ ] をクリックし、 [ 起動 ] をクリックしてジョブを開始します。
.. ジョブの出力と進行状況を監視するには、表示→ジョブを選択します。
.. linux_config ロールが完了したら、 ORACLE_config のプロセスを再度実行します。
.. [ リソース ] → [ テンプレート ] に移動します。
.. 目的のテンプレートを選択し、 [ 起動 ] をクリックします。
.. ジョブタグの起動時にプロンプトが表示されたら、 ORACLE_config と入力します。ORACLE_config の直下にある「ジョブタグの作成」行を選択して、ジョブタグを入力する必要がある場合があります。
.. [ 次へ ] をクリックし、 [ 起動 ] をクリックしてジョブを開始します。
.. ジョブの出力と進行状況を監視するには、表示→ジョブを選択します。






=== 6. 同じ Oracle ホストに追加のデータベースを配置します

このプレイブックの Oracle 部分では、 1 回の実行につき Oracle サーバ上に Oracle コンテナデータベースが 1 つ作成されます。同じサーバ上に追加のコンテナデータベースを作成するには、次の手順を実行します。

. host_vars 変数を改訂。
+
.. 手順 2 - Oracle host_vars の設定に戻ります。
.. Oracle SID を別の名前文字列に変更します。
.. リスナーポートを別の番号に変更します。
.. EM Express をインストールする場合は、 EM Express ポートを別の番号に変更します。
.. 改訂されたホスト変数を Host Configuration Detail タブの Oracle Host Variables フィールドにコピーして貼り付けます。


. ORACLE_config タグのみを使用して、導入ジョブテンプレートを起動します。




=== Oracle のインストールを検証します


[source, cli]
----
ps -ef | grep ora
----

NOTE: インストールが正常に完了した場合は、 Oracle プロセスが一覧表示されます Oracle DB のサポートを開始しました


[source, cli]
----
sqlplus / as sysdba
----
[oracle @localhost ~] $sqlplus / AS sysdba

SQL * Plus ：リリース 19.0.0.0.0 - 木曜日 5 月 6 日 12 ： 52 ： 51 2021 バージョン 19.8.0.0.0 の製造

Copyright （ c ） 1982 、 2019 、 OracleAll rights reserved.

接続先： Oracle Database 19C Enterprise Edition Release 19.0.0.0.0 - Production Version 19.8.0.0.0

SQL>

[source, cli]
----
select name, log_mode from v$database;
----
SQL> 名前の選択、 log_mode は V$ データベースから、名前 log_mode は ---- - - - - - - - - - - CDB2 ARCHIVELOG

[source, cli]
----
show pdbs;
----
SQL> PDB を表示

....
    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO
....
[source, cli]
----
col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;
----
SQL> col svrname フォーム A30 SQL> col dirname フォーム A30 SQL> select svrname 、 dirname 、 nfsversion from v$dnfs_servers ；

SVRNAME NFSVERVERSION-------------------------------- -------------- - - - - - - - - - - - - - 172.21.126.200/rhelora03_u02 NFSv4 3.0 172.21.126.200/rhelora03_u03 NFSv4 3.0 172.21.126.200/rhelora03_u01 NFSv3.0 を NFSv4 3.00 に戻します

[listing]
----
This confirms that dNFS is working properly.
----

[source, cli]
----
sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com
----
[oracle @ localhost ~] $sqlplus システム @ // localhost ： 1523 / cdb2_pdb1.cie.netapp.com

SQL * Plus ：リリース 19.0.0.0.0 - 木曜日 5 月 6 日 13 ： 19 ： 57 2021 バージョン 19.8.0.0.0 の製造

Copyright （ c ） 1982 、 2019 、 OracleAll rights reserved.

パスワード「 Last Successful login time ： Wed May 05 2021 17 ： 11 ： 11-04 ： 00 」を入力します

接続先： Oracle Database 19C Enterprise Edition Release 19.0.0.0.0 - Production Version 19.8.0.0.0

SQL> show user user is "system" SQL> show con_name CON_name CDB2_PDB1

[listing]
----
This confirms that Oracle listener is working properly.
----


=== サポートが必要な場所

ツールキットに関するサポートが必要な場合は、にご参加ください link:https://netapppub.slack.com/archives/C021R4WC0LC["ネットアップの解決策自動化コミュニティでは、余裕期間のチャネルがサポートさ"] また、ソリューション自動化チャネルを検索して、質問や問い合わせを投稿しましょう。
