---
sidebar: sidebar 
permalink: ent-apps-db/cli_automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: このページでは、 NetApp ONTAP ストレージ上に Oracle19c を導入するための自動化方式について説明します。 
---
= ステップバイステップの導入手順
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== CLI による Oracle 19C データベースの導入

このセクションでは、 CLI を使用して Oracle19c データベースを準備および導入するために必要な手順について説明します。を確認しておきます link:getting_started_requirements.html["「はじめに」および「要件」セクション"] それに応じて環境の準備を整えます。



=== Oracle19c repo をダウンロードします


[source, cli]
----
git clone https://github.com/NetApp-Automation/na_oracle19c_deploy.git
----



=== hosts ファイルを編集します

導入前に、次の手順を実行します。

. hosts ファイル na_oracle19c_deploy ディレクトリを編集します。
. ONTAP で、 IP アドレスをクラスタ管理 IP に変更します。
. [Oracle] グループの下に、 Oracle ホスト名を追加します。DNS または hosts ファイルを使用してホスト名を IP アドレスに解決しておくか、ホストで指定する必要があります。
. これらの手順を完了したら、変更を保存します。


次の例は、ホストファイルを示しています。


この例では、 Playbook を実行し、 Oracle 19C を 2 台の Oracle DB サーバに同時に導入しています。1 つの DB サーバでテストすることもできます。この場合、設定が必要なホスト変数ファイルは 1 つだけです。


NOTE: このプレイブックの内容は、導入する Oracle ホストとデータベースの数に関係なく同じです。



=== host_vars で host_name .yml ファイルを編集します

各 Oracle ホストには、ホスト固有の変数を含むホスト名で識別されるホスト変数ファイルがあります。ホストには任意の名前を指定できます。Host VAR Config セクションから「 host_vars 」を編集してコピーし、目的の「 host_name.yml 」ファイルに貼り付けます。


NOTE: 青の項目は、環境に合わせて変更する必要があります。



=== ホスト VAR 構成




=== vars.yml ファイルを編集します

変数 .yml` ファイルは 'Oracle の導入に向けて ' 環境固有のすべての変数（ ONTAP 'Linux'Oracle ）を統合します

* 変数を VAR セクションから編集してコピーし、変数を自分の「 vars.yml 」ファイルに貼り付けます。




=== VAR




=== プレイブックを実行します

必要な環境の前提条件を完了し ' 変数を vars.yml' および 'Your_host.yml' にコピーした後 ' プレイブックを導入する準備が整いました


NOTE: <username> は、環境に合わせて変更する必要があります。


[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t ontap_config -e @vars/vars.yml
----

[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t linux_config -e @vars/vars.yml
----

[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t oracle_config -e @vars/vars.yml
----


=== 同じ Oracle ホストに追加のデータベースを導入します

このプレイブックの Oracle 部分では、 1 回の実行につき Oracle サーバ上に Oracle コンテナデータベースが 1 つ作成されます。同じサーバ上に追加のコンテナデータベースを作成するには、次の手順を実行します。

. host_vars 変数を改訂します。
+
.. ステップ 3 に戻ります - 'host_vars' の下の 'host_name.yml' ファイルを編集します
.. Oracle SID を別の名前文字列に変更します。
.. リスナーポートを別の番号に変更します。
.. EM Express をインストールしている場合は、 EM Express ポートを別の番号に変更します。
.. 変更したホスト変数を 'host_vars' の下の Oracle ホスト変数ファイルにコピーして貼り付けます


. 上記のように 'ORACLE_CONFIG' タグを使用してプレイブックを実行します インチ <<Run the playbook>>。




=== Oracle のインストールを検証します


[source, cli]
----
ps -ef | grep ora
----

NOTE: インストールが正常に完了した場合は、 Oracle プロセスが一覧表示されます Oracle DB のサポートを開始しました


[source, cli]
----
sqlplus / as sysdba
----
[oracle @localhost ~] $sqlplus / AS sysdba

SQL * Plus ：リリース 19.0.0.0.0 - 木曜日 5 月 6 日 12 ： 52 ： 51 2021 バージョン 19.8.0.0.0 の製造

Copyright （ c ） 1982 、 2019 、 OracleAll rights reserved.

接続先： Oracle Database 19C Enterprise Edition Release 19.0.0.0.0 - Production Version 19.8.0.0.0

SQL>

[source, cli]
----
select name, log_mode from v$database;
----
SQL> 名前の選択、 log_mode は V$ データベースから、名前 log_mode は ---- - - - - - - - - - - CDB2 ARCHIVELOG

[source, cli]
----
show pdbs;
----
SQL> PDB を表示

....
    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO
....
[source, cli]
----
col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;
----
SQL> col svrname フォーム A30 SQL> col dirname フォーム A30 SQL> select svrname 、 dirname 、 nfsversion from v$dnfs_servers ；

SVRNAME NFSVERVERSION-------------------------------- -------------- - - - - - - - - - - - - - 172.21.126.200/rhelora03_u02 NFSv4 3.0 172.21.126.200/rhelora03_u03 NFSv4 3.0 172.21.126.200/rhelora03_u01 NFSv3.0 を NFSv4 3.00 に戻します

[listing]
----
This confirms that dNFS is working properly.
----

[source, cli]
----
sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com
----
[oracle @ localhost ~] $sqlplus システム @ // localhost ： 1523 / cdb2_pdb1.cie.netapp.com

SQL * Plus ：リリース 19.0.0.0.0 - 木曜日 5 月 6 日 13 ： 19 ： 57 2021 バージョン 19.8.0.0.0 の製造

Copyright （ c ） 1982 、 2019 、 OracleAll rights reserved.

パスワード「 Last Successful login time ： Wed May 05 2021 17 ： 11 ： 11-04 ： 00 」を入力します

接続先： Oracle Database 19C Enterprise Edition Release 19.0.0.0.0 - Production Version 19.8.0.0.0

SQL> show user user is "system" SQL> show con_name CON_name CDB2_PDB1

[listing]
----
This confirms that Oracle listener is working properly.
----


=== サポートが必要な場所

ツールキットに関するサポートが必要な場合は、にご参加ください link:https://netapppub.slack.com/archives/C021R4WC0LC["ネットアップの解決策自動化コミュニティでは、余裕期間のチャネルがサポートさ"] また、ソリューション自動化チャネルを検索して、質問や問い合わせを投稿しましょう。
