---
sidebar: sidebar 
permalink: ent-apps-db/db_protection_awx_automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: このページでは、 NetApp ONTAP ストレージ上の Oracle19c の自動データ保護について説明します。 
---
= ステップバイステップの導入手順
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== AWX/Tower Oracle データ保護



=== 1. 環境のインベントリ、グループ、ホスト、およびクレデンシャルを作成します

このセクションでは、ネットアップの自動化ソリューションを使用する環境を準備するための AWX/Ansible タワーでのインベントリ、グループ、ホスト、アクセスクレデンシャルのセットアップについて説明します。

. インベントリを設定します。
+
.. リソース→インベントリ→追加と進み、インベントリの追加をクリックします。
.. 名前と組織の詳細を入力し、 [ 保存 ] をクリックします。
.. インベントリページで、作成されたインベントリをクリックします。
.. [ グループ ] サブメニューに移動し、 [ 追加 ] をクリックします。
.. 最初のグループの Oracle という名前を入力し、 [ 保存 ] をクリックします。
.. DR_Oracle という名前の 2 つ目のグループに対してこの手順を繰り返します。
.. 作成した Oracle グループを選択し、 Hosts サブメニューに移動して、 Add New Host をクリックします。
.. ソース Oracle ホストの管理 IP の IP アドレスを入力し、 [ 保存 ] をクリックします。
.. DR_Oracle グループに対してこの手順を繰り返し、 DR/Destination Oracle ホストの管理 IP / ホスト名を追加する必要があります。


+

NOTE: 以下は、オンプレミスと ONTAP 、または AWS 上の CVO のクレデンシャルタイプとクレデンシャルを作成する手順です。



[role="tabbed-block"]
====
.オンプレミス
--
. クレデンシャルを設定します。
. クレデンシャルタイプの作成ONTAP を使用するソリューションでは、ユーザ名とパスワードのエントリを照合するようにクレデンシャルタイプを設定する必要があります。
+
.. [ 管理 ] → [ 資格情報の種類 ] に移動し、 [ 追加 ] をクリックします。
.. 名前と概要を指定します。
.. 入力構成に次の内容を貼り付けます。
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: Destination Cluster Username
  - id: dst_cluster_password
    type: string
    label: Destination Cluster Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
----
.. 次の内容をインジェクタ設定に貼り付け、 [ 保存 ] をクリックします。
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
----


. ONTAP のクレデンシャルを作成します
+
.. [ リソース ] → [ 資格情報 ] に移動し、 [ 追加 ] をクリックします。
.. ONTAP クレデンシャルの名前と組織の詳細を入力します
.. 前の手順で作成したクレデンシャルタイプを選択します。
.. タイプの詳細で、ソースクラスタとデスティネーションクラスタのユーザ名とパスワードを入力します。
.. [ 保存 ] をクリックします .


. Oracle のクレデンシャルを作成します
+
.. [ リソース ] → [ 資格情報 ] に移動し、 [ 追加 ] をクリックします。
.. Oracle の名前と組織の詳細を入力します。
.. マシンクレデンシャルタイプを選択します。
.. Type Details （タイプの詳細）に、 Oracle ホストのユーザー名とパスワードを入力します。
.. 適切な特権昇格方式を選択し、ユーザ名とパスワードを入力します。
.. [ 保存 ] をクリックします .
.. 必要に応じて、 DR_Oracle ホストの別のクレデンシャルに対して同じ手順を繰り返します。




--
.CVO を確認して
--
. クレデンシャルを設定します。
. クレデンシャルタイプを作成する。ONTAP が関連するソリューションでは、ユーザ名とパスワードのエントリに一致するクレデンシャルタイプを設定する必要があります。また、 Cloud Central と AWS のエントリも追加します。
+
.. [ 管理 ] → [ 資格情報の種類 ] に移動し、 [ 追加 ] をクリックします。
.. 名前と概要を指定します。
.. 入力構成に次の内容を貼り付けます。
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: CVO Username
  - id: dst_cluster_password
    type: string
    label: CVO Password
    secret: true
  - id: cvo_svm_password
    type: string
    label: CVO SVM Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
  - id: regular_id
    type: string
    label: Cloud Central ID
    secret: true
  - id: email_id
    type: string
    label: Cloud Manager Email
    secret: true
  - id: cm_password
    type: string
    label: Cloud Manager Password
    secret: true
  - id: access_key
    type: string
    label: AWS Access Key
    secret: true
  - id: secret_key
    type: string
    label: AWS Secret Key
    secret: true
  - id: token
    type: string
    label: Cloud Central Refresh Token
    secret: true
----
.. 次の内容をインジェクタ構成に貼り付け、 [ 保存（ Save ） ] をクリックする。
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  cvo_svm_password: '{{ cvo_svm_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
  regular_id: '{{ regular_id }}'
  email_id: '{{ email_id }}'
  cm_password: '{{ cm_password }}'
  access_key: '{{ access_key }}'
  secret_key: '{{ secret_key }}'
  token: '{{ token }}'
----


. ONTAP / CVO / AWS のクレデンシャルを作成
+
.. [ リソース ] → [ 資格情報 ] に移動し、 [ 追加 ] をクリックします。
.. ONTAP クレデンシャルの名前と組織の詳細を入力します
.. 前の手順で作成したクレデンシャルタイプを選択します。
.. Type Details に、ソースクラスタと CVO クラスタ、 Cloud Central / Manager 、 AWS Access / Secret Key 、 Cloud Central Refresh Token のユーザ名とパスワードを入力します。
.. [ 保存 ] をクリックします .


. Oracle のクレデンシャルの作成（ソース）
+
.. [ リソース ] → [ 資格情報 ] に移動し、 [ 追加 ] をクリックします。
.. Oracle ホストの名前と組織の詳細を入力します
.. マシンクレデンシャルタイプを選択します。
.. Type Details （タイプの詳細）に、 Oracle ホストのユーザー名とパスワードを入力します。
.. 適切な特権昇格方式を選択し、ユーザ名とパスワードを入力します。
.. [ 保存 ] をクリックします .


. Oracle 保存先のクレデンシャルを作成します
+
.. [ リソース ] → [ 資格情報 ] に移動し、 [ 追加 ] をクリックします。
.. DR Oracle ホストの名前と組織の詳細を入力します
.. マシンクレデンシャルタイプを選択します。
.. Type Details に、ユーザ名（ ec2-user またはデフォルトの入力から変更した場合は、そのユーザ名）と SSH 秘密鍵を入力します
.. 適切な特権昇格方式（ sudo ）を選択し、必要に応じてユーザ名とパスワードを入力します。
.. [ 保存 ] をクリックします .




--
====


=== 2. プロジェクトを作成します

. [ リソース ] → [ プロジェクト ] に移動し、 [ 追加 ] をクリックします。
+
.. 名前と組織の詳細を入力します
.. Source Control Credential Type フィールドで Git を選択します。
.. 入力するコマンド <https://github.com/NetApp-Automation/na_oracle19c_data_protection.git>[] をソース管理 URL として指定します。
.. [ 保存 ] をクリックします .
.. ソースコードが変更されたときに、プロジェクトの同期が必要になることがあります。






=== 3. グローバル変数を設定します

このセクションで定義する変数は、すべての Oracle ホスト、データベース、および ONTAP クラスタに適用されます。

. 次の組み込みグローバル変数または変数フォームに環境固有のパラメータを入力します。
+

NOTE: 青の項目は、環境に合わせて変更する必要があります。

+
[role="tabbed-block"]
====
.オンプレミス
--

--
.CVO を確認して
--

--
====




=== 4. 自動化に関するハンドブック

実行する必要があるプレイブックは 4 つあります。

. 環境のセットアップに関するプレイブック：オンプレミス、 CVO
. Oracle バイナリとデータベースをスケジュールどおりにレプリケートする Playbook
. Oracle ログをスケジュールどおりにレプリケートするためのプレイブック
. デスティネーションホストでのデータベースのリカバリに関するプレイブック


[role="tabbed-block"]
====
.ONTAP/CVO セットアップ
--
ONTAP と CVO のセットアップ

. ジョブテンプレートを設定して起動します。
+
.. ジョブテンプレートを作成します。
+
... [ リソース ] → [ テンプレート ] → [ 追加 ] に移動し、 [ ジョブテンプレートの追加 ] をクリックします。
... 「 ONTAP/CVO Setup 」という名前を入力します
... ジョブタイプを選択します。 Run は、プレイブックに基づいてシステムを設定します。
... 対応するインベントリ、プロジェクト、プレイブック、およびクレデンシャルを選択します。
... オンプレミス環境用の ONTAP_setup.yml プレイブックを選択するか、 CVO-setup.yml を選択して CVO インスタンスにレプリケーションします。
... 手順 4 からコピーしたグローバル変数を YAML タブの Template Variables フィールドに貼り付けます。
... [ 保存 ] をクリックします .


.. ジョブテンプレートを起動します。
+
... [ リソース ] → [ テンプレート ] に移動します。
... 目的のテンプレートをクリックし、 [ 起動 ] をクリックします。
+

NOTE: このテンプレートを使用して、他のプレイブック用にコピーします。







--
.バイナリおよびデータベースボリュームのレプリケーション
--
バイナリおよびデータベースのレプリケーションマニュアルのスケジュール

. ジョブテンプレートを設定して起動します。
+
.. 以前に作成したジョブテンプレートをコピーします。
+
... [ リソース ] → [ テンプレート ] に移動します。
... 「 ONTAP/CVO Setup Template 」を探して、右端で「 Copy Template 」をクリックします
... コピーしたテンプレートで [ テンプレートの編集 ] をクリックし、名前を [ バイナリおよびデータベースのレプリケーションのマニュアル ] に変更します。
... テンプレートの同じインベントリ、プロジェクト、資格情報を保持します。
... 実行するプレイブックとして ora_replication_cg.yml を選択します。
... 変数は変更されませんが、 CVO クラスタの IP は変数 dst_cluster_ip に設定する必要があります。
... [ 保存 ] をクリックします .


.. ジョブテンプレートをスケジュールします。
+
... [ リソース ] → [ テンプレート ] に移動します。
... バイナリおよびデータベースのレプリケーション用プレイブックテンプレートをクリックし、一番上のオプションセットにあるスケジュールをクリックします。
... [ 追加 ] をクリックし、 [ バイナリおよびデータベースレプリケーションの名前スケジュールの追加 ] をクリックし、時間の開始時に [ 開始日時 ] を選択し、 [ ローカルタイムゾーン ] を選択して、 [ 実行頻度 ] をクリックします。実行頻度は、多くの場合、 SnapMirror レプリケーションが更新されます。
+

NOTE: ログボリュームのレプリケーション用に別のスケジュールが作成されるため、より頻繁にレプリケートできます。







--
.ログボリュームのレプリケーション
--
ログ・レプリケーション・プレイブックのスケジュール

. ジョブテンプレートを設定して起動します。
+
.. 以前に作成したジョブテンプレートをコピーします。
+
... [ リソース ] → [ テンプレート ] に移動します。
... 「 ONTAP/CVO Setup Template 」を探して、右端で「 Copy Template 」をクリックします
... コピーしたテンプレートで [ テンプレートの編集 ] をクリックし、名前を [ ログレプリケーションのプレイブック ] に変更します。
... テンプレートの同じインベントリ、プロジェクト、資格情報を保持します。
... 実行するプレイブックとして ora_replication_loges.yml を選択します。
... 変数は変更されませんが、 CVO クラスタの IP は変数 dst_cluster_ip に設定する必要があります。
... [ 保存 ] をクリックします .


.. ジョブテンプレートをスケジュールします。
+
... [ リソース ] → [ テンプレート ] に移動します。
... Log Replication Playbook テンプレートをクリックし、一番上のオプションセットにある Schedules （スケジュール）をクリックします。
... [ 追加 ] をクリックし、 [ ログ複製の名前スケジュールの追加 ] をクリックし、時間の開始時に開始日時を選択し、 [ ローカルタイムゾーン ] と [ 実行頻度 ] を選択します。実行頻度は、多くの場合、 SnapMirror レプリケーションが更新されます。




+

NOTE: 1 時間ごとの最新の更新に確実にリカバリできるように、ログスケジュールを 1 時間ごとに更新するように設定することを推奨します。



--
.データベースのリストアとリカバリ
--
ログ・レプリケーション・プレイブックのスケジュール

. ジョブテンプレートを設定して起動します。
+
.. 以前に作成したジョブテンプレートをコピーします。
+
... [ リソース ] → [ テンプレート ] に移動します。
... 「 ONTAP/CVO Setup Template 」を探して、右端で「 Copy Template 」をクリックします
... コピーしたテンプレートで [ テンプレートの編集 ] をクリックし、名前を [ リストアとリカバリプレイブック ] に変更します。
... テンプレートの同じインベントリ、プロジェクト、資格情報を保持します。
... 実行するプレイブックとして ora_recoveryyml を選択します。
... 変数は変更されませんが、 CVO クラスタの IP は変数 dst_cluster_ip に設定する必要があります。
... [ 保存 ] をクリックします .




+

NOTE: このプレイブックは、リモートサイトでデータベースをリストアする準備ができるまでは実行されません。



--
====


=== 5. Oracle データベースのリカバリ

. オンプレミスの本番 Oracle データベースのデータボリュームは、 NetApp SnapMirror レプリケーションを使用して、セカンダリデータセンターの冗長 ONTAP クラスタまたはパブリッククラウドの Cloud Volume ONTAP に保護されます。完全に構成されたディザスタリカバリ環境では、セカンダリデータセンターまたはパブリッククラウドのリカバリコンピューティングインスタンスがスタンバイ状態になり、災害発生時に本番データベースをリカバリできます。スタンバイコンピューティングインスタンスは、 OS カーネルパッチで paraellel アップデートを実行するか、ロックステップでアップグレードすることで、オンプレミスインスタンスと同期したままになります。
. この解決策で実証されている Oracle バイナリ・ボリュームは、ターゲット・インスタンスに複製され、ターゲット・インスタンスにマウントされて、 Oracle ソフトウェア・スタックが起動されます。この Oracle リカバリアプローチには、災害発生時に Oracle を新規にインストールした場合よりも優れています。Oracle のインストールは、現在のオンプレミスの本番ソフトウェアのインストールレベルやパッチレベルと完全に同期されていることが保証されます。ただし、 Oracle でのソフトウェアライセンスの構成によっては、リカバリサイトで複製された Oracle バイナリボリュームにソフトウェアライセンスが影響する場合とそうでない場合があります。ユーザは、 Oracle のライセンス要件を評価するために、ソフトウェアライセンス担当者に確認してから、同じ方法を使用することを推奨します。
. デスティネーションのスタンバイ Oracle ホストには、 Oracle の前提条件となる構成が設定されています。
. SnapMirror が切断され、ボリュームが書き込み可能になり、スタンバイ Oracle ホストにマウントされます。
. すべての DB ボリュームがスタンバイコンピューティングインスタンスにマウントされたあと、 Oracle リカバリモジュールは以下のタスクを実行して、リカバリサイトで Oracle をリカバリおよび起動します。
+
.. 制御ファイルを同期します。重要なデータベース制御ファイルを保護するために、異なるデータベースボリュームに Oracle 制御ファイルを重複して配置しました。1 つはデータボリューム上にあり、もう 1 つはログボリューム上にあります。データボリュームとログボリュームは異なる頻度でレプリケートされるため、リカバリ時に同期されません。
.. Oracle バイナリの再リンク： Oracle バイナリは新しいホストに再配置されるため、再リンクが必要です。
.. Oracle データベースのリカバリ：リカバリ・メカニズムは、 Oracle ログ・ボリューム内の最後に使用可能なアーカイブ・ログのシステム変更番号を制御ファイルから取得し、 Oracle データベースをリカバリして、障害発生時に DR サイトにレプリケートされたすべてのビジネス・トランザクションをリカバリします。次に、データベースが新しいインカネーションで起動され、リカバリサイトでユーザ接続とビジネストランザクションが実行されます。





NOTE: Recovering Playbook を実行する前に、次の情報を確認してください。 /etc/oratab および /etc/oraInst.loc を介して、ソース Oracle ホストからデスティネーションホストにコピーしてください
