---
sidebar: sidebar 
permalink: ent-apps-db/saphana-fas-nfs_host_setup.html 
keywords: host, setup, configuration, parameter, enterprise, suse, linux, subdirectories, create, mount, points, file, systems 
summary: このセクションで説明するすべての手順は、物理サーバ上の SAP HANA 環境と、 VMware vSphere 上で実行される SAP HANA 環境の両方で有効です。 
---
= ホストのセットアップ
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


このセクションで説明するすべての手順は、物理サーバ上の SAP HANA 環境と、 VMware vSphere 上で実行される SAP HANA 環境の両方で有効です。



== SUSE Linux Enterprise Server の構成パラメータ

各 SAP HANA ホストでは、 SAP HANA によって生成されるワークロードに合わせて、追加のカーネルパラメータと構成パラメータを調整する必要があります。



=== SUSE Linux Enterprise Server 12 および 15

SUSE Linux Enterprise Server （ SLES ） 12 SP1 以降、カーネルパラメータは /etc/sysctl.d`d ディレクトリ内の構成ファイルで設定する必要があります。たとえば '91-NetApp-/hana.conf という名前の構成ファイルを作成する必要があります

....
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 131072 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.core.netdev_max_backlog = 300000net.ipv4.tcp_slow_start_after_idle=0net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
....

NOTE: SAP OS バージョン用の SLES に含まれている Saptune を使用してこれらの値を設定できます。を参照してください https://launchpad.support.sap.com/["SAP ノート 3024346"^] （ SAP ログインが必要です）。

NFSv3 を使用してストレージを接続する場合は、 'sunrpc.tcp_max_slot_table_entries パラメータを /etc/modprobe.d/sunrpc.conf に設定する必要があります。ファイルが存在しない場合は、次の行を追加して先に作成する必要があります。

....
options sunrpc tcp_max_slot_table_entries=128
....
nConnect マウント・オプションを使用する場合は ' 上記の値を 256 から 512 に増やすことができます



== Red Hat Enterprise Linux 7.2 以降の構成パラメータ

SAP HANA で生成されるワークロードに合わせて、各 SAP HANA ホストで追加のカーネルパラメータと構成パラメータを調整する必要があります。

ストレージの接続に NFSv3 を使用する場合は、 /etc/modprobe.d/sunrpc.conf 内のパラメータ 'unrpc.tcp_max_slot_table_entries を設定する必要があります。ファイルが存在しない場合は、次の行を追加して作成する必要があります。

....
options sunrpc tcp_max_slot_table_entries=128
....
nConnect マウント・オプションを使用する場合は ' 上記の値を 256 から 512 に増やすことができます

Red Hat Enterprise Linux 7.2 以降では、 /etc/sysctl.d` ディレクトリにある構成ファイルでカーネルパラメータを設定する必要があります。たとえば '91-NetApp-/hana.conf という名前の構成ファイルを作成する必要があります

....
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 131072 16777216
net.ipv4.tcp_wmem = 4096 16384  16777216
net.core.netdev_max_backlog = 300000net.ipv4.tcp_slow_start_after_idle=0net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
....


== /hana/shared ボリュームにサブディレクトリを作成します


NOTE: 以下の例は、 SID=NF2 の SAP HANA データベースを示しています。

必要なサブディレクトリを作成するには、次のいずれかの操作を行います。

* シングル・ホスト・システムの場合は '/hana/shared-volume をマウントし 'hared' サブディレクトリと usr-sap サブディレクトリを作成します


....
sapcc-hana-tst-06:/mnt # mount <storage-hostname>:/NF2_shared /mnt/tmp
sapcc-hana-tst-06:/mnt # cd /mnt/tmp
sapcc-hana-tst-06:/mnt/tmp # mkdir shared
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap
sapcc-hana-tst-06:/mnt/tmp # umount /mnt/tmp
....
* マルチ・ホスト・システムの場合は '/hana/shared-volume をマウントし ' 各ホストの 'hared' サブディレクトリと 'usr-sap' サブディレクトリを作成します
+
以下のコマンド例は、 2+1 のマルチホスト HANA システムを示しています。



....
sapcc-hana-tst-06:/mnt # mount <storage-hostname>:/NF2_shared /mnt/tmp
sapcc-hana-tst-06:/mnt # cd /mnt/tmp
sapcc-hana-tst-06:/mnt/tmp # mkdir shared
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host1
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host2
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host3
sapcc-hana-tst-06:/mnt # cd ..
sapcc-hana-tst-06:/mnt/tmp # umount /mnt/tmp
....


== マウントポイントを作成する


NOTE: 以下の例は、 SID=NF2 の SAP HANA データベースを示しています。

必要なマウントポイントディレクトリを作成するには、次のいずれかの操作を行います。

* シングルホストシステムの場合は、マウントポイントを作成し、データベースホストに権限を設定します。


....
sapcc-hana-tst-06:/ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-06:/ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-06:/ # mkdir -p /hana/shared
sapcc-hana-tst-06:/ # mkdir -p /usr/sap/NF2
sapcc-hana-tst-06:/ # chmod –R 777 /hana/log/NF2
sapcc-hana-tst-06:/ # chmod –R 777 /hana/data/NF2
sapcc-hana-tst-06:/ # chmod -R 777 /hana/shared
sapcc-hana-tst-06:/ # chmod -R 777 /usr/sap/NF2
....
* マルチホストシステムの場合は、マウントポイントを作成し、すべてのワーカーホストとスタンバイホストに権限を設定します。
+
以下のコマンド例は、 2+1 のマルチホスト HANA システムを示しています。

+
** 1 つ目のワーカーホスト：




....
sapcc-hana-tst-06:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-06:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-06:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-06:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-06:~ # mkdir -p /hana/shared
sapcc-hana-tst-06:~ # mkdir -p /usr/sap/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-06:~ # chmod -R 777 /usr/sap/NF2
....
* 2 つ目のワーカーホスト：


....
sapcc-hana-tst-07:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-07:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-07:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-07:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-07:~ # mkdir -p /hana/shared
sapcc-hana-tst-07:~ # mkdir -p /usr/sap/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-07:~ # chmod -R 777 /usr/sap/NF2
....
* スタンバイホスト：


....
sapcc-hana-tst-08:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-08:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-08:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-08:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-08:~ # mkdir -p /hana/shared
sapcc-hana-tst-08:~ # mkdir -p /usr/sap/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-08:~ # chmod -R 777 /usr/sap/NF2
....


== ファイルシステムをマウント

NFS のバージョンと ONTAP のリリースに応じて、異なるマウントオプションを使用する必要があります。次のファイルシステムをホストにマウントする必要があります。

* 「 /hana/data/sid/mnt0000* 」と入力します
* 「 /hana/log/sid/mnt0000* 」と入力します
* 「 /hana/shared 」
* /usr/sap/SID


次の表に、シングルホスト SAP HANA データベースとマルチホスト SAP HANA データベースのファイルシステムごとに使用する必要がある NFS のバージョンを示します。

|===
| ファイルシステム | SAP HANA シングルホスト | SAP HANA マルチホスト 


| /hana/data/sid/mnt0000* | NFSv3 または NFSv4 | NFSv4 


| /hana/log/sid/mnt0000* | NFSv3 または NFSv4 | NFSv4 


| /hana/shared にアクセスします | NFSv3 または NFSv4 | NFSv3 または NFSv4 


| /usr/sap/SID | NFSv3 または NFSv4 | NFSv3 または NFSv4 
|===
次の表に、 NFS の各バージョンと ONTAP のリリースのマウントオプションを示します。共通パラメータは、 NFS と ONTAP のバージョンには依存しません。


NOTE: SAP LaMa では、 /usr/sap/SID ディレクトリをローカルにする必要があります。したがって、 SAP LaMa を使用している場合は、 /usr/sap/SID の NFS ボリュームをマウントしないでください。

NFSv3 では、ソフトウェアまたはサーバに障害が発生した場合に NFS ロックのクリーンアップ処理が行われないようにするため、 NFS ロックをオフにする必要があります。

ONTAP 9 では、 NFS 転送サイズを最大 1MB に設定できます。具体的には、 40GbE 以上でのストレージシステムへの接続では、スループットの期待値を達成するために転送サイズを 1MB に設定する必要があります。

|===
| 共通パラメータ | NFSv3 | NFSv4 | NFSv4.1 | ONTAP 9 での NFS 転送サイズ | ONTAP 8 での NFS 転送サイズ 


| rw 、 bg 、 hard 、 timeo = 600 、 noatime 、 | バー = 3 、 nolock 、 | vers=4 、 minorversion=0 、 lock です | vers=4 、 minorversion=1 、 lock です | rsize=1048576 、 wsize=1048576 、 | rsize=65536 、 wsize=65536 、 
|===

NOTE: NFSv3 の読み取りパフォーマンスを向上させるには、「 nConnect=n 」マウントオプションを使用することをお勧めします。このオプションは、 SUSE Linux Enterprise Server 12 SP4 以降および RedHat Enterprise Linux （ RHEL ） 8.3 以降で使用できます。


NOTE: パフォーマンス・テストでは 'nConnect=8' の読み取り結果が良好であることが示されていますログの書き込みには 'nConnect=2.' など ' セッション数が少ないことがメリットとなります NFS サーバからの最初のマウント（ IP アドレス）では、使用されるセッションの量が定義されることに注意してください。それ以降のマウントでは 'nConnect' に異なる値が使用されていても ' この値は変更されません


NOTE: ONTAP 9.8 および SUSE SLES15SP2 または Red Hat RHEL 8.3 以降では、ネットアップで NFSv4.1 の nConnect オプションがサポートされます。追加情報については、 Linux ベンダーのマニュアルを参照してください。

/etc/fstab 構成ファイルを使用してシステムのブート中にファイル・システムをマウントするには ' 次の手順を実行します

次の例は、 SID=NF2 で、 NFSv3 を使用し、 NFS 転送サイズが 1MB の、シングルホスト SAP HANA データベースを示しています。

. 必要なファイル・システムを /etc/fstab 構成ファイルに追加します
+
....
sapcc-hana-tst-06:/ # cat /etc/fstab
<storage- vif-data01>:/NF2_data_mnt00001 /hana/data/NF2/mnt00001 nfs rw,vers=3,hard,timeo=600,rsize=1048576,wsize=1048576, bg, noatime,nolock 0 0
<storage- vif-log01>:/NF2_log_mnt00001 /hana/log/NF2/mnt00001 nfs rw,vers=3,hard,timeo=600,rsize=1048576,wsize=1048576, bg, noatime,nolock 0 0
<storage- vif-data01>:/NF2_shared/usr- sap /usr/sap/NF2 nfs rw,vers=3,hard,timeo=600,rsize=1048576,wsize=1048576, bg,  noatime,nolock 0 0
<storage- vif-data01>:/NF2_shared/shared /hana/shared nfs rw,vers=3,hard,timeo=600,rsize=1048576,wsize=1048576, bg,  noatime,nolock 0 0
....
. Run `ount – a を実行して、すべてのホストのファイルシステムをマウントします。


次の例は、 SID=NF2 で、データファイルシステムとログファイルシステムに NFSv4.1 を使用し、「 /hana/shared 」ファイルシステムと「 /usr/sap/nf2 」ファイルシステムに NFSv3 を使用する、マルチホスト SAP HANA データベースを示しています。使用される NFS 転送サイズは 1MB です。

. 必要なファイル・システムを ' すべてのホスト上の /etc/fstab 構成ファイルに追加します
+

NOTE: /usr/sap/nf2 ファイル・システムは ' データベース・ホストごとに異なります次の例は '/NF2_shared_usr-sap-host1' を示しています

+
....
sapcc-hana-tst-06:/ # cat /etc/fstab
<storage- vif-data01>:/NF2_data_mnt00001 /hana/data/NF2/mnt00001 nfs rw, vers=4, minorversion=1,hard,timeo=600,rsize=1048576,wsize=1048576, bg, noatime,lock 0 0
<storage- vif-data02>:/NF2_data_mnt00002 /hana/data/NF2/mnt00002 nfs rw, vers=4, minorversion=1,hard,timeo=600,rsize=1048576,wsize=1048576, bg, noatime,lock 0 0
<storage- vif-log01>:/NF2_log_mnt00001 /hana/log/NF2/mnt00001 nfs rw, vers=4, minorversion=1,hard,timeo=600,rsize=1048576,wsize=1048576, bg, noatime,lock 0 0
<storage- vif-log02>:/NF2_log_mnt00002 /hana/log/NF2/mnt00002 nfs rw, vers=4, minorversion=1,hard,timeo=600,rsize=1048576,wsize=1048576, bg, noatime,lock 0 0
<storage- vif-data02>:/NF2_shared/usr- sap- host1 /usr/sap/NF2 nfs rw,vers=3,hard,timeo=600,rsize=1048576,wsize=1048576, bg, noatime,nolock 0 0
<storage- vif-data02>:/NF2_shared/shared /hana/shared nfs rw,vers=3,hard,timeo=600,rsize=1048576,wsize=1048576, bg, noatime,nolock 0 0
....
. Run `ount – a を実行して、すべてのホストのファイルシステムをマウントします。

