---
sidebar: sidebar 
permalink: ent-apps-db/saphana-dr-anf_prepare_the_target_host_01.html 
keywords: prepare, target, host, sap, hana, azure, log, volume, users, ports, configure, file, system 
summary: ここでは、ディザスタリカバリフェイルオーバーに使用するサーバで必要な準備手順について説明します。 
---
= ターゲットホストを準備します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ここでは、ディザスタリカバリフェイルオーバーに使用するサーバで必要な準備手順について説明します。

通常運用時は、 HANA の QA やテスト用システムなど、通常はターゲットホストがその他の目的に使用されます。そのため、災害時のフェイルオーバーテストを実行する際には、ほとんどの手順を実行する必要があります。一方、関連する構成ファイルは、「 /etc/fstab 」や「 /usr/sap/sapservices 」のように準備し、構成ファイルをコピーするだけで運用に移すことができます。ディザスタリカバリフェイルオーバー手順は、準備された関連する構成ファイルが確実に正しく設定されるようにします。

ターゲット・ホストの準備には、 HANA の QA またはテスト・システムのシャットダウン、および「 systemctl stop sapinit 」を使用したすべてのサービスの停止も含まれます。



== ターゲットサーバのホスト名と IP アドレス

ターゲット・サーバのホスト名は ' ソース・システムのホスト名と同じである必要がありますIP アドレスは異なっていてもかまいません。


NOTE: ターゲットサーバが他のシステムと通信できないように、ターゲットサーバの適切なフェンシングを確立する必要があります。適切なフェンシングが設定されていないと、クローニングされた本番用システムは、他の本番用システムとデータを交換し、論理的にデータが破損する可能性があります。



== 必要なソフトウェアをインストールします

SAP ホストエージェントソフトウェアをターゲットサーバにインストールする必要があります。詳細については、を参照してください https://help.sap.com/viewer/9f03f1852ce94582af41bb49e0a667a7/103/en-US["SAP ホストエージェント"^] SAP ヘルプポータルで、次の作業を行います。


NOTE: ホストが HANA QA またはテストシステムとして使用されている場合は、 SAP ホストエージェントソフトウェアがすでにインストールされています。



== ユーザ、ポート、および SAP サービスを設定する

ターゲットサーバに、 SAP HANA データベースに必要なユーザとグループが配置されている必要があります。通常は、ユーザの一元管理が使用されるため、ターゲットサーバで設定手順を行う必要はありません。HANA データベースに必要なポートは、ターゲットホストで設定する必要があります。構成は '/etc/services ファイルをターゲット・サーバにコピーすることによって ' ソース・システムからコピーできます

必要な SAP サービスのエントリがターゲットホストにあることが必要です。/usr/sap/sapservices' ファイルをターゲットサーバにコピーすることで ' ソースシステムから構成をコピーできます次の出力は、このラボ環境で使用する SAP HANA データベースの必須エントリを示しています。

....
vm-pr1:~ # cat /usr/sap/sapservices
#!/bin/sh
LD_LIBRARY_PATH=/usr/sap/PR1/HDB01/exe:$LD_LIBRARY_PATH;export LD_LIBRARY_PATH;/usr/sap/PR1/HDB01/exe/sapstartsrv pf=/usr/sap/PR1/SYS/profile/PR1_HDB01_vm-pr1 -D -u pr1adm
limit.descriptors=1048576
....


== HANA のログボリュームを準備

HANA のログボリュームはレプリケーションの一部ではないため、空のログボリュームがターゲットホストに存在している必要があります。ログボリュームには、ソース HANA システムと同じサブディレクトリを含める必要があります。

....
vm-pr1:~ # ls -al /hana/log/PR1/mnt00001/
total 16
drwxrwxrwx 5 root   root   4096 Feb 19 16:20 .
drwxr-xr-x 3 root   root     22 Feb 18 13:38 ..
drwxr-xr-- 2 pr1adm sapsys 4096 Feb 22 10:25 hdb00001
drwxr-xr-- 2 pr1adm sapsys 4096 Feb 22 10:25 hdb00002.00003
drwxr-xr-- 2 pr1adm sapsys 4096 Feb 22 10:25 hdb00003.00003
vm-pr1:~ #
....


== ログバックアップボリュームを準備

ソースシステムは HANA ログバックアップ用の個別のボリュームで構成されているため、ターゲットホストにログバックアップボリュームも必要です。ログバックアップ用のボリュームを設定し、ターゲットホストにマウントする必要があります。

ディザスタリカバリの設定でログバックアップボリュームのレプリケーションを行う場合、複製されたログバックアップボリュームはターゲットホストにマウントされるため、追加のログバックアップボリュームを準備する必要はありません。



== ファイルシステムのマウントを準備

次の表に、このラボ環境で使用する命名規則を示します。災害復旧サイトのボリューム名は '/etc/fstab に含まれています

|===
| HANA PR1 ボリューム | ディザスタリカバリサイトにあるボリュームとサブディレクトリ | ターゲットホストのマウントポイント 


| データボリューム | pr1 -data-mnt00001 -sm -dest | /hana/data /pr1/mnt00001 


| 共有ボリューム | pr1 -shared-sm-dest/shared pr1 -shared-sm-dest/usr -sap-pr1 | /hana/shared /usr/sap/pr1 


| ログバックアップボリューム | hanabackup-sm -dest | / はなんバックアップ 
|===

NOTE: このテーブルのマウントポイントは、ターゲットホストに作成する必要があります。

ここでは ' 必須の /etc/fstab エントリを示します

....
vm-pr1:~ # cat /etc/fstab
# HANA ANF DB Mounts
10.0.2.4:/PR1-data-mnt0001-sm-dest /hana/data/PR1/mnt00001 nfs   rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys  0  0
10.0.2.4:/PR1-log-mnt00001-dr /hana/log/PR1/mnt00001 nfs   rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys  0  0
# HANA ANF Shared Mounts
10.0.2.4:/PR1-shared-sm-dest/hana-shared /hana/shared nfs rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys  0  0
10.0.2.4:/PR1-shared-sm-dest/usr-sap-PR1 /usr/sap/PR1 nfs rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys  0  0
# HANA file and log backup destination
10.0.2.4:/hanabackup-sm-dest    /hanabackup nfs   rw,vers=3,hard,timeo=600,rsize=262144,wsize=262144,nconnect=8,bg,noatime,nolock 0 0
....