---
sidebar: sidebar 
permalink: ent-apps-db/saphana_fas_fc_where_to_find_additional_information.html 
keywords: additional, information, sap, hana, fc 
summary: このドキュメントに記載されている情報の詳細については、以下のドキュメントや Web サイトを参照してください。 
---
= 追加情報の参照先
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana_fas_fc_adding_additional_data_volume_partitions_for_sap_hana_single-host_systems.html["前の手順： SAP HANA シングルホストシステムのデータボリュームパーティションを追加"]

このドキュメントに記載されている情報の詳細については、以下のドキュメントや Web サイトを参照してください。

* 『 Best Practices and Recommendations for Scale-Up Deployments of SAP HANA on VMware vSphere 』
+
http://www.vmware.com/files/pdf/SAP_HANA_on_vmware_vSphere_best_practices_guide.pdf["www.vmware.com/files/pdf/SAP_HANA_on_vmware_vSphere_best_practices_guide.pdf"^]

* 『 Best Practices and Recommendations for Scale-Out Deployments of SAP HANA on VMware vSphere 』
+
http://www.vmware.com/files/pdf/sap-hana-scale-out-deployments-on-vsphere.pdf["http://www.vmware.com/files/pdf/sap-hana-scale-out-deployments-on-vsphere.pdf"^]

* SAP HANA 向け SAP 認定エンタープライズストレージハードウェア
+
https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/enterprise-storage.html["https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/enterprise-storage.html"^]

* SAP HANA のストレージ要件
+
http://go.sap.com/documents/2015/03/74cdb554-5a7c-0010-82c7-eda71af511fa.html["http://go.sap.com/documents/2015/03/74cdb554-5a7c-0010-82c7-eda71af511fa.html"^]

* 『 SAP HANA Tailored Data Center Integration Frequently Asked Questions 』
+
https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html["https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html"^]

* TR-4646 ：『 SAP HANA Disaster Recovery with Asynchronous Storage Replication Using SnapCenter 4.0 SAP HANA Plug-in 』
+
https://www.netapp.com/us/media/tr-4646.pdf["https://www.netapp.com/us/media/tr-4646.pdf"^]

* TR-4614 ：『 SAP HANA Backup and Recovery with SnapCenter 』
+
https://www.netapp.com/us/media/tr-4614.pdf["https://www.netapp.com/us/media/tr-4614.pdf"^]

* TR-4338 ：『 SAP HANA on VMware vSphere with NetApp FAS and AFF Systems 』
+
http://www.netapp.com/us/media/tr-4338.pdf["www.netapp.com/us/media/tr-4338.pdf"^]

* TR-4667 ：『 Automating SAP System Copies Using the SnapCenter 4.0 SAP HANA Plug-in 』
+
https://www.netapp.com/us/media/tr-4667.pdf["https://www.netapp.com/us/media/tr-4667.pdf"^]

* ネットアップドキュメントセンター
+
https://www.netapp.com/us/documentation/index.aspx["https://www.netapp.com/us/documentation/index.aspx"^]

* NetApp FAS ストレージシステムの関連リソース
* https://mysupport.netapp.com/info/web/ECMLP2676498.html["https://mysupport.netapp.com/info/web/ECMLP2676498.html"^]
* SAP HANA ソフトウェアソリューション
+
http://www.netapp.com/us/solutions/applications/sap/index.aspx["www.netapp.com/us/solutions/applications/sap/index.aspx#sap-hana"^]



link:saphana_fas_fc_update_history.html["次：履歴を更新します。"]
