---
sidebar: sidebar 
permalink: change-log-display.html 
summary: ネットアップソリューション資料に対する最近の変更点のログ 
keywords: netapp, solutions, catalog, change, log 
---
= ネットアップソリューションの変更ログ
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/


[role="lead"]
ネットアップソリューション資料に対する最近の変更点。最新の変更が最初に表示されます。

[role="tabbed-block"]
====
.すべての変更
--
* 日付 * ： * 概要 Area * - * 解決策 of change *

12/06/2021 ： Hybrid Cloud/Virtualization - Creation of Enterprise Hybrid Cloud （ EHC ） content for virtualization environment and guest connected storage options 11/15/2021 ： Containers - Added a new video demo: Data Protection in CI/CD Pipeline with Astra Control to NVA-1160 11/15/2021 ： 『 Modern Data Analytics - new content 、 Best Practices for Conluent Kafka 11/02/2021 ： Automation - AWS Authentication Requirements for CVO and Connector using NetApp Cloud Manager 10/29/2021 ： Modern Data Analytics - new content 、 TR-4657 ： NetApp Hybrid Cloud Data Solutions - Spark and Hadoop 10/29/2021 ： Oracle Database - Automated Data Protection for Oracle Databases 10/26/2021 ： Enterprise Database - ネットアップのソリューションタイルに、エンタープライズアプリケーションとデータベースに関するブログセクションを追加。エンタープライズデータベースのブログ 10 / 18/2021 に 2 つのブログを追加： Enterprise Database-TR-4908 ：『 Hybrid Cloud Database Solutions with SnapCenter 10/14/2021 ： Virtualization - Added parts 1-4 of NetApp with VMware VCF blogs series 10 / 04/2021 ： Containers - Added a new video demo: Astra Control Center から NVA-11 60 09/23/2021 へのワークロードの移行：データの移行 - 新しいコンテンツ、 NetApp XCP 09/21/2021 のネットアップのベストプラクティス：仮想化 - 新しいコンテンツ、または VMware vSphere 管理者向けの ONTAP 、 VMware vSphere Automation 09/09/2021 ： コンテナ - OpenShift との F5 BIG-IP ロードバランサの統合を NVA-1160 08/05/2021 に追加：コンテナ - Red Hat OpenShift 07/21/2021 上の NetApp Astra Control Center に新しいテクノロジの統合を追加： Oracle Database - ONTAP 用 Oracle19c を NFS 07/02/2021 上に自動導入： SQL Server - TR-4897 ：『 SQL Server on Azure NetApp Files - Real Deployment View 06/16/2021 ： Containers - Added a new video demo: Installing OpenShift Virtualization - Red Hat OpenShift with NetApp 06/16/2021 ： Containers - Added a new video demo: OpenShift Virtualization による仮想マシンの導入 - Red Hat OpenShift と NetAppp 06/142021 ： SQL Server - Added 解決策： Azure NetApp Files 06/11/2021 ： Containers - Added a new video demo: Workload Migration using Astra Trident and SnapMirror to NVA-1160 06/09/2021 ： コンテナ - NetApp 05-28/2021 に搭載された Red Hat OpenShift での Kubernetes の高度なクラスタ管理に関する NVA-1160 の新しいユースケースを追加：コンテナ - NetApp ONTAP 05/27/2021 での NVA-1160 OpenShift 仮想化への新しいユースケースの追加： コンテナ - NetApp ONTAP 05/26/2021 で OpenShift 上の NVA-1160 マルチテナンシーに新しいユースケースを追加：コンテナ - 追加 NVA-1160-Red Hat OpenShift with NetApp 05/252021 ：コンテナ - ブログ： Installing NetApp Trident on Red Hat OpenShift – How to Solve the 'toomanyrequest' 問題！2021 年 5 月 19 日： FlexPod ソリューションへの一般的なリンクを追加 2021 年 5 月 19 日： AI による AI コントロールプレーン解決策の PDF から HTML 05/17/2021 への変換：ネットアップのソリューション - 解決策フィードバックタイルをメインページ 05 / 11/2021 に追加： 『 Oracle Database - Added automated deployment of Oracle 19C for ONTAP on NFS 05/10/2021 』：「 Virtualization-Video ： How to use VVOLs with NetApp and VMware Tanzu Basic 、 part 3 05/06/02021: Oracle Database - AFF データセンター上の Oracle 19C RAC データベースへのリンクを FC 05/05/2021 経由で Cisco UCS および NetApp FlexPod A800 に追加： Oracle Database - Added FlexPod Oracle NVA （ 1155 ） and Automation video 05/03/2021 ：デスクトップ仮想化 - FlexPod デスクトップ仮想化ソリューション 04/30/2021 へのリンクを追加： 仮想化 - ビデオ： How to use VVOLs with NetApp and VMware Tanzu Basic 、 Part 2 04/26/2021 ： Containers-Added blog ： Using VMware Tanzu with ONTAP to Accelerate Your Kubernetes Journey 04/06/2021 ： GeneralAdded "About this Repository" 03/312021 ： AI added TR-4886 ：エッジでの AI 推論： NetApp ONTAP with Lenovo ThinkSystem 解決策 Design 03/292021 ：最新のデータ分析 - NetApp Storage 解決策 03/23/2021 ： Virtualization - Video ： How to use VVOLs with NetApp and VMware Tanzu Basic 、 Part 1 03/09/2021 ： General added E-Series content; AI コンテンツの分類 03/04/2021 ： Automation - New content ： Getting started with NetApp 解決策 Automation 02/18/2021 ： Virtualization - Added TR-4597 ： VMware vSphere for ONTAP 02/16/2021 ： AI - Added Automated Deployment steps for AI Edge Inferencing 02/2021 03/02: SAP - SAP と SAP HANA のすべてのコンテンツ 02/01/2021 ：デスクトップ仮想化 - NetApp VDS を使用した VDI 、 GPU ノード 01/06/2021 のコンテンツの追加： AI - New 解決策： NVIDIA DGX A100 システムを使用した NetApp ONTAP AI と Mellanox Spectrum Ethernet Switch （設計と導入） 12/22/2020 ： General - NetApp Solutions リポジトリの初回リリース

--
.AI / データ分析
--
* 日付 * ： * 概要 Area * - * 解決策 of change * 11/15/2021 ： Modern Data Analytics - new content 、 Best Practices for Conluent Kafka 10/29/2021 ： Modern Data Analytics - new content 、 TR-4657 ： NetApp Hybrid Cloud Data Solutions - Spark and Hadoop 05/19/2021 ： AI で AI コントロールプレーン解決策を PDF から HTML 03/312021 に変換： AI による TR 4886 ：エッジでの AI 推論： ONTAP Lenovo ThinkSystem 解決策 Design 03/29/2021 ： Modern Data Analytics - Added NVA-1157 ： Apache Spark Workload with NetApp Storage 解決策 02/16/2021 ： AI - AI エッジ推論 01/06/2021 の自動導入手順を追加： AI - New 解決策： NVIDIA DGX A100 システムと Mellanox Spectrum イーサネットスイッチを使用した NetApp ONTAP AI （設計と導入）

--
.仮想化
--
* 日付 * ： * 概要 Area * - * 解決策 of change * 12/06/2021 ： Hybrid Cloud/Virtualization - Creation of Enterprise Hybrid Cloud （ EHC ） content for virtualization environment and guest connected storage options 10/14/2021 ： Virtualization Added parts 1-4 of NetApp with VMware VCF bblog series 09/21/2021 ： Virtualization-new content or ONTAP for VMware vSphere Administrators, VMware vSphere Automation 05/10/2021 ：仮想化 - ビデオ：ネットアップと VMware の Tanzu Basic による VVOL の使用方法、パート 3 04/30/2021 ：仮想化 - ビデオ：ネットアップと VMware の Tanzu Basic による VVOL の使用方法、パート 2 04/26/2021 ： コンテナ - ブログ： Using VMware Tanzu with ONTAP to Accelerate Your Kubernetes Journey 03/23/2021 ： Virtualization - Video ： How to use VVOLs with NetApp and VMware Tanzu Basic 、 Part 1 02/18/2021 ： Virtualization Added TR-4597 ： VMware vSphere for ONTAP

--
.仮想デスクトップ
--
* 日付 * ： * FlexPod Area* - * 概要 of change * 05/03/2021 ：デスクトップ仮想化 - 解決策デスクトップ仮想化ソリューション 02/01/2021 へのリンク追加：デスクトップ仮想化 - NetApp VDS を使用した VDI 、 GPU ノードのコンテンツの追加

--
.コンテナ
--
* 日付 * ： * 概要 Area* - * 解決策 of change * 11/15/2021 ：コンテナ - Added a new video demo: Data Protection in CI/CD Pipeline with Astra Control to NVA-1160 10/04/2021 ：コンテナ - 新しいビデオデモを追加： Astra Control Center を使用したワークロードの移行 09/09/2021 ： コンテナ - OpenShift を使用した F5 BIG-IP ロードバランサと NVA-1160 08/05/2021 に統合：コンテナ - Red Hat OpenShift 06/16/2021 上の NetApp Astra Control Center に新しいテクノロジ統合を追加 - コンテナ - 新しいビデオデモを追加： OpenShift Virtualization のインストール - Red Hat OpenShift with NetApp 06/162021 ：コンテナ - Added a new video demo: Deploying a Virtual Machine with OpenShift Virtualization - Red Hat OpenShift with NetAppp 06/11/2021 ： Containers - Added a new video demo: Astra Trident と SnapMirror を使用した NVA-1160 06/09/2021 ：コンテナ - Added a new usion-case to NVA-1160 - Advanced Cluster Management for Kubernetes on Red Hat OpenShift with NetApp 05/28/2021 ：コンテナ - Added a new usion-case to NVA-1160-OpenShift Virtualization with NetApp ONTAP 05/27/2021 ： コンテナ - NetApp ONTAP 05/26/2021 で OpenShift 上の NVA-1160 マルチテナンシーに新しいユースケースを追加：コンテナ - 追加 NVA-1160-Red Hat OpenShift with NetApp 05/252021 ：コンテナ - ブログ： Installing NetApp Trident on Red Hat OpenShift – How to Solve the 'toomanyrequest' 問題！05/10/2021 ：仮想化 - ビデオ： How to use VVOLs with NetApp and VMware Tanzu Basic, part 3 04/30/2021 ：仮想化 - ビデオ： How to use VVOLs with NetApp and VMware Tanzu Basic, part 2 04/26/2021 ： Containers - Added bblog ： 『 Using VMware Tanzu with ONTAP to Accelerate Your Kubernetes Journey 03/23/2021 』：「仮想化 - ビデオ： How to use VVOLs with NetApp and VMware Tanzu Basic 、 part 1

--
.エンタープライズアプリケーション
--
* 日付 * ： * 概要 Area * - * 解決策 of change * 02/03/2021 ： SAP - Added landing page for all SAP and SAP HANA content

--
.エンタープライズデータベース
--
* 日付 * ： * 概要 Area * - * 解決策 of change * 10/29/2021 ： Oracle Database の自動データ保護： 10/26/2021 ： Enterprise Database - Added Blog section for enterprise applications and database to NetApp solutions tileエンタープライズデータベースのブログ 10 / 18/2021 に、 2 つのブログを追加しました。エンタープライズデータベース - TR-4908 ：『 Hybrid Cloud Database Solutions with SnapCenter 07/21/2021 』：『 Oracle Database - Automated Deployment of Oracle19c for ONTAP on NFS 07/02/2021 ： SQL Server - TR-487: SQL Server on Azure NetApp Files - Real Deployment View 06/14/2021 ： SQL Server - Added 解決策： Microsoft SQL Server on Azure NetApp Files 05/11/2021 ： Oracle Database - Added automated deployment of Oracle 19C for ONTAP on NFS 05/06/2021 ： Oracle Database - AFF データセンター上の Oracle 19C RAC データベースへのリンクを追加。 Cisco UCS および NetApp FlexPod A800 over FC 05/05/2021 ： Oracle Database - Added FlexPod Oracle NVA （ 1155 ） and Automation のビデオをご覧ください

--
.データ保護と移行
--
* 日付 * ： * 概要 Area* - * 解決策 of change * 10/29/2021 ： Oracle Database の自動データ保護 09/23/2021 ：データ移行 - 新しいコンテンツ、 NetApp XCP 向けネットアップのベストプラクティス

--
.解決策の自動化
--
* 日付 * ： * ONTAP Area* - * 概要 of change * 11/022021 ： NetApp Cloud Manager 10/29/2021 を使用した CVO とコネクタの自動化 - AWS 認証の要件： Oracle Database - Oracle Database の自動化されたデータ保護 07/21/2021 ： Oracle Database - 解決策 for 05/11/2021 の自動導入： Oracle Database - ONTAP 19C for 解決策の自動導入を NFS 03/04/2021 ： Automation - New content: Getting started with NetApp automation

--
====