---
sidebar:
  entries:
  - title: ネットアップソリューションのドキュメント
    url: "/index.html"
  - section: ai
  - section: data-analytics
  - section: hybrid-cloud
  - section: vdi-vds
  - section: containers
  - section: biz-apps
  - section: ent-db
  - section: dp-sec
  - section: infra
  - section: automation
  - title: FlexPod ソリューション
    url: https://docs.netapp.com/us-en/flexpod/
  - title: 変更ログ
    url: "/change-log-display.html"
  - title: ネットアップのソリューションについて
    url: "/about.html"
homepage:
  tiles:
  - title: AI による最新データ分析
    links:
    - title: 新機能
      summary: 最新の AI ソリューションと最新のデータ分析ソリューションをご確認ください
      url: aimda-whatsnew.html
    - title: NetApp Data Science ツールキット
      summary: データサイエンティストとエンジニア向けのデータ管理ツールキット
      url: https://github.com/NetApp/netapp-data-science-toolkit
    - title: ビデオとデモ
      summary: AI と最新データ分析のためのショートビデオ / デモ の機能
      url: aimda-videos.html
    - title: ブログ
      summary: AI と最新のデータ分析機能を紹介したテクニカルブログです
      url: aimda-blogs.html
  - title: ハイブリッドクラウド、仮想化コンテナ
    links:
    - title: 新機能
      summary: 最新のハイブリッドクラウド、仮想デスクトップ、コンテナソリューションをご確認ください
      url: hc-whatsnew.html
    - title: ビデオとデモ
      summary: ハイブリッドクラウド、仮想化、コンテナ機能に関する短いビデオ / デモ
      url: hc-videos.html
    - title: ブログ
      summary: ハイブリッドクラウド、仮想化、コンテナ機能を紹介するテクニカルブログ
      url: hc-blogs.html
  - title: ビジネスアプリケーションエンタープライズデータベース
    links:
    - title: 新機能
      summary: 最新の Business Applications Enterprise Database ソリューションをご確認ください
      url: appsdb-whatsnew.html
    - title: ビデオとデモ
      summary: Business Applications Enterprise Database 機能のショートビデオ / デモ
      url: appsdb-videos.html
  - title: データ保護セキュリティ
    links:
    - title: 新機能
      summary: 最新のデータ保護セキュリティソリューションをご確認ください
      url: dpsec-whatsnew.html
  - title: 解決策の自動化
    links:
    - title: 新機能
      summary: ネットアップのソリューションの最新の自動化機能をご確認ください
      url: automation-whatsnew.html
    - title: ビデオとデモ
      summary: ネットアップソリューション自動化に関するショートビデオ / デモ
      url: automation-videos.html
    - title: 自動化をリクエスト
      summary: 新しい自動化を申請したい場合は、リクエストフォームに必要事項を入力してください。
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Automation]%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20%3Crequest_title%3E
  - title: フィードバック
    links:
    - title: 新しい解決策を提案する
      summary: 提供されていない解決策をお探しですか？お探しの解決策の概要を教えてください。
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Solution]%0d%0a%0d%0aSolution%20Use%20Case:%20%0d%0aSolution%20Description:%20%0d%0aAdditional%20Comments:&title=Request%20Solution%20-%20%3Csolution%3E
    - title: 解決策に関するご意見・ご要望
      summary: 既存の解決策に関するご質問やご意見はありますか？解決策資料に関するフィードバックをお寄せください。
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Solution%20Feedback]%0d%0a%0d%0aSolution%20Name:%20%0d%0aSolution%20Feedback:%20%0d%0aAdditional%20Comments:&title=Solution%20Feedback%20-%20%3Csolution%3E
