---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: false
    lipi_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: ネットアップソリューションのドキュメント
    url: "/index.html"
  - section: ai
  - section: containers
  - section: data-access
  - title: エンタープライズアプリケーション
    entries:
    - title: SAP SAP HANAの導入に最適です
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - section: databases
  - section: data-analytics
  - section: ehc
  - section: rhhc
  - section: virtualization
  - section: automation
  - title: FlexPod ソリューション
    url: https://docs.netapp.com/us-en/flexpod/
  - title: レガシー NetApp HCI ソリューション
    url: https://docs.netapp.com/us-en/hci-solutions/
  - title: 変更ログ
    url: "/change-log-display.html"
  - title: ネットアップのソリューションについて
    url: "/about.html"
  - title: 法的通知
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: このリポジトリについて
      url: about.html
    - title: 変更履歴
      url: change-log-display.html
    - title: ブログ
      url: blogs.html
    - title: デモビデオ
      url: videos.html
    - title: 法的通知
      url: legal-notices.html
  - title: 解決策 ランディングページ
    links:
    - title: 人工知能
      url: ai/index.html
    - title: コンテナ
      url: containers/index.html
    - title: エンタープライズデータベース
      url: databases/index.html
    - title: 最新のデータ分析
      url: data-analytics/index.html
    - title: VMwareを使用したネットアップのハイブリッドマルチクラウド
      url: ehc/index.html
    - title: Red Hatを使用したネットアップのハイブリッドマルチクラウド
      url: rhhc/index.html
    - title: SAP と SAP HANA に対応しています
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/index.html
    - title: 仮想化
      url: virtualization/index.html
  - title: 解決策の自動化
    links:
    - title: はじめに
      url: automation/automation_introduction.html
    - title: はじめに
      url: automation/getting-started.html
    - title: 自動化をリクエスト
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Automation]%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20%3Crequest_title%3E
  - title: FlexPod - ネットアップの Cisco 解決策
    links:
    - title: FlexPod ソリューションのテクニカルコンテンツ
      url: https://docs.netapp.com/us-en/flexpod/
    - title: FlexPod のセールスページ
      url: https://flexpod.com
    - title: ビデオとデモ
      url: https://tv.netapp.com/search?q=flexpod
    - title: ブログ
      url: https://blog.netapp.com/tag/FlexPod/
  - title: フィードバック
    links:
    - title: 新しい解決策を提案する
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Solution]%0d%0a%0d%0aSolution%20Use%20Case:%20%0d%0aSolution%20Description:%20%0d%0aAdditional%20Comments:&title=Request%20Solution%20-%20%3Csolution%3E
    - title: 解決策に関するご意見・ご要望
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Solution%20Feedback]%0d%0a%0d%0aSolution%20Name:%20%0d%0aSolution%20Feedback:%20%0d%0aAdditional%20Comments:&title=Solution%20Feedback%20-%20%3Csolution%3E
