---
sidebar: sidebar 
permalink: videos.html 
summary: ネットアップのソリューションの多くの機能を紹介する一連のビデオとデモ 
keywords: netapp, solutions, videos, demos 
---
= ネットアップのソリューション：ビデオとデモ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/


[role="lead"]
ネットアップのソリューションの特定の機能を紹介するビデオとデモの概要

.人工知能（AI）と最新のデータ分析
[#ai%collapsible]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO["ネットアップの AI ソリューション"^]
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW["MLOps の 1 つです"^]


====
.エンタープライズアプリケーションとデータベース
[#db%collapsible]
====
[下線]#*オープンソースデータベース用のビデオ*#

[cols="5a, 5a, 5a"]
|===


 a| 
PostgreSQLの自動導入、HA/DRレプリケーションのセットアップ、フェイルオーバー、再同期

 a| 
 a| 

|===
[underline]#* AWSとFSX *でハイブリッドクラウドを使用したOracleの最新化に関するビデオ

[cols="5a, 5a, 5a"]
|===


 a| 
パート1 -ユースケースと解決策 アーキテクチャ

 a| 
パート2a -自動PDB再配置機能を使用した、オンプレミスからAWSへのデータベース移行と可用性の最大化

 a| 
パート2b - SnapMirrorを使用したBlueXPコンソールを使用したオンプレミスからAWSへのデータベースの移行




 a| 
第3部-データベースの自動HA / DRレプリケーションのセットアップ、フェイルオーバー、再同期

 a| 
パート4a -複製されたスタンバイコピーから、SnapCenter UIを使用した開発とテストのためのデータベースクローン

 a| 
パート4b - SnapCenter UIを使用したデータベースのバックアップ、リストア、クローニング




 a| 
パート4c -データベースのバックアップ、BlueXP SaaS Appsによるリストアのバックアップとリカバリ

 a| 
 a| 

|===
[下線]#* SQL Serverデータベース用ビデオ*#

[cols="5a, 5a, 5a"]
|===


 a| 
Amazon FSX for NetApp ONTAP を使用して、AWS EC2にSQL Serverを導入します

 a| 
ストレージSnapshotを使用したOracleマルチテナントプラグイン可能なデータベースクローン

video::krzMWjrrMb0[youtube,width=360] a| 
Ansible による FlexPod での Oracle 19C RAC の自動導入

video::VcQMJIRzhoY[youtube,width=360]
|===
*ケーススタディ*

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study["Azure NetApp Files を使用して SAP を運用"^]


====
.ハイブリッドマルチクラウド（HMC）
[#hmc%collapsible]
====
[下線]#* AWS/VMC *#用ビデオ

[cols="5a, 5a, 5a"]
|===


 a| 
iSCSIを使用したFSX ONTAP を使用したWindowsゲスト接続ストレージ

 a| 
NFSを使用したFSX ONTAP を使用したLinuxゲスト接続ストレージ

 a| 
Amazon FSX for NetApp ONTAP を使用すると、VMware Cloud on AWSのTCOを削減できます




 a| 
AWS上のVMware Cloud追加データストア、Amazon FSX for NetApp ONTAP

 a| 
VMCのVMware HCX展開と構成のセットアップ

 a| 
VMCおよびFSxN向けVMware HCXによるVMotion移行のデモ




 a| 
VMware HCX for VMCおよびFSxNを使用したコールドマイグレーションデモ

 a| 
 a| 

|===
[underline]#* Azure/AVSのビデオ*#

[cols="5a, 5a, 5a"]
|===


 a| 
Azure NetApp Files を使用したAzure VMware解決策 補足データストアの概要

 a| 
Cloud Volumes ONTAP 、SnapCenter 、JetStreamを使用したAzure VMware解決策 DR

 a| 
VMware HCX for AVSとANFを使用したコールドマイグレーションデモ




 a| 
VMware HCX for AVSとANFでのvMotionのデモ

 a| 
AVSとANF向けVMware HCXの一括移行デモ

 a| 

|===
====
.Red Hat OpenShiftを使用したハイブリッドマルチクラウド
[#rhhc%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Astra Controlサービスを使用したRosa DR

 a| 
FSxNとAstra Tridentの統合

 a| 
FSxNを使用したROSA上のアプリのフェイルオーバーとフェイルバック




 a| 
Astra Control Centerを使用したDR

link:https://www.netapp.tv/details/29504?mcid=35609780286441704190790628065560989458["NetAppTVで視聴できます"]
 a| 
 a| 

|===
====
.仮想化
[#virtualization%collapsible]
====
* link:virtualization/vsphere_demos_videos.html["VMwareビデオコレクション"]


====
.コンテナ/ Kubernetes
[#containers%collapsible]
====
* link:containers/anthos-with-netapp/a-w-n_videos_and_demos.html["NetAppとGoogle Anthosのビデオ"]
* link:containers/tanzu_with_netapp/vtwn_videos_and_demos.html["ネットアップとVMware Tanzuのビデオ"]
* link:containers/devops_with_netapp/dwn_videos_and_demos.html["ネットアップのDevOps向けビデオ"]
* link:containers/rh-os-n_videos_and_demos.html["Red Hat OpenShiftを搭載したネットアップのビデオをご覧ください"]


====
.解決策の自動化
[#automation%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Ansible による FlexPod での Oracle 19C RAC の自動導入

video::VcQMJIRzhoY[youtube,width=360] a| 
 a| 

|===
====