---
sidebar: sidebar 
permalink: videos.html 
summary: ネットアップのソリューションの多くの機能を紹介する一連のビデオとデモ 
keywords: netapp, solutions, videos, demos 
---
= ネットアップのソリューション：ビデオとデモ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ネットアップのソリューションの特定の機能を紹介するビデオとデモの概要

.人工知能（AI）と最新のデータ分析
[#ai%collapsible%open]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO["ネットアップの AI ソリューション"^]
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW["MLOps の 1 つです"^]


====
.エンタープライズアプリケーションとデータベース
[#db%collapsible%open]
====
[下線]#*オープンソースデータベース用のビデオ*#

.PostgreSQLの自動導入、HA/DRレプリケーションのセットアップ、フェイルオーバー、再同期
video::c381b887-8c8b-4d7d-8b0f-b0c0010c5c04[panopto,width=360]
[下線]#* Oracleデータベース用のビデオ*#

.ASMを使用したGCNV上のDataGuardスタンバイからのOracle DBの自動クローニング
video::74062c18-b120-45b7-9bf9-b2db00f73675[panopto,width=360]
.SnapCenterを使用したANFでのOracleデータベースのバックアップ、リカバリ、クローン
video::960fb370-c6e0-4406-b6d5-b110014130e8[panopto,width=360]
.NFSを使用したAzure NetApp FilesへのOracle導入の簡易化と自動化
video::d1c859b6-e45a-44c7-8361-b10f012fc89b[panopto,width=360]
.Amazon FSx ONTAP with iSCSIへのOracle導入の簡易化と自動化
video::81e389a0-d9b8-495c-883b-b0d701710847[panopto,width=360]
.iSCSIを使用したNetApp ASAへのOracle導入の簡易化と自動化
video::79095731-6b02-41d5-9fa1-b0c00100d055[panopto,width=360]
.パート1 - AWSとFSx ONTAPでのハイブリッドクラウドによるOracleの最新化
video::b1a7bb05-caea-44a0-bd9a-b01200f372e9[panopto,width=360]
.パート2a -自動PDB再配置機能を使用した、オンプレミスからAWSへのデータベース移行と可用性の最大化
video::bb088a3e-bbfb-4927-bf44-b01200f38b17[panopto,width=360]
.パート2b - SnapMirrorを使用したBlueXPコンソールを使用したオンプレミスからAWSへのデータベースの移行
video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto,width=360]
.第3部-データベースの自動HA / DRレプリケーションのセットアップ、フェイルオーバー、再同期
video::5fd03759-a691-4007-9748-b01200f3b79c[panopto,width=360]
.パート4a -複製されたスタンバイコピーから、SnapCenter UIを使用した開発とテストのためのデータベースクローン
video::2f731d7c-0873-4a4d-8491-b01200f90a82[panopto,width=360]
.パート4b - SnapCenter UIを使用したデータベースのバックアップ、リストア、クローニング
video::97790d62-ff19-40e0-9784-b01200f920ed[panopto,width=360]
.パート4c -データベースのバックアップ、BlueXP SaaS Appsによるリストアのバックアップとリカバリ
video::4b0fd212-7641-46b8-9e55-b01200f9383a[panopto,width=360]
[下線]#* SQL Serverデータベース用ビデオ*#

.Amazon FSx ONTAPを使用してAWS EC2にSQL Serverを導入
video::27f28284-433d-4273-8748-b01200fb3cd7[panopto,width=360]
.ストレージSnapshotを使用したOracleマルチテナントプラグイン可能なデータベースクローン
video::krzMWjrrMb0[youtube,width=360]
.Ansible による FlexPod での Oracle 19C RAC の自動導入
video::VcQMJIRzhoY[youtube,width=360]
*ケーススタディ*

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study["Azure NetApp Files を使用して SAP を運用"^]


====
.ハイブリッドマルチクラウド（HMC）
[#hmc%collapsible%open]
====
[下線]#* AWS/VMC *#用ビデオ

.iSCSIを使用したFSX ONTAP を使用したWindowsゲスト接続ストレージ
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.NFSを使用したFSX ONTAP を使用したLinuxゲスト接続ストレージ
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.Amazon FSx ONTAPを使用したVMware Cloud on AWSのTCO削減率
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.Amazon FSx ONTAPを使用したVMware Cloud on AWSの補完的データストア
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.VMCのVMware HCX展開と構成のセットアップ
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.VMware HCX for VMCとFSx ONTAPを使用したVMotion移行のデモ
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.VMware HCX for VMCとFSx ONTAPによるコールド移行のデモ
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
[underline]#* Azure/AVSのビデオ*#

.Azure NetApp Files を使用したAzure VMware解決策 補足データストアの概要
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
.Cloud Volumes ONTAP 、SnapCenter 、JetStreamを使用したAzure VMware解決策 DR
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.VMware HCX for AVSとANFを使用したコールドマイグレーションデモ
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.VMware HCX for AVSとANFでのvMotionのデモ
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.AVSとANF向けVMware HCXの一括移行デモ
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.Red Hat OpenShiftを使用したハイブリッドマルチクラウド
[#rhhc%collapsible%open]
====
.Amazon FSx ONTAPストレージを使用したRed Hat OpenShift Service on AWS（ROSA）クラスタでのアプリケーションのスナップショット/リストア
video::36ecf505-5d1d-4e99-a6f8-b11c00341793[panopto,width=360]
.FSx ONTAPとTridentの統合
video::621ae20d-7567-4bbf-809d-b01200fa7a68[panopto,width=360]
.FSx ONTAPを使用したROSAでのアプリケーションのフェイルオーバーとフェイルバック
video::e9a07d79-42a1-4480-86be-b01200fa62f5[panopto,width=360]
====
.仮想化
[#virtualization%collapsible%open]
====
* link:vmware/vsphere_demos_videos.html["VMwareビデオコレクション"]


====
.コンテナ/ Kubernetes
[#containers%collapsible%open]
====
* link:containers/a-w-n_videos_and_demos.html["NetAppとGoogle Anthosのビデオ"]
* link:containers/vtwn_videos_and_demos.html["ネットアップとVMware Tanzuのビデオ"]
* link:containers/rh-os-n_videos_and_demos.html["Red Hat OpenShiftを搭載したネットアップのビデオをご覧ください"]


====
.解決策の自動化
[#automation%collapsible%open]
====
.Ansible による FlexPod での Oracle 19C RAC の自動導入
video::VcQMJIRzhoY[youtube,width=360]
====