---
sidebar: sidebar 
permalink: videos.html 
summary: ネットアップのソリューションの多くの機能を紹介する一連のビデオとデモ 
keywords: netapp, solutions, videos, demos 
---
= ネットアップのソリューション：ビデオとデモ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/


[role="lead"]
ネットアップのソリューションの特定の機能を紹介するビデオとデモの概要

.人工知能（AI）と最新のデータ分析
[#ai%collapsible]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO["ネットアップの AI ソリューション"^]
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW["MLOps の 1 つです"^]


.DataOps ToolkitとAstra Control CenterによるクラウドバースティングによるDevOpsの高速化
video::e87773e3-dc53-4195-83ed-b0d50100a788[panopto,width=360]
====
.エンタープライズアプリケーションとデータベース
[#db%collapsible]
====
[下線]#*オープンソースデータベース用のビデオ*#

.PostgreSQLの自動導入、HA/DRレプリケーションのセットアップ、フェイルオーバー、再同期
video::c381b887-8c8b-4d7d-8b0f-b0c0010c5c04[panopto,width=360]
[下線]#* Oracleデータベース用のビデオ*#

.NFSを使用したAzure NetApp FilesへのOracle導入の簡易化と自動化
video::d1c859b6-e45a-44c7-8361-b10f012fc89b[panopto,width=360]
.Amazon FSx ONTAP with iSCSIへのOracle導入の簡易化と自動化
video::81e389a0-d9b8-495c-883b-b0d701710847[panopto,width=360]
.iSCSIを使用したNetApp ASAへのOracle導入の簡易化と自動化
video::79095731-6b02-41d5-9fa1-b0c00100d055[panopto,width=360]
.パート1 - AWSとFSxでのハイブリッドクラウドによるOracleの最新化
video::b1a7bb05-caea-44a0-bd9a-b01200f372e9[panopto,width=360]
.パート2a -自動PDB再配置機能を使用した、オンプレミスからAWSへのデータベース移行と可用性の最大化
video::bb088a3e-bbfb-4927-bf44-b01200f38b17[panopto,width=360]
.パート2b - SnapMirrorを使用したBlueXPコンソールを使用したオンプレミスからAWSへのデータベースの移行
video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto,width=360]
.第3部-データベースの自動HA / DRレプリケーションのセットアップ、フェイルオーバー、再同期
video::5fd03759-a691-4007-9748-b01200f3b79c[panopto,width=360]
.パート4a -複製されたスタンバイコピーから、SnapCenter UIを使用した開発とテストのためのデータベースクローン
video::2f731d7c-0873-4a4d-8491-b01200f90a82[panopto,width=360]
.パート4b - SnapCenter UIを使用したデータベースのバックアップ、リストア、クローニング
video::97790d62-ff19-40e0-9784-b01200f920ed[panopto,width=360]
.パート4c -データベースのバックアップ、BlueXP SaaS Appsによるリストアのバックアップとリカバリ
video::4b0fd212-7641-46b8-9e55-b01200f9383a[panopto,width=360]
[下線]#* SQL Serverデータベース用ビデオ*#

.Amazon FSX for NetApp ONTAP を使用して、AWS EC2にSQL Serverを導入します
video::27f28284-433d-4273-8748-b01200fb3cd7[panopto,width=360]
.ストレージSnapshotを使用したOracleマルチテナントプラグイン可能なデータベースクローン
video::krzMWjrrMb0[youtube,width=360]
.Ansible による FlexPod での Oracle 19C RAC の自動導入
video::VcQMJIRzhoY[youtube,width=360]
*ケーススタディ*

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study["Azure NetApp Files を使用して SAP を運用"^]


====
.ハイブリッドマルチクラウド（HMC）
[#hmc%collapsible]
====
[下線]#* AWS/VMC *#用ビデオ

.iSCSIを使用したFSX ONTAP を使用したWindowsゲスト接続ストレージ
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.NFSを使用したFSX ONTAP を使用したLinuxゲスト接続ストレージ
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
. Amazon FSX for NetApp ONTAP を使用すると、VMware Cloud on AWSのTCOを削減できます
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.AWS上のVMware Cloud追加データストア、Amazon FSX for NetApp ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.VMCのVMware HCX展開と構成のセットアップ
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.VMCおよびFSxN向けVMware HCXによるVMotion移行のデモ
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.VMware HCX for VMCおよびFSxNを使用したコールドマイグレーションデモ
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
.iSCSIを使用したFSX ONTAP を使用したWindowsゲスト接続ストレージ
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.NFSを使用したFSX ONTAP を使用したLinuxゲスト接続ストレージ
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
. Amazon FSX for NetApp ONTAP を使用すると、VMware Cloud on AWSのTCOを削減できます
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.AWS上のVMware Cloud追加データストア、Amazon FSX for NetApp ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.VMCのVMware HCX展開と構成のセットアップ
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.VMCおよびFSxN向けVMware HCXによるVMotion移行のデモ
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.VMware HCX for VMCおよびFSxNを使用したコールドマイグレーションデモ
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
[underline]#* Azure/AVSのビデオ*#

.Azure NetApp Files を使用したAzure VMware解決策 補足データストアの概要
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
. Cloud Volumes ONTAP 、SnapCenter 、JetStreamを使用したAzure VMware解決策 DR
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.VMware HCX for AVSとANFを使用したコールドマイグレーションデモ
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.VMware HCX for AVSとANFでのvMotionのデモ
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.AVSとANF向けVMware HCXの一括移行デモ
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.Red Hat OpenShiftを使用したハイブリッドマルチクラウド
[#rhhc%collapsible]
====
.Astra Controlサービスを使用したRosa DR
video::01dd455e-7f5a-421c-b501-b01200fa91fd[panopto,width=360]
.FSxNとAstra Tridentの統合
video::621ae20d-7567-4bbf-809d-b01200fa7a68[panopto,width=360]
.FSxNを使用したROSA上のアプリのフェイルオーバーとフェイルバック
video::e9a07d79-42a1-4480-86be-b01200fa62f5[panopto,width=360]
[下線]#* Astra Control Centerを使用したDR *#

link:https://www.netapp.tv/details/29504?mcid=35609780286441704190790628065560989458["NetAppTVで視聴できます"]

.Google Cloud PlatformへのOpenShiftクラスタのインストール
video::4efc68f1-d37f-4cdd-874a-b09700e71da9[panopto,width=360]
.Astra Control CenterへのOpenShiftクラスタのインポート
video::57b63822-6bf0-4d7b-b844-b09700eac6ac[panopto,width=360]
.Astra Control Centerによるデータ保護
video::0cec0c90-4c6f-4018-9e4f-b09700eefb3a[panopto,width=360]
.Astra Control Centerを使用したフェイルオーバーフェイルバック
video::1546191b-bc46-42eb-ac34-b0d60142c58d[panopto,width=360]
====
.仮想化
[#virtualization%collapsible]
====
* link:virtualization/vsphere_demos_videos.html["VMwareビデオコレクション"]


====
.コンテナ/ Kubernetes
[#containers%collapsible]
====
* link:containers/anthos-with-netapp/a-w-n_videos_and_demos.html["NetAppとGoogle Anthosのビデオ"]
* link:containers/tanzu_with_netapp/vtwn_videos_and_demos.html["ネットアップとVMware Tanzuのビデオ"]
* link:containers/devops_with_netapp/dwn_videos_and_demos.html["ネットアップのDevOps向けビデオ"]
* link:containers/rh-os-n_videos_and_demos.html["Red Hat OpenShiftを搭載したネットアップのビデオをご覧ください"]


====
.解決策の自動化
[#automation%collapsible]
====
.Ansible による FlexPod での Oracle 19C RAC の自動導入
video::VcQMJIRzhoY[youtube,width=360]
====