---
sidebar: sidebar 
permalink: ehc/dr-draas-overview.html 
keywords: dr, draas, bluexp, disaster recovery, vmfs datastore, nfs datastore, overview 
summary: このセクションでは、オンプレミスのVMware VMから別の指定されたサイトへのディザスタリカバリを設定するためのBlueXP  DRaaSの構成について説明します。 
---
= 概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ディザスタリカバリは、すべてのVMware管理者の最重要課題です。VMwareは、サーバ全体を仮想マシンを構成する一連のファイルにカプセル化するため、管理者は、クローン、スナップショット、レプリカなどのブロックストレージベースの手法を利用して、これらのVMを保護します。ONTAPアレイには、ボリュームデータ、つまり指定したデータストアLUN上の仮想マシンをあるサイトから別のサイトに転送するレプリケーション機能が組み込まれています。BlueXP  DRaaSはvSphereと統合され、災害発生時のシームレスなフェイルオーバーとフェイルバックのためのワークフロー全体を自動化します。ストレージレプリケーションとインテリジェントな自動化機能を組み合わせることで、管理者はディザスタリカバリ計画を設定、自動化、テストできるだけでなく、災害発生時に計画を簡単に実行できる管理手段を手に入れることができます。

VMware vSphere環境におけるDRフェイルオーバーで最も時間のかかる作業は、DRサイトでVMのインベントリ作成、登録、再設定、電源投入に必要な手順を実行することです。理想的なソリューションは、RPO（数分で測定）とRTO（数分から数時間で測定）の両方を実現します。DRソリューションで見落とされることが多い要因の1つは、DRソリューションを定期的に効率的にテストできることです。

DRソリューションを設計するには、次の要素に注意してください。

* 目標復旧時間（RTO）。RTOとは、災害からビジネスをどれだけ迅速にリカバリできるか、具体的には、リカバリプロセスを実行してビジネスサービスを再び利用できるようにするのにかかる時間です。
* Recovery Point Objective（RPO；目標復旧時点）。RPOは、災害が発生した時点を基準とした、リカバリされたデータが利用可能になってからの経過時間です。
* 拡張性と適応性：これには、需要の増加に応じてストレージリソースを段階的に拡張できる機能が含まれます。


利用可能なソリューションの技術情報については、次のサイトを参照してください。

* link:dr-draas-nfs.html["BlueXP  データストア向けDRaaSを使用したDR"]
* link:dr-draas-vmfs.html["BlueXP  DRaaS for VMFSデータストアを使用したDR"]

