---
sidebar: sidebar 
permalink: ehc/ehc-use-cases.html 
keywords: NetApp Solutions, ehc, enterprise hybrid cloud, use case, hyperscalers, vmware 
summary:  
---
= エンタープライズハイブリッドクラウド（ EHC ）のユースケース
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
ハイブリッドクラウドまたはクラウドファーストの導入を計画する際に IT 組織にとって重要なユースケースの概要。



== 一般的なユースケース

ユースケースには次のものがあり

* ディザスタリカバリ、 SVM
* データセンターのメンテナンス時にワークロードをホストする。 * ローカルのデータセンターでプロビジョニングされたリソース以外に追加のリソースが必要になる、迅速なバースト。
* VMware サイトの拡張
* クラウドへの迅速な移行
* 開発 / テスト、および
* クラウドネイティブなテクノロジを活用したアプリケーションの最新化。




=== IT の旅の中で

ほとんどの組織は、変革と最新化への移行を進めています。このプロセスの一環として、企業は既存の VMware への投資を活用しながら、クラウドのメリットを活用し、移行プロセスをできるだけシームレスに実行する方法を模索しています。このアプローチでは、データがすでにクラウドにあるため、最新化への取り組みが非常に簡単になります。

このシナリオに最も簡単に使用できる回答は、各ハイパースケーラにおける VMware ソリューションです。ネットアップの Cloud Volume と同様に、 VMware はオンプレミスの VMware 環境を任意のクラウドに移行または拡張できるため、既存のオンプレミスの資産、スキル、ツールを保持しながら、ワークロードをクラウド内でネイティブに実行できます。これにより、サービスの中断や IP 変更の必要性がなくなり、 IT チームは既存のスキルやツールを使用してオンプレミスで行う方法を運用できるようになるため、リスクが軽減されます。これにより、クラウドへの移行が高速化され、ハイブリッドマルチクラウドアーキテクチャへの移行が大幅にスムーズになります。



=== ネイティブストレージオプションの重要性を理解する

あらゆるクラウドで VMware が提供する独自のハイブリッド機能はすべてのお客様に提供されますが、ネイティブストレージの選択肢が限られているため、ストレージの負荷が高い組織での有用性が制限されています。ストレージはホストに直接関連付けられているため、ストレージを拡張する唯一の方法は、ホストを追加することです。これにより、ストレージを大量に消費するワークロードの場合、 35 ～ 40% 以上のコストがかかる可能性があります。このようなワークロードに必要なストレージ容量は増えても容量は増えません。つまり、追加のホストに料金を支払うことになります。

次のシナリオを考えてみましょう。

CPU とメモリ用にわずか 5 台のホストが必要ですが、ストレージには多くのニーズがあり、ストレージ要件を満たすために 12 台のホストが必要です。この要件は、ストレージを増設するだけで追加の処理能力を購入する必要があるため、財務面での拡張性に大きな転換を実現できます。

クラウドの導入と移行を計画する場合は、最適なアプローチを評価し、投資の総削減に最も簡単な方法をとることが常に重要です。あらゆるアプリケーション移行で最も一般的かつ簡単なアプローチは、仮想マシン（ VM ）やデータ変換がない場所でリホスト（リフトアンドシフト）を行うことです。NetApp Cloud Volume と VMware の Software-Defined Data Center （ SDDC ）を併用し、 vSAN を補完することで、移行と切り替えが容易になります。
