---
sidebar: sidebar 
permalink: ehc/ehc-config-vmware.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, config, configuration 
summary:  
---
= クラウドプロバイダでの仮想化環境の設定
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
サポートされている各ハイパースケーラで仮想化環境を設定する方法については、こちらで詳しく説明しています。

次のオプションを選択して、目的のハイパースケーラのセクションに移動します。

* link:#aws-config["Amazon VMware 解決策（ AVS ）の設定"]
* link:#azure-config["Azure VMware マネージドクラウド（ VMC ）の設定"]
* link:#gcp-config["Google Cloud Virtualization Engine （ GCVE ）の設定"]




== VMC を AWS 用に設定しています

オンプレミスと同様に、 VM と移行を作成する本番環境に適した VMware Cloud on AWS を計画することが重要です。

このセクションでは、 AWS SDDC で VMware Cloud をセットアップおよび管理する方法と、ネットアップストレージの接続に使用できるオプションについて説明します。


NOTE: FSX ONTAP および Cloud Volumes ONTAP を AWS VMC に接続する方法としてサポートされているのは、ゲスト内ストレージだけです。

セットアッププロセスは、次の手順に分けることができます。

* link:aws-deploy-config.html["VMware Cloud for AWS を導入して設定"]
* link:aws-connect-fsx.html["VMware Cloud を FSX ONTAP に接続します"]




== VMC を Azure 用に設定しています

オンプレミスと同様に、 Azure VMware 解決策を計画することは、 VM と移行を作成する本番環境に欠かせません。

このセクションでは、 Azure VMware 解決策をセットアップおよび管理する方法と、ネットアップストレージの接続に使用できるオプションについて説明します。


NOTE: Azure NetApp Files と Cloud Volumes ONTAP を Azure VMware 解決策に接続する方法としてサポートされているのは、ゲスト内ストレージだけです。

セットアッププロセスは、次の手順に分けることができます。

* link:azure-register-create-pc.html["リソースプロバイダを登録し、プライベートクラウドを作成"]
* link:azure-connect-virtual-gateway.html["新しい ExpressRoute 仮想ネットワークゲートウェイまたは既存の ExpressRoute 仮想ネットワークゲートウェイに接続します"]
* link:azure-validate-network.html["ネットワーク接続を検証し、プライベートクラウドにアクセス"]




== Google Cloud Platform 用の GCVE の設定

オンプレミスと同様に、 VM と移行を作成する本番環境に成功するには、 Google Cloud VMware Engine （ GCVE ）の計画が不可欠です。

このセクションでは、 GCVE のセットアップと管理方法、およびネットアップストレージの接続に使用できるオプションとの組み合わせについて説明します。


NOTE: Cloud Volume と Cloud Volumes ONTAP サービスを GCVE に接続する方法としてサポートされているのは、ゲスト内ストレージだけです。

セットアッププロセスは、次の手順に分けることができます。

* link:gcve-deploy-config.html["GCVE を導入および設定します"]
* link:gcve-enable-access.html["GCVE へのプライベートアクセスを有効にします"]

