---
sidebar: sidebar 
permalink: ehc/ehc-summary.html 
keywords: NetApp Solutions, hybrid, multi-cloud, enterprise hybrid cloud, hyperscalers, vmware 
summary:  
---
= まとめ：ネットアップのハイブリッドマルチクラウドとVMwareを選ぶ理由
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
ネットアップの Cloud Volume と主要ハイパースケーラ向け VMware ソリューションは、ハイブリッドクラウドの活用を検討している組織に大きな可能性をもたらします。以降では、 NetApp Cloud Volume の統合による真のハイブリッドマルチクラウド機能のユースケースについて説明します。



== ユースケース 1 ：ストレージの最適化

RVtools の出力を使用したサイジングの演習では、馬力（ vCPU / vMem ）のスケールがストレージと平行になっていることが常に明らかです。多くの場合、組織は、ストレージスペースを必要とするだけでなく、クラスタのサイズを十分に拡張して処理能力を必要とする状況に遭遇します。

NetApp Cloud Volume を統合することで、組織は vSphere ベースのクラウド解決策を簡単な移行アプローチで実現できます。再プラットフォーム化や IP の変更は不要で、アーキテクチャの変更も必要ありません。また、この最適化により、ホストの数を vSphere で必要な量以上に抑えながらストレージの設置面積を拡張できます。ただし、ストレージ階層、セキュリティ、ファイルは変更されません。これにより、導入を最適化し、全体的な TCO を 35 ～ 45% 削減できます。この統合により、ウォームストレージから本番環境レベルのパフォーマンスまで、ストレージを数秒で拡張できます。



== ユースケース 2 ：クラウドへの移行

企業は、次のような理由から、オンプレミスのデータセンターからパブリッククラウドへのアプリケーション移行を迫られています。設備投資（ CAPEX ）から運用コスト（ OPEX ）に移行するための資金調達ディレクティブや、すべてをクラウドへ移行するというトップダウンの指示など、さまざまな理由があります。

スピードが重要な場合は、合理化された移行アプローチのみが可能です。これは、クラウド固有の IaaS プラットフォームに適応するためのアプリケーションの再プラットフォーム化とリファクタリングが低速でコストがかかるためですが、多くの場合、数か月かかることがあります。ネットアップの Cloud Volume とゲスト接続ストレージ用の帯域幅効率に優れた SnapMirror レプリケーションを組み合わせることで、アプリケーションと整合性のある Snapshot コピーと HCX 、クラウド固有の移行（例 Azure Migrate ）、または VM のレプリケーションに使用するサードパーティ製品）。この移行は、時間のかかる I/O フィルタメカニズムを使用する場合よりも簡単です。



== ユースケース 3 ：データセンターの拡張

季節によって変動する需要の急増や、わずかに変動する有機的な成長によってデータセンターの容量が上限に達し解決策た場合、 NetApp Cloud Volume と一緒にクラウドホスト型の VMware 環境に移行するのは簡単です。NetApp Cloud Volume を利用すると、アベイラビリティゾーン全体の高可用性と動的な拡張機能を提供することで、ストレージの作成、レプリケーション、拡張が非常に簡単に行えます。NetApp Cloud Volume を活用すると、ストレッチクラスタが不要になるため、ホストクラスタの容量を最小限に抑えることができます。



== ユースケース 4 ：クラウドへのディザスタリカバリ

従来のアプローチでは、災害が発生した場合、クラウドに複製された VM は、クラウドに復元する前にクラウド独自のハイパーバイザプラットフォームに変換する必要があります。これは、危機的な状況では対処できません。

SnapCenter を使用してゲスト接続ストレージに NetApp Cloud Volume を使用し、オンプレミスからの SnapMirror レプリケーションとパブリッククラウド仮想化ソリューションを使用することで、ディザスタリカバリに対する優れたアプローチを考案できます。これにより、完全に一貫性のある VMware SDDC インフラ上で VM レプリカをリカバリできるようになり、クラウド固有のリカバリツールも利用できます Azure Site Recovery を参照）、または Veeam などの同等のサードパーティツールが必要です。また、このアプローチにより、ランサムウェアからのディザスタリカバリ訓練やリカバリも迅速に実行できます。また、テスト用や災害時に、ホストをオンデマンドで追加することで、フル本番環境に拡張することもできます。



== ユースケース 5 ：アプリケーションの最新化

アプリケーションがパブリッククラウドに配置されたら、組織は数百もの強力なクラウドサービスを活用して最新化と拡張を実現したいと考えています。NetApp Cloud Volume を使用すると、アプリケーションデータが vSAN にロックされず、 Kubernetes などの幅広いユースケースでデータを移動できるため、最新化は簡単なプロセスです。



== まとめ

オールクラウドとハイブリッドクラウドのどちらをターゲットとしている場合でも、 NetApp Cloud Volume は、アプリケーションワークロードを導入、管理するための優れたオプションを提供し、ファイルサービスとブロックプロトコルに加えて、データ要件をアプリケーションレイヤとシームレスにすることで TCO を削減します。

どのようなユースケースでも、任意のクラウドやハイパースケーラを NetApp Cloud Volume と組み合わせることで、オンプレミスと複数のクラウドにわたるクラウドのメリット、一貫したインフラ、運用、ワークロードの双方向の移動、エンタープライズクラスの容量とパフォーマンスを迅速に実現できます。

ストレージの接続に使用する一般的なプロセスや手順は同じです。新しい名前で変更されたデータの位置にすぎません。ツールやプロセスはすべて変わらないので、 NetApp Cloud Volume を使用すれば導入全体を最適化できます。
