---
sidebar: sidebar 
permalink: ehc/ehc-datastore-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= パブリッククラウドプロバイダ向けのネットアップストレージオプション
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
主要な 3 種類のハイパースケーラにおけるストレージとしてのネットアップのオプションをご確認ください。

[role="tabbed-block"]
====
.AWS / VMC
--
AWS は、次の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての FSX ONTAP
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* ネイティブデータストアとしてのFSX ONTAP ^1 ^


詳細を表示します link:aws/aws-guest.html["VMCのゲスト接続ストレージオプション"]。


NOTE: VMCの1-FSxNは現在IA（Initial Availability）にあります。詳細については、ネットアップの営業担当までお問い合わせください。

--
.Azure / AVS
--
Azure は、以下の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての Azure NetApp Files （ ANF
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* ネイティブデータストアとしてのAzure NetApp Files （ANF）^1 ^


詳細を表示します link:azure/azure-guest.html["AVSのゲスト接続ストレージオプション"]。


NOTE: 1 - AVSのネイティブデータストアとしてのANFは、現時点ではパブリックプレビュー版です。詳細はこちら https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?branch=main&tabs=azure-portal["こちらをご覧ください"]。

--
.GCP/GCVE
--
Google Cloud は、次の構成でネットアップストレージをサポートします。

* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* Cloud Volumes Service （ CVS ）をゲスト接続ストレージとして使用できるようになりました
* ネイティブデータストアとしてのCloud Volumes Service （CVS）^1 ^


詳細を表示します link:gcp/gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。

詳細については、をご覧ください link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/["ネイティブデータストアとしての Cloud Volumes Service （ CVS ） ^1"^]。


NOTE: 1- 現在プライベートプレビュー中です

--
====