---
sidebar: sidebar 
permalink: ehc/ehc-datastore-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= パブリッククラウドプロバイダ向けのネットアップストレージオプション
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
主要な 3 種類のハイパースケーラにおけるストレージとしてのネットアップのオプションをご確認ください。

[role="tabbed-block"]
====
.AWS / VMC
--
AWS は、次の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての FSX ONTAP
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* 補足的なNFSデータストアとしてのFSX ONTAP


詳細を表示しますlink:aws-guest.html["VMCのゲスト接続ストレージオプション"]。詳細を表示しますlink:aws-native-nfs-datastore-option.html["VMCの補足的なNFSデータストアオプション"]。

--
.Azure / AVS
--
Azure は、以下の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての Azure NetApp Files （ ANF
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* Azure NetApp Files （ANF）を追加のNFSデータストアとして使用できます


詳細を表示しますlink:azure-guest.html["AVSのゲスト接続ストレージオプション"]。詳細を表示しますlink:azure-native-nfs-datastore-option.html["AVSの補足的なNFSデータストアオプション"]。

--
.GCP/GCVE
--
Google Cloud は、次の構成でネットアップストレージをサポートします。

* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* ゲスト接続ストレージとしてのGoogle Cloud NetApp Volume（NetApp Volume）
* 補完的なNFSデータストアとしてのGoogle Cloud NetApp Volume（NetApp Volume）


詳細を表示しますlink:gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。詳細を表示しますlink:gcp-ncvs-datastore.html["GCVEの補足的なNFSデータストアオプション"]。

またはの詳細については、link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Google Cloud NetApp VolumeデータストアでのGoogle Cloud VMware Engineのサポート（NetAppブログ）"^]link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["How to use Google Cloud NetApp Volumes as datastore for Google Cloud VMware Engine（Googleブログ）"^]

--
====