---
sidebar: sidebar 
permalink: ehc/ehc-config-vmware-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, config, configuration 
summary:  
---
= クラウドプロバイダでの仮想化環境の設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
サポートされている各ハイパースケーラで仮想化環境を設定する方法については、こちらで詳しく説明しています。



=== AWS （ VMC ）の仮想化環境構成

このセクションでは、 AWS SDDC で VMware Cloud をセットアップおよび管理する方法と、ネットアップストレージの接続に使用できるオプションについて説明します。


NOTE: FSX ONTAP および Cloud Volumes ONTAP を AWS VMC に接続する方法としてサポートされているのは、ゲスト内ストレージだけです。

セットアッププロセスは、次の手順に分けることができます。

* link:aws/aws-setup.html#deploy["VMware Cloud for AWS を導入して設定"]
* link:aws/aws-setup.html#connect["VMware Cloud を FSX ONTAP に接続します"]




=== Azure 向け仮想化環境の構成（ AVS ）

このセクションでは、 Azure VMware 解決策をセットアップおよび管理する方法と、ネットアップストレージの接続に使用できるオプションについて説明します。


NOTE: Azure NetApp Files と Cloud Volumes ONTAP を Azure VMware 解決策に接続する方法としてサポートされているのは、ゲスト内ストレージだけです。

セットアッププロセスは、次の手順に分けることができます。

* link:azure/azure-setup.html#register["リソースプロバイダを登録し、プライベートクラウドを作成"]
* link:azure/azure-setup.html#connect["新しい ExpressRoute 仮想ネットワークゲートウェイまたは既存の ExpressRoute 仮想ネットワークゲートウェイに接続します"]
* link:azure/azure-setup.html#validate["ネットワーク接続を検証し、プライベートクラウドにアクセス"]




=== GCP の仮想化環境構成（ GCVE ）

このセクションでは、 GCVE のセットアップと管理方法、およびネットアップストレージの接続に使用できるオプションとの組み合わせについて説明します。


NOTE: Cloud Volume と Cloud Volumes ONTAP サービスを GCVE に接続する方法としてサポートされているのは、ゲスト内ストレージだけです。

セットアッププロセスは、次の手順に分けることができます。

* link:gcp/gcp-setup.html#deploy["GCVE を導入および設定します"]
* link:gcp/gcp-setup.html#enable-access["GCVE へのプライベートアクセスを有効にします"]

