---
sidebar: sidebar 
permalink: ehc/ehc-datastore-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= パブリッククラウドプロバイダ向けのネットアップストレージオプション
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
主要な 3 種類のハイパースケーラにおけるストレージとしてのネットアップのオプションをご確認ください。

[role="tabbed-block"]
====
.AWS / VMC
--
AWS は、次の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての FSX ONTAP
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* 補足的なNFSデータストアとしてのFSX ONTAP


詳細を表示します link:aws/aws-guest.html["VMCのゲスト接続ストレージオプション"]。詳細を表示します link:aws/aws-native-nfs-datastore-option.html["VMCの追加のNFSデータストアオプション"]。

--
.Azure / AVS
--
Azure は、以下の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての Azure NetApp Files （ ANF
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* Azure NetApp Files （ANF）を追加のNFSデータストアとして使用できます


詳細を表示します link:azure/azure-guest.html["AVSのゲスト接続ストレージオプション"]。詳細を表示します link:azure/azure-native-nfs-datastore-option.html["AVSの補足的なNFSデータストアオプション"]。

--
.GCP/GCVE
--
Google Cloud は、次の構成でネットアップストレージをサポートします。

* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* Cloud Volumes Service （ CVS ）をゲスト接続ストレージとして使用できるようになりました
* Cloud Volumes Service （CVS）をNFSデータストアとして追加


詳細を表示します link:gcp/gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。

詳細については、をご覧ください link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["NetApp Cloud Volumes Service データストアでGoogle Cloud VMware Engineがサポートされるようになりました"^]

--
====