---
sidebar: sidebar 
permalink: ehc/gcp-gcve.html 
keywords: NetApp Solutions, hyperscalers, google cloud, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Google Cloud Platform GCVE のネットアップ機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetAppがGoogle Cloud Platform（GCP）にもたらす機能の詳細については、ゲスト接続ストレージデバイスとしてのNetAppや補完的なNFSデータストアから、ワークフローの移行、クラウドへの拡張/バースト、バックアップ/リストア、ディザスタリカバリまで、Google Cloud VMware Engine（GCVE）をご覧ください。

次のオプションから選択して、目的のコンテンツのセクションに移動します。

* link:#config["GCP での GCVE の設定"]
* link:#datastore["GCVE のネットアップストレージオプション"]
* link:#solutions["ネットアップとVMwareのクラウドソリューション"]




== GCP での GCVE の設定

オンプレミスと同様に、 VM と移行を作成する本番環境に適したクラウドベースの仮想化環境を計画することが重要です。

このセクションでは、 GCVE のセットアップと管理方法、およびネットアップストレージの接続に使用できるオプションとの組み合わせについて説明します。


NOTE: Cloud Volumes ONTAPとGoogle Cloud NetApp VolumeをGCVEに接続するためにサポートされている唯一の方法はゲスト内ストレージです。

セットアッププロセスは、次の手順に分けることができます。

* GCVE を導入および設定します
* GCVE へのプライベートアクセスを有効にします


詳細を表示します link:gcp-setup.html["GCVEの設定手順"]。



== GCVE のネットアップストレージオプション

ネットアップストレージは、接続されている推測データストアまたはNFSデータストア補助的なGCP GCVE内のいくつかの方法で利用できます。

にアクセスしてください link:ehc-support-configs.html["サポートされているネットアップストレージオプション"] を参照してください。

Google Cloud は、次の構成でネットアップストレージをサポートします。

* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* ゲスト接続ストレージとしてのGoogle Cloud NetApp Volume（NetApp Volume）
* 補完的なNFSデータストアとしてのGoogle Cloud NetApp Volume（NetApp Volume）


詳細を表示しますlink:gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。詳細を表示しますlink:gcp-ncvs-datastore.html["GCVEの補足的なNFSデータストアオプション"]。

またはの詳細については、link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Google Cloud NetApp VolumeデータストアでのGoogle Cloud VMware Engineのサポート（NetAppブログ）"^]link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["How to use Google Cloud NetApp Volumes as datastore for Google Cloud VMware Engine（Googleブログ）"^]



== 解決策のユースケース

ネットアップと VMware のクラウドソリューションを使用すれば、多くのユースケースを Azure AVS で簡単に導入できます。SEケースは、VMwareが定義したクラウド領域ごとに定義されます。

* 保護（ディザスタリカバリとバックアップ/リストアの両方を含む）
* 拡張
* 移動


link:gcp-solutions.html["ネットアップの Google Cloud GCVE ソリューションをご覧ください"]
