---
sidebar: sidebar 
permalink: ehc/ncvs-gc-control-plane-architecture.html 
keywords: identity, access, management, authorization, permission, service accounts, cloud volumes service api, jwt tokens 
summary: Google Cloud NetApp Volumeに対するすべての管理操作はAPIを介して実行されます。GCP Cloudコンソールに統合されたGoogle Cloud NetApp Volumeの管理には、Google Cloud NetApp Volumes APIも使用されます。 
---
= コントロールプレーンのアーキテクチャ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumeに対するすべての管理操作はAPIを介して実行されます。GCP Cloudコンソールに統合されたGoogle Cloud NetApp Volumeの管理には、Google Cloud NetApp Volumes APIも使用されます。



== IDおよびアクセス管理

IDおよびアクセス管理(https://cloud.google.com/iam/docs/overview["IAM"^]）は、Google Cloudプロジェクトインスタンスに対する認証（ログイン）と許可（権限）を制御できる標準サービスです。Google IAMには、許可の承認と削除に関する完全な監査証跡が用意されています。現時点では、Google Cloud NetApp Volumeではコントロールプレーン監査は提供されていません。



=== 承認/権限の概要

IAMは、Google Cloud NetApp Volumeに対して、組み込みのきめ細かな権限を提供します。を見つけることができます https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["詳細な権限の一覧をここに入力します"^]。

IAMには、と `netappcloudvolumes.viewer`という2つの事前定義されたロールもあります `netappcloudvolumes.admin`。これらのロールは、特定のユーザまたはサービスアカウントに割り当てることができます。

適切なロールと権限を割り当てて、IAMユーザがGoogle Cloud NetApp Volumeを管理できるようにします。

きめ細かい権限の使用例を次に示します。

* ボリュームを削除できないように、権限の取得/リスト/作成/更新だけを指定してカスタムロールを作成します。
* アプリケーションと整合性のあるSnapshot統合の構築に使用するサービスアカウントを作成するには、権限のみを持つカスタムロールを使用し `snapshot.*`ます。
* 特定のユーザーに委任するカスタムロールを作成し `volumereplication.*`ます。




=== サービスアカウント

スクリプトまたはを使用してGoogle Cloud NetApp Volumes API呼び出しを行うには https://registry.terraform.io/providers/NetApp/netapp-gcp/latest/docs["テラフォーム"^]、ロールを持つサービスアカウントを作成する必要があります `roles/netappcloudvolumes.admin`。このサービスアカウントを使用して、次の2つの方法でGoogle Cloud NetApp Volumes API要求の認証に必要なJWTトークンを生成できます。

* JSONキーを生成し、Google APIを使用してJWTトークンを取得します。これは最もシンプルなアプローチですが、手動のシークレット（JSONキー）管理が必要になります。
* で使用し https://cloud.google.com/iam/docs/impersonating-service-accounts["サービスアカウントのなりすまし"^] `roles/iam.serviceAccountTokenCreator`ます。コード（スクリプト、Terraformなど）はで実行され https://google.aip.dev/auth/4110["アプリケーションのデフォルトクレデンシャル"^]、サービスアカウントになりすまして権限を取得します。このアプローチは、Googleのセキュリティのベストプラクティスを反映しています。


詳細については、Google Cloudのドキュメントのを参照してください https://cloud.google.com/architecture/partners/netapp-cloud-volumes/api?hl=en_US["サービスアカウントと秘密鍵を作成しています"^]。



== Google Cloud NetApp Volumes API

Google Cloud NetApp Volumes APIでは、RESTベースのAPIを使用し、基盤となるネットワーク転送としてHTTPS（TLSv1.2）を使用します。最新のAPI定義とAPIの使用方法については、を参照して https://cloudvolumesgcp-api.netapp.com/swagger.json["ここをクリック"^]ください https://cloud.google.com/architecture/partners/netapp-cloud-volumes/api?hl=en_US["Google CloudドキュメントのCloud Volume API"^]。

APIエンドポイントは、標準のHTTPS（TLSv1.2）機能を使用してネットアップによって処理および保護されます。



=== JWTトークン

APIへの認証は、JWTベアラトークンを使用して実行され(https://datatracker.ietf.org/doc/html/rfc7519["RFC-7519"^]ます)。有効なJWTトークンは、Google Cloud IAM認証を使用して取得する必要があります。そのためには、サービスアカウントのJSONキーを指定してIAMからトークンを取得する必要があります。



== 監査ロギング

現在、ユーザがアクセスできるコントロールプレーン監査ログはありません。
