---
sidebar: sidebar 
permalink: ehc/ncvs-gc-architecture_overview.html 
keywords: architecture overview, control plane, data plane 
summary: クラウド解決策 を信頼する一部は、アーキテクチャとその保護方法を理解していることです。このセクションでは、データの保護方法に関する潜在的な懸念を軽減するためにGoogle Cloud NetApp Volumeアーキテクチャのさまざまな側面について説明します。また、最もセキュアな導入を実現するために追加の設定手順が必要な領域についても説明します。 
---
= 概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラウド解決策 を信頼する一部は、アーキテクチャとその保護方法を理解していることです。このセクションでは、データの保護方法に関する潜在的な懸念を軽減するためにGoogle Cloud NetApp Volumeアーキテクチャのさまざまな側面について説明します。また、最もセキュアな導入を実現するために追加の設定手順が必要な領域についても説明します。

Google Cloud NetApp Volumeの一般的なアーキテクチャは、コントロールプレーンとデータプレーンという2つの主要コンポーネントに分類できます。



== コントロールプレーン

Google Cloud NetApp Volumesのコントロールプレーンは、Google Cloud NetApp Volumes管理者とNetAppネイティブの自動化ソフトウェアが管理するバックエンドインフラです。このプレーンはエンドユーザに対して完全に透過的で、ネットワーク、ストレージハードウェア、ソフトウェアの更新などが含まれ、Google Cloud NetApp Volumeなどのクラウドに実装されたソリューションに価値を提供するのに役立ちます。



== データプレーン

Google Cloud NetApp Volumeのデータプレーンには、実際のデータボリュームとGoogle Cloud NetApp Volumeの全体的な設定（アクセス制御、Kerberos認証など）が含まれます。データプレーンは、エンドユーザとGoogle Cloud NetApp Volumeプラットフォームの利用者が完全に制御します。

各平面の保護および管理方法には、異なる違いがあります。以降のセクションでは、これらの違いについて説明します。まずは、Google Cloud NetApp Volumeのアーキテクチャ概要について説明します。
