---
sidebar: sidebar 
permalink: ehc/ncvs-gc-dual-protocol-multiprotocol.html 
keywords: access control, user mapping, permission model 
summary: Google Cloud NetApp Volumeを使用すると、適切なアクセス権限デュアルプロトコルを維持しながら、SMBクライアントとNFSクライアントの両方で同じデータセットを共有できます。これは、プロトコル間のIDマッピングを調整し、一元化されたバックエンドLDAPサーバを使用してUNIX IDをGoogle Cloud NetApp Volumeに提供することによって実現されます。Windows Active Directoryを使用すると、WindowsとUNIXの両方のユーザに使いやすさを提供できます。 
---
= デュアルプロトコル/マルチプロトコル
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumeを使用すると、適切なアクセス権限を維持しながら、SMBクライアントとNFSクライアントの両方で同じデータセットを共有でき(https://cloud.google.com/architecture/partners/netapp-cloud-volumes/managing-dual-protocol-access["デュアルプロトコル"^]ます）。これは、プロトコル間のIDマッピングを調整し、一元化されたバックエンドLDAPサーバを使用してUNIX IDをGoogle Cloud NetApp Volumeに提供することによって実現されます。Windows Active Directoryを使用すると、WindowsとUNIXの両方のユーザに使いやすさを提供できます。



== Access Control の略

* *共有アクセス制御。*NAS共有にアクセスできるクライアント/ユーザー/グループを決定します。NFSの場合は、エクスポートへのクライアントアクセスを制御するエクスポートポリシーとルールがあります。NFSエクスポートは、Google Cloud NetApp Volumeインスタンスから管理されます。SMBは、CIFS / SMB共有と共有ACLを利用して、ユーザレベルおよびグループレベルでより細かく制御します。クライアントから共有レベルのACLを設定するには、https://libraryを使用する必要があります。Google Cloud NetApp Volumeインスタンスに対する管理者権限を持つアカウント（「NetApp：com/ecmdocs/ECMP1401220/HTML/GUID-C1772CDF-8AEE-422B-AB87-CFCB7E50FF94.html[UMC/Computer Management^]
* *ファイルアクセス制御。*権限をファイルまたはフォルダレベルで制御し、常にNASクライアントから管理します。NFSクライアントは、従来のモードビット（rwx）またはNFSv4 ACLを使用できます。SMBクライアントはNTFS権限を利用します。


NFSとSMBの両方にデータを提供するボリュームのアクセス制御は、使用しているプロトコルによって異なります。デュアルプロトコルの権限の詳細については、を参照してください<<アクセス許可モデル>>。



== ユーザマッピング

クライアントがボリュームにアクセスすると、Google Cloud NetApp Volumeは受信ユーザを有効なユーザに逆方向にマッピングしようとします。これは、プロトコルを使用して適切なアクセスを決定し、アクセスを要求しているユーザが実際に誰であるかを確認するために必要です。

たとえば、というWindowsユーザ `joe`がSMB経由でUNIX権限を使用するボリュームにアクセスしようとすると、Google Cloud NetApp Volumesはという名前の対応するUNIXユーザを検索します `joe`。ファイルが存在する場合、WindowsユーザとしてSMB共有に書き込まれたファイル `joe`は、NFSクライアントからはUNIXユーザとして表示されます `joe`。

または、という名前のUNIXユーザがWindows権限を使用してGoogle Cloud NetApp Volumeボリュームにアクセスしようとする場合は `joe`、そのUNIXユーザが有効なWindowsユーザにマッピングできる必要があります。そうしないと、ボリュームへのアクセスが拒否されます。

現時点では、LDAPを使用した外部UNIX IDの管理でサポートされているのはActive Directoryのみです。このサービスへのアクセスの設定の詳細については、を参照してください https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-smb-volumes["AD接続の作成"^]。



== アクセス許可モデル

デュアルプロトコルセットアップを使用する場合、Google Cloud NetApp Volumeはボリュームのセキュリティ形式を使用してACLのタイプを決定します。これらのセキュリティ形式は、指定するNASプロトコルに基づいて設定されます。デュアルプロトコルの場合は、Google Cloud NetApp Volumeボリュームの作成時に選択されます。

* NFSのみを使用している場合は、Google Cloud NetApp VolumeボリュームでUNIX権限が使用されます。
* SMBのみを使用している場合は、Google Cloud NetApp VolumeボリュームでNTFS権限が使用されます。


デュアルプロトコルボリュームを作成する場合は、ボリュームの作成時にACL形式を選択できます。この決定は、必要な権限管理に基づいて行う必要があります。ユーザがWindows / SMBクライアントから権限を管理している場合は、NTFSを選択します。ユーザがNFSクライアントおよびchmod / chownを使用することを希望する場合は、UNIXセキュリティ形式を使用します。
