---
sidebar: sidebar 
permalink: ehc/ncvs-gc-basics-of-nas-protocols.html 
keywords: nas, basics, gcp, nfs, smb 
summary: NASプロトコルは、ネットワーク上の複数のクライアントが、GCP上のCloud Volumes Service などのストレージシステム上の同じデータにアクセスするための方法です。NFSとSMBは定義済みのNASプロトコルであり、Cloud Volumes Service がサーバとして機能するクライアント/サーバベースで動作します。 
---
= NASプロトコルの基本
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NASプロトコルは、ネットワーク上の複数のクライアントが、GCP上のCloud Volumes Service などのストレージシステム上の同じデータにアクセスするための方法です。NFSとSMBは定義済みのNASプロトコルであり、Cloud Volumes Service がサーバとして機能するクライアント/サーバベースで動作します。クライアントは、アクセス要求、読み取り要求、および書き込み要求をサーバに送信します。サーバは、ファイルのロックメカニズムを調整し、権限を格納し、IDおよび認証要求を処理します。

たとえば、NASクライアントがフォルダに新しいファイルを作成する場合は、次の一般的なプロセスが実行されます。

. クライアントは、ディレクトリに関する情報（権限、所有者、グループ、ファイルID、使用可能なスペース、 など）。要求元のクライアントとユーザが親フォルダに対して必要な権限を持っている場合、サーバは情報を返します。
. ディレクトリ上のアクセス許可がアクセスを許可されている場合、クライアントは、作成されるファイル名がファイルシステムにすでに存在するかどうかをサーバに確認します。ファイル名がすでに使用されている場合は、の作成に失敗します。ファイル名が存在しない場合、サーバーはクライアントに処理を続行できることを通知します。
. クライアントがサーバを呼び出して、ディレクトリハンドルとファイル名を指定してファイルを作成し、アクセス日時と変更日時を設定します。サーバは、一意のファイルIDをファイルに発行して、同じファイルIDで他のファイルが作成されないようにします。
. クライアントは、書き込み処理の前に、ファイル属性をチェックする呼び出しを送信します。権限で許可されている場合、クライアントは新しいファイルを書き込みます。プロトコル/アプリケーションでロックが使用されている場合、クライアントは、データ破損を防ぐために、ロック中に他のクライアントがファイルにアクセスできないようにするために、サーバにロックを要求します。

