---
sidebar: sidebar 
permalink: ehc/ncvs-gc-service-operation.html 
keywords: physical security, operations team, customer responsibilities, malicious sre protection, certifications, gdpr 
summary: Google Cloud NetApp Volumesチームは、Google Cloudのバックエンドサービスを管理し、複数の戦略を使用してプラットフォームを保護し、不要なアクセスを防止します。 
---
= サービスの処理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumesチームは、Google Cloudのバックエンドサービスを管理し、複数の戦略を使用してプラットフォームを保護し、不要なアクセスを防止します。

各お客様には、デフォルトで他のお客様から遮断された独自のサブネットが割り当てられ、Google Cloud NetApp Volume内のすべてのテナントには独自のネームスペースとVLANが割り当てられてデータが完全に分離されます。ユーザが認証されると、Service Delivery Engine（SDE；サービス提供エンジン）はそのテナントに固有の設定データのみを読み取ることができます。



== 物理的セキュリティ

事前承認が必要な場合、ケージとラックにアクセスできるのは、オンサイトエンジニアとネットアップ認定のフィールドサポートエンジニア（FSE）のみです。ストレージとネットワークの管理は許可されていません。ハードウェアのメンテナンス作業を実行できるのは、これらのオンサイトリソースのみです。

オンサイトエンジニアの場合は、作業仕様書（SOW）のチケットが発行されます。この作業内容には、ラックIDとデバイスの場所（RU）、その他すべての詳細情報が含まれます。NetApp FSEの場合、サイト訪問チケットはColoで発行する必要があります。チケットには、監査を目的とした訪問者の詳細、日付、時刻が含まれています。FSEのSOWは、社内でネットアップに通知されます。



== 運用チーム

Google Cloud NetApp Volumesの運用チームは、本番エンジニアリングチームと、Google Cloud NetApp Volumesのサイト信頼性エンジニア（SRE）と、ハードウェアのNetAppフィールドサポートエンジニアおよびパートナーで構成されています。すべての運用チームメンバーは、Google Cloudでの作業が認定されており、発行されたチケットごとに詳細な作業記録が保持されています。また、各意思決定が適切に精査されるように、厳格な変更管理および承認プロセスが用意されています。

SREチームはコントロールプレーンを管理し、Google Cloud NetApp VolumeのUI要求からバックエンドのハードウェアやソフトウェアにデータがどのようにルーティングされるかを管理します。SREチームは、ボリュームやinodeの最大数などのシステムリソースも管理します。SREは、カスタマーデータとやり取りしたり、カスタマーデータにアクセスしたりすることはできません。SREは、バックエンドハードウェアに対する新しいディスク交換要求やメモリ交換要求などのReturn Material Authorizations（RMA）との調整も行います。



== お客様の責任

Google Cloud NetApp Volumeをご利用のお客様は、組織のActive Directoryとユーザロールの管理、およびボリュームとデータの操作を管理しています。お客様は管理者ロールを割り当てられ、ネットアップとGoogle Cloudが提供する2つの事前定義されたロール（管理者とビューア）を使用して、同じGoogle Cloudプロジェクト内の他のエンドユーザに権限を委譲できます。

管理者は、お客様が適切であると判断したお客様のプロジェクト内の任意のVPCをGoogle Cloud NetApp Volumeとピアリングできます。Google Cloud Marketplaceサブスクリプションへのアクセスの管理、およびデータプレーンへのアクセス権を持つVPCの管理は、お客様の責任において行ってください。



== 悪意のあるSRE保護

発生する可能性がある懸念事項の1つは、Google Cloud NetApp Volumeが悪意のあるSREが存在するシナリオやSREクレデンシャルが侵害されたシナリオからどのように保護するかです。

本番環境へのアクセスには、限られた数のSRE担当者のみが使用されます。管理者権限は、経験豊富な一部の管理者にも制限されています。Google Cloud NetApp Volumes本番環境のユーザが実行したすべてのアクションがログに記録され、ベースラインへの異常な動作や疑わしいアクティビティがあれば、ネットアップのセキュリティ情報イベント管理（SIEM）脅威インテリジェンスプラットフォームによって検出されます。その結果、Google Cloud NetApp Volumeのバックエンドに多大な被害が及ぶ前に、悪意のある操作を追跡して軽減できます。



== ボリュームのライフサイクル

Google Cloud NetApp Volumeはサービス内のオブジェクトのみを管理し、ボリューム内のデータは管理しません。データ、ACL、ファイル所有者などを管理できるのは、ボリュームにアクセスしているクライアントだけです。これらのボリューム内のデータは保存時に暗号化され、アクセスはGoogle Cloud NetApp Volumeインスタンスのテナントに制限されます。

Google Cloud NetApp Volumeのボリュームライフサイクルは、create-update-deleteです。ボリュームのSnapshotコピーは、ボリュームが削除されるまで保持されます。また、Google Cloud NetApp Volumeのボリュームを削除できるのは、検証済みのGoogle Cloud NetApp Volume管理者だけです。管理者がボリューム削除を要求した場合、削除の確認のためにボリューム名を入力する手順が追加で必要になります。ボリュームを削除すると、そのボリュームは削除され、リカバリできなくなります。

Google Cloud NetApp Volumeの契約が終了した場合、NetAppは一定期間が経過した時点でボリュームを削除対象としてマークします。この期間が終了する前に、お客様の要求に応じてボリュームをリカバリできます。



== 認定資格

Google Cloud NetApp Volume for Google Cloudは、現在、ISO/IEC 27001：2013およびISO/IEC 27018：2019規格の認定を受けています。サービスは最近、SOC2 Type Iアテステーションレポートを受信しました。データセキュリティとプライバシーに対するNetAppの取り組みの詳細については、を参照してください https://www.netapp.com/company/trust-center/compliance/["コンプライアンス：データ セキュリティ とデータプライバシー"^]。



== GDPR

プライバシーとGDPRへの準拠に対する当社のコミットメントは、欧州委員会が提供するを含む https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en["標準契約条項"^]当社などの https://netapp.na1.echosign.com/public/esignWidget?wid=CBFCIBAA3AAABLblqZhCqPPgcufskl_71q-FelD4DHz5EMJVOkqqT0iiORT10DlfZnZeMpDrse5W6K9LEw6o*["カスタマーデータ処理補遺"^]多数の当社で利用できます https://www.netapp.com/how-to-buy/sales-terms-and-conditions%22%20/o%20%22SEO%20-%20Sales%20Terms%20and%20Conditions["お客様との契約"^]。また、当社のプライバシーポリシーには、当社の企業行動規範に規定されている中核的な価値観に裏付けられたこれらのコミットメントを定めています。
