---
sidebar: sidebar 
permalink: hybrid-cloud/vsphere_admin_introduction.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: このページでは、 VMware vSphere 環境に NetApp ONTAP ストレージ解決策を実装するためのベストプラクティスについて説明します。 
---
= vSphere 管理者向けの ONTAP の概要
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== ONTAP for vSphere を選ぶ理由

NetApp ONTAP は、オンプレミス環境とクラウド環境のどちらに導入しても、ストレージやデータの管理を簡易化し、 VMware 環境を明確に補完します。ネットアップの SAN ベースと NAS ベースのどちらの VMware アーキテクチャでも、業界最高レベルのデータ保護、 Storage Efficiency テクノロジ、卓越したパフォーマンスを実現できることは、何万ものお客様が vSphere 環境向けのストレージ解決策として ONTAP を選択している理由の 1 つです。

ネットアップでは、仮想化環境の管理という課題に直面しているお客様をサポートするために、さまざまな VMware 製品の VMware プラグイン、検証、および認定資格を多数提供しています。ネットアップは、 VMware が仮想化に何をもたらすかをストレージとデータの管理に活用することで、お客様は物理ストレージの管理ではなく、中核となるコンピテンシーに注力できます。VMware とネットアップの 20 年近くにわたるこのパートナーシップは、 VMware Cloud Foundation や Tanzu などの新しいテクノロジが出現したときに、 vSphere の基盤を引き続きサポートしつつ、お客様に高い価値を提供し続けています。

お客様が重視する主な要因は次のとおりです。

* * ユニファイドストレージ *
* * ストレージ効率 *
* * 仮想ボリュームとストレージ・ポリシー・ベースの管理 *
* * ハイブリッドクラウド *


サポートされているネットアップと VMware のソリューションの詳細については、次のリソースを参照してください。

* https://mysupport.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool を参照してください"^] IMTIMT では、 FC / FCoE 、 iSCSI 、 NFS 、 CIFS の各構成の構築に使用できる正規のコンポーネントとバージョンを定義しています。
* https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san&details=1&partner=64&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["『 VMware Compatibility Guide 』を参照してください"^]。『 VMware Compatibility Guide 』には、システム、 I/O 、ストレージ /SAN 、およびバックアップと VMware Infrastructure およびソフトウェア製品との互換性が記載されています
* https://www.netapp.com/support-and-training/documentation/ontap-tools-for-vmware-vsphere-documentation/["VMware 向け NetApp ONTAP ツール"^]。VMware vSphere 用の ONTAP ツールは、 VSC 、 VASA Provider 、 Storage Replication Adapter （ SRA ）の拡張機能を含む vCenter Server プラグインです。

