---
sidebar: sidebar 
permalink: containers/tanzu_with_netapp/vtwn_solution_overview.html 
keywords: VMware Tanzu, Tanzu, DevOps, Netapp, Astra Trident, Astra Control, Astra 
summary: このリファレンスガイドでは、Tanzu Kubernetes Grid（TKG）、Tanzu Kubernetes Grid Service（TKGS）、またはTanzu Kubernetes Grid Integrated（TKGI）のいずれかとして、ネットアップによって検証済みの複数のデータセンター環境に導入された、さまざまなVMware Tanzu Kubernetesソリューションの導入方法を検証します。 
---
= NVA-1166：ネットアップを使用したVMware Tanzuの評価
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


ネットアップ、 Alan Cowles 氏と Nikhil M Kulkarni 氏

このリファレンスガイドでは、Tanzu Kubernetes Grid（TKG）、Tanzu Kubernetes Grid Service（TKGS）、またはTanzu Kubernetes Grid Integrated（TKGI）のいずれかとして、ネットアップによって検証済みの複数のデータセンター環境に導入された、さまざまなVMware Tanzu Kubernetesソリューションの導入方法を検証します。また、ネットアップストレージシステムとAstra Tridentストレージオーケストレーションツールとのストレージ統合についても説明します。Tridentストレージオーケストレーションツールを使用して永続的ストレージを管理し、Astra Control Centerで、永続的ストレージを使用してステートフルアプリケーションのバックアップとクローニングを実行できます。最後に、解決策 の統合と検証のビデオデモを紹介します。



== ユースケース

NetApp解決策 を搭載したVMware Tanzuは、次のユースケースにおいて、お客様に卓越した価値を提供するように設計されています。

* VMware vSphereに導入され、ネットアップストレージシステムと統合されたVMware Tanzu Kubernetes Gridサービスの導入と管理が簡単です。
* VMware Tanzu Kubernetes Gridソリューションは、エンタープライズコンテナと仮想化ワークロードの機能を統合したものです。
* VMware Tanzuの機能にネットアップのストレージやネットアップのAstra製品スイートを使用した実際の構成とユースケース
* VMware Tanzu Kubernetes Gridクラスタに導入されたコンテナ化ワークロードを、Astra Control Centerを使用してネットアップストレージシステムにアプリケーションと整合性のある方法で保護または移行




== ビジネスバリュー

企業は、新しい製品の作成、リリースサイクルの短縮、新機能の迅速な追加を目的として、 DevOps の手法を採用する傾向に迫られています。即応性に優れた本来の性質から、コンテナやマイクロサービスは、 DevOps の実践を支援するうえで重要な役割を果たします。しかし、エンタープライズ環境で本番環境規模で DevOps を実践する場合、独自の課題が生じ、基盤となるインフラに次のような一定の要件が課せられます。

* スタック内のすべてのレイヤで高可用性を実現します
* 導入手順の簡易化
* ノンストップオペレーションとアップグレード
* API ベースのプログラム可能なインフラで、マイクロサービスの即応性を維持します
* パフォーマンスを保証するマルチテナンシー
* 仮想ワークロードとコンテナ化されたワークロードを同時に実行できます
* ワークロードのニーズに応じてインフラを個別に拡張できる
* オンプレミスのデータセンターとクラウドの両方でコンテナを実行するハイブリッドクラウドモデルに導入できます。


ネットアップのVMware Tanzuにはこのような課題があることを認め、お客様が選択したハイブリッドクラウド環境にVMware Tanzu Kubernetesソリューションを導入することで、それぞれの問題に対処できる解決策 が示されています。



== テクノロジの概要

NetApp解決策 を搭載したVMware Tanzuは、次の主要コンポーネントで構成されています。



=== VMware Tanzu Kubernetesプラットフォーム

VMware Tanzuには、ネットアップのソリューションエンジニアリングチームがラボで検証したさまざまなフレーバーがあります。各Tanzuリリースはネットアップのストレージポートフォリオと正常に統合されており、各リリースが特定のインフラ要件を満たすのに役立ちます。次の各バージョンのTanzuの特徴と機能については、このドキュメントで説明します。

VMware Tanzu Kubernetes Grid（TKG）

* VMware vSphere環境に展開される標準のアップストリームKubernetes環境。
* 以前はEssential PKSと呼ばれていました（Heptio買収により、2019年2月に取得）。
* TKGは、vSphere 6.7U3以降でサポートされる独立した管理クラスタインスタンスとともに導入されています。
* TKGの導入は、AWSやAzureと同様にクラウドにも導入できます。
* WindowsまたはLinuxのワーカーノード（Ubuntu / Photon）を使用できます。
* NSXとT、HA Proxy、AVIネットワーク、またはロードバランサをコントロールプレーンに使用できます。
* TKGはアプリケーション/データプレーンでMetalLBをサポートしています。
* vSphere CSIおよびNetApp Astra TridentなどのサードパーティCSISを使用可能


VMware Tanzu Kubernetes Grid Service（TKGS）

* VMware vSphere環境に展開される標準のアップストリームKubernetes環境。
* 以前はEssential PKSと呼ばれていました（Heptio買収により、2019年2月に取得）。
* TKGSは、vSphere 7.0U1以降でのみスーパーバイザクラスタおよびワークロードクラスタとともに配置されます。
* WindowsまたはLinuxのワーカーノード（Ubuntu / Photon）を使用できます。
* NSXとT、HA Proxy、AVIネットワーク、またはロードバランサをコントロールプレーンに使用できます。
* TKGSはアプリケーション/データプレーンでMetalLBをサポートしています。
* vSphere CSIおよびNetApp Astra TridentなどのサードパーティCSISを使用可能
* は、Tanzuを使用したvSphereポッドのサポートを提供し、環境内の有効なESXiホストでポッドを直接実行できるようにします。


VMware Tanzu Kubernetes Grid Integrated（TKGI）

* 以前の名称はEnterprise PKS（Heptio取得、2019年2月）です。
* NSXとT、HAプロキシ、AVIのいずれかを使用できます。独自のロードバランサを指定することもできます。
* vSphere 6.7U3以降、およびAWS、Azure、GCPでサポートされます。
* ウィザードを使用してセットアップすると、導入が簡単になります。
* BOSHが管理する変更不可の制御VMでTanzuを実行します。
* NetApp Astra Tridentのように、vSphere CSIやサードパーティのCSISを利用できる（一部の条件が適用される）


Tanzuを備えたvSphere（vSphereポッド）

* vSphereネイティブポッドは、完全な分離のために、処方された仮想ハードウェアを使用して、薄い光子ベースのレイヤで実行されます。
* NSXは必須ですが'Harborイメージ・レジストリなどの機能を追加サポートすることができます
* TKGSなどの仮想スーパーバイザクラスタを使用してvSphere 7.0U1以降に導入および管理し、ESXiノードでポッドを直接実行します。
* vSphere管理者による完全なvSphere統合、最高レベルの可視性と制御。
* 独立したCRXベースのポッドにより、最高レベルのセキュリティを実現。
* vSphere CSIの永続的ストレージ/サードパーティ製ストレージオーケストレーションツールはサポートされていません。




=== ネットアップストレージシステム

ネットアップには、エンタープライズデータセンターやハイブリッドクラウド環境に最適なストレージシステムが複数あります。ネットアップのポートフォリオには、コンテナ化されたアプリケーションに永続的ストレージを提供できる NetApp ONTAP 、 NetApp Element 、および NetApp E シリーズストレージシステムが含まれています。

詳細については、ネットアップのWebサイトを参照してください https://www.netapp.com["こちらをご覧ください"]。



=== ネットアップとストレージの統合

NetApp Astra Control Centerは、ステートフルKubernetesワークロード向けの充実したストレージおよびアプリケーション対応のデータ管理サービスを提供します。オンプレミス環境に導入され、信頼できるネットアップのデータ保護テクノロジを基盤としています。

詳細については、 NetApp Astra の Web サイトをご覧ください https://cloud.netapp.com/astra["こちらをご覧ください"]。

Astra Tridentは、VMware TanzuなどのコンテナやKubernetesディストリビューション向けの、オープンソースで完全にサポートされているストレージオーケストレーションツールです。

詳細については、 Astra Trident の Web サイトをご覧ください https://docs.netapp.com/us-en/trident/index.html["こちらをご覧ください"]。



== 検証済みリリースの現在のサポートマトリックスです

|===


| テクノロジ | 目的 | ソフトウェアのバージョン 


| NetApp ONTAP | ストレージ | 9.9.1 


| ネットアップアストラコントロールセンター | アプリケーション対応データ管理 | 22.04 


| ネットアップアストラト Trident | ストレージオーケストレーション | 22.04.0 


| VMware Tanzu Kubernetesグリッド | コンテナオーケストレーション | 1.4以降 


.2+| VMware Tanzu Kubernetes Gridサービス .2+| コンテナオーケストレーション | 0.0.15 [vSphere名前空間] 


| 1.22.6 [スーパーバイザクラスタのKubernetes ] 


| VMware Tanzu Kubernetes Grid統合 | コンテナオーケストレーション | 1.13.3 


| VMware vSphere の場合 | データセンターの仮想化 | 7.0U3 


| VMware NSX -Tデータセンター | ネットワークとセキュリティ | 3.1.3 


| VMware NSX Advanced Load Balancerの略 | ロードバランサ | 20.1.3 
|===
link:vtwn_overview_vmware_tanzu.html["次のステップ：VMware Tanzuの概要"]
