---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_overview_storint.html 
keywords: Astra, Astra Control Center, Trident, Astra Trident, persistent storage 
summary: ネットアップは、Anthosなどのコンテナベース環境における永続的データのオーケストレーションや管理を支援する製品を多数提供しています。 
---
= ネットアップストレージ統合の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/




== Anthos Readyストレージパートナープログラム：

Google Cloudは、Anthos Readyストレージパートナープログラムを通じて、パートナー様のストレージ統合とAnthosの新しいリリースの統合に関する最新検証を定期的にリクエストしています。現在検証済みのストレージソリューション、CSIドライバ、使用可能な機能、サポートされているAnthosのバージョンの一覧が表示されます https://cloud.google.com/anthos/docs/resources/partner-storage["こちらをご覧ください"^]。

ネットアップは、ネットアップのAstra CSI準拠のストレージオーケストレーションツールであるネットアップのONTAP およびElementストレージシステムとAnthosのバージョンを四半期ごとに検証する要求に定期的に準拠しています。

次の表に、ネットアップおよびネットアップパートナーのエンジニアが、Anthos Readyストレージパートナープログラムの一環としてネットアップAstra CSIドライバおよび機能セットの検証に使用してテストしたAnthosのバージョンを示します。

|===


| 展開タイプ | バージョン | ストレージシステム | Astra Tridentバージョン | プロトコル | の機能 


| VMware | 1.10 | ONTAP | 22.01 | NAS | マルチライター、ボリューム拡張、スナップショット 


| VMware | 1.10 | ONTAP | 22.01 | SAN | Raw Block、Volume Expansion、Snapshot 


| VMware | 1.10 | 要素（ Element ） | 22.01 | SAN | Raw Block、Volume Expansion、Snapshot 


| ベアメタル | 1.10 | ONTAP | 22.01 | NAS | マルチライター、ボリューム拡張、スナップショット 


| ベアメタル | 1.10 | ONTAP | 22.01 | SAN | Raw Block、Volume Expansion、Snapshot 
|===


== ネットアップとストレージの統合

ネットアップは、Anthosなどのコンテナベース環境における永続的データのオーケストレーションと管理に役立つ製品を多数提供しています。

NetApp Astra Tridentは、オープンソースで、Anthosを含むコンテナやKubernetesディストリビューション向けの完全にサポートされているストレージオーケストレーションツールです。詳細については、 Astra Trident の Web サイトをご覧ください https://docs.netapp.com/us-en/trident/index.html["こちらをご覧ください"]。

以下のページには、追加情報 解決策 を使用したAnthosでアプリケーションおよび永続的ストレージの管理向けに検証されたネットアップ製品に関する情報が掲載されています。

* link:a-w-n_overview_trident.html["ネットアップアストラト Trident"]


link:a-w-n_overview_advanced.html["次のオプション：高度な構成オプション：ネットアップを使用したAnthos"]
