---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_LB_SeeSaw.html 
summary: このページでは、シーソーロードバランサのインストールおよび設定手順について説明します。 
keywords: Anthos, GKE, Kubernetes, SeeSaw, LoadBalancer 
---
= Seesawロードバランサをインストールしています
:allow-uri-read: 


[role="lead"]
このページには、Seesaw管理対象ロードバランサのインストールおよび設定手順がリストされています。

Seesawは、VMware環境のAnthosクラスタにインストールされているデフォルトのマネージドネットワークロードバランサで、バージョン1.6～1.10です。



== シーソーロードバランサの取り付け

Seesawロードバランサは、VMware上のAnthosクラスタと完全に統合されており、AdminクラスタとUserクラスタセットアップの一部として自動で導入されています。'cluster.yaml'コンフィギュレーションファイルには'ロード・バランサ情報を提供するために変更する必要があるテキストのブロックがあります次に'組み込みのgkectl'ツールを使用してロード・バランサを導入するためのクラスタ配備の前に'追加のステップがあります


NOTE: シーソーロードバランサは、HAモードまたは非HAモードで展開できます。この検証の目的で、シーソーロードバランサはデフォルト設定である非HAモードで展開されました。本番環境では、フォールトトレランスと信頼性を確保するために、HA構成でシーソーを導入することを推奨します。



== Anthosとの統合

管理クラスタ用の各構成ファイルと、オンプレミスのAnthosで管理されるようにロードバランサを構成するために導入するユーザクラスタごとにセクションがあります。

次のテキストは、GKE-Adminクラスタ用パーティションの設定例です。コメントを解除して変更する必要がある値は、次の太字で表示されます。

[listing, subs="+quotes,+verbatim"]
----
*loadBalancer:*
  # (Required) The VIPs to use for load balancing
  *vips:*
    # Used to connect to the Kubernetes API
    *controlPlaneVIP: "10.61.181.230"*
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    # # addonsVIP: ""
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" or "ManualLB". Uncomment
  # the corresponding field below to provide the detailed spec
  *kind: Seesaw*
  # # (Required when using "ManualLB" kind) Specify pre-defined nodeports
  # manualLB:
  #   # NodePort for ingress service's http (only needed for user cluster)
  #   ingressHTTPNodePort: 0
  #   # NodePort for ingress service's https (only needed for user cluster)
  #   ingressHTTPSNodePort: 0
  #   # NodePort for control plane service
  #   controlPlaneNodePort: 30968
  #   # NodePort for addon service (only needed for admin cluster)
  #   addonsNodePort: 31405
  # # (Required when using "F5BigIP" kind) Specify the already-existing partition and
  # # credentials
  # f5BigIP:
  #   address:
  #   credentials:
  #     username:
  #     password:
  #   partition:
  #   # # (Optional) Specify a pool name if using SNAT
  #   # snatPoolName: ""
  # (Required when using "Seesaw" kind) Specify the Seesaw configs
  *seesaw:*
  # (Required) The absolute or relative path to the yaml file to use for IP allocation
  #  for LB VMs. Must contain one or two IPs.
  *ipBlockFilePath: "admin-seesaw-block.yaml"*
  #   (Required) The Virtual Router IDentifier of VRRP for the Seesaw group. Must
  #   be between 1-255 and unique in a VLAN.
    *vrid: 100*
  #   (Required) The IP announced by the master of Seesaw group
    *masterIP: "10.61.181.236"*
  #   (Required) The number CPUs per machine
    *cpus: 1*
  #   (Required) Memory size in MB per machine
    *memoryMB: 2048*
  #   (Optional) Network that the LB interface of Seesaw runs in (default: cluster
  #   network)
    *vCenter:*
  #   vSphere network name
      *networkName: VM_Network*
  #   (Optional) Run two LB VMs to achieve high availability (default: false)
    *enableHA: false*
----
Seesawロードバランサには、クラスタの展開ごとに提供する必要のある個別の静的な「seesaw-block.yaml」ファイルもあります。このファイルは'cluster.yaml配備ファイルと同じディレクトリに配置する必要がありますまたは'上記のセクションでフルパスを指定する必要があります

「admin-seesa-block.yaml」ファイルのサンプルは、次のスクリプトのようになります。

[listing, subs="+quotes,+verbatim"]
----
blocks:
  - netmask: "255.255.255.0"
    gateway: "10.63.172.1"
    ips:
    - ip: "10.63.172.152"
      hostname: "admin-seesaw-vm"
----

NOTE: このファイルは、ロードバランサが基盤となるクラスタに提供するネットワークのゲートウェイとネットマスク、およびロードバランサを実行するために導入された仮想マシンの管理IPとホスト名を提供します。

link:a-w-n_use_cases.html["次：解決策の検証 / ユースケース"]
