---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_overview_storint.html 
keywords: Astra, Astra Control Center, Trident, Astra Trident, persistent storage 
summary: ネットアップは、Anthosなどのコンテナベース環境における永続的データのオーケストレーションや管理を支援する製品を多数提供しています。 
---
= ネットアップストレージ統合の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/




== Anthos Readyストレージパートナープログラム：

Google Cloudは、Anthos Readyストレージパートナープログラムを通じて、パートナー様のストレージ統合とAnthosの新しいリリースの統合に関する最新検証を定期的にリクエストしています。現在検証済みのストレージソリューション、CSIドライバ、使用可能な機能、サポートされているAnthosのバージョンのリストが見つかります https://cloud.google.com/anthos/docs/resources/partner-storage["こちらをご覧ください"^]。

ネットアップは、ネットアップのAstra Trident CSI準拠ストレージオーケストレーションツール、およびONTAP とElementストレージシステムとAnthosのバージョンの検証を求める要望を、四半期ごとに定期的に満たしています。

次の表に、ネットアップおよびネットアップパートナーのエンジニアが、Anthos Readyストレージパートナープログラムの一環としてNetApp Astra CSIドライバおよび機能セットの検証にテストしたAnthosのバージョンを示します。

|===


| 展開タイプ | バージョン | ストレージシステム | Astra Tridentバージョン | プロトコル | の機能 


| VMware | 1.11 | ONTAP | 22.04 | NAS | マルチライター、ボリューム拡張、スナップショット 


| VMware | 1.11 | ONTAP | 22.04 | SAN | Raw Block、Volume Expansion、Snapshot 


| VMware | 1.11 | 要素（ Element ） | 22.04 | SAN | Raw Block、Volume Expansion、Snapshot 


| ベアメタル | 1.10 | ONTAP | 22.01 | NAS | マルチライター、ボリューム拡張、スナップショット 


| ベアメタル | 1.10 | ONTAP | 22.01 | SAN | Raw Block、Volume Expansion、Snapshot 
|===


== ネットアップとストレージの統合

ネットアップは、Anthosなどのコンテナベース環境における永続的データのオーケストレーションと管理に役立つ製品を多数提供しています。

NetApp Astra Tridentは、オープンソースで、Anthosを含むコンテナやKubernetesディストリビューション向けの完全にサポートされているストレージオーケストレーションツールです。詳細については、 Astra Trident の Web サイトをご覧ください https://docs.netapp.com/us-en/trident/index.html["こちらをご覧ください"]。

以下のページでは、追加情報 解決策 を使用したAnthosでアプリケーションおよび永続的ストレージの管理向けに検証されたネットアップ製品について説明します。

link:a-w-n_overview_trident.html["次のセクションでは、NetApp Astra Tridentの概要について説明します。"]
