---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_solution_overview.html 
keywords: NVA-1165, Anthos, GKE, Netapp, Astra Trident 
summary: このリファレンスガイドで解決策 は、ネットアップとエンジニアリングパートナーの検証を受け、複数のデータセンター環境に導入する場合のAnthosの導入を検証しました。 
---
= NVA-1165：ネットアップを使用したAnthos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


ネットアップ、Alan Cowles氏とNikhil Kulkarni氏

このリファレンスガイドで解決策 は、ネットアップとエンジニアリングパートナーによるAnthosの導入を検証し、複数のデータセンター環境に導入された場合について説明します。

また、ネットアップストレージシステムとの統合についても、 Astra Trident ストレージオーケストレーションツールを使用して永続的ストレージを管理することで詳しく説明します。最後に、解決策検証と実際の使用事例をいくつか確認して文書化します。



== ユースケース

NetApp解決策 を搭載したAnthosは、以下のユースケースでお客様に卓越した価値を提供するように設計されています。

* ベアメタル上の「bmctl」ツールまたはVMware vSphere上の「gkectl」ツールを使用して導入したAnthos環境の導入と管理が簡単です。
* エンタープライズコンテナと仮想化ワークロードのパワーを、vSphere上またはとベアメタル上に仮想的に導入されたAnthosで活用できます https://cloud.google.com/anthos/clusters/docs/bare-metal/1.9/how-to/vm-workloads["Kubevirt"^]。
* ネットアップストレージとKubernetes向けオープンソースストレージオーケストレーションツールであるAstra Tridentとともに使用されるAnthosの特徴を強調した実際の構成とユースケース




== ビジネスバリュー

企業は、新しい製品の作成、リリースサイクルの短縮、新機能の迅速な追加を目的として、 DevOps の手法を採用する傾向に迫られています。即応性に優れた本来の性質から、コンテナやマイクロサービスは、 DevOps の実践を支援するうえで重要な役割を果たします。しかし、エンタープライズ環境で本番環境規模で DevOps を実践する場合、独自の課題が生じ、基盤となるインフラに次のような一定の要件が課せられます。

* スタック内のすべてのレイヤで高可用性を実現します
* 導入手順の簡易化
* ノンストップオペレーションとアップグレード
* API ベースのプログラム可能なインフラで、マイクロサービスの即応性を維持します
* パフォーマンスを保証するマルチテナンシー
* 仮想ワークロードとコンテナ化されたワークロードを同時に実行できます
* ワークロードのニーズに応じてインフラを個別に拡張できる


NetApp解決策 を搭載したAnthosはこのような課題に対応し、オンプレミス環境に導入された完全自動化されたAnthosを、お客様のデータセンター環境に導入することで、それぞれの懸念に対応できる解決策 を提供します。



== テクノロジの概要

NetApp解決策 を搭載したAnthosは、以下の主要コンポーネントで構成されています。



=== オンプレミスのAnthos

オンプレミスのAnthosは、VMware vSphereハイパーバイザーや、選択したベアメタルインフラに導入可能な、完全にサポートされているエンタープライズ向けKubernetesプラットフォームです。

Anthos の詳細については、 Anthos の Web サイトを参照してください https://https://cloud.google.com/anthos/["こちらをご覧ください"^]。



=== ネットアップストレージシステム

ネットアップには、エンタープライズデータセンターやハイブリッドクラウド環境に最適なストレージシステムが複数あります。ネットアップのポートフォリオには、コンテナ化されたアプリケーションに永続的ストレージを提供できる NetApp ONTAP 、 NetApp Element 、および NetApp E シリーズストレージシステムが含まれています。

詳細については、ネットアップの Web サイトをご覧ください https://www.netapp.com["こちらをご覧ください"]。



=== ネットアップとストレージの統合

Astra Tridentは、オープンソースで、Anthosを含むコンテナやKubernetesディストリビューション向けの完全にサポートされているストレージオーケストレーションツールです。

詳細については、 Astra Trident の Web サイトをご覧ください https://docs.netapp.com/us-en/trident/index.html["こちらをご覧ください"]。



== Advanced Configuration Options （詳細設定オプション）

このセクションは、実環境のユーザがこの解決策を本番環境に導入するときに実行する必要があるカスタマイズ（専用のプライベートイメージレジストリの作成やカスタムロードバランサインスタンスの導入など）に特化したものです。



== 検証済みリリースの現在のサポートマトリックスです

|===


| テクノロジ | 目的 | ソフトウェアのバージョン 


| NetApp ONTAP | ストレージ | 9.8 、 9.9.1 


| NetApp Element | ストレージ | 12.3 


| ネットアップアストラト Trident | ストレージオーケストレーション | 22.01.0 


| VMware上のAnthosクラスタ | コンテナオーケストレーション | 1.10 


| ベアメタルの Anthos | コンテナオーケストレーション | 1.10 


| VMware vSphere の場合 | データセンターの仮想化 | 6.7U3、7.0U3 
|===
link:a-w-n_overview_anthos.html["次のステップ：Anthosの概要：ネットアップを基盤とするAnthos"]
