---
sidebar: sidebar 
permalink: infra/hcicaci_design_considerations.html 
keywords:  
summary:  
---
= 設計上の考慮事項
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== ネットワーク設計

Cisco ACI ファブリックの最小構成は、 2 つのリーフスイッチと 2 つのスパインスイッチで構成されます。これらのスイッチには、ファブリック全体を管理および制御する 3 つ以上の APIC が含まれます。すべてのワークロードはリーフスイッチに接続されます。スパインスイッチはネットワークのバックボーンであり、すべてのリーフスイッチの相互接続を行います。相互接続できるリーフスイッチは 2 つありません。各リーフスイッチは、フルメッシュトポロジで各スパインスイッチに接続されています。

この 2 層スパイン / リーフアーキテクチャでは、サーバがどのリーフスイッチに接続されているかに関係なく、トラフィックは常に同じデバイス数を超えて、ファブリックに接続されている別のサーバに到達します（他のサーバが同じリーフに配置されている場合を除く）。このアプローチにより、レイテンシを予測可能なレベルに維持できます。



== 設計を計算（ Compute Design

NetApp HCI を使用した高可用性インフラに最低限必要なコンピューティングノード数は 2 つです。NetApp HCI には、ケーブル接続用の 2 つのオプションがあります。ケーブルは 2 本から 6 本までです。NetApp HCI H410C コンピューティングノードには、 2 つの 1GbE ポート（ポート A と B ）と 4 つの 10 / 25GbE ポート（ポート C 、 D 、 E 、 F ）が搭載されています。ケーブルを 2 本使用する場合は、ポート D と E をアップリンクスイッチへの接続に使用し、 6 本のケーブルを使用する場合は A から F までのすべてのポートを使用します。各ノードには、 Intelligent Platform Management Interface （ IPMI ）機能をサポートするアウトオブバンド管理ポートも追加されています。この解決策では、コンピューティングノードにケーブル 2 本のオプションを使用します。

VMware 環境には、 NetApp HCI に NetApp Deployment Engine （ NDE ）と呼ばれる自動導入ツールが付属しています。VMware 以外の環境では、コンピューティングノードにハイパーバイザーやオペレーティングシステムを手動でインストールする必要があります。



== ストレージ設計

NetApp HCI では、ストレージノードにケーブル 4 本のオプションを使用します。NetApp HCI H410S ストレージノードは、オンボードの 2 つの 1GbE ポート（ポート A と B ）と 2 つの 10 / 25GbE ポート（ポート C と D ）で構成されています。2 つの 1GbE ポートは管理トラフィックに使用される Bond1G （アクティブ / パッシブモード）としてバンドルされており、 2 つの 10 / 25GbE ポートはストレージデータトラフィックに使用される Bond10G （ LACP アクティブモード）としてバンドルされています。

VMware 以外の環境では、 NetApp HCI ストレージクラスタの最小構成は 4 ノードです。1.8 より前のバージョンの NetApp HCI を VMware 環境で使用する場合の最小構成は、 4 つのストレージノードです。ただし、 VMware 環境で HCI バージョン 1.8 を使用する場合、 NetApp HCI ストレージクラスタの最小構成は 2 ノードです。NetApp HCI の 2 ノードストレージクラスタの詳細については、のドキュメントを参照してください https://www.netapp.com/us/media/tr-4823.pdf["こちらをご覧ください"^]。

link:hcicaci_vmware_vsphere.html["次の例： VMware vSphere ： NetApp HCI with Cisco ACI"]
