---
sidebar: sidebar 
permalink: infra/rhv-2._configure_data_switches.html 
keywords: Mellanox, MLAG cluster, fault tolerance, ILP, LLDP 
summary:  
---
= 2. データスイッチの構成： NetApp HCI with RHV
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
この導入では、 Mellanox SN2010 スイッチを使用手順して、コンピューティングノードとストレージノードのデータプレーンに 25Gbps 接続を提供します。これらの手順は、スイッチがラックに設置されてケーブル接続され、初期セットアッププロセスが完了したあとに開始されます。インフラへのデータ接続を提供するようにスイッチを設定するには、次の手順を実行します。



=== MLAG クラスタを作成して、フォールトトレランスを実現します

. 一般的な設定を行うには、各 Mellanox SN210 スイッチで次のコマンドを実行します。
+
.. コンフィギュレーションモードを開始します。
+
....
Switch-01 enable
Switch-01 configure terminal
....
.. Inter-Peer Link （ IPL ）に必要な LACP を有効にします。
+
....
Switch-01 (config) # lacp
....
.. Link Layer Discovery Protocol （ LLDP ）を有効にします。
+
....
Switch-01 (config) # lldp
....
.. IP ルーティングを有効にします。
+
....
Switch-01 (config) # ip routing
....
.. MLAG プロトコルをイネーブルにします。
+
....
Switch-01 (config) # protocol mlag
....
.. グローバル QoS を有効にします。
+
....
Switch-01 (config) # dcb priority-flow-control enable force
....


. MLAG を機能させるには、スイッチを IPL 経由で相互にピア関係を設定する必要があります。冗長性を確保するには、 2 つ以上の物理リンクで構成する必要があります。IPL の MTU はジャンボフレームに設定されています（ 9216 ）。すべての VLAN はデフォルトで有効になっています。ドメイン内の各スイッチで次のコマンドを実行します。
+
.. IPL のポートチャネル 10 を作成します。
+
....
Switch-01 (config) # interface port-channel 10
Switch-01 (config interface port-channel 10) # description IPL
Switch-01 (config interface port-channel 10) # exit
....
.. インターフェイス ETH 1/20 および 1/22 をポートチャネルに追加します。
+
....
Switch-01 (config) # interface ethernet 1/20 channel-group 10 mode active
Switch-01 (config) # interface ethernet 1/20 description ISL-SWB_01
Switch-01 (config) # interface ethernet 1/22 channel-group 10 mode active
Switch-01 (config) # interface ethernet 1/22 description ISL-SWB_02
....
.. IPL トラフィック専用の標準範囲外の VLAN を作成します。
+
....
Switch-01 (config) # vlan 4000
Switch-01 (config vlan 4000) # name IPL VLAN
Switch-01 (config vlan 4000) # exit
....
.. ポートチャネルを IPL として定義します。
+
....
Switch-01 (config) # interface port-channel 10 ipl 1
Switch-01 (config) # interface port-channel 10 dcb priority-flow-control mode on force
....
.. 各 IPL メンバーに IP を設定します（ルーティング不可。スイッチの外部ではアドバタイズされません）。
+
....
Switch-01 (config) # interface vlan 4000
Switch-01 (config vlan 4000) # ip address 10.0.0.1 255.255.255.0
Switch-01 (config vlan 4000) # ipl 1 peer-address 10.0.0.2
Switch-01 (config vlan 4000) # exit
....


. 2 つのスイッチに一意の MLAG ドメイン名を作成し、 MLAG 仮想 IP （ VIP ）を割り当てます。この IP は、 2 つのスイッチ間のキープアライブハートビートメッセージに使用されます。ドメイン内の各スイッチで、次のコマンドを実行します。
+
.. MLAG ドメインを作成し、 IP アドレスとサブネットを設定します。
+
....
Switch-01 (config) # mlag-vip MLAG-VIP-DOM ip a.b.c.d /24 force
....
.. システム MLAG の仮想 MAC アドレスを作成します。
+
....
Switch-01 (config) # mlag system-mac AA:BB:CC:DD:EE:FF
....
.. グローバルにアクティブになるように MLAG ドメインを設定します。
+
....
Switch-01 (config) # no mlag shutdown
....




MLAG VIP 用の IP は、スイッチ管理ネットワーク（ mgmt0 ）と同じサブネット内に配置する必要があります。また、使用する MAC アドレスは任意のユニキャスト MAC アドレスにすることができ、 MLAG ドメイン内の両方のスイッチで同じ値に設定する必要があります。



=== ストレージホストとコンピューティングホストに接続するためのポートの設定

. NetApp HCI のサービスをサポートするために必要な VLAN をそれぞれ作成します。ドメイン内の各スイッチで、次のコマンドを実行します。
+
.. VLAN を作成します。
+
....
Switch-01 (config) # vlan 1172
Switch-01 (config vlan 1172) exit
Switch-01 (config) # vlan 3343
Switch-01 (config vlan 3343) exit
Switch-01 (config) # vlan 3344
Switch-01 (config vlan 3345) exit
Switch-01 (config) # vlan 3345
Switch-01 (config vlan 3346) exit
....
.. アカウンティングを容易にするために、各 VLAN の名前を作成します。
+
....
Switch-01 (config) # vlan 1172 name “MGMT_Network”
Switch-01 (config) # vlan 3343 name “Storage_Network”
Switch-01 (config) # vlan 3345 name “Migration_Network”
Switch-01 (config) # vlan 3346 name “VM_Network”
....


. スイッチ間に接続を分散し、 NetApp HCI コンピューティングノードに適切な VLAN にタグ付けできるように、特定されたポートに MLAG インターフェイスとハイブリッド VLAN を作成します。
+
.. 使用するポートを選択します。
+
....
Switch-01 (config) # interface ethernet 1/15
....
.. 各ポートに MTU を設定します。
+
....
Switch-01 (config interface ethernet 1/15) # mtu 9216 force
....
.. 各ポートのスパニングツリー設定を変更します。
+
....
Switch-01 (config interface ethernet 1/15) # spanning-tree bpdufilter enable
Switch-01 (config interface ethernet 1/15) # spanning-tree port type edge
Switch-01 (config interface ethernet 1/15) # spanning-tree bpduguard enable
....
.. スイッチポートモードをハイブリッドに設定します。
+
....
Switch-01 (config interface ethernet 1/15) # switchport mode hybrid
Switch-01 (config interface ethernet 1/15) # exit
....
.. 変更する各ポートの説明を作成します。
+
....
Switch-01 (config) # interface ethernet 1/15 description HCI-CMP-01 PortD
....
.. MLAG ポートチャネルを作成し、設定します。
+
....
Switch-01 (config) # interface mlag-port-channel 215
Switch-01 (config interface mlag-port-channel 215) # exit
Switch-01 (config) # interface mlag-port-channel 215 no shutdown
Switch-01 (config) # interface mlag-port-channel 215 mtu 9216 force
Switch-01 (config) # interface ethernet 1/15 lacp port-priority 10
Switch-01 (config) # interface ethernet 1/15 lacp rate fast
Switch-01 (config) # interface ethernet 1/15 mlag-channel-group 215 mode active
....
.. NetApp HCI 環境に適した VLAN にタグを付けます。
+
....
Switch-01 (config) # interface mlag-port-channel 215 switchport hybrid
Switch-01 (config) # interface mlag-port-channel 215 switchport hybrid allowed-vlan add 1172
Switch-01 (config) # interface mlag-port-channel 215 switchport hybrid allowed-vlan add 3343
Switch-01 (config) # interface mlag-port-channel 215 switchport hybrid allowed-vlan add 3345
Switch-01 (config) # interface mlag-port-channel 215 switchport hybrid allowed-vlan add 3346
....


. スイッチ間に接続を分散し、 NetApp HCI ストレージノードに適切な VLAN にタグ付けできるように、 MLAG インターフェイスとハイブリッド VLAN ポートを特定します。
+
.. 使用するポートを選択します。
+
....
Switch-01 (config) # interface ethernet 1/3
....
.. 各ポートに MTU を設定します。
+
....
Switch-01 (config interface ethernet 1/3) # mtu 9216 force
....
.. 各ポートのスパニングツリー設定を変更します。
+
....
Switch-01 (config interface ethernet 1/3) # spanning-tree bpdufilter enable
Switch-01 (config interface ethernet 1/3) # spanning-tree port type edge
Switch-01 (config interface ethernet 1/3) # spanning-tree bpduguard enable
....
.. スイッチポートモードをハイブリッドに設定します。
+
....
Switch-01 (config interface ethernet 1/3) # switchport mode hybrid
Switch-01 (config interface ethernet 1/3) # exit
....
.. 変更する各ポートの説明を作成します。
+
....
Switch-01 (config) # interface ethernet 1/3 description HCI-STG-01 PortD
....
.. MLAG ポートチャネルを作成し、設定します。
+
....
Switch-01 (config) # interface mlag-port-channel 203
Switch-01 (config interface mlag-port-channel 203) # exit
Switch-01 (config) # interface mlag-port-channel 203 no shutdown
Switch-01 (config) # interface mlag-port-channel 203 mtu 9216 force
Switch-01 (config) # interface mlag-port-channel 203 lacp-individual enable force
Switch-01 (config) # interface ethernet 203 lacp port-priority 10
Switch-01 (config) # interface ethernet 203 lacp rate fast
Switch-01 (config) # interface ethernet 1/3 mlag-channel-group 203 mode active
....
.. ストレージ環境に適した VLAN にタグを付けます。
+
....
Switch-01 (config) # interface mlag-port-channel 203 switchport mode hybrid
Switch-01 (config) # interface mlag-port-channel 203 switchport hybrid allowed-vlan add 1172
Switch-01 (config) # interface mlag-port-channel 203 switchport hybrid allowed-vlan add 3343
....





NOTE: ここでは、例として単一ポートの構成を示します。また、解決策で接続されている追加ポートごとに、および MLAG ドメイン内の 2 番目のスイッチの関連ポートに対しても実行する必要があります。各ポートの説明を更新して、もう一方のスイッチでケーブル接続および設定されているデバイスポートを反映することを推奨します。



=== スイッチのアップリンクポートを作成します

. MLAG インターフェイスを作成して、コアネットワークから両方の Mellanox SN2010 スイッチへのアップリンクを提供します。
+
....
Switch-01 (config) # interface mlag port-channel 201
Switch-01 (config interface mlag port-channel) # description Uplink CORE-SWITCH port PORT
Switch-01 (config interface mlag port-channel) # exit
....
. MLAG メンバーを設定します。
+
....
Switch-01 (config) # interface ethernet 1/1 description Uplink to CORE-SWITCH port PORT
Switch-01 (config) # interface ethernet 1/1 speed 10000 force
Switch-01 (config) # interface mlag-port-channel 201 mtu 9216 force
Switch-01 (config) # interface ethernet 1/1 mlag-channel-group 201 mode active
....
. スイッチポートモードを hybrid に設定し、コアアップリンクスイッチからすべての VLAN を許可します。
+
....
Switch-01 (config) # interface mlag-port-channel switchport mode hybrid
Switch-01 (config) # interface mlag-port-channel switchport hybrid allowed-vlan all
....
. MLAG インターフェイスが動作していることを確認します。
+
....
Switch-01 (config) # interface mlag-port-channel 201 no shutdown
Switch-01 (config) # exit
....



NOTE: このセクションの設定は、 MLAG ドメイン内の 2 番目のスイッチでも実行する必要があります。各ポートの説明を更新して、もう一方のスイッチでケーブル接続および設定されているデバイスポートを反映することを推奨します。

link:rhv-3._deploy_element_storage_system.html["次へ： 3.HCI ストレージノードに Element ストレージシステムを導入します"]
