---
sidebar: sidebar 
permalink: vmw-sc/sc-overview.html 
keywords: NetApp Solutions, vmware, sovereign cloud 
summary:  
---
= VMware Sovereign Cloudの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
国や州の政府、規制の厳しい業界（金融や医療など）など、機密性の高いデータを処理、維持する多くの企業にとって、クラウドコンピューティングに必要なコンポーネントとして主権の概念が登場しています。政府はまた、デジタル経済能力を拡大し、クラウドサービスに対する多国籍企業への依存を減らすことを目指しています。



== VMwareソブリンクラウドイニシアチブ

VMwareは、ソブリンクラウドを次のようなメリットの1つとして定義

* 民間部門と公共部門の両方の組織にとって重要なデータ（国のデータ、企業データ、個人データなど）の価値を保護し、最大限に引き出す
* デジタル経済に国家的な能力を提供する
* 監査されたセキュリティ管理でデータを保護
* データプライバシー法へのコンプライアンスを確保
* データの常駐とデータ主権の両方を管轄区域全体で管理することで、データの制御性を向上




== 信頼できるVMwareソブリンクラウドサービスプロバイダとのパートナーシップ

成功を確実にするには、信頼できる、独立した信頼できるクラウドプラットフォームをホスティングできるパートナーと協力する必要があります。VMware Sovereign Cloudイニシアチブで認められたVMwareクラウドプロバイダは、VMware Sovereign Cloudフレームワークで概説されている主要な原則とベストプラクティスを具体化した、最新のソフトウェア定義アーキテクチャに基づいたクラウドソリューションの設計と運用に取り組んでいます。

* *データ主権と管轄権*–すべてのデータは居住者であり、そのデータが収集された国の排他的な管理と権限の対象となります。管轄区域内で運用を完全に管理
* *データアクセスと整合性*–クラウドインフラストラクチャは耐障害性に優れており、管轄区域内の少なくとも2つのデータセンターロケーションで利用でき、セキュアでプライベートな接続オプションを利用できます。
* *データセキュリティとコンプライアンス*–情報セキュリティ管理システムの制御は、業界で認められたグローバル（または地域）基準に照らして認定され、定期的に監査されます。
* *データの独立性と移動性*–最新のアプリケーションアーキテクチャをサポートし、ベンダーのクラウドロックインを防ぎ、アプリケーションのモビリティと独立性を実現


VMwareの詳細については、次のサイトを参照してください。

* link:https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/docs/vmw-sovereign-cloud-solution-brief-customer.pdf["VMware Sovereign Cloudの概要"]
* link:https://www.vmware.com/topics/glossary/content/sovereign-cloud.html["VMware Sovereign Cloudとは"]
* link:https://blogs.vmware.com/cloud/2021/10/06/vmware-sovereign-cloud/["新しいVMware Sovereign Cloud Initiativeのご紹介"]
* link:https://www.vmware.com/solutions/cloud-infrastructure/sovereign-cloud["VMwareソブリンクラウドソリューション"]

