---
sidebar: sidebar 
permalink: vmw-sc/sc-use-cases.html 
keywords: NetApp Solutions, vmware, sovereign cloud, netapp, use case 
summary:  
---
= NetppとVMware Sovereign Cloud：ユースケース
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetAppは、複数のNetAppテクノロジを統合することで、VMwareソブリンクラウドの概念をサポートします。

VMwareソブリンクラウドとのNetAppテクノロジ統合の詳細については、次のリンクを参照してください。

* link:#storageGRID["オブジェクトストア拡張機能としてのNetApp StorageGRID"]




== オブジェクトストア拡張機能としてのNetApp StorageGRID

NetAppは、VMwareと協力してNetApp StorageGRIDをVMware Cloud Directorに統合し、VMwareソブリンクラウドをサポートしています。このVMware Cloud Directorのプラグインを使用すると、サービスプロバイダは、ユースケースに関係なくStorageGRIDをオブジェクトストレージ製品として使用できます。また、サービスプロバイダが提供カタログの他の部分を管理するために使用するのと同じVMwareマルチテナント解決策（VMware Cloud Director）を使用してStorageGRIDを管理できます。

VMwareソブリンクラウドを提供するパートナーは、NetApp StorageGRIDを選択して、非構造化データを使用したクラウド環境の管理と保守を支援できます。Amazon S3 APIなどの業界標準のAPIをネイティブにサポートしているため、幅広いクラウド環境間でのスムーズな相互運用性が確保されます。また、自動化されたライフサイクル管理などの独自のイノベーションにより、非構造化データのより対費用効果の高い保護、ストレージ、長期保存が保証されます。

クラウドディレクタープロバイダのお客様とネットアップのソブリンクラウド統合により、次のようなメリットが得られます。

* メタデータを含む機密データを主権の下に保持しながら、データプライバシー法に違反する可能性のある外国当局によるアクセスを防止します。
* セキュリティとコンプライアンスの強化により、急速に進化する攻撃ベクトルからアプリケーションとデータを保護しながら、信頼できるローカルインフラストラクチャ、組み込みフレームワーク、ローカルエキスパートによる継続的なコンプライアンスを維持します。
* 将来を見据えたインフラ：変化するデータプライバシー規制、セキュリティ上の脅威、地政学に迅速に対応できます。
* 安全なデータ共有と分析によってデータの価値を最大限に引き出し、プライバシー法に違反することなくイノベーションを推進できます。データの整合性が保護され、正確な分析情報が得られます。


StorageGRIDとの統合の詳細については、以下を参照してください。

* link:https://www.netapp.com/newsroom/press-releases/news-rel-20231107-561294/["NetAppの発表"]

