---
sidebar: sidebar 
permalink: containers/a-w-n_overview_storint.html 
keywords: Astra, Astra Control Center, Trident, Trident, persistent storage 
summary: ネットアップは、Anthosなどのコンテナベース環境における永続的データのオーケストレーションや管理を支援する製品を多数提供しています。 
---
= ネットアップストレージ統合の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ネットアップは、Anthosなどのコンテナベース環境における永続的データのオーケストレーションや管理を支援する製品を多数提供しています。



== Anthos Readyストレージパートナープログラム：

Google Cloudは、Anthos Readyストレージパートナープログラムを通じて、パートナー様のストレージ統合とAnthosの新しいリリースの統合に関する最新検証を定期的にリクエストしています。現在検証済みのストレージソリューション、CSIドライバ、利用可能な機能、サポートされているAnthosのバージョンのリストを参照 https://cloud.google.com/anthos/docs/resources/partner-storage["ここをクリック"^]できます。

NetAppは四半期ごとに定期的にコンプライアンスを維持しており、Trident CSI準拠のストレージオーケストレーションツールとONTAPストレージシステムのバージョンをAnthosで検証するよう求められています。

次の表に、NetAppおよびNetAppパートナーのエンジニアがAnthos Readyストレージパートナープログラムの一環としてNetApp Trident CSIドライバと機能セットを検証するためにテストしたAnthosのバージョンを示します。

|===


| 展開タイプ | バージョン | ストレージシステム | Tridentバージョン | プロトコル | 特徴 


| VMware | 1.28 | ONTAP 9.12.1 | 24.02 | NAS | マルチライター、ボリューム拡張、スナップショット、PVCDataSource 


| VMware | 1.28 | ONTAP 9.12.1 | 24.02 | SAN | rawブロック、ボリューム拡張、スナップショット、PVCDataSource 


| VMware | 1.15 | ONTAP 9.12.1 | 23.04 | NAS | マルチライター、ボリューム拡張、スナップショット、PVCDataSource 


| VMware | 1.15 | ONTAP 9.12.1 | 23.04 | SAN | rawブロック、ボリューム拡張、スナップショット、PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | NAS | マルチライター、ボリューム拡張、スナップショット、PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | SAN | rawブロック、ボリューム拡張、スナップショット、PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | NAS | マルチライター、ボリューム拡張、スナップショット、PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | SAN | rawブロック、ボリューム拡張、スナップショット、PVCDataSource 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | NAS | マルチライター、ボリューム拡張、スナップショット 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | SAN | Raw Block、Volume Expansion、Snapshot 


| VMware | 1.11 | 要素12.3 | 22.04 | SAN | Raw Block、Volume Expansion、Snapshot 


| ベアメタル | 1.10 | ONTAP 9.8 | 22.01 | NAS | マルチライター、ボリューム拡張、スナップショット 


| ベアメタル | 1.10 | ONTAP 9.8 | 22.01 | SAN | Raw Block、Volume Expansion、Snapshot 
|===


== ネットアップとストレージの統合

ネットアップは、Anthosなどのコンテナベース環境における永続的データのオーケストレーションと管理に役立つ製品を多数提供しています。

NetApp Tridentは、Anthosを含むコンテナとKubernetesディストリビューション向けの、オープンソースで完全サポートされたストレージオーケストレーションツールです。詳細については、TridentのWebサイトを参照して https://docs.netapp.com/us-en/trident/index.html["ここをクリック"]ください。

以下のページでは、追加情報 解決策 を使用したAnthosでアプリケーションおよび永続的ストレージの管理向けに検証されたネットアップ製品について説明します。
