---
sidebar: sidebar 
permalink: containers/a-w-n_solution_overview.html 
keywords: NVA-1165, Anthos, GKE, Netapp, Trident 
summary: このリファレンスガイドで解決策 は、ネットアップとエンジニアリングパートナーの検証を受け、複数のデータセンター環境に導入する場合のAnthosの導入を検証しました。 
---
= NVA-1165：ネットアップを使用したAnthos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


ネットアップBanu SundharとSuresh Thoppay

[role="lead"]
このリファレンスガイドで解決策 は、ネットアップとエンジニアリングパートナーの協力のもと、Anthosを複数のデータセンター環境に導入する際の検証について説明します。また、永続的ストレージを管理するためのTridentストレージオーケストレーションツールを使用したNetAppストレージシステムとのストレージ統合についても詳しく説明します。最後に、解決策 検証と実際のユースケースをいくつか確認して文書化します。



== ユースケース

NetApp解決策 を搭載したAnthosは、以下のユースケースでお客様に卓越した価値を提供するように設計されています。

* ベアメタル上の「bmctl」ツールまたはVMware vSphere上の「gkectl」ツールを使用して展開されたAnthos環境の導入と管理が容易になります。
* エンタープライズコンテナと仮想化ワークロードのパワーを、vSphere上またはとベアメタル上に仮想的に導入されたAnthosで活用できます https://cloud.google.com/anthos/clusters/docs/bare-metal/1.9/how-to/vm-workloads["Kubevirt"^]。
* NetAppストレージやKubernetes向けのオープンソースストレージオーケストレーションツールであるTridentと併用した場合の、Anthosの機能に焦点を当てた実際の構成とユースケース。




== ビジネスバリュー

企業は、新しい製品の作成、リリースサイクルの短縮、新機能の迅速な追加を目的として、 DevOps の手法を採用する傾向に迫られています。即応性に優れた本来の性質から、コンテナやマイクロサービスは、 DevOps の実践を支援するうえで重要な役割を果たします。しかし、エンタープライズ環境で本番環境規模で DevOps を実践する場合、独自の課題が生じ、基盤となるインフラに次のような一定の要件が課せられます。

* スタック内のすべてのレイヤで高可用性を実現します
* 導入手順の簡易化
* ノンストップオペレーションとアップグレード
* API ベースのプログラム可能なインフラで、マイクロサービスの即応性を維持します
* パフォーマンスを保証するマルチテナンシー
* 仮想ワークロードとコンテナ化されたワークロードを同時に実行できます
* ワークロードのニーズに応じてインフラを個別に拡張できること


NetApp解決策 を搭載したAnthosは、このような課題に対応し、お客様のデータセンター環境にオンプレミス環境に完全に自動化された導入を実装することで、それぞれの問題に対処できる解決策 を提供します。



== テクノロジの概要

NetApp解決策 を搭載したAnthosは、以下の主要コンポーネントで構成されています。



=== オンプレミスのAnthos

オンプレミスのAnthosは、VMware vSphereハイパーバイザーや、選択したベアメタルインフラに導入可能な、完全にサポートされているエンタープライズ向けKubernetesプラットフォームです。

Anthos の詳細については、 Anthos の Web サイトを参照してください https://cloud.google.com/anthos["こちらをご覧ください"^]。



=== ネットアップストレージシステム

ネットアップには、エンタープライズデータセンターやハイブリッドクラウド環境に最適なストレージシステムが複数あります。ネットアップのポートフォリオには、NetApp ONTAP ストレージシステム用のNetApp ONTAP 、Cloud Volumes ONTAP 、Cloud Volumes Service 、Azure NetApp Files 、FSxNが含まれており、いずれもコンテナ化されたアプリケーション用の永続的ストレージを提供できます。

詳細については、ネットアップの Web サイトをご覧ください https://www.netapp.com["こちらをご覧ください"]。



=== ネットアップとストレージの統合

Tridentは、Anthosを含むコンテナとKubernetesディストリビューション向けのオープンソースで完全サポートされているストレージオーケストレーションツールです。

詳細については、TridentのWebサイトを参照して https://docs.netapp.com/us-en/trident/index.html["こちらをご覧ください"]ください。



== Advanced Configuration Options （詳細設定オプション）

このセクションは、実環境のユーザがこの解決策を本番環境に導入するときに実行する必要があるカスタマイズ（専用のプライベートイメージレジストリの作成やカスタムロードバランサインスタンスの導入など）に特化したものです。



== 検証済みリリースの現在のサポートマトリックスです

を参照してください https://cloud.google.com/anthos/docs/resources/partner-storage#netapp["こちらをご覧ください"] を参照してください。
