---
sidebar: sidebar 
permalink: containers/a-w-n_solution_overview.html 
keywords: NVA-1165, Anthos, GKE, Netapp, Trident 
summary: このリファレンスガイドで解決策 は、ネットアップとエンジニアリングパートナーの検証を受け、複数のデータセンター環境に導入する場合のAnthosの導入を検証しました。 
---
= NVA-1165：ネットアップを使用したAnthos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


ネットアップBanu SundharとSuresh Thoppay

[role="lead"]
このリファレンスガイドで解決策 は、ネットアップとエンジニアリングパートナーの協力のもと、Anthosを複数のデータセンター環境に導入する際の検証について説明します。また、永続的ストレージを管理するためのTridentストレージオーケストレーションツールを使用したNetAppストレージシステムとのストレージ統合についても詳しく説明します。最後に、解決策 検証と実際のユースケースをいくつか確認して文書化します。



== ユースケース

NetApp解決策 を搭載したAnthosは、以下のユースケースでお客様に卓越した価値を提供するように設計されています。

* ベアメタルで提供されているツールまたはVMware vSphereで提供されているツール `gkectl`を使用して、導入されたAnthos環境を簡単に導入および管理でき `bmctl`ます。
* Anthosは、エンタープライズコンテナと仮想ワークロードの機能を、vSphereに仮想的に導入するか、を使用してベアメタルに導入し https://cloud.google.com/anthos/clusters/docs/bare-metal/1.9/how-to/vm-workloads["Kubevirt"^]ます。
* NetAppストレージやKubernetes向けのオープンソースストレージオーケストレーションツールであるTridentと併用した場合の、Anthosの機能に焦点を当てた実際の構成とユースケース。




== ビジネスバリュー

企業は、新しい製品の作成、リリースサイクルの短縮、新機能の迅速な追加を目的として、 DevOps の手法を採用する傾向に迫られています。即応性に優れた本来の性質から、コンテナやマイクロサービスは、 DevOps の実践を支援するうえで重要な役割を果たします。しかし、エンタープライズ環境で本番環境規模で DevOps を実践する場合、独自の課題が生じ、基盤となるインフラに次のような一定の要件が課せられます。

* スタック内のすべてのレイヤで高可用性を実現します
* 導入手順の簡易化
* ノンストップオペレーションとアップグレード
* API ベースのプログラム可能なインフラで、マイクロサービスの即応性を維持します
* パフォーマンスを保証するマルチテナンシー
* 仮想ワークロードとコンテナ化されたワークロードを同時に実行できます
* ワークロードのニーズに応じてインフラを個別に拡張できること


NetApp解決策 を搭載したAnthosは、このような課題に対応し、お客様のデータセンター環境にオンプレミス環境に完全に自動化された導入を実装することで、それぞれの問題に対処できる解決策 を提供します。



== テクノロジの概要

NetApp解決策 を搭載したAnthosは、以下の主要コンポーネントで構成されています。



=== オンプレミスのAnthos

オンプレミスのAnthosは、VMware vSphereハイパーバイザーや、選択したベアメタルインフラに導入可能な、完全にサポートされているエンタープライズ向けKubernetesプラットフォームです。

Anthosの詳細については、AnthosのWebサイトを参照してください https://cloud.google.com/anthos["ここをクリック"^]。



=== NetAppストレージシステム

ネットアップには、エンタープライズデータセンターやハイブリッドクラウド環境に最適なストレージシステムが複数あります。NetAppポートフォリオには、NetApp ONTAP、Cloud Volumes ONTAP、Google Cloud NetApp Volumes、Azure NetApp Files、FSx ONTAP for NetApp ONTAPストレージシステムが含まれており、すべてコンテナ化されたアプリケーションに永続的ストレージを提供できます。

詳細については、NetAppのWebサイトを参照して https://www.netapp.com["ここをクリック"]ください。



=== ネットアップとストレージの統合

Tridentは、Anthosを含むコンテナとKubernetesディストリビューション向けのオープンソースで完全サポートされているストレージオーケストレーションツールです。

詳細については、TridentのWebサイトを参照して https://docs.netapp.com/us-en/trident/index.html["ここをクリック"]ください。



== Advanced Configuration Options （詳細設定オプション）

このセクションは、実環境のユーザがこの解決策を本番環境に導入するときに実行する必要があるカスタマイズ（専用のプライベートイメージレジストリの作成やカスタムロードバランサインスタンスの導入など）に特化したものです。



== 検証済みリリースの現在のサポートマトリックスです

検証済みリリースのサポートマトリックスについては、を参照してください https://cloud.google.com/anthos/docs/resources/partner-storage#netapp["ここをクリック"]。
