---
sidebar: sidebar 
permalink: containers/a-w-n_LB_MetalLB.html 
summary: このページでは、 MetalLB ロードバランサのインストールおよび設定手順について説明します。 
keywords: Anthos, Kubernetes, MetalLB, LoadBalancer, 
---
= MetalLBロードバランサをインストールしています
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このページでは、MetalLB管理対象ロードバランサのインストールおよび設定手順を示します。



== MetalLB ロードバランサをインストールします

MetalLBロードバランサは、VMware上のAnthosクラスタと完全に統合されており、1.11リリース以降のAdminおよびUserクラスタセットアップの一部として自動展開を実行しています。それぞれの構成ファイルには、ロードバランサ情報を提供するために変更が必要なテキストブロックがあり `cluster.yaml`ます。サポートされている他のロードバランサソリューションのような外部リソースの導入を必要とするのではなく、Anthosクラスタで自己ホストされます。また、IPプールを作成し、クラウドプロバイダで実行されていないクラスタでロードバランサタイプのKubernetesサービスの作成時にアドレスを自動的に割り当てることもできます。



== Anthosとの統合

Anthos adminでMetalLBロードバランサを有効にする場合は、ファイル内のセクションの `admin-cluster.yaml`いくつかの行を変更する必要があります `loadBalancer:`。変更する必要がある値は、アドレスを設定してから、をMetalLBとして設定する `kind:`ことだけです `controlPlaneVIP:`。例については、次のコードスニペットを参照してください。

[listing]
----
# (Required) Load balancer configuration
loadBalancer:
  # (Required) The VIPs to use for load balancing
  vips:
    # Used to connect to the Kubernetes API
    controlPlaneVIP: "10.61.181.230"
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    # addonsVIP: ""
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" "ManualLB" or "MetalLB".
  # Uncomment the corresponding field below to provide the detailed spec
  kind: MetalLB
----
AnthosユーザクラスタでMetalLBロードバランサを有効にする場合は、各ファイルで更新が必要な領域が2つあり `user-cluster.yaml`ます。まず、ファイルと同様に、 `admin-cluster.yaml`セクションの、、 `ingressVIP:`および `kind:`の値を `loadBalancer:`変更する必要があります `controlPlaneVIP:`。例については、次のコードスニペットを参照してください。

[listing]
----
loadBalancer:
  # (Required) The VIPs to use for load balancing
  vips:
    # Used to connect to the Kubernetes API
    controlPlaneVIP: "10.61.181.240"
    # Shared by all services for ingress traffic
    ingressVIP: "10.61.181.244"
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" "ManualLB" or "MetalLB".
  # Uncomment the corresponding field below to provide the detailed spec
  kind: MetalLB
----

NOTE: 設定の後半で、MetalLBロードバランサに割り当てられたIPアドレスのプール内に、ingressVIP IPアドレスが存在している必要があります。

次に、サブセクションに移動し、変数でプールに名前を付けてセクションを `- name:`変更する `addressPools:`必要があり `metalLB:`ます。また、変数に範囲を指定することで、MetalLBがLoadBalancerタイプのサービスに割り当てることができるIPアドレスのプールを作成する必要があります `addresses:`。

[listing]
----
# # (Required when using "MetalLB" kind in user clusters) Specify the MetalLB config
 metalLB:
 #   # (Required) A list of non-overlapping IP pools used by load balancer typed services.
 #   # Must include ingressVIP of the cluster.
    addressPools:
 #   # (Required) Name of the address pool
    - name: "default"
 #     # (Required) The addresses that are part of this pool. Each address must be either
 #     # in the CIDR form (1.2.3.0/24) or range form (1.2.3.1-1.2.3.5).
      addresses:
      - "10.61.181.244-10.61.181.249"
----

NOTE: この例のような範囲を指定すると、特定のサブネット内のアドレス数に制限することも、サブネット全体が使用可能になった場合にCIDR表記として指定することもできます。

. LoadBalancerタイプのKubernetesサービスが作成されると、MetalLBは自動的にそのサービスに外部IPを割り当て、ARP要求に応答してIPアドレスをアドバタイズします。

