---
sidebar: sidebar 
permalink: containers/anthos_reference_workflow_summary.html 
summary: ここでは、 NetApp HCI 解決策 for Anthos の実装に必要な詳細なプロトコルの概要を説明します。 
keywords: NDE, Trident, vCenter, switches 
---
= 導入手順


ここでは、 NetApp HCI 解決策 for Anthos を実装するためのプロトコルについて詳しく説明します。

この構成は、大きく分けて次のタスクに分かれています。 1. link:anthos_task_configure_management_switches.html["管理スイッチを設定"]2. link:anthos_task_configure_data_switches.html["データスイッチを設定する"]3. link:anthos_task_deploy_netapp_hci.html["NetApp Deployment Engine を使用して NetApp HCI を導入"]4. link:anthos_task_configure_the_vcenter_server.html["vCenter Server を設定します"]5. link:anthos_task_deploy_the_f5_big-ip.html["F5 BIG-IP Virtual Edition アプライアンスを導入して設定します"]6. link:anthos_task_complete_anthos_prerequisites.html["Anthos の前提条件"]7. link:anthos_task_deploy_the_anthos_admin_workstation.html["Anthos 管理ワークステーションを導入します"]8. link:anthos_task_deploy_the_admin.html["管理クラスタを導入"]9. link:anthos_task_deploy_user_clusters.html["ユーザクラスタを導入"]10. link:anthos_task_enable_access_to_the_cluster.html["GKE コンソールでクラスタにアクセスできるようにします"]11. link:anthos_task_install_and_configure_trident.html["NetApp Trident ストレージプロビジョニングツールをインストールし、設定します"]

link:anthos_task_configure_management_switches.html["次の手順：管理スイッチを設定します。"]
