---
sidebar: sidebar 
permalink: containers/anthos_concept_overview.html 
summary: NetApp HCI with Anthos は、信頼性の高い方法でオンプレミスの Google Kubernetes Engine （ GKE ）環境を導入するための、検証済みでベストプラクティスに基づいたハイブリッドクラウドアーキテクチャです。この NetApp Verified Architecture リファレンスドキュメントは、解決策上の Anthos NetApp HCI の設計ガイドおよび導入検証版として提供されています。 
keywords: Kubernetes, GKE, NVA-1141 
---
= NVA-1141 ： Anthos 、設計、導入環境で NetApp HCI を使用しています


アラン・カウレス

本ドキュメントで説明しているプログラムソリューションは、導入リスクを最小限に抑え、製品化サイクルを短縮するために設計され、徹底的なテストが行われています。

本ドキュメントは、ネットアップおよびパートナー様のソリューションエンジニアと、お客様の戦略的意思決定者を対象としています。ここでは、検証済みのワークロードに対応するために必要な機器、ケーブル接続、構成を決定するための、アーキテクチャ設計に関する考慮事項について説明します。

NetApp HCI with Anthos は、信頼性の高い方法でオンプレミスの Google Kubernetes Engine （ GKE ）環境を導入するための、検証済みでベストプラクティスに基づいたハイブリッドクラウドアーキテクチャです。この NetApp Verified Architecture リファレンスドキュメントは、解決策上の Anthos NetApp HCI の設計ガイドおよび導入検証版として提供されています。本ドキュメントで説明しているアーキテクチャは、ネットアップと Google のエキスパートによって検証されたものであり、お客様のエンタープライズデータセンター環境で NetApp HCI 上で Anthos を実行する利点を提供します。

NetApp HCI は、業界初の分離型ハイブリッドクラウドインフラであり、広く認められているハイパーコンバージドソリューションのメリットを提供します。TCO の削減、仮想化ワークロードの導入、導入、管理の容易さなどのメリットがあります。また、企業のお客様は、コンピューティングリソースとストレージリソースを必要に応じて個別に拡張できます。NetApp HCI と Anthos を使用すると、オンプレミスにある Anthos GKE で管理されるコンテナ化されたワークロードを、クラウドと同等のエクスペリエンスで導入できます。この解決策は、シンプルな管理、詳細な指標、さまざまな追加機能を提供し、オンサイトとクラウドの両方に導入されたワークロードを簡単に移動できるようにします。



== の機能

NetApp HCI for Anthos を使用すると、オンプレミスのデータセンターに、完全に統合された本番環境レベルの Anthos GKE 環境を導入できます。これにより、以下の機能を活用できます。

* NetApp HCI のコンピューティングノードとストレージノード
+
** ハイブリッドクラウドワークロード向けに設計された、エンタープライズクラスのハイパーコンバージドインフラ
** NetApp Element ストレージソフトウェア
** Intel ベースのサーバコンピューティングノード（ Nvidia GPU のオプションを含む）


* VMware vSphere 6.7U3
+
** 仮想インフラの導入と管理に使用するエンタープライズハイパーバイザー解決策です


* Google Cloud およびオンプレミスの Anthos GKE
+
** Google Cloud またはネットアップ環境に Anthos GKE インスタンスを導入 できません




NetApp Verified Architecture プログラムは、お客様向けのリファレンス構成とサイジングガイダンスを提供する、特定のワークロードとユースケース向けのプログラムです。

link:anthos_concept_solution_components.html["次の例は、解決策コンポーネントです"]
