---
sidebar: sidebar 
permalink: containers/anthos_task_complete_anthos_prerequisites.html 
summary: 物理環境をセットアップすると、 Anthos の導入を開始できます。まず、解決策を導入してあとでアクセスするためのいくつかの前提条件について説明します。 
keywords: Google Cloud, SDK, govc, Hashicorp, Terraform 
---
= Anthos の前提条件


物理環境のセットアップが完了したら、 Anthos の導入を開始できます。まず、解決策を導入してあとでアクセスするためのいくつかの前提条件について説明します。これらの各手順については、で詳しく説明します Anthos の場合 https://cloud.google.com/gke-on-prem/docs/["GKE オンプレミスガイド"]。

VMware 環境に Anthos を導入する準備をするには、次の手順を実行します。

. 利用可能な手順に従って Google Cloud プロジェクトを作成します https://cloud.google.com/resource-manager/docs/creating-managing-projects#creating_a_project["こちらをご覧ください"]。
+

NOTE: この目的のためのプロジェクトがすでに組織に存在している場合もあります。クラウド管理チームに問い合わせて、 VMware 上の Anthos にアクセスするようにプロジェクトが存在し、すでに構成されているかどうかを確認してください。Anthos で使用するプロジェクトは、すべて Google にホワイトリスト登録されている必要があります。これには、プライマリユーザアカウント、追加のチームメンバー、および以降の手順で作成したアクセスサービスアカウントが含まれます。

. VMware への Anthos のインストールを管理するための導入ワークステーションを作成します。配置ワークステーションには、 Linux 、 MacOS 、 Windows があります。今回の検証済みの導入では、 Red Hat Enterprise Linux 7 を使用しました。
+

NOTE: このワークステーションは、 NetApp HCI 環境の内部または外部でホストできます。唯一の要件は、導入した VMware vCenter Server とインターネットが正常に機能するためには通信が可能であることです。

. をインストールします https://cloud.google.com/sdk/install["Google Cloud SDK の場合"] Google Cloud とのやり取り用です。このパッケージは、手動インストール用のバイナリのアーカイブとしてダウンロードすることも、 apt-get （ Ubuntu / Debian ）または yum （ RHEL ）パッケージマネージャによってインストールすることもできます。
+
[listing]
----
[user@rhel7 ~]$ sudo yum install google-cloud-sdk
Failed to set locale, defaulting to C
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package google-cloud-sdk.noarch 0:270.0.0-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=================================================================================================
Package                   Arch            Version             Repository                Size
=================================================================================================
Installing:
google-cloud-sdk         noarch          270.0.0-1       google-cloud-sdk               36 M

Transaction Summary
=================================================================================================
Install  1 Package

Total download size: 36 M
Installed size: 174 M
Is this ok [y/d/N]: y
Downloading packages:
6d81c821884ae40244c746f6044fc1bcd801143a0d9c8da06767036b8d090a24-google-cloud-sdk-270.0.0-1.noar |  36 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : google-cloud-sdk-270.0.0-1.noarch                                      1/1
  Verifying  : google-cloud-sdk-270.0.0-1.noarch                                      1/1

Installed:
  google-cloud-sdk.noarch 0:270.0.0-1

Complete!
----
+

NOTE: gcloud バイナリは、バージョン 265.0 以上である必要があります。gcloud components update を使用して手動インストールを更新できます。ただし、 SDK がパッケージマネージャーによってインストールされている場合は、同じパッケージマネージャーを使用して、今後の更新も実行する必要があります。

. ワークステーションが設定されている状態で、資格情報を使用して Google Cloud にログインします。これを行うには、配置ワークステーションから login コマンドを入力し、リンクを取得します。リンクをブラウザにコピーして貼り付け、 Google サービスへの対話型サインインを許可します。ログインすると、 Web ページにコードが表示されます。コードは、プロンプトが表示されたら、コピーして展開ワークステーションに貼り付けることができます。
+
[listing]
----
[user@rhel7 ~]$ gcloud auth login
Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?code_challenge=-7oPNSySHr_Sd2ZZ4K83koIeGTLVcdbjc8omr6zCbAI&prompt=select_account&code_challenge_method=S256&access_type=offline&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=32655940559.apps.googleusercontent.com&scope=https%3A%3F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%6F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth


Enter verification code: 6/swGAh52VVgB-TRS5LVrSvP79ZdDlb9V6ObyUGqoY67a3zp9NPciIKsM
You are now logged in as [user@netapp.com].
Your current project is [anthos-dev].  You can change this setting by running:
  $ gcloud config set project PROJECT_ID
----
. 複数の API を有効にして、環境が Google Cloud と通信できるようにします。クラスタに導入するポッドは、で実行できる必要があります にアクセスします https://www.googleapis.com[""] および https://gkeconnect.googleapis.com[""] 期待どおりに機能すること。そのため、ワーカーノードが接続されている VM_Network でインターネットアクセスを有効にする必要があります。必要な API を有効にするには、導入ワークステーションから次のコマンドを実行します。
+
[listing]
----
[user@rhel7 ~]$ gcloud services enable --project anthos-dev \
cloudresourcemanager.googleapis.com \
container.googleapis.com \
gkeconnect.googleapis.com \
gkehub.googleapis.com \
serviceusage.googleapis.com \
stackdriver.googleapis.com \
monitoring.googleapis.com \
logging.googleapis.com
----
. Anthos-install という名前の作業ディレクトリを作成し、そのディレクトリに移動します。
+
[listing]
----
[user@rhel7 ~]$ mkdir anthos-install && cd anthos-install
[user@rhel7 anthos-install]$
----
. VMware に Anthos をインストールする前に、 4 つのサービスアカウントを作成して、それぞれ Google Cloud と連携するための特定の目的を設定する必要があります。次の表に、アカウントとその目的を示します。
+
[cols="33,67"]
|===
| アカウント名 | 目的 


| component-access-sa | Cloud Storage から Anthos バイナリをダウンロードする際に使用されます。 


| connect-register-sa | Anthos クラスタを Google Cloud コンソールに登録する際に使用されます。 


| connect-agent-sa | ユーザクラスタと Google Cloud 間の接続を維持するために使用します。 


| logging-monitoring -sa のように入力します | ロギングデータとモニタリングデータを Stackdriver に書き込むために使用します。 
|===
+

NOTE: 各アカウントには、承認された Google Cloud プロジェクト名を参照する電子メールアドレスが割り当てられます。以下の例では、ネットアップの検証で使用した Anthos-Dev プロジェクトをすべて表示しています。必要に応じて、構文例の中で適切なプロジェクト名を置き換えてください。

+
[listing]
----
[user@rhel7 anthos-install]$ gcloud iam service-accounts create component-access-sa \
    --display-name "Component Access Service Account" \
    --project anthos-dev
[user@rhel7 anthos-install]$ gcloud iam service-accounts keys create component-access-key.json \
   --iam-account component-access-sa@anthos-dev.iam.gserviceaccount.com

[user@rhel7 anthos-install]$ gcloud iam service-accounts create connect-register-sa \
    --project anthos-dev
[user@rhel7 anthos-install]$ gcloud iam service-accounts keys create connect-register-key.json \
   --iam-account connect-register-sa@anthos-dev.iam.gserviceaccount.com

[user@rhel7 anthos-install]$ gcloud iam service-accounts create connect-agent-sa \
    --project anthos-dev
[user@rhel7 anthos-install]$ gcloud iam service-accounts keys create connect-agent-key.json \
    --iam-account connect-agent-sa@anthos-dev.iam.gserviceaccount.com

[user@rhel7 anthos-install]$ gcloud iam service-accounts create logging-monitoring-sa \
    --project anthos-dev
[user@rhel7 anthos-install]$ gcloud iam service-accounts keys create logging-monitoring-key.json \
    --iam-account logging-monitoring-sa@anthos-dev.iam.gserviceaccount.com
----
. Anthos を導入するための環境を準備するために必要な最後の手順は、サービスアカウントに特定の権限を制限することです。手順 7 でリストした各サービスアカウントに関連付けられた E メールアドレスが必要です。
+
.. component-access -sa アカウントを使用して '`serviceuseage.serviceUsageViewer` ' iam.serviceAccountCreator` ' および iam.roleViewer' のロールを割り当てます
+
[listing]
----
[user@rhel7 anthos-install]$ gcloud projects add-iam-policy-binding anthos-dev\
    --member "serviceAccount:component-access-sa@anthos-dev.iam.gserviceaccount.com" \
    --role "roles/serviceusage.serviceUsageViewer"
[user@rhel7 anthos-install]$ gcloud projects add-iam-policy-binding anthos-dev\
    --member "serviceAccount:component-access-sa@anthos-dev.iam.gserviceaccount.com" \
    --role "roles/iam.serviceAccountCreator"
[user@rhel7 anthos-install]$ gcloud projects add-iam-policy-binding anthos-dev\
    --member "serviceAccount:component-access-sa@anthos-dev.iam.gserviceaccount.com" \
    --role "roles/iam.roleViewer"
----
.. connect-register-sa サービスアカウントを使用して 'gkehub.admin' のロールを割り当てます
+
[listing]
----
[user@rhel7 anthos-install]$ gcloud projects add-iam-policy-binding anthos-dev \
    --member "serviceAccount:connect-register-sa@anthos-dev.iam.gserviceaccount.com " \
    --role "roles/gkehub.admin"
----
.. connect-agent-sa acccount を使用して 'gkehub.connect' のロールを割り当てます
+
[listing]
----
[user@rhel7 anthos-install]$ gcloud projects add-iam-policy-binding anthos-dev \
    --member "serviceAccount:connect-agent-sa@anthos-dev.iam.gserviceaccount.com" \
    --role "roles/gkehub.connect"
----
.. logging-monitoring -sa サービスアカウントを使用して、「 sとともに driver.resourceMetadata.writer' 」、「 logging.logWriter 」、「 m onitoring.mmetricWriter 」、および「 monitoring.dashboardEditor 」のロールを割り当てます。
+
[listing]
----
[user@rhel7 anthos-install]$ gcloud projects add-iam-policy-binding anthos-dev \
    --member "serviceAccount:logging-monitoring-sa@anthos-dev.iam.gserviceaccount.com" \
    --role "roles/stackdriver.resourceMetadata.writer"
[user@rhel7 anthos-install]$ gcloud projects add-iam-policy-binding anthos-dev\
    --member "serviceAccount:logging-monitoring-sa@anthos-dev.iam.gserviceaccount.com" \
    --role "roles/logging.logWriter"
[user@rhel7 anthos-install]$ gcloud projects add-iam-policy-binding anthos-dev\
    --member "serviceAccount:logging-monitoring-sa@anthos-dev.iam.gserviceaccount.com" \
    --role "roles/monitoring.metricWriter"
[user@rhel7 anthos-install]$ gcloud projects add-iam-policy-binding anthos-dev\
    --member "serviceAccount:logging-monitoring-sa@anthos-dev.iam.gserviceaccount.com" \
    --role "roles/monitoring.dashboardEditor"
----


. VMware CA の vCenter 証明書をダウンロードします。この証明書は、インストール時に vCenter への認証で使用されます。
+
[listing]
----
[user@rhel7 anthos-install]$ true | openssl s_client -connect anthos-vc.cie.netapp.com:443 -showcerts 2>/dev/null | sed -ne '/-BEGIN/,/-END/p' > vcenter.pem
----


link:anthos_task_deploy_the_anthos_admin_workstation.html["次に、 Anthos 管理ワークステーションを導入します"]
