---
sidebar: sidebar 
permalink: containers/anthos_task_configure_data_switches.html 
summary: Mellanox SN2010 スイッチは、コンピューティングノードとストレージノードのデータプレーンに 25Gbps 接続を提供します。インフラへのデータ接続を提供するようにスイッチを設定するには、このページに記載されている手順を実行します。 
keywords: Mellanox, LACP, IPL, LLDP, MLAG, VLAN 
---
= 2. データスイッチの設定


Mellanox SN2010 スイッチは、コンピューティングノードとストレージノードのデータプレーンに 25Gbps 接続を提供します。インフラへのデータ接続を提供するようにスイッチを設定するには、次の手順を実行します。



== MLAG クラスタを作成し、フォールトトレランスを実現します

. 一般的な設定を行うには、各 Mellanox SN210 スイッチで次のコマンドを実行します。
+
.. コンフィギュレーションモードを開始します。
+
[listing]
----
Switch-01 enable
Switch-01 configure terminal
----
.. Inter-Peer Link （ IPL ）に必要な LACP を有効にします。
+
[listing]
----
Switch-01 (config) # lacp
----
.. Link Layer Discovery Protocol （ LLDP ）を有効にします。
+
[listing]
----
Switch-01 (config) # lldp
----
.. IP ルーティングを有効にします。
+
[listing]
----
Switch-01 (config) # ip routing
----
.. MLAG プロトコルをイネーブルにします。
+
[listing]
----
Switch-01 (config) # protocol mlag
----
.. グローバル QoS を有効にします。
+
[listing]
----
Switch-01 (config) # dcb priority-flow-control enable force
----


. MLAG を機能させるには、スイッチを IPL 経由で相互にピア関係を設定する必要があります。冗長性を確保するには、 2 つ以上の物理リンクで構成する必要があります。IPL の MTU はジャンボフレームに設定されています（ 9216 ）。すべての VLAN はデフォルトで有効になっています。ドメイン内の各スイッチで次のコマンドを実行します。
+
.. IPL のポートチャネル 10 を作成します。
+
[listing]
----
Switch-01 (config) # interface port-channel 10
Switch-01 (config interface port-channel 10) # description IPL
Switch-01 (config interface port-channel 10) # exit
----
.. インターフェイス ETH 1/20 および 1/22 をポートチャネルに追加します。
+
[listing]
----
Switch-01 (config) # interface ethernet 1/20 channel-group 10 mode active
Switch-01 (config) # interface ethernet 1/20 description ISL-SWB_01
Switch-01 (config) # interface ethernet 1/22 channel-group 10 mode active
Switch-01 (config) # interface ethernet 1/22 description ISL-SWB_02
----
.. IPL トラフィック専用の標準範囲外の VLAN を作成します。
+
[listing]
----
Switch-01 (config) # vlan 4000
Switch-01 (config vlan 4000) # name IPL VLAN
Switch-01 (config vlan 4000) # exit
----
.. ポートチャネルを IPL として定義します。
+
[listing]
----
Switch-01 (config) # interface port-channel 10 ipl 1
Switch-01 (config) # interface port-channel 10 dcb priority-flow-control mode on force
----
.. 各 IPL メンバーに IP を設定します（ルーティング不可。スイッチの外部ではアドバタイズされません）。
+
[listing]
----
Switch-01 (config) # interface vlan 4000
Switch-01 (config vlan 4000) # ip address 10.0.0.1 255.255.255.0
Switch-01 (config vlan 4000) # ipl 1 peer-address 10.0.0.2
Switch-01 (config vlan 4000) # exit
----


. 2 つのスイッチに一意の MLAG ドメイン名を作成し、 MLAG 仮想 IP （ VIP ）を割り当てます。この IP は、 2 つのスイッチ間のキープアライブハートビートメッセージに使用されます。ドメイン内の各スイッチで、次のコマンドを実行します。
+
.. MLAG ドメインを作成し、 IP アドレスとサブネットを設定します。
+
[listing]
----
Switch-01 (config) # mlag-vip MLAG-VIP-DOM ip a.b.c.d /24 force
----
.. システム MLAG の仮想 MAC アドレスを作成します。
+
[listing]
----
Switch-01 (config) # mlag system-mac AA:BB:CC:DD:EE:FF
----
.. グローバルにアクティブになるように MLAG ドメインを設定します。
+
[listing]
----
Switch-01 (config) # no mlag shutdown
----





NOTE: MLAG VIP 用の IP は、スイッチ管理ネットワーク（ mgmt0 ）と同じサブネット内に配置する必要があります。


NOTE: 使用する MAC アドレスは任意のユニキャスト MAC アドレスで、 MLAG ドメイン内の両方のスイッチで同じ値に設定する必要があります。



== ストレージホストとコンピューティングホストに接続するポートを設定します

. NetApp HCI のサービスをサポートするために必要な VLAN をそれぞれ作成します。ドメイン内の各スイッチで、次のコマンドを実行します。
+
.. VLAN を作成します。
+
[listing]
----
Switch-01 (config) # vlan 1172
Switch-01 (config vlan 1172) exit
Switch-01 (config) # vlan 3480-3482
Switch-01 (config vlan 3480-3482) exit
----
.. アカウンティングを容易にするために、各 VLAN の名前を作成します。
+
[listing]
----
Switch-01 (config) # vlan 1172 name “VM_Network”
Switch-01 (config) # vlan 3480 name “MGMT_Network”
Switch-01 (config) # vlan 3481 name “Storage_Network”
Switch-01 (config) # vlan 3482 name “vMotion_Network”
+
----


. ポート Eth1/9-10 にハイブリッド VLAN ポートを作成して、 NetApp HCI コンピューティングノードに適切な VLAN にタグ付けできるようにします。
+
.. 使用するポートを選択します。
+
[listing]
----
Switch-01 (config) # interface ethernet 1/9-1/10
----
.. 各ポートに MTU を設定します。
+
[listing]
----
Switch-01 (config interface ethernet 1/9-1/10) # mtu 9216 force
----
.. 各ポートのスパニングツリー設定を変更します。
+
[listing]
----
Switch-01 (config interface ethernet 1/9-1/10) # spanning-tree bpdufilter enable
Switch-01 (config interface ethernet 1/9-1/10) # spanning-tree port type edge
Switch-01 (config interface ethernet 1/9-1/10) # spanning-tree bpduguard enable
----
.. スイッチポートモードをハイブリッドに設定します。
+
[listing]
----
Switch-01 (config interface ethernet 1/9-1/10 ) # switchport mode hybrid
Switch-01 (config interface ethernet 1/9-1/10 ) # exit
----
.. 変更する各ポートの説明を作成します。
+
[listing]
----
Switch-01 (config) # interface ethernet 1/9 description HCI-CMP-01 PortD
Switch-01 (config) # interface ethernet 1/10 description HCI-CMP-02 PortD
----
.. NetApp HCI 環境に適した VLAN にタグを付けます。
+
[listing]
----
Switch-01 (config) # interface ethernet 1/9 switchport hybrid allowed-vlan add 1172
Switch-01 (config) # interface ethernet 1/9 switchport hybrid allowed-vlan add 3480-3482
Switch-01 (config) # interface ethernet 1/10 switchport hybrid allowed-vlan add 1172
Switch-01 (config) # interface ethernet 1/10 switchport hybrid allowed-vlan add 3480-3482
----


. ポート Eth1/5-8 に MLAG インターフェイスとハイブリッド VLAN ポートを作成して、スイッチ間の接続を分散し、 NetApp HCI ストレージノードに適切な VLAN にタグ付けできるようにします。
+
.. 使用するポートを選択します。
+
[listing]
----
Switch-01 (config) # interface ethernet 1/5-1/8
----
.. 各ポートに MTU を設定します。
+
[listing]
----
Switch-01 (config interface ethernet 1/5-1/8) # mtu 9216 force
----
.. 各ポートのスパニングツリー設定を変更します。
+
[listing]
----
Switch-01 (config interface ethernet 1/5-1/8) # spanning-tree bpdufilter enable
Switch-01 (config interface ethernet 1/5-1/8) # spanning-tree port type edge
Switch-01 (config interface ethernet 1/5-1/8) # spanning-tree bpduguard enable
----
.. スイッチポートモードをハイブリッドに設定します。
+
[listing]
----
Switch-01 (config interface ethernet 1/5-1/8 ) # switchport mode hybrid
Switch-01 (config interface ethernet 1/5-1/8 ) # exit
----
.. 変更する各ポートの説明を作成します。
+
[listing]
----
Switch-01 (config) # interface ethernet 1/5 description HCI-STG-01 PortD
Switch-01 (config) # interface ethernet 1/6 description HCI-STG-02 PortD
Switch-01 (config) # interface ethernet 1/7 description HCI-STG-03 PortD
Switch-01 (config) # interface ethernet 1/8 description HCI-STG-04 PortD
----
.. MLAG ポートチャネルを作成し、設定します。
+
[listing]
----
Switch-01 (config) # interface mlag-port-channel 115-118
Switch-01 (config interface mlag-port-channel 115-118) # exit
Switch-01 (config) # interface mlag-port-channel 115-118 no shutdown
Switch-01 (config) # interface mlag-port-channel 115-118 mtu 9216 force
Switch-01 (config) # interface mlag-port-channel 115-118 lacp-individual enable force
Switch-01 (config) # interface ethernet 1/5-1/8 lacp port-priority 10
Switch-01 (config) # interface ethernet 1/5-1/8 lacp rate fast
Switch-01 (config) # interface ethernet 1/5 mlag-channel-group 115 mode active
Switch-01 (config) # interface ethernet 1/6 mlag-channel-group 116 mode active
Switch-01 (config) # interface ethernet 1/7 mlag-channel-group 117 mode active
Switch-01 (config) # interface ethernet 1/8 mlag-channel-group 118 mode active
----
.. ストレージ環境に適した VLAN にタグを付けます。
+
[listing]
----
Switch-01 (config) # interface mlag-port-channel 115-118 switchport mode hybrid
Switch-01 (config) # interface mlag-port-channel 115 switchport hybrid allowed-vlan add 1172 Switch-01 (config) # interface mlag-port-channel 116 switchport hybrid allowed-vlan add 1172
Switch-01 (config) # interface mlag-port-channel 117 switchport hybrid allowed-vlan add 1172
Switch-01 (config) # interface mlag-port-channel 118 switchport hybrid allowed-vlan add 1172
Switch-01 (config) # interface mlag-port-channel 115 switchport hybrid allowed-vlan add 3481
Switch-01 (config) # interface mlag-port-channel 116 switchport hybrid allowed-vlan add 3481
Switch-01 (config) # interface mlag-port-channel 117 switchport hybrid allowed-vlan add 3481
Switch-01 (config) # interface mlag-port-channel 118 switchport hybrid allowed-vlan add 3481
----





NOTE: このセクションの設定は、 MLAG ドメイン内の 2 番目のスイッチでも実行する必要があります。各ポートの説明を更新して、もう一方のスイッチでケーブル接続および設定されているデバイスポートを反映することを推奨します。



== スイッチのアップリンクポートを作成します

. MLAG インターフェイスを作成して、コアネットワークから両方の Mellanox SN2010 スイッチへのアップリンクを提供します。
+
[listing]
----
Switch-01 (config) # interface mlag port-channel 101
Switch-01 (config interface mlag port-channel) # description Uplink CORE-SWITCH port PORT
Switch-01 (config interface mlag port-channel) # exit
----
. MLAG メンバーを設定します。
+
[listing]
----
Switch-01 (config) # interface ethernet 1/18 description Uplink to CORE-SWITCH port PORT
Switch-01 (config) # interface ethernet 1/18 speed 10000 force
Switch-01 (config) # interface mlag-port-channel 101 mtu 9216 force
Switch-01 (config) # interface ethernet 1/18 mlag-channel-group 101 mode active
----
. スイッチポートモードを hybrid に設定し、コアアップリンクスイッチからすべての VLAN を許可します。
+
[listing]
----
Switch-01 (config) # interface mlag-port-channel switchport mode hybrid
Switch-01 (config) # interface mlag-port-channel switchport hybrid allowed-vlan all
----
. MLAG インターフェイスが動作していることを確認します。
+
[listing]
----
Switch-01 (config) # interface mlag-port-channel 101 no shutdown
Switch-01 (config) # exit
----


link:anthos_task_deploy_netapp_hci.html["次のステップ： NetApp HCI を NetApp Deployment Engine に導入します"]
