---
sidebar: sidebar 
permalink: containers/bmanthos_solution_requirements.html 
keywords: Hardware, software, compute, storage, requirements 
summary: ハードウェアに依存しないベアメタル上の Anthos 機能により、ユースケースに最適化されたコンピューティングプラットフォームを選択できます。したがって、既存のインフラに合わせて、設備投資を削減できます。 
---
= 解決策の要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== ハードウェア要件



=== コンピューティング：お客様所有のサーバを使用

ハードウェアに依存しないベアメタル上の Anthos 機能により、ユースケースに最適化されたコンピューティングプラットフォームを選択できます。したがって、既存のインフラに合わせて、設備投資を削減できます。

次の表に、この解決策の実装に必要なコンピューティングハードウェアコンポーネントの最小数を示します。ただし、使用されるハードウェアモデルはお客様の要件に応じて異なる場合があります。

|===
| 使用方法 | ハードウェアおよびモデル | 数量 


| 管理ノード | Cisco UCS B200 | 3. 


| ワーカーノード | HP ProLiant DL360 | 4. 
|===


=== ストレージ： NetApp ONTAP

次の表に、解決策の実装に必要なストレージハードウェアコンポーネントの最小数を示します。ただし、使用するハードウェアモデルはお客様の要件に応じて異なる場合があります。

|===
| ハードウェア | モデル | 数量 


| NetApp AFF | NetApp AFF A300 | 2 （ HA ペア × 1 ） 
|===


== ソフトウェア要件

次の表に示したソフトウェアバージョンは、ネットアップとパートナー様による解決策の検証に使用されています。ただし、使用されるソフトウェアコンポーネントはお客様の要件に応じて異なる場合があります。

|===
| ソフトウェア | 目的 | バージョン 


| Ubuntu | 3 人の管理者の OS | 20.04 


|  | Worker4 上の OS | 20.04 


|  | Worker3 上の OS | 18.04 


| CentOS の場合 | Worker2 上の OS | 8.2 


| Red Hat Enterprise Linux の場合 | Worker1 上の OS | 8.1 


| ベアメタルの Anthos | コンテナオーケストレーション | 1.6.0 


| NetApp ONTAP | Storage OS | 9.7P8. 


| NetApp Trident | Container Storage Management （コンテナストレージ管理） | 20.10 
|===

NOTE: このマルチ OS 環境は、ベアメタル解決策上のサポートされている OS バージョンの Anthos との相互運用性を示しています。導入のために、お客様が 1 つまたは一部のオペレーティングシステムで標準化されると予想されます。

ベアメタルハードウェアおよびソフトウェアの要件を満たす Anthos の場合は、を参照してください https://cloud.google.com/anthos/gke/docs/bare-metal/concepts/hw-sw-storage["ベアメタルドキュメント上の Anthos"^] ページ

link:bmanthos_deployment_summary.html["次の例は、導入の概要です。"]
