---
sidebar: sidebar 
permalink: containers/rh-os-n_solution_overview.html 
keywords: NVA-1160, Red Hat, OpenShift, Netapp, Astra Trident 
summary: このリファレンスドキュメントでは、ネットアップによって検証済みの複数の異なるデータセンター環境に Installer Provisioned Infrastructure （ IPI ）を通じて導入された Red Hat OpenShift 解決策の導入を検証します。また、ネットアップストレージシステムとの統合についても、 Astra Trident ストレージオーケストレーションツールを使用して永続的ストレージを管理することで詳しく説明します。最後に、解決策検証と実際の使用事例をいくつか確認して文書化します。 
---
= NVA-1160 ：ネットアップでの Red Hat OpenShift
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ネットアップ、 Alan Cowles 氏と Nikhil M Kulkarni 氏

このリファレンスドキュメントでは、ネットアップによって検証済みの複数の異なるデータセンター環境に Installer Provisioned Infrastructure （ IPI ）を通じて導入された Red Hat OpenShift 解決策の導入を検証します。また、ネットアップストレージシステムとの統合についても、 Astra Trident ストレージオーケストレーションツールを使用して永続的ストレージを管理することで詳しく説明します。最後に、解決策検証と実際の使用事例をいくつか確認して文書化します。



== ユースケース

ネットアップ解決策を使用した Red Hat OpenShift は、次のユースケースでお客様に卓越した価値を提供するように設計されています。

* ベアメタル、 Red Hat OpenStack Platform 、 Red Hat Virtualization 、 VMware vSphere に IPI （インストーラでプロビジョニングされたインフラ）を使用して導入した Red Hat OpenShift の導入と管理が容易です。
* OSP 、 RHV 、 vSphere 、または OpenShift Virtualization を使用したベアメタルに導入された Red Hat OpenShift を使用して、エンタープライズコンテナと仮想化ワークロードのパワーを組み合わせたもの。
* ネットアップストレージと Kubernetes 向けオープンソースストレージオーケストレーションツールである Astra Trident とともに使用される Red Hat OpenShift の機能を紹介する実際の構成とユースケース。




== ビジネスバリュー

企業は、新しい製品の作成、リリースサイクルの短縮、新機能の迅速な追加を目的として、 DevOps の手法を採用する傾向に迫られています。即応性に優れた本来の性質から、コンテナやマイクロサービスは、 DevOps の実践を支援するうえで重要な役割を果たします。しかし、エンタープライズ環境で本番環境規模で DevOps を実践する場合、独自の課題が生じ、基盤となるインフラに次のような一定の要件が課せられます。

* スタック内のすべてのレイヤで高可用性を実現します
* 導入手順の簡易化
* ノンストップオペレーションとアップグレード
* API ベースのプログラム可能なインフラで、マイクロサービスの即応性を維持します
* パフォーマンスを保証するマルチテナンシー
* 仮想ワークロードとコンテナ化されたワークロードを同時に実行できます
* ワークロードのニーズに応じてインフラを個別に拡張できる


ネットアップとともに Red Hat OpenShift を導入することで、これらの課題に対応し、お客様が選択したデータセンター環境に RedHat OpenShift IPI を完全に自動で導入できるようになり、それぞれの問題に対処できる解決策が提供されます。



== テクノロジの概要

NetApp 解決策を使用した Red Hat OpenShift は、次の主要コンポーネントで構成されています。



=== Red Hat OpenShift Container Platform

Red Hat OpenShift Container Platform は、完全にサポートされているエンタープライズ向け Kubernetes プラットフォームです。Red Hat は、オープンソースの Kubernetes をいくつか強化して、コンテナ化されたアプリケーションの構築、導入、管理を完全に統合したすべてのコンポーネントを備えたアプリケーションプラットフォームを提供します。

詳細については、 OpenShift の Web サイトを参照してください https://www.openshift.com["こちらをご覧ください"]。



=== ネットアップストレージシステム

ネットアップには、エンタープライズデータセンターやハイブリッドクラウド環境に最適なストレージシステムが複数あります。ネットアップのポートフォリオには、コンテナ化されたアプリケーションに永続的ストレージを提供できる NetApp ONTAP 、 NetApp Element 、および NetApp E シリーズストレージシステムが含まれています。

詳細については、ネットアップの Web サイトをご覧ください https://www.netapp.com["こちらをご覧ください"]。



=== ネットアップとストレージの統合

NetApp Astra Controlは、オンプレミス環境に導入され、信頼性の高いNetAppデータ保護テクノロジを基盤とする、ステートフルなKubernetesワークロード向けのストレージとアプリケーション対応のデータ管理サービスの豊富なセットを提供します。

詳細については、 NetApp Astra の Web サイトをご覧ください https://docs.netapp.com/us-en/astra-family/["こちらをご覧ください"]。

Astra Trident は、コンテナや Kubernetes ディストリビューション向けの、 Red Hat OpenShift などのオープンソースで完全にサポートされているストレージオーケストレーションツールです。

詳細については、 Astra Trident の Web サイトをご覧ください https://docs.netapp.com/us-en/trident/index.html["こちらをご覧ください"]。



== Advanced Configuration Options （詳細設定オプション）

このセクションは、実環境のユーザがこの解決策を本番環境に導入するときに実行する必要があるカスタマイズ（専用のプライベートイメージレジストリの作成やカスタムロードバランサインスタンスの導入など）に特化したものです。



== 検証済みリリースの現在のサポートマトリックスです

|===


| テクノロジ | 目的 | ソフトウェアのバージョン 


| NetApp ONTAP | ストレージ | 9.8、9.9.1、9.12.1 


| NetApp Element | ストレージ | 12.3 


| ネットアップアストラコントロール | アプリケーション対応データ管理 | 21.12.60、23.04、23.07、23.10、24.02 


| ネットアップアストラト Trident | ストレージオーケストレーション | 22.01.0、23.04、23.07、23.10、24.02 


| Red Hat OpenShift のサービスです | コンテナオーケストレーション | 4.6 EUS、4.7、4.8、4.10、4.11、 4.12、4.13、4.14 


| VMware vSphere の場合 | データセンターの仮想化 | 7.0、8.0.2 
|===