---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_multitenancy_overview.html 
keywords: OpenShift, OCP, NetApp Trident, NetApp ONTAP, Red Hat OpenShift, Multitenancy, Multi-tenancy 
summary: ネットアップを使用した Red Hat OpenShift でのマルチテナンシーの構成 
---
= ネットアップを使用した Red Hat OpenShift でのマルチテナンシーの構成：ネットアップでの Red Hat OpenShift


[role="lead"]
コンテナで複数のアプリケーションやワークロードを実行する多くの組織は、アプリケーションやワークロードごとに 1 つの Red Hat OpenShift クラスタを導入する傾向にあります。これにより、組織はアプリケーションやワークロードを厳密に分離してパフォーマンスを最適化し、セキュリティの脆弱性を軽減できます。ただし、アプリケーションごとに独立した Red Hat OpenShift クラスタを導入するには、独自の問題が発生します。これにより、各クラスタを個別に監視および管理する必要がある運用上のオーバーヘッドが増大し、さまざまなアプリケーションに専用リソースを使用することでコストが増大し、効率的な拡張性が妨げられます。

この問題を解決するには、すべてのアプリケーションとワークロードを 1 つの Red Hat OpenShift クラスタで実行することを検討します。しかし、このようなアーキテクチャでは、リソースの分離やアプリケーションのセキュリティの脆弱性が大きな課題の 1 つになっています。あるワークロードのセキュリティ上の脆弱性は、自然に別のワークロードにオーバーフローするため、影響ゾーンが増加します。また、リソース割り当てポリシーがデフォルトで存在しないため、あるアプリケーションによる突然の制御されないリソース使用率は、別のアプリケーションのパフォーマンスに影響します。

そのため、組織は両方の世界で最も優れたソリューションを探しています。つまり、すべてのワークロードを 1 つのクラスタで実行しながら、各ワークロードに専用クラスタのメリットを提供できるということです。このように効果的な解決策の 1 つは、 Red Hat OpenShift でマルチテナンシーを設定することです。マルチテナンシーは、同じクラスタ上で複数のテナントを共存させ、リソースやセキュリティなどを適切に分離できるアーキテクチャです。 テナントは、特定のユーザグループが専用として使用するように設定されたクラスタリソースのサブセットとみなすことができます。したがって、 Red Hat OpenShift クラスタにマルチテナンシーを設定することには、以下のような利点があります

. クラスタリソースを共有できるようにすることで、 CapEx / OpEx を削減します。
. 運用と管理のオーバーヘッドを軽減
. セキュリティ侵害のクロスコンタミネーションからワークロードを保護
. リソースの競合による予期しないパフォーマンスの低下からワークロードを保護


本格的なマルチテナント OpenShift クラスタでは、コンピューティング、ストレージ、ネットワーク、セキュリティなど、異なるリソースバケットに属するクラスタリソースに対してクォータと制限を設定する必要があります。ただし、この解決策のすべてのリソースバケットの特定の側面については説明します。 特に、 NetApp ONTAP をベースとする NetApp Trident が動的に割り当てられるストレージリソースにマルチテナンシーを設定することで、同じ Red Hat OpenShift クラスタ上の複数のワークロードが提供または消費するデータを分離し、保護するためのベストプラクティスに焦点を当てます。

link:rh-os-n_use_case_multitenancy_architecture.html["次の例は、アーキテクチャです"]
