---
sidebar: sidebar 
permalink: containers/rh-os-rhv_best_practices_for_production_deployments.html 
summary: NetApp HCI に Red Hat OpenShift を導入するためのベストプラクティスです 
keywords: best practices, VM, Virtual Machine, Host affinity, custom install file, customized install 
---
= 本番環境への導入に関するベストプラクティス - NetApp HCI for Red RHV 上の HAT OpenShift
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
このセクションでは、この解決策を本番環境に導入する前に考慮する必要があるベストプラクティスをいくつか紹介します。



=== 少なくとも 3 つの RHV クラスタに OpenShift を導入する ノード

このドキュメントで説明する検証済みのアーキテクチャは、 2 つの RHV-H ハイパーバイザーノードを導入し、ホスト型エンジンと導入済み VM を両方のホストで管理して 2 つのハイパーバイザー間で移行できるフォールトトレラントな構成を確保することによって、 HA 処理に適した最小限のハードウェア導入を示しています。Red Hat OpenShift は最初に 3 つのマスターノードで導入するため、 2 ノード構成で少なくとも 2 つのマスターが同じノードを占有します。そのため、特定のノードが使用できなくなった場合に OpenShift が停止する可能性があります。そのため、解決策の一部として少なくとも 3 つの RHV - H ハイパーバイザーノードを導入して、 OpenShift マスターを均等に分散できるようにし、解決策にさらにフォールトトレランスを追加することが Red Hat のベストプラクティスです。



=== 仮想マシンとホストのアフィニティを設定します

VM とホストのアフィニティを有効にすることで、複数のハイパーバイザーノードに OpenShift マスターを確実に分散させることができます。アフィニティとは、 VM やホストのセットに対してルールを定義する方法で、グループ内の同じホストで複数の VM が実行されるか、別々のホストで実行されるかを決定します。VM とホストで構成されるアフィニティグループを作成することで、 VM に適用されます。このアフィニティグループには同じパラメータと条件が設定されます。アフィニティグループ内の VM がグループ内の同じホストで実行されているのか、または別々のホストで実行されているのかに応じて、アフィニティグループのパラメータでは正のアフィニティまたは負のアフィニティを定義できます。パラメータに定義された条件は、強制またはソフト強制のいずれかです。強制を強く行うことで、アフィニティグループ内の VM は、外部条件に関係なく常に正 / 負のアフィニティに従って配置されます。一方、ソフトな適用では、アフィニティグループ内の VM が可能なかぎり肯定的または否定的なアフィニティに従っている場合に、より高い優先度が設定されます。このドキュメントで説明する 2 つまたは 3 つのハイパーバイザー構成では、推奨設定はソフトアフィニティです。大規模なクラスタでは、 OpenShift ノードの分散を確保するためにハードアフィニティを利用できます。アフィニティグループを設定するには、を参照してください https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html/virtual_machine_management_guide/sect-affinity_groups["Red Hat 6.11アフィニティグループのドキュメント"^]。



=== OpenShift Deployment にカスタムインストールファイルを使用します

IPI を使用すると、このドキュメントで前述した対話型ウィザードを使用して、 OpenShift クラスタを簡単に導入できます。ただし、一部のデフォルト値については、クラスタの導入時に変更が必要になる場合があります。このような場合、クラスタをすぐに導入せずにウィザードを実行してタスクを割り当てることができますが、あとでクラスタを導入できる構成ファイルを出力する必要はありません。これは、任意の IPI デフォルトを変更する必要がある場合や、マルチテナンシーなどの他の用途のために、同一のクラスタを環境内に複数導入する必要がある場合に非常に便利です。OpenShift 用にカスタマイズされたインストール構成の作成の詳細については、を参照してください https://docs.openshift.com/container-platform/4.4/installing/installing_rhv/installing-rhv-customizations.html["Red Hat OpenShift カスタマイズを使用した RHV へのクラスタのインストール"^]。

link:rh-os-rhv_videos_and_demos.html["次のビデオとデモ： NetApp HCI for Red Hat OpenShift on Red Hat Virtualization"]
