---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= ビデオとデモ：ネットアップを使用した Red Hat OpenShift
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
次のビデオでは、このドキュメントで説明している機能の一部を紹介します。

.Cloud InsightsとOpenShift仮想化の統合
video::29ed6938-eeaf-4e70-ae7b-b15d011d75ff[panopto,width=360]
.Red Hat MTVを使用したNetApp ONTAPストレージによるOpenShift仮想化へのVMの移行
video::bac58645-dd75-4e92-b5fe-b12b015dc199[panopto,width=360]
.Astra ControlとNetApp FlexCloneテクノロジでソフトウェア開発を高速化- Red Hat OpenShift with NetApp
video::26b7ea00-9eda-4864-80ab-b01200fa13ac[panopto,width=360]
.NetApp Astra Control を活用して、事後分析とアプリケーションのリストアを実行
video::3ae8eb53-eda3-410b-99e8-b01200fa30a8[panopto,width=360]
.Astra Control Centerを使用したCI / CDパイプラインのデータ保護
video::a6400379-52ff-4c8f-867f-b01200fa4a5e[panopto,width=360]
.Astra Control Center - Red Hat OpenShiftとNetAppを使用したワークロードの移行
video::e397e023-5204-464d-ab00-b01200f9e6b5[panopto,width=360]
.ワークロードの移行 - ネットアップを使用した Red Hat OpenShift
video::27773297-a80c-473c-ab41-b01200fa009a[panopto,width=360]
.OpenShift Virtualizationのインストール-ネットアップでRed Hat OpenShiftを実装します
video::e589a8a3-ce82-4a0a-adb6-b01200f9b907[panopto,width=360]
.OpenShift仮想化を使用した仮想マシンの導入-ネットアップでRed Hat OpenShiftを実装します
video::8a29fa18-8643-499e-94c7-b01200f9ce11[panopto,width=360]
.Red Hat 仮想化での NetApp HCI for Red Hat OpenShift
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]