---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= ビデオとデモ：ネットアップを使用した Red Hat OpenShift
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
次のビデオでは、このドキュメントに記載されている機能の一部を紹介します。

.Trident保護を使用したVMのディザスタリカバリ
video::ae4bdcf7-b344-4f19-89ed-b2d500f94efd[panopto,width=360]
.Trident protectを使用したVMの保護
video::4670e188-3d67-4207-84c5-b2d500f934a0[panopto,width=360]
.iSCSIストレージを使用したOpenShift仮想化でのVMの作成
video::497b868d-2917-4824-bbaa-b2d500f92dda[panopto,width=360]
.Red Hat Certified Trident Operatorを使用したTridentのインストール
video::15c225f3-13ef-41ba-b255-b2d500f927c0[panopto,width=360]
.Amazon FSx for NetApp ONTAPとAWSでのRed Hat OpenShiftサービス（ホスト型コントロールプレーンを使用）
video::213061d2-53e6-4762-a68f-b21401519023[panopto,width=360]
.Amazon FSx for NetApp ONTAPを使用したROSA上のOpenShift仮想化における仮想マシンのライブ移行
video::4b3ef03d-7d65-4637-9dab-b21301371d7d[panopto,width=360]
.Ansibleによる自動化：Tridentの導入とOpenShiftクラスタへのストレージクラスの作成
video::fae6605f-b61a-4a34-a97f-b1ed00d2de93[panopto,width=360]
link:https://github.com/NetApp/trident-install["Ansibleを使用してNetApp Trident、StorageClasses、バックエンドをインストールするためのPlaybookは、githubにあります。"]

.ONTAP SAN（iSCSI）ストレージクラスを使用したOpenShift仮想化での新しいVMの導入
video::2e2c6fdb-4651-46dd-b028-b1ed00d37da3[panopto,width=360]
.ONTAP NASストレージクラスを使用したPostgreSQLコンテナアプリケーションの導入
video::d3eacf8c-888f-4028-a695-b1ed00d28dee[panopto,width=360]
.Cloud InsightsとOpenShift仮想化の統合
video::29ed6938-eeaf-4e70-ae7b-b15d011d75ff[panopto,width=360]
.Red Hat MTVを使用したNetApp ONTAPストレージによるOpenShift仮想化へのVMの移行
video::bac58645-dd75-4e92-b5fe-b12b015dc199[panopto,width=360]
.Tridentの高度なデータ管理機能を使用したOpenShift VMのフェイルオーバー/フェイルバック（早期アクセスプログラムのみ利用可能）
video::f2a8fa24-2971-4cdc-9bbb-b1f1007032ea[panopto,width=360]
.Cloud InsightsとOpenShift仮想化の統合
video::29ed6938-eeaf-4e70-ae7b-b15d011d75ff[panopto,width=360]
.Ansibleによる自動化：Tridentの導入とOpenShiftクラスタへのストレージクラスの作成
video::fae6605f-b61a-4a34-a97f-b1ed00d2de93[panopto,width=360]
** GitHubのサンプルAnsibleコード**link:https://github.com/NetApp/trident-install["Ansibleを使用してNetApp Trident、StorageClasses、バックエンドをインストールするためのPlaybookは、githubにあります。"]

.ONTAP NASストレージクラスを使用したPostgreSQLコンテナアプリケーションの導入
video::d3eacf8c-888f-4028-a695-b1ed00d28dee[panopto,width=360]
.ワークロードの移行 - ネットアップを使用した Red Hat OpenShift
video::27773297-a80c-473c-ab41-b01200fa009a[panopto,width=360]
.OpenShift Virtualizationのインストール-ネットアップでRed Hat OpenShiftを実装します
video::e589a8a3-ce82-4a0a-adb6-b01200f9b907[panopto,width=360]
.OpenShift仮想化を使用した仮想マシンの導入-ネットアップでRed Hat OpenShiftを実装します
video::8a29fa18-8643-499e-94c7-b01200f9ce11[panopto,width=360]
.Red Hat 仮想化での NetApp HCI for Red Hat OpenShift
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]