---
sidebar: sidebar 
permalink: dp-sec/cleondris_disaster_recovery_overview.html 
keywords: DR	Disaster, TR-4380, 4830, tr4830, continuity, application catalog 
summary:  
---
= TR-48930 ：『 NetApp HCI Disaster Recovery with Cleondris 』
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ネットアップ Michael White 氏



== ビジネス継続性とディザスタリカバリの概要

ビジネス継続性と災害復旧（ BCDR ）モデルは、人々を職場に戻すことを目的としています。ディザスタリカバリは、 E メールサーバなどのテクノロジを実際に使用できるようにすることに重点を置いています。ビジネス継続性により、ユーザーはその電子メールサーバーにアクセスできます。ディザスタ・リカバリだけでは、このテクノロジーは動作していますが、使用している企業はありません。 BCDR とは、回復されたテクノロジーを使用し始めたことを意味します。



== ビジネスへの影響評価

ティア 1 アプリケーションを動作させるために必要なものを理解することは困難です。通常、認証サーバと DNS が重要であることは明らかです。しかし、データベースサーバもどこかにありますか。

この情報は、テストフェイルオーバーと実際のフェイルオーバーの両方で機能するようにティア 1 アプリケーションをパッケージ化する必要があるため、重要です。会計会社は、ビジネスインパクト評価（ BIA ）を実行して、アプリケーションを適切に保護するために必要なすべての情報を提供できます。たとえば、必要なコンポーネントの特定、アプリケーションの所有者、アプリケーションの最適なサポート担当者などを特定できます。



== アプリケーションカタログ

BIA をお持ちでない場合は、自分でバージョンの BIA を実行できます。つまり、アプリケーションカタログです。これは、アプリケーション名、コンポーネント、要件、所有者、サポート、 電話番号、スポンサーまたはビジネスアプリケーションの所有者をサポートします。このようなカタログは、アプリケーションを保護する上で重要で有用です。ヘルプデスクは、アプリケーションカタログを支援する場合があります。多くの場合、ヘルプデスクはすでにアプリケーションカタログを起動しています。



== 保護すべきではないこと

保護すべきでないアプリケーションがあります。たとえば、ディザスタリカバリサイトで仮想マシン（ VM ）として実行されるドメインコントローラを簡単に安く導入できるため、保護する必要はありません。実際、ドメインコントローラをリカバリすると、リカバリ中に原因の問題が発生する可能性があります。本番用サイトで使用されている監視ソフトウェアが、そのサイトでリカバリされた場合、そのサイトで動作しているとは限りません。

通常、高可用性で保護できるアプリケーションを保護する必要はありません。高可用性は保護として最適であり、多くの場合、フェイルオーバー時間は 1 秒未満です。したがって、ディザスタリカバリオーケストレーションツールではこれらのアプリケーションを保護すべきではありませんが、高可用性では実現できます。たとえば、 ATM をサポートする銀行のソフトウェアなどです。

アプリケーション所有者の RTO （ Recovery Time Objective ：目標復旧時間）が 20 秒の場合に、アプリケーションの高可用性ソリューションを検討する必要があることを説明します。その RTO はレプリケーションソリューションの枠を超えています。



== 製品の概要

Cleondris HCI Control Center （ HCC ）は、新規および既存の NetApp HCI 環境にディザスタリカバリ機能を追加します。NetApp SolidFire ストレージエンジンと完全に統合されており、あらゆる種類のデータやアプリケーションを保護できます。お客様のサイトで障害が発生した場合は、ポリシーベースの VM 起動オーケストレーションなど、セカンダリ NetApp HCI サイトのすべてのデータをリカバリするために HCC を使用できます。

複数のボリュームにレプリケーションを設定すると、手動で実行する場合に時間がかかり、エラーが発生しやすくなります。HCC は複製ウィザードを支援します。ウィザードを使用してレプリケーションを正しく設定すると、災害発生時にサーバからボリュームにアクセスできるようになります。HCC を使用すると、本番環境に影響を与えずに、 VMware 環境をサンドボックス内のセカンダリシステムで起動できます。VM は分離されたネットワークで起動され、機能テストが可能です。
