---
sidebar: sidebar 
permalink: vdi-vds/citrix_user_layer.html 
keywords: static desktop, task worker, office worker, knowledge worker, power user, 
summary: Citrix Virtual Apps and Desktops を使用すると、インターネットアクセスを使用して、 HTML5 をサポートしている Web ブラウザや Citrix Workspace アプリケーションを使用している任意のデバイスから、ユーザーはワークスペース環境にアクセスできます。 
---
= ユーザー層（ User Layer ）
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Citrix Virtual Apps and Desktops を使用すると、インターネットアクセスを使用して、 HTML5 をサポートしている Web ブラウザや Citrix Workspace アプリケーションを使用している任意のデバイスから、ユーザーはワークスペース環境にアクセスできます。

ユーザーは、タスクワーカー、オフィスワーカー、ナレッジワーカー、パワーユーザに分類できます。タスクワーカーは、主に事前定義されたアプリケーションを 1 日中使用して作業を行います。ホストされている Windows アプリケーションは、ニーズに対応できます。Office ワーカーには、オフィスアプリケーションや Web ブラウザなどを実行するデスクトップインターフェイスが必要です。通常、ワークスペースにアプリケーションをインストールすることはできません。サーバ OS 上でマルチセッションを実行できる共有デスクトップとプールデスクトップのどちらにも最適です。

ナレッジワーカーは、通常、複数のアプリケーションを同時に操作するデスクトップ環境を必要とし、ワークスペースにインストールされているアプリケーションを維持できる必要があります。これは、静的デスクトップ（個人用デスクトップとも呼ばれます）で可能です。パワーユーザは通常、グラフィックを多用するアプリケーションや、より多くのハードウェアリソースを必要とするその他のアプリケーションで作業します。適切なマスターイメージを使用して作成された静的デスクトップは、パワーユーザのニーズに対応します。
