---
sidebar: sidebar 
permalink: vdi-vds/citrix_executive_summary.html 
keywords: TR-4854, tr4854, 4854, NetApp HCI, virtual apps, desktops, citrix hypervisor, Xen, pvs accelerator, LTSR 
summary: この解決策では、 NetApp HCI インフラ、 Citrix 仮想アプリケーションおよびデスクトップ、および Citrix ハイパーバイザーの統合について説明します。 
---
= TR-4854 ：『 NetApp HCI for Citrix Virtual Apps and Desktops with Citrix Hypervisor 』


[role="lead"]
ネットアップ Suresh Thoppay

NetApp HCI インフラでは、最初は小規模な構成から始めて、少しずつ段階的に構築して仮想デスクトップユーザのニーズに応えることができます。ビジネス要件の変化に対応するために、コンピューティングノードまたはストレージノードを追加または削除できます。

Citrix 仮想アプリケーションおよびデスクトップは、エンドユーザコンピューティング向けの機能豊富なプラットフォームを提供します。このプラットフォームは、さまざまな導入ニーズに対応し、複数のハイパーバイザーをサポートします。このソフトウェアのプレミアムエディションには、イメージとユーザーポリシーを管理するツールが含まれています。

Citrix ハイパーバイザー（旧称 Citrix Xen Hypervisor ）は、他のハイパーバイザープラットフォームで実行されている場合と比較して、 Citrix 仮想アプリケーションおよびデスクトップに追加機能を提供します。Citrix ハイパーバイザーで実行する主な利点は次のとおりです。

* Citrix ハイパーバイザーのライセンスは、すべてのバージョンの Citrix 仮想アプリケーションおよびデスクトップに含まれています。このライセンスは、 Citrix Virtual Apps and Desktops プラットフォームの実行コストを削減するのに役立ちます。
* PVS アクセラレータやストレージアクセラレータなどの機能は、 Citrix ハイパーバイザーでのみ使用できます。
* Citrix ソリューションでは、ワークロードの選択肢として Citrix ハイパーバイザーを使用することを推奨します。
* 長期サービスリリース（ LTSR ； Citrix 仮想アプリケーションおよびデスクトップに対応）および最新リリース（ CR ）のオプションで提供されます。

