---
sidebar: sidebar 
permalink: vdi-vds/citrix_netapp_value.html 
keywords: Data fabric, Cloud Volumes ONTAP, Azure NetApp Files, ShareFile, filecache 
summary: ネットアップのデータファブリックを基盤とするインフラでは、データを移行したり、あるサイトから別のサイト（クラウドを含む）へディザスタリカバリを実行したりできます。Cloud Insights を使用すると、パブリッククラウドやプライベートデータセンターに導入されたリソースの監視、最適化、トラブルシューティングを行うことができます。 
---
= ネットアップの価値
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




=== データファブリック

ネットアップのデータファブリックを基盤とするインフラでは、データを移行したり、あるサイトから別のサイト（クラウドを含む）へディザスタリカバリを実行したりできます。Citrix 仮想アプリケーションおよびデスクトップのデータは、次のように分類できます。

* インフラコンポーネント
* マシンイメージ
* アプリケーション
* ユーザプロファイル
* ユーザデータ


サイトは、ニーズに応じてアクティブ / アクティブまたはアクティブ / パッシブとして構成できます。インフラコンポーネントは、オンプレミスでもクラウドでも利用でき、サービスとしてアクセスできます。デスクトップおよびアプリケーションプールをプロビジョニングするには、 VM テンプレートを各サイトに分散する必要があります。アプリケーションレイヤ、ユーザプロファイル、およびデータは SMB ファイル共有に格納され、各サイトで利用できる必要があります。

グローバルネームスペースは、ほとんどのユーザが配置されている場所で、 Azure NetApp Files 、 NetApp Cloud Volumes ONTAP 、および FlexGroup ボリュームを使用して作成できます。他の場所では、グローバルファイルキャッシュを使用して、コンテンツをファイルサーバー上にローカルにキャッシュできます。Citrix ShareFile を使用する場合は、 NetApp StorageGRID により、ハイパフォーマンスで S3 と互換性のあるストレージが提供され、オンプレミスで NAS ゲートウェイにアクセスしてデータをホストできます。



=== Cloud Insights の機能です

Cloud Insights を使用すると、パブリッククラウドやプライベートデータセンターに導入されたリソースの監視、最適化、トラブルシューティングを行うことができます。

Cloud Insights は、次のようなメリットを提供します。

* * 平均問題解決時間を最大 90% 短縮。 * 長時間のログ検索を停止し、インフラストラクチャの手動相関に失敗します。当社の動的なトポロジーと相関分析を使用して、問題領域を即座に特定します。
* * クラウドインフラストラクチャのコストを平均 33% 削減 * 放置された未使用のリソースと適切なサイズのワークロードを特定して、パフォーマンスとコストの階層を最適化することで、非効率性を解消します。
* * クラウドの問題の 80% がエンドユーザーに影響を与えないようにします。 * 高度な分析と機械学習を使用して、重大なシステム停止になる前に問題を特定することで、膨大な量のデータを検索して関連項目を見つけるのを止めます。

