---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_why_ontap.html 
keywords: VDS, Virtual Desktop Service, ONTAP, FlexGroup, File System analytics, cloud tiering, global namespace 
summary: 仮想デスクトップサービスの ONTAP 機能。 
---
= 仮想デスクトップサービスの ONTAP 機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


次の ONTAP 機能は、仮想デスクトップサービスでの使用に適しています。

* * スケールアウトファイルシステム。 * ONTAP FlexGroup ボリュームは 20PB 以上のサイズに拡張でき、 1 つのネームスペースに 4 、 000 億を超えるファイルを格納できます。クラスタには最大 24 個のストレージノードを含めることができ、各ノードには、使用するモデルに応じた柔軟な数のネットワークインターフェイスカードを使用できます。
+
ユーザの仮想デスクトップ、ホームフォルダ、ユーザプロファイルコンテナ、共有データなどは、ファイルシステムの制限を気にせずに、必要に応じて拡張できます。

* * ファイルシステム分析。 * XCP ツールを使用して、共有データの分析情報を取得できます。ONTAP 9.8+ と ActiveIQ の Unified Manager を使用すると、ファイルのメタデータ情報の照会と取得、コールドデータの特定を簡単に実行できます。
* * クラウドの階層化。 * コールドデータをクラウド内のオブジェクトストアや、データセンター内の任意の S3 互換ストレージに移行できます。
* * ファイルバージョン。 * ユーザは、 NetApp ONTAP Snapshot コピーで保護されているファイルをリカバリできます。ONTAP の Snapshot コピーでは変更されたブロックのみが記録されるため、スペース効率に優れています。
* * グローバル・ネームスペース。 * ONTAP FlexCache テクノロジーにより、ファイル・ストレージのリモート・キャッシュが可能になり、 ONTAP ストレージ・システムを含む複数の場所で共有データを容易に管理できます。
* * セキュアマルチテナンシーのサポート。 * 1 つの物理ストレージクラスタを、それぞれ独自のボリューム、ストレージプロトコル、論理ネットワークインターフェイス、 ID および認証ドメイン、管理ユーザなどを持つ複数の仮想ストレージアレイとして提供できます。そのため、テスト、開発、本番環境など、複数のビジネスユニットや環境でストレージアレイを共有することができます。
+
パフォーマンスを保証するために、アダプティブ QoS を使用して使用済みスペースまたは割り当て済みスペースに基づいてパフォーマンスレベルを設定し、クォータを使用してストレージ容量を制御することができます。

* * VMware 統合。 * VMware vSphere 用 ONTAP ツールは、データストアのプロビジョニング、 vSphere ホストのベストプラクティスの実装、および ONTAP リソースの監視を行うための vCenter プラグインを提供します。
+
ONTAP は、 SCSI / ファイルの処理をストレージアレイにオフロードするための vStorage API for Array Integration （ VAAI ）をサポートしています。ONTAP は、 vStorage APIs for Storage Awareness （ VASA ）もサポートしており、ブロックプロトコルとファイルプロトコルの両方をサポートしています。

+
SnapCenter Plug-in for VMware vSphere を使用すると、ストレージアレイの Snapshot 機能を使用して仮想マシンのバックアップとリストアを簡単に実行できます。

+
ActiveIQ Unified Manager は、 vSphere 環境でストレージネットワークをエンドツーエンドで可視化できる機能を提供します。管理者は、 ONTAP でホストされている仮想デスクトップ環境で発生する可能性のあるレイテンシの問題を簡単に特定できます。

* * セキュリティコンプライアンス。 * ActiveIQ Unified Manager では、複数の ONTAP システムを監視し、ポリシー違反のアラートを通知できます。
* * マルチプロトコル対応。 * ONTAP はブロック（ iSCSI 、 FC 、 FCoE 、 NVMe/FC ）、ファイル（ NFSv3 、 NFSv4.1 、 SMB2.x 、および smb3.x ）のストレージプロトコル、およびオブジェクト（ S3 ）ストレージプロトコル。
* * 自動化のサポート。 * ONTAP は、 VDS 管理ポータルでタスクを自動化する REST API 、 Ansible 、 PowerShell モジュールを提供します。


link:hcvdivds_data_management.html["次のステップ：データ管理"]
