---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_use_cases.html 
keywords: Use cases, target audience 
summary: NetApp VDS を使用したハイブリッド VDI により、サービスプロバイダとエンタープライズ仮想デスクトップ管理者は、ユーザに影響を与えることなく、簡単にリソースを他のクラウド環境に拡張できます。NetApp HCI 上にオンプレミスリソースを配置すると、 GPU リソースをより細かく制御でき、コンピューティングノードやストレージノードをオンデマンドで拡張できます。 
---
= ユースケース
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


NetApp VDS を使用したハイブリッド VDI により、サービスプロバイダとエンタープライズ仮想デスクトップ管理者は、ユーザに影響を与えることなく、簡単にリソースを他のクラウド環境に拡張できます。オンプレミスのリソースを使用することで、リソースをより効率的に管理でき、需要に応じて幅広い選択肢（コンピューティング、 GPU 、ストレージ、ネットワーク）を選択できます。

この解決策環境のユースケースは次のとおりです。

* クラウドにバーストして、リモートの需要急増に対応します デスクトップとアプリケーション
* 長時間のリモートデスクトップおよびアプリケーションの運用における TCO を削減 フラッシュストレージと GPU リソースをオンプレミスでホストできます
* クラウド全体にわたるリモートデスクトップとアプリケーションの管理が容易 環境
* ソフトウェアサービスを使用して、リモートデスクトップとリモートアプリケーションを体験できます オンプレミスのリソースを使用するモデル




=== 対象読者

解決策の対象となるグループは次のとおりです。

* の要件を理解したい EUC / VDI アーキテクト ハイブリッド VDS
* ネットアップのパートナーが、お客様の支援を希望しています リモートデスクトップとアプリケーションのニーズ
* リモートデスクトップに対応したい既存の NetApp HCI ユーザ アプリケーションのニーズも高まります


link:hcvdivds_netapp_virtual_desktop_service_overview.html["次のページ： NetApp Virtual Desktop Service の概要"]
