---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_nvidia_licensing.html 
keywords: Licensing, NVIDIA, GPU, GRID, Virtual PC 
summary: H610C または H615C を使用している場合、 GPU のライセンスはライセンスの再販権を持つ NVIDIA パートナーから購入する必要があります。 
---
= NVIDIA ライセンス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


H610C または H615C を使用している場合、 GPU のライセンスはライセンスの再販権を持つ NVIDIA パートナーから購入する必要があります。NVIDIA パートナーは、で検索できます https://www.nvidia.com/object/partner-locator.html["パートナー検索機能"^]。仮想 GPU （ vGPU ）や Tesla などで検索してください。

NVIDIA vGPU ソフトウェアには、次の 4 つのエディションがあります。

* NVIDIA GRID Virtual PC （ GRID vPC ）
* NVIDIA GRID 仮想アプリケーション（ GRID vApps ）
* NVIDIA Quadro Virtual Data Center Workstation （ Quadro vDWS ）
* NVIDIA Virtual ComputeServer （ vComputeServer ）




== GRID Virtual PC の場合

この製品は、 Microsoft Windows アプリケーション、ブラウザ、高解像度ビデオ、およびマルチモニタのサポートに優れたユーザエクスペリエンスを提供する仮想デスクトップを必要とするユーザに最適です。NVIDIA GRID Virtual PC は仮想環境でネイティブエクスペリエンスを実現し、すべての PC アプリケーションをフルパフォーマンスで実行できます。



== Grid 仮想アプリケーション

GRID vApps は、リモートデスクトップセッションホスト（ RDSH ）またはその他のアプリケーションストリーミングやセッションベースのソリューションを導入する組織向けの製品です。Microsoft Windows アプリケーションをフルパフォーマンスで実行できるように設計された Windows Server ホスト型の RDSH デスクトップも、 GRID vApps でサポートされています。



== Quadro Virtual Data Center Workstation の略

このエディションは、 Dassault CATIA 、 SOLIDWORKS 、 3Dexite 、 Siemens NX 、 PTC Creo などの強力な 3D コンテンツ作成アプリケーションを使用するメインストリームおよびハイエンドのデザイナーに最適です。 Schlumberger Petrel または Autodesk Maya 。NVIDIA Quadro vDWS を使用すると、すべてのデバイスのすべての機能とパフォーマンスを使用して、プロフェッショナルなグラフィックスアプリケーションにアクセスできます。



== NVIDIA Virtual ComputeServer のこと

多くの組織が、人工知能（ AI ）、ディープラーニング（ DL ）、データサイエンスなど、コンピューティング負荷の高いサーバワークロードを実行しています。このようなユースケースでは、 NVIDIA vComputeServer ソフトウェアが NVIDIA GPU を仮想化することで、エラー修正コード、ページのリタイアメント、 NVLink 経由のピアツーピア、マルチ vGPU などの機能を使用して、コンピューティング負荷の高いサーバワークロードを高速化します。


NOTE: Quadro vDWS ライセンスで GRID vPC と NVIDIA vComputeServer を使用できます。

link:hcvdivds_deployment.html["次の手順：導入"]
