---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html 
keywords: TR-4861, VDS, Windows Virtual Desktop, Remote Desktop Services, Virtual Desktop Services, 
summary: ネットアップの仮想デスクトップサービス（ VDS ）は、主要なパブリッククラウドとプライベートクラウドで Remote Desktop Services （ RDS ）のオーケストレーションを実現します。VDS は、 Microsoft Azure で Windows Virtual Desktop （ WVD ）をサポートします。VDS は、 WVD または RDS の導入後に実行する必要がある多くのタスクを自動化します。たとえば、 SMB ファイル共有（ユーザプロファイル、共有データ、およびユーザホームドライブ用）の設定、 Windows の機能、アプリケーションとエージェントのインストール、ファイアウォール、ポリシーなどを有効にします。 
---
= TR-4861 ：『 Hybrid Cloud VDI with Virtual Desktop Service 』
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ネットアップ Suresh Thoppay

ネットアップの仮想デスクトップサービス（ VDS ）は、主要なパブリッククラウドとプライベートクラウドで Remote Desktop Services （ RDS ）のオーケストレーションを実現します。VDS は、 Microsoft Azure で Windows Virtual Desktop （ WVD ）をサポートします。VDS は、 WVD または RDS の導入後に実行する必要がある多くのタスクを自動化します。たとえば、 SMB ファイル共有（ユーザプロファイル、共有データ、およびユーザホームドライブ用）の設定、 Windows の機能、アプリケーションとエージェントのインストール、ファイアウォール、ポリシーなどを有効にします。

ユーザは専用デスクトップ、共有デスクトップ、およびリモートアプリケーション用の VDS を使用します。VDS では、デスクトップのアプリケーション管理を自動化するスクリプト化されたイベントが提供され、管理するイメージの数が削減されます。

VDS では、パブリッククラウド環境とプライベートクラウド環境の導入を処理するための単一の管理ポータルが提供されます。



== お客様にもたらされる価値

2020 年のリモートワーカーの急増により、ビジネス継続性の要件が変化しています。IT 部門は、仮想デスクトップを迅速にプロビジョニングするという新たな課題に直面しています。そのためには、オンプレミスとクラウドのリソースのプロビジョニングを簡単に行えるハイブリッドクラウドのプロビジョニング即応性、リモート管理、 TCO のメリットが必要です。次のようなハイブリッドクラウド解決策が必要です。

* 新型コロナウイルス感染症ワークスペースの実際の状況に対処して、柔軟なワークモデルを実現します グローバルダイナミクスを備えています
* タスクワーカーからパワーユーザまで、すべての従業員の作業環境の導入を簡素化し、迅速化することで、シフトワークを可能にします
* 物理的な場所に関係なく、リッチでセキュアな VDI リソースを提供することで、従業員をモバイル化します
* ハイブリッドクラウドの導入を簡易化
* リスク軽減管理を自動化して簡素化します


link:hcvdivds_use_cases.html["次：ユースケース"]
