---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_solutions_for_industry.html 
keywords: GPU, Azure, NVIDIA, Tesla M60, 
summary: グラフィックス・ワークステーションは通常、製造、医療、エネルギー、メディアおよびエンターテイメント、教育、教育などの業界で使用されています。 アーキテクチャなど。モバイル性は、グラフィックスを多用するアプリケーションには限定されることがよくあります。 
---
= 業界向けソリューション
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
グラフィックス・ワークステーションは通常、製造、医療、エネルギー、メディアおよびエンターテイメント、教育、教育などの業界で使用されています。 アーキテクチャなど。モバイル性は、グラフィックスを多用するアプリケーションには限定されることがよくあります。

問題のモビリティに対応するため、仮想デスクトップサービスは、タスクワーカーからエキスパートユーザまで、クラウドまたは NetApp HCI でハードウェアリソースを使用して、あらゆるタイプの従業員にデスクトップ環境を提供します。 には、柔軟な GPU 構成のオプションも含まれます。VDS を使用すると、ラップトップ、タブレット、その他のモバイルデバイスを使用して、どこからでも作業環境にアクセスできます。

ANSYS Fluent'ANSYS Mechanical 'Autodesk AutoCAD'Autodesk Inventor'Autodesk 3ds Max などのソフトウェアを使用して製造ワークロードを実行するには ' 次の手順に従います Dassault Syst è mes SOLIDWORKS 、 Dassault Syst è mes CATIA 、 PTC Creo 、 Siemens PLM NX など さまざまなクラウド（ 2021 年 1 月現在）で利用可能な GPU を次の表に示します。

[cols="20%, 20%, 20%, 20%, 20%"]
|===
| GPU モデル | Microsoft Azure | Google Compute （ GCP ） | Amazon Web Services （ AWS ） | オンプレミス（ NetApp HCI ） 


| NVIDIA M60 | はい。 | はい。 | はい。 | いいえ 


| NVIDIA T4 | いいえ | はい。 | はい。 | はい。 


| NVIDIA P100 | いいえ | はい。 | いいえ | いいえ 


| NVIDIA P4 | いいえ | はい。 | いいえ | いいえ 
|===
他のユーザとの共有デスクトップセッションや、専用の個人用デスクトップも利用できます。仮想デスクトップには、 1 ～ 4 台の GPU を搭載することも、 NetApp HCI で部分的な GPU を利用することもできます。NVIDIA T4 は汎用性に優れた GPU カードで、幅広いユーザワークロードのニーズに対応できます。NetApp HCI H615C の各 GPU カードには、 16GB のフレームバッファメモリとサーバあたり 3 枚のカードが搭載されています。1 台の H615C サーバでホストできるユーザの数は、ユーザワークロードによって異なります。

[cols="25%, 25%, 25%, 25%"]
|===
| ユーザ / サーバ | ライト（ 4GB ） | メディア（ 8GB ） | 重量（ 16GB ） 


| H615C | 12. | 6. | 3. 
|===
ユーザタイプを確認するには、アプリケーションで一般的なタスクを実行している間に GPU プロファイラツールを実行します。GPU プロファイラは、メモリ要求、表示数、およびユーザが必要とする解像度をキャプチャします。その後、要件を満たす vGPU プロファイルを選択できます。

GPU を搭載した仮想デスクトップでは、最大 8K の表示解像度がサポートされます。また、ユーティリティ nView では、 1 つのモニタを複数の領域に分割して、異なるデータセットで動作させることができます。

ONTAP ファイルストレージでは、次のメリットを実現できます。

* 4 、 000 億個のファイルを含むストレージで最大 20PB まで拡張可能な単一のネームスペース。管理情報は必要ありません
* グローバルを使用して世界中にまたがることができるネームスペースです ファイルキャッシュ
* 管理対象のネットアップストレージでセキュアマルチテナンシーを実現
* ネットアップを使用したオブジェクトストアへのコールドデータの移行 FabricPool
* ファイルシステム分析によるクイックファイル統計
* ストレージクラスタの容量を最大 24 ノードまで拡張可能 パフォーマンスの向上を実現
* クォータを使用してストレージスペースを制御し、保証する機能 パフォーマンスと QoS 制限
* 暗号化によるデータの保護
* データ保護とコンプライアンスに関する幅広い要件に対応
* 柔軟なビジネス継続性オプションを提供

