---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: このページでは、ビデオとチュートリアルについて説明します。 
---
= ハイブリッドクラウド、仮想化、コンテナのビデオとデモ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
ハイブリッドクラウド、仮想化、およびコンテナソリューションの特定の機能を紹介するビデオとデモをご覧ください。

.NetApp ONTAP Tools for VMware vSphere の略
[%collapsible]
====
.ONTAP Tools for VMware -概要
[%collapsible]
=====
video::otv_overview.mp4[]
=====
.ONTAP によるVMware iSCSIデータストアのプロビジョニング
[%collapsible]
=====
video::otv_iscsi_provision.mp4[]
=====
.ONTAP によるVMware NFSデータストアのプロビジョニング
[%collapsible]
=====
video::otv_nfs_provision.mp4[]
=====
====
.AWS FSX for NetApp ONTAP を使用したVMware Cloud on AWS
[%collapsible]
====
.iSCSIを使用したFSX ONTAP を使用したWindowsゲスト接続ストレージ
[%collapsible]
=====
video::vmc_windows_vm_iscsi.mp4[]
=====
.NFSを使用したFSX ONTAP を使用したLinuxゲスト接続ストレージ
[%collapsible]
=====
video::vmc_linux_vm_nfs.mp4[]
=====
.Amazon FSX for NetApp ONTAP を使用すると、VMware Cloud on AWSのTCOを削減できます
[%collapsible]
=====
video::FSxN-NFS-Datastore-on-VMC-TCO-calculator.mp4[]
=====
.AWS上のVMware Cloud追加データストア、Amazon FSX for NetApp ONTAP
[%collapsible]
=====
video::FSxN-NFS-Datastore-on-VMC.mp4[]
=====
.VMware Cloud on AWS Migrate with FSxN、VMware HCX
[%collapsible]
=====
video::VMC_HCX_Setup.mp4[]
video::Migration_HCX_VMC_FSxN_VMotion.mp4[]
video::Migration_HCX_VMC_FSxN_cold_migration.mp4[]
=====
====
.Azure VMware Services on AzureとAzure NetApp Files （ANF）
[%collapsible]
====
.Azure NetApp Files を使用したAzure VMware解決策 補足データストアの概要
[%collapsible]
=====
video::ANF-NFS-datastore-on-AVS.mp4[]
=====
.Cloud Volumes ONTAP 、SnapCenter 、JetStreamを使用したAzure VMware解決策 DR
[%collapsible]
=====
video::AVS-guest-connect-DR-use-case.mp4[]
=====
.Azure VMware解決策 Migrate with ANF、VMware HCX
[%collapsible]
=====
video::Migration_HCX_AVS_ANF_ColdMigration.mp4[]
video::Migration_HCX_AVS_ANF_VMotion.mp4[]
video::Migration_HCX_AVS_ANF_Bulk.mp4[]
=====
====
.SnapCenter Plug-in for VMware vSphere
[%collapsible]
====
NetApp SnapCenter ソフトウェアは、使いやすいエンタープライズプラットフォームで、アプリケーション、データベース、ファイルシステム全体でデータ保護をセキュアに調整、管理できます。

SnapCenter Plug-in for VMware vSphere を使用 SnapCenter すると、 VMware vCenter に直接登録されている VM とデータストアのバックアップ、リストア、および接続処理を実行し、バックアップおよびマウント処理を実行できます。

NetApp SnapCenter Plug-in for VMware vSphere の詳細については、を参照してください link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["NetApp SnapCenter Plug-in for VMware vSphere の概要"]。

.VMware vSphere 解決策 用の SnapCenter プラグインの前提条件
[%collapsible]
=====
video::scv_prereq_overview.mp4[]
=====
.SnapCenter Plug-in for VMware vSphere - 導入
[%collapsible]
=====
video::scv_deployment.mp4[]
=====
.SnapCenter Plug-in for VMware vSphere - バックアップワークフロー
[%collapsible]
=====
video::scv_backup_workflow.mp4[]
=====
.SnapCenter Plug-in for VMware vSphere - リストアワークフロー
[%collapsible]
=====
video::scv_restore_workflow.mp4[]
=====
.SnapCenter - SQL リストアワークフロー
[%collapsible]
=====
video::scv_sql_restore.mp4[]
=====
====
.VMware Tanzu ネットアップソリューション
[%collapsible]
====
VMware Tanzu を使用すると、お客様は vSphere または VMware Cloud Foundation を通じて Kubernetes 環境を導入、管理、および管理できます。VMware のこの製品ポートフォリオでは、お客様のニーズに最適な VMware Tanzu エディションを選択することで、関連するすべての Kubernetes クラスタを単一のコントロールプレーンから管理できます。

VMware Tanzu の詳細については、を参照してください https://["VMware Tanzu の概要"^]。このレビューでは、 VMware Tanzu のユースケース、利用可能な追加機能などについて説明します。

* https://["VVOL をネットアップおよび VMware の Tanzu Basic で使用する方法、パート 1"^]
* https://["VVOL をネットアップおよび VMware の Tanzu Basic で使用する方法、パート 2"^]
* https://["VVOL をネットアップおよび VMware の Tanzu Basic で使用する方法、パート 3"^]


====
.ネットアップは Red Hat OpenShift を採用しています
[%collapsible]
====
エンタープライズ向け Kubernetes プラットフォームである Red Hat OpenShift を使用すると、オープンなハイブリッドクラウド戦略でコンテナベースのアプリケーションを実行できます。Red Hat OpenShift は、主要なパブリッククラウド上でクラウドサービスとして、または自己管理ソフトウェアとして利用でき、コンテナベースの解決策を設計する際に必要な柔軟性をお客様に提供します。

Red Hat OpenShift の詳細については、こちらを参照してください https://["Red Hat OpenShift の概要"^]。また、製品ドキュメントや導入オプションを確認して、 Red Hat OpenShift の詳細を確認することもできます。

* https://["ワークロードの移行 - ネットアップを使用した Red Hat OpenShift"^]
* https://["RHV への Red Hat OpenShift 導入：ネットアップを使用した Red Hat OpenShift"^]


====