---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: このページでは、ビデオとチュートリアルについて説明します。 
---
= 仮想化のビデオとデモ
:hardbreaks:
:allow-uri-read: 
:firstname: = Virtualization Videos and Demos
:author: = Virtualization Videos and Demos
:authorinitials: =
:authors: = Virtualization Videos and Demos
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
ハイブリッドクラウド、仮想化、およびコンテナソリューションの特定の機能を紹介するビデオとデモをご覧ください。

.NetApp ONTAP Tools for VMware vSphere の略
[%collapsible]
====
.ONTAP Tools for VMware -概要
video::d2ac19ba-28c4-4c07-8724-b01200f99845[panopto]
.ONTAP によるVMware iSCSIデータストアのプロビジョニング
video::5c047271-aecc-437c-a444-b01200f9671a[panopto]
.ONTAP によるVMware NFSデータストアのプロビジョニング
video::a34bcd1c-3aaa-4917-9a5d-b01200f97f08[panopto]
====
.AWS FSX for NetApp ONTAP を使用したVMware Cloud on AWS
[%collapsible]
====
.iSCSIを使用したFSX ONTAP を使用したWindowsゲスト接続ストレージ
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.NFSを使用したFSX ONTAP を使用したLinuxゲスト接続ストレージ
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.Amazon FSX for NetApp ONTAP を使用すると、VMware Cloud on AWSのTCOを削減できます
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.AWS上のVMware Cloud追加データストア、Amazon FSX for NetApp ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.VMCのVMware HCX展開と構成のセットアップ
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.VMCおよびFSxN向けVMware HCXによるVMotion移行のデモ
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.VMware HCX for VMCおよびFSxNを使用したコールドマイグレーションデモ
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
====
.Azure VMware Services on AzureとAzure NetApp Files （ANF）
[%collapsible]
====
.Azure NetApp Files を使用したAzure VMware解決策 補足データストアの概要
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
.Cloud Volumes ONTAP 、SnapCenter 、JetStreamを使用したAzure VMware解決策 DR
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.VMware HCX for AVSとANFを使用したコールドマイグレーションデモ
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.VMware HCX for AVSとANFでのvMotionのデモ
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.AVSとANF向けVMware HCXの一括移行デモ
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.SnapCenter Plug-in for VMware vSphere
[%collapsible]
====
NetApp SnapCenter ソフトウェアは、使いやすいエンタープライズプラットフォームで、アプリケーション、データベース、ファイルシステム全体でデータ保護をセキュアに調整、管理できます。

SnapCenter Plug-in for VMware vSphere を使用 SnapCenter すると、 VMware vCenter に直接登録されている VM とデータストアのバックアップ、リストア、および接続処理を実行し、バックアップおよびマウント処理を実行できます。

NetApp SnapCenter Plug-in for VMware vSphere の詳細については、を参照してください link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["NetApp SnapCenter Plug-in for VMware vSphere の概要"]。

.VMware vSphere 解決策 用の SnapCenter プラグインの前提条件
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto,width=360]
.SnapCenter Plug-in for VMware vSphere - 導入
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto,width=360]
.SnapCenter Plug-in for VMware vSphere - バックアップワークフロー
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto,width=360]
.SnapCenter Plug-in for VMware vSphere - リストアワークフロー
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto,width=360]
.SnapCenter - SQL リストアワークフロー
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto,width=360]
====
.VMware Tanzu ネットアップソリューション
[%collapsible]
====
VMware Tanzu を使用すると、お客様は vSphere または VMware Cloud Foundation を通じて Kubernetes 環境を導入、管理、および管理できます。VMware のこの製品ポートフォリオでは、お客様のニーズに最適な VMware Tanzu エディションを選択することで、関連するすべての Kubernetes クラスタを単一のコントロールプレーンから管理できます。

VMware Tanzu の詳細については、を参照してください https://tanzu.vmware.com/tanzu["VMware Tanzu の概要"^]。このレビューでは、 VMware Tanzu のユースケース、利用可能な追加機能などについて説明します。

.VVOL をネットアップおよび VMware の Tanzu Basic で使用する方法、パート 1
video::ZtbXeOJKhrc[youtube,width=360]
.VVOL をネットアップおよび VMware の Tanzu Basic で使用する方法、パート 2
video::FVRKjWH7AoE[youtube,width=360]
.VVOL をネットアップおよび VMware の Tanzu Basic で使用する方法、パート 3
video::Y-34SUtTTtU[youtube,width=360]
====