---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: このページでは、ビデオとチュートリアルについて説明します。 
---
= 仮想化のビデオとデモ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
ハイブリッドクラウド、仮想化、およびコンテナソリューションの特定の機能を紹介するビデオとデモをご覧ください。

.NetApp ONTAP Tools for VMware vSphere の略
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
ONTAP Tools for VMware -概要

 a| 
ONTAP によるVMware iSCSIデータストアのプロビジョニング

 a| 
ONTAP によるVMware NFSデータストアのプロビジョニング


|===
====
.AWS FSX for NetApp ONTAP を使用したVMware Cloud on AWS
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
iSCSIを使用したFSX ONTAP を使用したWindowsゲスト接続ストレージ

 a| 
NFSを使用したFSX ONTAP を使用したLinuxゲスト接続ストレージ

 a| 
Amazon FSX for NetApp ONTAP を使用すると、VMware Cloud on AWSのTCOを削減できます




 a| 
AWS上のVMware Cloud追加データストア、Amazon FSX for NetApp ONTAP

 a| 
VMCのVMware HCX展開と構成のセットアップ

 a| 
VMCおよびFSxN向けVMware HCXによるVMotion移行のデモ




 a| 
VMware HCX for VMCおよびFSxNを使用したコールドマイグレーションデモ

 a| 
 a| 

|===
====
.Azure VMware Services on AzureとAzure NetApp Files （ANF）
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Azure NetApp Files を使用したAzure VMware解決策 補足データストアの概要

 a| 
Cloud Volumes ONTAP 、SnapCenter 、JetStreamを使用したAzure VMware解決策 DR

 a| 
VMware HCX for AVSとANFを使用したコールドマイグレーションデモ




 a| 
VMware HCX for AVSとANFでのvMotionのデモ

 a| 
AVSとANF向けVMware HCXの一括移行デモ

 a| 

|===
====
.SnapCenter Plug-in for VMware vSphere
[%collapsible]
====
NetApp SnapCenter ソフトウェアは、使いやすいエンタープライズプラットフォームで、アプリケーション、データベース、ファイルシステム全体でデータ保護をセキュアに調整、管理できます。

SnapCenter Plug-in for VMware vSphere を使用 SnapCenter すると、 VMware vCenter に直接登録されている VM とデータストアのバックアップ、リストア、および接続処理を実行し、バックアップおよびマウント処理を実行できます。

NetApp SnapCenter Plug-in for VMware vSphere の詳細については、を参照してください link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["NetApp SnapCenter Plug-in for VMware vSphere の概要"]。

[cols="5a, 5a, 5a"]
|===


 a| 
VMware vSphere 解決策 用の SnapCenter プラグインの前提条件

 a| 
SnapCenter Plug-in for VMware vSphere - 導入

 a| 
SnapCenter Plug-in for VMware vSphere - バックアップワークフロー




 a| 
SnapCenter Plug-in for VMware vSphere - リストアワークフロー

 a| 
SnapCenter - SQL リストアワークフロー

 a| 

|===
====
.VMware Tanzu ネットアップソリューション
[%collapsible]
====
VMware Tanzu を使用すると、お客様は vSphere または VMware Cloud Foundation を通じて Kubernetes 環境を導入、管理、および管理できます。VMware のこの製品ポートフォリオでは、お客様のニーズに最適な VMware Tanzu エディションを選択することで、関連するすべての Kubernetes クラスタを単一のコントロールプレーンから管理できます。

VMware Tanzu の詳細については、を参照してください https://tanzu.vmware.com/tanzu["VMware Tanzu の概要"^]。このレビューでは、 VMware Tanzu のユースケース、利用可能な追加機能などについて説明します。

[cols="5a, 5a, 5a"]
|===


 a| 
VVOL をネットアップおよび VMware の Tanzu Basic で使用する方法、パート 1

video::ZtbXeOJKhrc[youtube,width=360] a| 
VVOL をネットアップおよび VMware の Tanzu Basic で使用する方法、パート 2

video::FVRKjWH7AoE[youtube,width=360] a| 
VVOL をネットアップおよび VMware の Tanzu Basic で使用する方法、パート 3

video::Y-34SUtTTtU[youtube,width=360]
|===
====