---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: このページでは、ビデオとチュートリアルについて説明します。 
---
= ハイブリッドクラウド、仮想化、コンテナのビデオとデモ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ハイブリッドクラウド、仮想化、およびコンテナソリューションの特定の機能を紹介するビデオとデモをご覧ください。



== NetApp SnapCenter および SnapCenter Plug-in for VMware vSphere

NetApp SnapCenter ソフトウェアは、使いやすいエンタープライズプラットフォームで、アプリケーション、データベース、ファイルシステム全体でデータ保護をセキュアに調整、管理できます。

SnapCenter Plug-in for VMware vSphere を使用 SnapCenter すると、 VMware vCenter に直接登録されている VM とデータストアのバックアップ、リストア、および接続処理を実行し、バックアップおよびマウント処理を実行できます。

NetApp SnapCenter Plug-in for VMware vSphere の詳細については、を参照してください link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["NetApp SnapCenter Plug-in for VMware vSphere の概要"]。

.VMware vSphere 解決策 用の SnapCenter プラグインの前提条件
====
video::scv_prereq_overview.mp4[]
====
.SnapCenter Plug-in for VMware vSphere - 導入
====
video::scv_deployment.mp4[]
====
.SnapCenter Plug-in for VMware vSphere - バックアップワークフロー
====
video::scv_backup_workflow.mp4[]
====
.SnapCenter Plug-in for VMware vSphere - リストアワークフロー
====
video::scv_restore_workflow.mp4[]
====
.SnapCenter - SQL リストアワークフロー
====
video::scv_sql_restore.mp4[]
====


== VMware Tanzu ネットアップソリューション

VMware Tanzu を使用すると、お客様は vSphere または VMware Cloud Foundation を通じて Kubernetes 環境を導入、管理、および管理できます。VMware のこの製品ポートフォリオでは、お客様のニーズに最適な VMware Tanzu エディションを選択することで、関連するすべての Kubernetes クラスタを単一のコントロールプレーンから管理できます。

VMware Tanzu の詳細については、を参照してください https://tanzu.vmware.com/tanzu["VMware Tanzu の概要"^]。このレビューでは、 VMware Tanzu のユースケース、利用可能な追加機能などについて説明します。

.ネットアップとVMware Tanzuのビデオ
====
* https://www.youtube.com/watch?v=ZtbXeOJKhrc["VVOL をネットアップおよび VMware の Tanzu Basic で使用する方法、パート 1"^]
* https://www.youtube.com/watch?v=FVRKjWH7AoE["VVOL をネットアップおよび VMware の Tanzu Basic で使用する方法、パート 2"^]
* https://www.youtube.com/watch?v=Y-34SUtTTtU["VVOL をネットアップおよび VMware の Tanzu Basic で使用する方法、パート 3"^]


====


== ネットアップは Red Hat OpenShift を採用しています

エンタープライズ向け Kubernetes プラットフォームである Red Hat OpenShift を使用すると、オープンなハイブリッドクラウド戦略でコンテナベースのアプリケーションを実行できます。Red Hat OpenShift は、主要なパブリッククラウド上でクラウドサービスとして、または自己管理ソフトウェアとして利用でき、コンテナベースの解決策を設計する際に必要な柔軟性をお客様に提供します。

Red Hat OpenShift の詳細については、こちらを参照してください https://www.redhat.com/en/technologies/cloud-computing/openshift["Red Hat OpenShift の概要"^]。また、製品ドキュメントや導入オプションを確認して、 Red Hat OpenShift の詳細を確認することもできます。

.Red Hat OpenShift を搭載したネットアップのビデオ
====
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_workload_migration_manual.html["ワークロードの移行 - ネットアップを使用した Red Hat OpenShift"^]
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_RHV_deployment.html["RHV への Red Hat OpenShift 導入：ネットアップを使用した Red Hat OpenShift"^]


====