---
sidebar: sidebar 
permalink: containers/baremetal-anthos/bmanthos_introduction.html 
keywords: WP-7337, Google Cloud, Cloud Volumes ONTAP, Cloud Volume Service, hypervisor, Kubernetes 
summary: ネットアップと Google Cloud は数年前から強力な関係を築いてきました。ネットアップは最初に、 Cloud Volumes ONTAP と Cloud Volumes Service を使用してクラウドデータサービスを Google Cloud に導入しました。この関係をさらに強化するために、解決策プラットフォームをオンプレミスの Google Cloud Anthos で使用できるようになりました。オンプレミス環境は、ハイパーバイザーベースのハイブリッドマルチクラウド Kubernetes NetApp HCI を VMware vSphere 上に導入した環境です。次に、ネットアップは、NetApp Astra Trident、ONTAP 、NFSプロトコル向けAnthos Ready認定を受けて、コンテナ向けの動的な永続的ストレージを提供しています。 
---
= WP-7337 ：『 Anthos on Bare Metal 』
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


ネットアップ、 Alan Cowles 氏と Nikhil M Kulkarni 氏

ネットアップと Google Cloud は数年前から強力な関係を築いてきました。ネットアップは最初に、 Cloud Volumes ONTAP と Cloud Volumes Service を使用して Google Cloud 向けのクラウドデータサービスを導入しました。この関係をさらに強化するために、解決策プラットフォームをオンプレミスの Google Cloud Anthos で使用できるようになりました。オンプレミス環境は、ハイパーバイザーベースのハイブリッドマルチクラウド Kubernetes NetApp HCI を VMware vSphere 上に導入した環境です。次に、ネットアップは、NetApp Astra Trident、ONTAP 、NFSプロトコル向けAnthos Ready認定を受けて、コンテナ向けの動的な永続的ストレージを提供しています。

Anthosは、お客様の環境のベアメタルサーバに直接インストールできるようになりました。これにより、お客様はハイパーバイザを使用せずにGoogle Cloudをローカルデータセンターに拡張できます。さらに、NetApp ONTAP ストレージオペレーティングシステムとNetApp Astra Tridentの機能を活用すれば、コンテナ向けの永続的ストレージを統合して、プラットフォームの機能を拡張できます。

この組み合わせにより、 Google Cloud が提供するサポート、サービスレベル、月額課金、オンデマンドの柔軟性と組み合わせることで、サーバ、ストレージ、ネットワークの潜在的な可能性を最大限に引き出すことができます。独自のハードウェア、ネットワーク、ストレージを使用しているため、アプリケーションの規模、セキュリティ、ネットワークのレイテンシを直接制御でき、管理対象アプリケーションとコンテナ化されたアプリケーションをベアメタルの Anthos で利用できます。

link:bmanthos_solution_overview.html["次の手順：解決策の概要"]
