= 容量サイジングに関する考慮事項
:allow-uri-read: 




== 容量サイジングに関する考慮事項

ONTAPサイバーバックアップデスティネーションボリュームに必要なディスクスペースの量はさまざまな要因によって異なりますが、最も重要な要因はソースボリュームのデータの変更率です。デスティネーションボリュームでのバックアップスケジュールとSnapshotスケジュールはどちらもデスティネーションボリュームのディスク使用量に影響し、ソースボリュームでの変更率は一定ではない可能性があります。エンドユーザやアプリケーションの今後の動作の変化に対応するために必要な容量よりも多くのストレージ容量を確保することを推奨します。

ONTAPで保持期間1カ月の関係をサイジングするには、プライマリデータセットのサイズ、データ変更率（日次変更率）、重複排除と圧縮による削減量（該当する場合）など、いくつかの要因に基づいてストレージ要件を計算する必要があります。

ステップバイステップのアプローチは次のとおりです。

最初のステップは、サイバーヴォールトで保護するソースボリュームのサイズを確認することです。これは、サイバーヴォールトデスティネーションに最初にレプリケートされるデータの基本量です。次に、データセットの1日の変更率を見積もります。日 々 変化するデータの割合です。データの動的性について十分に理解しておくことが重要です。

例：

* プライマリデータセットのサイズ= 5TB
* 1日の変更率= 5%（0.05）
* 重複排除と圧縮による削減率= 50%（0.50）


では、計算を見ていきましょう。

* 日単位のデータ変更率を計算します。
+
`Changed data per day = 5000 * 5% = 250GB`

* 30日間の変更データの合計を計算します。
+
`Total changed data in 30 days = 250 GB * 14 = 3.5TB`

* 必要な総ストレージ容量を計算します。
+
`TOTAL = 5TB + 3.5TB = 8.5TB`

* 重複排除と圧縮による削減効果を適用します。
+
`EFFECTIVE = 8.5TB * 50% = 4.25TB`



*ストレージニーズの概要*

* 効率性がない場合：30日間分のサイバーヴォールトデータを保存するには* 8.5TB *が必要です。
* 50%の効率性で、重複排除と圧縮のあとに* 4.25TB *のストレージが必要になります。



NOTE: Snapshotコピーではメタデータによってオーバーヘッドが増える可能性がありますが、通常はこれはわずかです。


NOTE: 1日に複数のバックアップが作成される場合は、1日に作成されるSnapshotコピーの数で計算を調整します。


NOTE: 長期的なデータ増加を考慮して、サイジングが将来のニーズにも対応できるようにします。
