= 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


. クレデンシャルを設定します。
. クレデンシャルタイプを作成する。ONTAP が関連するソリューションでは、ユーザ名とパスワードのエントリに一致するクレデンシャルタイプを設定する必要があります。また、 Cloud Central と AWS のエントリも追加します。
+
.. [ 管理 ] → [ 資格情報の種類 ] に移動し、 [ 追加 ] をクリックします。
.. 名前と概要を指定します。
.. 入力構成に次の内容を貼り付けます。
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: CVO Username
  - id: dst_cluster_password
    type: string
    label: CVO Password
    secret: true
  - id: cvo_svm_password
    type: string
    label: CVO SVM Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
  - id: regular_id
    type: string
    label: Cloud Central ID
    secret: true
  - id: email_id
    type: string
    label: Cloud Manager Email
    secret: true
  - id: cm_password
    type: string
    label: Cloud Manager Password
    secret: true
  - id: access_key
    type: string
    label: AWS Access Key
    secret: true
  - id: secret_key
    type: string
    label: AWS Secret Key
    secret: true
  - id: token
    type: string
    label: Cloud Central Refresh Token
    secret: true
----
.. 次の内容をインジェクタ構成に貼り付け、 [ 保存（ Save ） ] をクリックする。
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  cvo_svm_password: '{{ cvo_svm_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
  regular_id: '{{ regular_id }}'
  email_id: '{{ email_id }}'
  cm_password: '{{ cm_password }}'
  access_key: '{{ access_key }}'
  secret_key: '{{ secret_key }}'
  token: '{{ token }}'
----


. ONTAP / CVO / AWS のクレデンシャルを作成
+
.. [ リソース ] → [ 資格情報 ] に移動し、 [ 追加 ] をクリックします。
.. ONTAP クレデンシャルの名前と組織の詳細を入力します
.. 前の手順で作成したクレデンシャルタイプを選択します。
.. Type Details に、ソースクラスタと CVO クラスタ、 Cloud Central / Manager 、 AWS Access / Secret Key 、 Cloud Central Refresh Token のユーザ名とパスワードを入力します。
.. [ 保存 ] をクリックします .


. Oracle のクレデンシャルの作成（ソース）
+
.. [ リソース ] → [ 資格情報 ] に移動し、 [ 追加 ] をクリックします。
.. Oracle ホストの名前と組織の詳細を入力します
.. マシンクレデンシャルタイプを選択します。
.. Type Details （タイプの詳細）に、 Oracle ホストのユーザー名とパスワードを入力します。
.. 適切な特権昇格方式を選択し、ユーザ名とパスワードを入力します。
.. [ 保存 ] をクリックします .


. Oracle 保存先のクレデンシャルを作成します
+
.. [ リソース ] → [ 資格情報 ] に移動し、 [ 追加 ] をクリックします。
.. DR Oracle ホストの名前と組織の詳細を入力します
.. マシンクレデンシャルタイプを選択します。
.. Type Details に、ユーザ名（ ec2-user またはデフォルトの入力から変更した場合は、そのユーザ名）と SSH 秘密鍵を入力します
.. 適切な特権昇格方式（ sudo ）を選択し、必要に応じてユーザ名とパスワードを入力します。
.. [ 保存 ] をクリックします .



