= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS / VMC
--
AWS は、次の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての FSX ONTAP
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* ネイティブデータストアとしてのFSX ONTAP ^1 ^


詳細を表示します link:aws/aws-guest.html["VMCのゲスト接続ストレージオプション"]。

詳細を表示します link:aws-guest.html["VMCのゲスト接続ストレージオプション"]。

詳細については、をご覧ください link:https://blogs.vmware.com/cloud/2021/12/01/vmware-cloud-on-aws-going-big-reinvent2021/["ネイティブデータストアとしての FSX ONTAP ^1"^]。


NOTE: 1- 現在プライベートプレビュー中です

--
.Azure / AVS
--
Azure は、以下の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての Azure NetApp Files （ ANF
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* ネイティブデータストアとしてのAzure NetApp Files （ANF）^1 ^


詳細を表示します link:azure/azure-guest.html["AVSのゲスト接続ストレージオプション"]。

詳細を表示します link:azure-guest.html["AVSのゲスト接続ストレージオプション"]。

詳細については、をご覧ください link:https://azure.microsoft.com/en-us/updates/azure-netapp-files-datastores-for-azure-vmware-solution-is-coming-soon/["ネイティブデータストアとしての Azure NetApp Files （ ANF ） ^1"^]。


NOTE: 1- 現在プライベートプレビュー中です

--
.GCP/GCVE
--
Google Cloud は、次の構成でネットアップストレージをサポートします。

* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* Cloud Volumes Service （ CVS ）をゲスト接続ストレージとして使用できるようになりました
* ネイティブデータストアとしてのCloud Volumes Service （CVS）^1 ^


詳細を表示します link:gcp/gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。

詳細を表示します link:gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。

詳細については、をご覧ください link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/["ネイティブデータストアとしての Cloud Volumes Service （ CVS ） ^1"^]。


NOTE: 1- 現在プライベートプレビュー中です

--
====