= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS / VMC
--
このセクションでは、 AWS SDDC で VMware Cloud をセットアップおよび管理する方法と、ネットアップストレージの接続に使用できるオプションについて説明します。


NOTE: Cloud Volumes ONTAP をAWS VMCに接続する方法としてサポートされているのは、ゲスト内ストレージだけです。

セットアッププロセスは、次の手順に分けることができます。

* VMware Cloud for AWSを導入して設定
* VMware Cloud を FSX ONTAP に接続します


詳細を表示します link:aws/aws-setup.html["VMCの設定手順"]。

詳細を表示します link:aws-setup.html["VMCの設定手順"]。

--
.Azure / AVS
--
このセクションでは、 Azure VMware 解決策をセットアップおよび管理する方法と、ネットアップストレージの接続に使用できるオプションについて説明します。


NOTE: Cloud Volumes ONTAP をAzure VMware解決策 に接続する方法としてサポートされているのは、ゲスト内ストレージだけです。

セットアッププロセスは、次の手順に分けることができます。

* リソースプロバイダを登録し、プライベートクラウドを作成
* 新しい ExpressRoute 仮想ネットワークゲートウェイまたは既存の ExpressRoute 仮想ネットワークゲートウェイに接続します
* ネットワーク接続を検証し、プライベートクラウドにアクセス


詳細を表示します link:azure/azure-setup.html["AVSの設定手順"]。

詳細を表示します link:azure-setup.html["AVSの設定手順"]。

--
.GCP/GCVE
--
このセクションでは、 GCVE のセットアップと管理方法、およびネットアップストレージの接続に使用できるオプションとの組み合わせについて説明します。


NOTE: Cloud Volume と Cloud Volumes ONTAP サービスを GCVE に接続する方法としてサポートされているのは、ゲスト内ストレージだけです。

セットアッププロセスは、次の手順に分けることができます。

* GCVE を導入および設定します
* GCVE へのプライベートアクセスを有効にします


詳細を表示します link:gcp/gcp-setup.html["GCVEの設定手順"]。

詳細を表示します link:gcp-setup.html["GCVEの設定手順"]。

--
====