= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS / VMC
--
AWS は、次の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての FSX ONTAP
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* 補足的なNFSデータストアとしてのFSX ONTAP


詳細を表示します link:aws-guest.html["VMCのゲスト接続ストレージオプション"]。詳細を表示します link:aws-native-nfs-datastore-option.html["VMCの追加のNFSデータストアオプション"]。

詳細を表示します link:aws-guest.html["VMCのゲスト接続ストレージオプション"]。詳細を表示します link:aws-native-nfs-datastore-option.html["VMCの追加のNFSデータストアオプション"]。

--
.Azure / AVS
--
Azure は、以下の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての Azure NetApp Files （ ANF
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* Azure NetApp Files （ANF）を追加のNFSデータストアとして使用できます


詳細を表示します link:azure-guest.html["AVSのゲスト接続ストレージオプション"]。詳細を表示します link:azure-native-nfs-datastore-option.html["AVSの補足的なNFSデータストアオプション"]。

詳細を表示します link:azure-guest.html["AVSのゲスト接続ストレージオプション"]。詳細を表示します link:azure-native-nfs-datastore-option.html["AVSの補足的なNFSデータストアオプション"]。

--
.GCP/GCVE
--
Google Cloud は、次の構成でネットアップストレージをサポートします。

* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* Cloud Volumes Service （ CVS ）をゲスト接続ストレージとして使用できるようになりました
* Cloud Volumes Service （CVS）をNFSデータストアとして追加


詳細を表示します link:gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。

詳細を表示します link:gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。

詳細については、をご覧ください link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["NetApp Cloud Volumes Service データストアでのGoogle Cloud VMware Engineのサポート（ネットアップブログ）"^] または link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["ネットアップCVSをGoogle Cloud VMware Engineのデータストアとして使用する方法（Googleブログ）"^]

--
====