= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS / VMC
--
AWS は、次の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての FSX ONTAP
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* ネイティブデータストアとしてのFSX ONTAP ^1 ^


詳細を表示します link:aws/aws-guest.html["VMCのゲスト接続ストレージオプション"]。

詳細を表示します link:aws-guest.html["VMCのゲスト接続ストレージオプション"]。

FSX ONTAP の詳細については、AWS Press Releaseからネイティブデータストアパブリックプレビュー版をご覧ください（近日公開予定）。

--
.Azure / AVS
--
Azure は、以下の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての Azure NetApp Files （ ANF
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* ネイティブデータストアとしてのAzure NetApp Files （ANF）^1 ^


詳細を表示します link:azure/azure-guest.html["AVSのゲスト接続ストレージオプション"]。

詳細を表示します link:azure-guest.html["AVSのゲスト接続ストレージオプション"]。

詳細については、をご覧ください https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?branch=main&tabs=azure-portal["Azure NetApp Files （ANF）をネイティブデータストアとして使用-パブリックプレビュー"]。

--
.GCP/GCVE
--
Google Cloud は、次の構成でネットアップストレージをサポートします。

* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* Cloud Volumes Service （ CVS ）をゲスト接続ストレージとして使用できるようになりました
* ネイティブデータストアとしてのCloud Volumes Service （CVS）^1 ^


詳細を表示します link:gcp/gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。

詳細を表示します link:gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。

詳細については、をご覧ください link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/["ネイティブデータストアとしての Cloud Volumes Service （ CVS ） ^1"^]。


NOTE: 1- 現在プライベートプレビュー中です

--
====