= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS / VMC
--
AWS は、次の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての FSX ONTAP
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* 補足的なNFSデータストアとしてのFSX ONTAP


詳細を表示します link:aws/aws-guest.html["VMCのゲスト接続ストレージオプション"]。詳細を表示します link:aws/aws-native-nfs-datastore-option.html["VMCの追加のNFSデータストアオプション"]。

詳細を表示します link:aws-guest.html["VMCのゲスト接続ストレージオプション"]。詳細を表示します link:aws-native-nfs-datastore-option.html["VMCの追加のNFSデータストアオプション"]。

--
.Azure / AVS
--
Azure は、以下の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての Azure NetApp Files （ ANF
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* Azure NetApp Files （ANF）をNFSデータストア^1の補足情報として使用しています


詳細を表示します link:azure/azure-guest.html["AVSのゲスト接続ストレージオプション"]。詳細を表示します link:azure/azure-native-nfs-datastore-option.html["AVSの補足的なNFSデータストアオプション"]。

詳細を表示します link:azure-guest.html["AVSのゲスト接続ストレージオプション"]。詳細を表示します link:azure-native-nfs-datastore-option.html["AVSの補足的なNFSデータストアオプション"]。


NOTE: 1 - AVSの補足的なNFSデータストアであるANFは、現在パブリックプレビュー版です。詳細はこちら https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?branch=main&tabs=azure-portal["こちらをご覧ください"]。

--
.GCP/GCVE
--
Google Cloud は、次の構成でネットアップストレージをサポートします。

* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* Cloud Volumes Service （ CVS ）をゲスト接続ストレージとして使用できるようになりました
* Cloud Volumes Service （CVS）をNFSデータストア^1^として追加で作成します


詳細を表示します link:gcp/gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。

詳細を表示します link:gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。

詳細については、をご覧ください link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/["Cloud Volumes Service （CVS）をNFSデータストア^1の補足情報として追加しました"^]。


NOTE: 1- 現在プライベートプレビュー中です

--
====