= Oracle のインストールを検証します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




=== Oracle のインストールを検証します

. OracleユーザとしてOracleサーバにログインし、次のコマンドを実行します。


[source, cli]
----
ps -ef | grep ora
----

NOTE: インストールが正常に完了した場合は、 Oracle プロセスが一覧表示されます Oracle DB のサポートを開始しました

. データベースにログインして、次のコマンドセットを使用して作成されたDB設定およびPDBを確認します。


[source, cli]
----
sqlplus / as sysdba
----
[oracle @localhost ~] $sqlplus / AS sysdba

SQL * Plus ：リリース 19.0.0.0.0 - 木曜日 5 月 6 日 12 ： 52 ： 51 2021 バージョン 19.8.0.0.0 の製造

Copyright （ c ） 1982 、 2019 、 OracleAll rights reserved.

接続先： Oracle Database 19C Enterprise Edition Release 19.0.0.0.0 - Production Version 19.8.0.0.0

SQL>

[source, cli]
----
select name, log_mode from v$database;
----
SQL> 名前の選択、 log_mode は V$ データベースから、名前 log_mode は ---- - - - - - - - - - - CDB2 ARCHIVELOG

[source, cli]
----
show pdbs;
----
SQL> PDB を表示

....
    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO
....
[source, cli]
----
col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;
----
SQL> col svrname フォーム A30 SQL> col dirname フォーム A30 SQL> select svrname 、 dirname 、 nfsversion from v$dnfs_servers ；

SVRNAME NFSVERVERSION-------------------------------- -------------- - - - - - - - - - - - - - 172.21.126.200/rhelora03_u02 NFSv4 3.0 172.21.126.200/rhelora03_u03 NFSv4 3.0 172.21.126.200/rhelora03_u01 NFSv3.0 を NFSv4 3.00 に戻します

[listing]
----
This confirms that dNFS is working properly.
----
. 次のコマンドを使用して'リスナー経由でデータベースに接続し'Oracleリスナーの構成を確認します適切なリスナーポートとデータベースサービス名に変更します。


[source, cli]
----
sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com
----
[oracle @ localhost ~] $sqlplus システム @ // localhost ： 1523 / cdb2_pdb1.cie.netapp.com

SQL * Plus ：リリース 19.0.0.0.0 - 木曜日 5 月 6 日 13 ： 19 ： 57 2021 バージョン 19.8.0.0.0 の製造

Copyright （ c ） 1982 、 2019 、 OracleAll rights reserved.

パスワード「 Last Successful login time ： Wed May 05 2021 17 ： 11 ： 11-04 ： 00 」を入力します

接続先： Oracle Database 19C Enterprise Edition Release 19.0.0.0.0 - Production Version 19.8.0.0.0

SQL> show user user is "system" SQL> show con_name CON_name CDB2_PDB1

[listing]
----
This confirms that Oracle listener is working properly.
----


=== サポートが必要な場所

ツールキットに関するサポートが必要な場合は、にご参加ください link:https://netapppub.slack.com/archives/C021R4WC0LC["ネットアップの解決策自動化コミュニティでは、余裕期間のチャネルがサポートさ"] また、ソリューション自動化チャネルを検索して、質問や問い合わせを投稿しましょう。
