---
sidebar: sidebar 
permalink: databases/aws_ora_fsx_ec2_migration.html 
summary: このセクションでは、オンプレミスからAWS EC2インスタンスおよびFSXストレージにOracleデータベースを移行する場合に考慮すべき要素について詳しく説明します。 
keywords: HA, DR, database, Oracle, RDS, AWS, SnapCenter 
---
= オンプレミスからパブリッククラウドへのデータベースの移行
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


link:aws_ora_fsx_ec2_mgmt.html["Previous：データベース管理。"]

データベースの移行は、どのような方法でも難しい課題です。オンプレミスからクラウドへのOracleデータベースの移行も例外ではありません。

以降のセクションでは、AWS EC2コンピューティングとFSXストレージプラットフォームを使用してOracleデータベースをAWSパブリッククラウドに移行する場合に考慮すべき主な要素について説明します。



== ONTAP ストレージはオンプレミスで利用できます

オンプレミスのOracleデータベースがONTAP ストレージアレイに配置されている場合は、NetApp SnapCenter UIツールを使用してデータベースを移行するためのレプリケーションを簡単に設定できます。

. オンプレミスのインスタンスと一致するターゲットコンピューティングEC2インスタンスを構築します。
. FSXコンソールから、同じサイズの一致するデータベースボリュームをプロビジョニングします。
. FSXデータベースボリュームをEC2インスタンスにマウントします。
. オンプレミスのデータベースボリュームとターゲットのFSXデータベースボリュームとの間にSnapMirrorレプリケーションを設定します。初期同期ではプライマリソースデータの移動に時間がかかる場合がありますが、次の差分更新の方がはるかに高速です。
. スイッチオーバー時に、プライマリアプリケーションをシャットダウンしてすべてのトランザクションを停止します。SnapCenter で、ログバックアップを実行して残りのトランザクションをターゲットにフラッシュします。
. ミラーボリュームを切断し、ターゲットでOracleリカバリを実行し、データベースを稼働状態にしてサービスを開始します。
. アプリケーションをクラウド内のOracleデータベースに指定します。




== ONTAP ストレージはオンプレミスでは利用できません

オンプレミスのOracleデータベースがONTAP 以外のサードパーティストレージでホストされている場合、データベースの移行はOracleデータベースのバックアップコピーのリストアに基づいて行われます。スイッチオーバーする前に、アーカイブログを再生して最新の状態にする必要があります。

AWS S3は、データベースの移動と移行のステージングストレージ領域として使用できます。この方法の手順の概要は、次のとおりです。

. オンプレミスのインスタンスと同等の、一致する新しいEC2インスタンスをプロビジョニングします。
. FSXストレージから同一のデータベースボリュームをプロビジョニングし、そのボリュームをEC2インスタンスにマウントします。
. ディスクレベルのOracleバックアップコピーを作成する。
. バックアップコピーをAWS S3ストレージに移動します。
. Oracleの制御ファイルを再作成し、S3ストレージからデータとアーカイブログを取得してデータベースをリカバリします。
. ターゲットのOracleデータベースをオンプレミスのソースデータベースと同期します。
. スイッチオーバー時に、アプリケーションとソースのOracleデータベースをシャットダウンします。最新の状態にするために、最後のいくつかのアーカイブ・ログをコピーし、ターゲットOracleデータベースに適用します。
. ユーザアクセス用にターゲットデータベースを起動します。
. アプリケーションをターゲットデータベースにリダイレクトして、スイッチオーバーを完了します。




== OracleマルチテナンシーCDB/PDBアーキテクチャを使用して、OracleデータベースをAWSに統合します

. AWSパブリッククラウドにCDBを作成します。
. CDB / PDBのマルチテナンシーにオンプレミスデータベースも導入されている場合は、移行するPDBを取り外します。
. メタデータと下線付きのOracleデータファイルをターゲットCDBインスタンスに転送します。
. Oracleの検証手順との互換性を検証
. 互換性検証に合格した場合は、未接続のPDBをターゲットCDBコンテナに接続します。
. 必要に応じてデータディクショナリを更新します。
. アクセスできるように、移行されたPDBをバックアップして開きます。



NOTE: PDBのプラグインとプラグインを取り外すには、移行計画の際に考慮すべきアプリケーションのダウンタイムが必要です。

繰り返しになりますが、ネットアップの自動化チームが提供する移行ツールキットを使用すれば、オンプレミスからAWSクラウドへのOracleデータベースの移行をスムーズに進めることができます。ネットアップのパブリックGitHubサイトで、最新のデータベース移行ツールを確認してください。
