---
sidebar: sidebar 
permalink: databases/aws_ora_fsx_ec2_migration.html 
summary: このセクションでは、オンプレミスからAWS EC2インスタンスおよびFSXストレージにOracleデータベースを移行する場合に考慮すべき要素について詳しく説明します。 
keywords: HA, DR, database, Oracle, RDS, AWS, SnapCenter 
---
= オンプレミスからパブリッククラウドへのデータベースの移行
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
データベースの移行は、どのような方法でも難しい課題です。オンプレミスからクラウドへのOracleデータベースの移行も例外ではありません。

以降のセクションでは、AWS EC2コンピューティングとFSXストレージプラットフォームを使用してOracleデータベースをAWSパブリッククラウドに移行する場合に考慮すべき主な要素について説明します。



== ONTAP ストレージはオンプレミスで利用できます

オンプレミスのOracleデータベースがONTAP ストレージアレイに配置されている場合は、AWS FSX ONTAP ストレージに組み込まれているNetApp SnapMirrorテクノロジを使用して、データベースを移行するためのレプリケーションを簡単に設定できます。移行プロセスは、NetApp BlueXPコンソールを使用してオーケストレーションできます。

. オンプレミスのインスタンスと一致するターゲットコンピューティングEC2インスタンスを構築します。
. FSXコンソールから、同じサイズの一致するデータベースボリュームをプロビジョニングします。
. FSXデータベースボリュームをEC2インスタンスにマウントします。
. オンプレミスのデータベースボリュームとターゲットのFSXデータベースボリュームとの間にSnapMirrorレプリケーションを設定します。初期同期ではプライマリソースデータの移動に時間がかかる場合がありますが、次の差分更新の方がはるかに高速です。
. スイッチオーバー時に、プライマリアプリケーションをシャットダウンしてすべてのトランザクションを停止します。Oracleのsqlplus CLIインターフェイスから、Oracleオンラインログスイッチを実行し、SnapMirrorの同期を有効にして、最後にアーカイブされたログをターゲットボリュームにプッシュします。
. ミラーボリュームを切断し、ターゲットでOracleリカバリを実行し、データベースを稼働状態にしてサービスを開始します。
. アプリケーションをクラウド内のOracleデータベースに指定します。


次のビデオでは、NetApp BlueXPコンソールとSnapMirrorレプリケーションを使用して、OracleデータベースをオンプレミスからAWS FSX/EC2に移行する方法を紹介します。

.オンプレミスのOracle DBをAWSに移行
video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto]


== ONTAP ストレージはオンプレミスでは利用できません

オンプレミスのOracleデータベースがONTAP 以外のサードパーティストレージでホストされている場合、データベースの移行はOracleデータベースのバックアップコピーのリストアに基づいて行われます。スイッチオーバーする前に、アーカイブログを再生して最新の状態にする必要があります。

AWS S3は、データベースの移動と移行のステージングストレージ領域として使用できます。この方法の手順の概要は、次のとおりです。

. オンプレミスのインスタンスと同等の、一致する新しいEC2インスタンスをプロビジョニングします。
. FSXストレージから同一のデータベースボリュームをプロビジョニングし、そのボリュームをEC2インスタンスにマウントします。
. ディスクレベルのOracleバックアップコピーを作成する。
. バックアップコピーをAWS S3ストレージに移動します。
. Oracleの制御ファイルを再作成し、S3ストレージからデータとアーカイブログを取得してデータベースをリカバリします。
. ターゲットのOracleデータベースをオンプレミスのソースデータベースと同期します。
. スイッチオーバー時に、アプリケーションとソースのOracleデータベースをシャットダウンします。最新の状態にするために、最後のいくつかのアーカイブ・ログをコピーし、ターゲットOracleデータベースに適用します。
. ユーザアクセス用にターゲットデータベースを起動します。
. アプリケーションをターゲットデータベースにリダイレクトして、スイッチオーバーを完了します。




== PDBの再配置によって可用性を最大限に高め、オンプレミスのOracleデータベースをAWS FSX/EC2に移行

この移行アプローチは、PDB / CDBマルチテナントモデルですでに導入されているOracleデータベースに最適です。ONTAP ストレージはオンプレミスでは利用できません。PDBの再配置方式では、サービスの中断を最小限に抑えながら、Oracle PDBのホットクローンテクノロジを使用して、ソースCDBとターゲットCDB間でPDBを移動します。

まず、オンプレミスから移行するPDBをホストするための十分なストレージを備えたAWS FSX/EC2にCDBを作成します。複数のオンプレミスPDBを一度に1つずつ再配置できます。

. マルチテナントのPDB / CDBモデルではなく単一のインスタンスにオンプレミスデータベースを導入している場合は、の手順に従います link:azure_ora_nfile_migration.html#converting-a-single-instance-non-cdb-to-a-pdb-in-a-multitenant-cdb["マルチテナントCDBで単一インスタンスの非CDBをPDBに変換します"^] 単一のインスタンスをマルチテナントPDB / CDBに変換します。次に、変換したPDBをAWS FSX/EC2内のCDBに移行する手順を実行します。
. マルチテナントのPDB / CDBモデルにオンプレミスデータベースがすでに導入されている場合は、の手順に従います link:azure_ora_nfile_migration.html#migrate-on-premises-oracle-databases-to-azure-with-pdb-relocation["PDBの再配置で、オンプレミスのOracleデータベースをクラウドに移行"^] 移行を実行します。


次のビデオでは、PDB（Oracle Database）を、最大限の可用性を備えたPDBの再配置を使用してFSX/EC2に移行する方法について説明します。

link:https://www.netapp.tv/insight/details/29998?playlist_id=0&mcid=85384745435828386870393606008847491796["オンプレミスのOracle PDBをAWS CDBに移行し、可用性を最大限に高めます"^]


NOTE: ステップ1と2の手順をAzureパブリッククラウドのコンテキストで説明していますが、この手順は変更を加えることなくAWSクラウドに適用できます。

NetApp Solutions Automationチームが提供する移行ツールキットを使用すれば、オンプレミスからAWSクラウドへのOracleデータベースの移行をスムーズに進めることができます。PDBの再配置用のOracleデータベース移行ツールキットをダウンロードするには、次のコマンドを使用します。

[source, cli]
----
git clone https://github.com/NetApp-Automation/na_ora_aws_migration.git
----