---
sidebar: sidebar 
permalink: databases/aws_ora_fsx_ec2_deploy_intro.html 
summary: このホワイトペーパーでは、AWS向けにカスタマイズされたOracle RDSデータベースHAおよびDR用の解決策 の概要と検証について説明し、複数のアベイラビリティゾーン環境でAWS FSXストレージサービスを利用しています。 
keywords: HA, DR, database, Oracle, RDS, AWS 
---
= WP-7357：『Oracle Database Deployment on EC2 and FSX Best Practices Introduction』
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


ネットアップ、Niyaz Mohamed、Jeffrey Steiner、Allen Cao氏

[role="lead"]
ミッションクリティカルなエンタープライズOracleデータベースの多くはオンプレミスでホストされており、多くの企業はこれらのOracleデータベースをパブリッククラウドに移行しようとしています。このようなOracleデータベースはアプリケーション中心のものであるため、ユーザ固有の設定が必要になることがよくあります。これは、多くのパブリッククラウドサービスが提供するデータベースサービスに欠けている機能です。そのため、現在のデータベース環境では、パフォーマンスと拡張性に優れたコンピューティングおよびストレージサービスを基盤に構築されたパブリッククラウドベースのOracleデータベース解決策 が、独自の要件に対応できるようになっている必要があります。AWS EC2コンピューティングインスタンスとAWS FSXストレージサービスは、ミッションクリティカルなOracleデータベースワークロードを構築してパブリッククラウドに移行するためのパズルのピースとして欠けているかもしれません。

Amazon Elastic Compute Cloud（Amazon EC2）は、サイズ変更が可能なセキュアなコンピューティング容量をクラウドで提供するWebサービスです。Webスケールのクラウドコンピューティングを企業にとって容易にするように設計されています。シンプルなAmazon EC2 Webサービスインターフェイスを使用すると、摩擦を最小限に抑えて容量を取得し、設定できます。コンピューティングリソースを完全に管理し、Amazonの実績あるコンピューティング環境で実行できます。

Amazon FSX for ONTAP は、業界をリードするNetApp ONTAP のブロックストレージとファイルストレージを使用するAWSストレージサービスで、NFS、SMB、iSCSIを公開します。このような強力なストレージエンジンを使用することで、ミッションクリティカルなOracleデータベースアプリケーションを、1ミリ秒未満の応答時間、数Gbpsのスループット、データベースインスタンスあたり10万以上のIOPSでAWSに簡単に再配置できます。さらに、FSXストレージサービスにはネイティブレプリケーション機能が備わっているため、オンプレミスのOracleデータベースをAWSに簡単に移行したり、ミッションクリティカルなOracleデータベースをHAまたはDR用のセカンダリAWSアベイラビリティゾーンにレプリケートしたりできます。

このドキュメントの目的は、FSXストレージを使用してOracleデータベースを導入し、構成する方法に関するステップバイステップのプロセス、手順、ベストプラクティスのガイダンスを提供することと、オンプレミスシステムと同様のパフォーマンスを提供するEC2インスタンスを提供することです。ネットアップは、AWSパブリッククラウドでOracleデータベースワークロードを導入、設定、管理するために必要なほとんどのタスクを自動化するための自動化ツールキットも提供しています。

解決策 とユースケースの詳細については、次の概要ビデオをご覧ください。

link:https://www.netapp.tv/insight/details/30000?playlist_id=275&mcid=04891225598830484314259903524057913910["AWSのハイブリッドクラウドと、Part1 -ユースケース、解決策 アーキテクチャであるFSX ONTAP を使用して、Oracleデータベースを最新化しましょう"^]

link:aws_ora_fsx_ec2_architecture.html["次は、ソリューションアーキテクチャです。"]
