---
sidebar: sidebar 
permalink: databases/cli_automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: このページでは、 NetApp ONTAP ストレージ上に Oracle19c を導入するための自動化方式について説明します。 
---
= ステップバイステップの導入手順
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
このドキュメントでは、自動コマンドラインインターフェイス（CLI）を使用したOracle 19Cの導入について詳しく説明します。



== CLI による Oracle 19C データベースの導入

このセクションでは、 CLI を使用して Oracle19c データベースを準備および導入するために必要な手順について説明します。を確認しておきます link:getting_started_requirements.html["「はじめに」および「要件」セクション"] それに応じて環境の準備を整えます。



=== Oracle19c repo をダウンロードします

. Ansibleコントローラで、次のコマンドを実行します。


[source, cli]
----
git clone https://github.com/NetApp-Automation/na_oracle19c_deploy.git
----
. リポジトリをダウンロードしたら、ディレクトリをna_oracle19c_deploy <cd na_oracle19c_deploy>に変更します。




=== hosts ファイルを編集します

導入前に、次の手順を実行します。

. hosts ファイル na_oracle19c_deploy ディレクトリを編集します。
. ONTAP で、 IP アドレスをクラスタ管理 IP に変更します。
. [Oracle] グループの下に、 Oracle ホスト名を追加します。DNS または hosts ファイルを使用してホスト名を IP アドレスに解決しておくか、ホストで指定する必要があります。
. これらの手順を完了したら、変更を保存します。


次の例は、ホストファイルを示しています。

[source, shell]
----
#ONTAP Host

[ontap]

"10.61.184.183"

#Oracle hosts

[oracle]

"rtpora01"

"rtpora02"
----
この例では、 Playbook を実行し、 Oracle 19C を 2 台の Oracle DB サーバに同時に導入しています。1 つの DB サーバでテストすることもできます。この場合、設定が必要なホスト変数ファイルは 1 つだけです。


NOTE: このプレイブックの内容は、導入する Oracle ホストとデータベースの数に関係なく同じです。



=== host_vars で host_name .yml ファイルを編集します

各 Oracle ホストには、ホスト固有の変数を含むホスト名で識別されるホスト変数ファイルがあります。ホストには任意の名前を指定できます。Host VAR Config セクションから「 host_vars 」を編集してコピーし、目的の「 host_name.yml 」ファイルに貼り付けます。


NOTE: 青の項目は、環境に合わせて変更する必要があります。



=== ホスト VAR 構成

[source, shell]
----
######################################################################
##############      Host Variables Configuration        ##############
######################################################################

# Add your Oracle Host
ansible_host: "10.61.180.15"

# Oracle db log archive mode: true - ARCHIVELOG or false - NOARCHIVELOG
log_archive_mode: "true"

# Number of pluggable databases per container instance identified by sid. Pdb_name specifies the prefix for container database naming in this case cdb2_pdb1, cdb2_pdb2, cdb2_pdb3
oracle_sid: "cdb2"
pdb_num: "3"
pdb_name: "{{ oracle_sid }}_pdb"

# CDB listener port, use different listener port for additional CDB on same host
listener_port: "1523"

# CDB is created with SGA at 75% of memory_limit, MB. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB. The grand total SGA should not exceed 75% available RAM on node.
memory_limit: "5464"

# Set "em_configuration: DBEXPRESS" to install enterprise manager express and choose a unique port from 5500 to 5599 for each sid on the host.
# Leave them black if em express is not installed.
em_configuration: "DBEXPRESS"
em_express_port: "5501"

# {{groups.oracle[0]}} represents first Oracle DB server as defined in Oracle hosts group [oracle]. For concurrent multiple Oracle DB servers deployment, [0] will be incremented for each additional DB server. For example,  {{groups.oracle[1]}}" represents DB server 2, "{{groups.oracle[2]}}" represents DB server 3 ... As a good practice and the default, minimum three volumes is allocated to a DB server with corresponding /u01, /u02, /u03 mount points, which store oracle binary, oracle data, and oracle recovery files respectively. Additional volumes can be added by click on "More NFS volumes" but the number of volumes allocated to a DB server must match with what is defined in global vars file by volumes_nfs parameter, which dictates how many volumes are to be created for each DB server.
host_datastores_nfs:
  - {vol_name: "{{groups.oracle[0]}}_u01", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u02", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u03", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
----


=== vars.yml ファイルを編集します

変数 .yml` ファイルは 'Oracle の導入に向けて ' 環境固有のすべての変数（ ONTAP 'Linux'Oracle ）を統合します

* 変数を VAR セクションから編集してコピーし、変数を自分の「 vars.yml 」ファイルに貼り付けます。


[source, shell]
----
#######################################################################
###### Oracle 19c deployment global user configuration variables ######
######  Consolidate all variables from ontap, linux and oracle   ######
#######################################################################

###########################################
### Ontap env specific config variables ###
###########################################

#Inventory group name
#Default inventory group name - 'ontap'
#Change only if you are changing the group name either in inventory/hosts file or in inventory groups in case of AWX/Tower
hosts_group: "ontap"

#CA_signed_certificates (ONLY CHANGE to 'true' IF YOU ARE USING CA SIGNED CERTIFICATES)
ca_signed_certs: "false"

#Names of the Nodes in the ONTAP Cluster
nodes:
 - "AFF-01"
 - "AFF-02"


#Storage VLANs
#Add additional rows for vlans as necessary
storage_vlans:
   - {vlan_id: "203", name: "infra_NFS", protocol: "NFS"}
More Storage VLANsEnter Storage VLANs details

#Details of the Data Aggregates that need to be created
#If Aggregate creation takes longer, subsequent tasks of creating volumes may fail.
#There should be enough disks already zeroed in the cluster, otherwise aggregate create will zero the disks and will take long time
data_aggregates:
  - {aggr_name: "aggr01_node01"}
  - {aggr_name: "aggr01_node02"}

#SVM name
svm_name: "ora_svm"


# SVM Management LIF Details
svm_mgmt_details:
  - {address: "172.21.91.100", netmask: "255.255.255.0", home_port: "e0M"}

# NFS storage parameters when data_protocol set to NFS. Volume named after Oracle hosts name identified by mount point as follow for oracle DB server 1. Each mount point dedicates to a particular Oracle files: u01 - Oracle binary, u02 - Oracle data, u03 - Oracle redo. Add additional volumes by click on "More NFS volumes" and also add the volumes list to corresponding host_vars as host_datastores_nfs variable. For multiple DB server deployment, additional volumes sets needs to be added for additional DB server. Input variable "{{groups.oracle[1]}}_u01", "{{groups.oracle[1]}}_u02", and "{{groups.oracle[1]}}_u03" as vol_name for second DB server. Place volumes for multiple DB servers alternatingly between controllers for balanced IO performance, e.g. DB server 1 on controller node1, DB server 2 on controller node2 etc. Make sure match lif address with controller node.
volumes_nfs:
  - {vol_name: "{{groups.oracle[0]}}_u01", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u02", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u03", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}

#NFS LIFs IP address and netmask
nfs_lifs_details:
  - address: "172.21.94.200" #for node-1
    netmask: "255.255.255.0"
  - address: "172.21.94.201" #for node-2
    netmask: "255.255.255.0"

#NFS client match
client_match: "172.21.94.0/24"

###########################################
### Linux env specific config variables ###
###########################################

#NFS Mount points for Oracle DB volumes
mount_points:
  - "/u01"
  - "/u02"
  - "/u03"

# Up to 75% of node memory size divided by 2mb. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB.
# Leave it blank if hugepage is not configured on the host.
hugepages_nr: "1234"

# RedHat subscription username and password
redhat_sub_username: "xxx"
redhat_sub_password: "xxx"

####################################################
### DB env specific install and config variables ###
####################################################

db_domain: "your.domain.com"

# Set initial password for all required Oracle passwords. Change them after installation.
initial_pwd_all: "netapp123"
----


=== プレイブックを実行します

必要な環境の前提条件を完了し ' 変数を vars.yml' および 'Your_host.yml' にコピーした後 ' プレイブックを導入する準備が整いました


NOTE: <username> は、環境に合わせて変更する必要があります。

. 正しいタグとONTAPクラスタユーザ名を渡してONTAP Playbookを実行します。プロンプトが表示されたら、ONTAPクラスタのパスワードとvsadminを入力します。


[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t ontap_config -e @vars/vars.yml
----
. Linux Playbookを実行して、導入のLinux部分を実行します。admin sshパスワードとsudoパスワードを入力します。


[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t linux_config -e @vars/vars.yml
----
. Oracle Playbookを実行して、導入のOracle部分を実行します。admin sshパスワードとsudoパスワードを入力します。


[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t oracle_config -e @vars/vars.yml
----


=== 同じ Oracle ホストに追加のデータベースを導入します

このプレイブックの Oracle 部分では、 1 回の実行につき Oracle サーバ上に Oracle コンテナデータベースが 1 つ作成されます。同じサーバ上に追加のコンテナデータベースを作成するには、次の手順を実行します。

. host_vars 変数を改訂します。
+
.. ステップ 3 に戻ります - 'host_vars' の下の 'host_name.yml' ファイルを編集します
.. Oracle SID を別の名前文字列に変更します。
.. リスナーポートを別の番号に変更します。
.. EM Express をインストールしている場合は、 EM Express ポートを別の番号に変更します。
.. 変更したホスト変数を 'host_vars' の下の Oracle ホスト変数ファイルにコピーして貼り付けます


. 上記のように 'ORACLE_CONFIG' タグを使用してプレイブックを実行します インチ <<プレイブックを実行します>>。




=== Oracle のインストールを検証します

. OracleユーザとしてOracleサーバにログインし、次のコマンドを実行します。


[source, cli]
----
ps -ef | grep ora
----

NOTE: インストールが正常に完了した場合は、 Oracle プロセスが一覧表示されます Oracle DB のサポートを開始しました

. データベースにログインして、次のコマンドセットを使用して作成されたDB設定およびPDBを確認します。


[source, cli]
----
sqlplus / as sysdba
----
[oracle @localhost ~] $sqlplus / AS sysdba

SQL * Plus ：リリース 19.0.0.0.0 - 木曜日 5 月 6 日 12 ： 52 ： 51 2021 バージョン 19.8.0.0.0 の製造

Copyright （ c ） 1982 、 2019 、 OracleAll rights reserved.

接続先： Oracle Database 19C Enterprise Edition Release 19.0.0.0.0 - Production Version 19.8.0.0.0

SQL>

[source, cli]
----
select name, log_mode from v$database;
----
SQL> 名前の選択、 log_mode は V$ データベースから、名前 log_mode は ---- - - - - - - - - - - CDB2 ARCHIVELOG

[source, cli]
----
show pdbs;
----
SQL> PDB を表示

....
    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO
....
[source, cli]
----
col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;
----
SQL> col svrname フォーム A30 SQL> col dirname フォーム A30 SQL> select svrname 、 dirname 、 nfsversion from v$dnfs_servers ；

SVRNAME NFSVERVERSION-------------------------------- -------------- - - - - - - - - - - - - - 172.21.126.200/rhelora03_u02 NFSv4 3.0 172.21.126.200/rhelora03_u03 NFSv4 3.0 172.21.126.200/rhelora03_u01 NFSv3.0 を NFSv4 3.00 に戻します

[listing]
----
This confirms that dNFS is working properly.
----
. 次のコマンドを使用して'リスナー経由でデータベースに接続し'Oracleリスナーの構成を確認します適切なリスナーポートとデータベースサービス名に変更します。


[source, cli]
----
sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com
----
[oracle @ localhost ~] $sqlplus システム @ // localhost ： 1523 / cdb2_pdb1.cie.netapp.com

SQL * Plus ：リリース 19.0.0.0.0 - 木曜日 5 月 6 日 13 ： 19 ： 57 2021 バージョン 19.8.0.0.0 の製造

Copyright （ c ） 1982 、 2019 、 OracleAll rights reserved.

パスワード「 Last Successful login time ： Wed May 05 2021 17 ： 11 ： 11-04 ： 00 」を入力します

接続先： Oracle Database 19C Enterprise Edition Release 19.0.0.0.0 - Production Version 19.8.0.0.0

SQL> show user user is "system" SQL> show con_name CON_name CDB2_PDB1

[listing]
----
This confirms that Oracle listener is working properly.
----


=== サポートが必要な場所

ツールキットに関するサポートが必要な場合は、にご参加ください link:https://netapppub.slack.com/archives/C021R4WC0LC["ネットアップの解決策自動化コミュニティでは、余裕期間のチャネルがサポートさ"] また、ソリューション自動化チャネルを検索して、質問や問い合わせを投稿しましょう。
