---
sidebar: sidebar 
permalink: databases/db_protection_overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: このページでは、 NetApp ONTAP ストレージ上に Oracle19c を導入するための自動化方式について説明します。 
---
= 解決策の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
このページでは、 NetApp ONTAP ストレージ上に Oracle19c を導入するための自動化方式について説明します。



== Oracle データベースのデータ保護を自動化

組織は環境を自動化して、効率を高め、導入を高速化し、手動作業を削減しています。Ansible などの構成管理ツールを使用して、エンタープライズデータベースの運用を合理化しています。この解決策では、 Ansible を使用して NetApp ONTAP による Oracle のデータ保護を自動化する方法を紹介します。ストレージ管理者、システム管理者、 DBA は、オフサイトのデータセンターやパブリッククラウドへのデータレプリケーションを一貫して迅速にセットアップできるため、次のようなメリットがあります。

* 設計の複雑さと人為的ミスを排除し、繰り返し実行可能な一貫した導入とベストプラクティスを実装する
* クラスタ間レプリケーション、 CVO のインスタンス化、 Oracle データベースのリカバリの構成にかかる時間を短縮できます
* データベース管理者、システム管理者、ストレージ管理者の生産性を向上
* データベースリカバリワークフローを使用して、 DR シナリオを簡単にテストできます。


ネットアップは、検証済みの Ansible モジュールとロールをお客様に提供し、 Oracle データベース環境の導入、構成、ライフサイクル管理を迅速化します。この解決策では、以下の作業に役立つ Ansible の Playbook コードを提供しています。



=== オンプレミスからオンプレミスへのレプリケーション

* ソースとデスティネーションにクラスタ間 LIF を作成
* クラスタと SVM のピア関係を確立
* Oracle ボリュームの SnapMirror を作成して初期化
* AWX/Tower を使用して、 Oracle バイナリ、データベース、ログ用のレプリケーションスケジュールを作成します
* デスティネーションで Oracle DB のリストアを行い、データベースをオンラインにします




=== オンプレミスから AWS の CVO へ

* AWS コネクタを作成します
* AWS で CVO インスタンスを作成
* オンプレミスのクラスタを Cloud Manager に追加
* ソースにクラスタ間 LIF を作成
* クラスタと SVM のピア関係を確立
* Oracle ボリュームの SnapMirror を作成して初期化
* AWX/Tower を使用して、 Oracle バイナリ、データベース、ログ用のレプリケーションスケジュールを作成します
* デスティネーションで Oracle DB のリストアを行い、データベースをオンラインにします


準備ができたら、をクリックします link:db_protection_getting_started.html["解決策の使用を開始するには、こちらをクリックしてください"]。
