---
sidebar: sidebar 
permalink: databases/getting_started_requirements.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: このページでは、 NetApp ONTAP ストレージ上に Oracle19c を導入するための自動化方式について説明します。 
---
= はじめに
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
この解決策は、 AWX/Tower 環境または Ansible コントロールホストの CLI で実行されるように設計されています。



== AWX ／タワー

AWX / タワー環境の場合は、 ONTAP クラスタ管理と Oracle サーバ（ IP およびホスト名）のインベントリの作成、クレデンシャルの作成、 NetApp Automation Github から Ansible コードを取得するプロジェクトの設定、および自動化を開始するジョブテンプレートの設定を案内されます。

. 環境に固有の変数を入力し、ジョブテンプレートのその他の VAR フィールドにコピーして貼り付けます。
. ジョブテンプレートに変数を追加したら、自動化を起動できます。
. ジョブテンプレートは、 ontap/config 、 linux_config 、および ORACLE_config のタグを指定することで、 3 つのフェーズで実行されます。




== Ansible コントロールホストを介して CLI に接続します

. Ansible 制御ホストとして使用できるように Linux ホストを設定するには、link:../automation/getting-started.html["詳細な手順については、ここをクリックしてください"]
. Ansible 制御ホストが設定されたら、 Ansible Automation リポジトリのクローンを Git で作成できます。
. ONTAP クラスタ管理 IP および Oracle サーバの管理 IP の IP またはホスト名を使用して hosts ファイルを編集してください。
. 環境に固有の変数を入力し ' 変数 .yml ファイルにコピーして貼り付けます
. 各 Oracle ホストには、ホスト固有の変数を含むホスト名で識別される変数ファイルがあります。
. すべての変数ファイルが完了したら 'ONTAP_config' 'linux_config' および 'ORACLE_config' のタグを指定することで ' 3 つのフェーズでプレイブックを実行できます




== 要件

[cols="3, 9"]
|===
| 環境 | 要件 


.4+| * Ansible 環境 * | AWX/Tower または Linux ホストを Ansible コントロールホストにします 


| Ansible v.2.10 以上 


| Python 3. 


| Python ライブラリ - NetApp-lib-xmltodict-jmespath 


.3+| * ONTAP * | ONTAP バージョン 9.3-9.7 


| データアグリゲート × 2 


| NFS VLAN および ifgrp が作成されました 


.5+| * Oracle サーバ * | RHEL 7/8 


| Oracle Linux 7/8 


| NFS 、パブリック、オプションの管理用のネットワークインターフェイス 


| Oracle サーバ上の Oracle インストールファイル 
|===


== 自動化の詳細

この自動導入は、 3 つのロールで構成される Ansible プレイブックを使用して設計されています。ロールは ONTAP 、 Linux 、 Oracle の各構成に対応しています。次の表に、自動化されるタスクを示します。

[cols="4, 9"]
|===
| ロール | タスク 


.5+| * ONTAP_CONFIG * | ONTAP 環境の事前チェック 


| Oracle 用の NFS ベースの SVM の作成 


| エクスポートポリシーが作成されました 


| Oracle 用のボリュームの作成 


| NFS LIF の作成 


.9+| *linux_config* | マウントポイントを作成し、 NFS ボリュームをマウント 


| NFS マウントを確認 


| OS 固有の設定 


| Oracle ディレクトリを作成します 


| hugepages を設定します 


| SELinux とファイアウォールデーモンを無効にする 


| サービスを有効にして開始します 


| ファイル記述子のハードリミットを増やします 


| pam.d セッションファイルを作成します 


.8+| * ORACLE_CONFIG * | Oracle ソフトウェアのインストール 


| Oracle リスナーを作成します 


| Oracle データベースを作成します 


| Oracle 環境構成 


| PDB 状態を保存します 


| インスタンスアーカイブモードを有効にします 


| DNFS クライアントを有効にしてください 


| OS のリブート間のデータベースの自動起動とシャットダウンを有効にします 
|===


== デフォルトパラメータ

自動化を簡易化するために、必要な Oracle 導入パラメータが多数デフォルト値であらかじめ設定されています。通常、ほとんどの環境でデフォルトパラメータを変更する必要はありません。上級ユーザーは ' デフォルト・パラメータを変更する際に注意してくださいデフォルトのパラメータは、各ロールフォルダの defaults ディレクトリにあります。



== 導入手順

開始する前に ' 次の Oracle インストール・ファイルとパッチ・ファイルをダウンロードし '/tmp/archive' ディレクトリに配置しますこのディレクトリには ' 展開する各 DB サーバ上のすべてのユーザに対する読み取り ' 書き込み ' および実行のアクセス権が含まれます自動化タスクは、その特定のディレクトリにある指定されたインストールファイルを検索して、 Oracle のインストールと構成を行います。

[listing]
----
LINUX.X64_193000_db_home.zip -- 19.3 base installer
p31281355_190000_Linux-x86-64.zip -- 19.8 RU patch
p6880880_190000_Linux-x86-64.zip -- opatch version 12.2.0.1.23
----


== 使用許諾

Github リポジトリに記載されているライセンス情報をお読みください。このリポジトリ内のコンテンツにアクセス、ダウンロード、インストール、または使用することにより、ライセンスの条項に同意したものとみなされます link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["こちらをご覧ください"^]。

このリポジトリ内のコンテンツの作成および / または派生著作物の共有に関しては、一定の制限事項があります。の条件を必ずお読みください link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["使用許諾"^] コンテンツを使用する前に。すべての条件に同意しない場合は、このリポジトリのコンテンツにアクセスしたり、コンテンツをダウンロードしたり、使用したりしないでください。

準備ができたら、をクリックします link:awx_automation.html["AWX/Tower の導入手順の詳細については、こちらを参照してください"] または link:cli_automation.html["CLI の導入については、こちらをご覧ください"]。
