---
sidebar: sidebar 
permalink: databases/sql-srv-anf_conclusion.html 
keywords: takeaways, hybrid-cloud 
summary: オールクラウドにも、ストレッチデータベースを使用したハイブリッドクラウドにも、 Azure NetApp Files は、データベースワークロードの導入と管理に最適なオプションを提供します。データ要件はアプリケーションレイヤとシームレスに連携し、 TCO を削減します。 
---
= まとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


オールクラウドにも、ストレッチデータベースを使用したハイブリッドクラウドにも、 Azure NetApp Files は、データベースワークロードの導入と管理に最適なオプションを提供します。データ要件はアプリケーションレイヤとシームレスに連携し、 TCO を削減します。

このドキュメントでは、 Azure NetApp Files を使用した Microsoft SQL Server 環境の計画、設計、最適化、拡張に関する推奨事項について説明します。この推奨事項は、実装によって大きく異なる場合があります。適切な解決策は、導入の技術的な詳細と、プロジェクトの背景にあるビジネス要件の両方によって異なります。



=== 重要なポイント

本ドキュメントの主な内容は次のとおりです。

* Azure NetApp Files を使用して、 SQL Server クラスタのデータベースおよびファイル共有監視をホストできるようになりました。
* アプリケーションの応答時間を短縮し、 99.9999% の可用性を実現して、必要なときに必要な場所で SQL Server データにアクセスできるようにします。
* シンプルで瞬時のサイズ変更により、 SQL Server の導入と、 RAID ストライピングなどの継続的な管理の全体的な複雑さを緩和できます。
* インテリジェントな運用機能を利用すれば、 SQL Server データベースを数分で導入し、開発サイクルを短縮できます。
* Azure クラウドが移行先である場合、最適化された導入に最適なストレージ解決策は Azure NetApp Files です。

