---
sidebar: sidebar 
permalink: databases/sql-srv-anf_overview.html 
keywords: use case, rehosting, enterprise resource planning, RDBMS, cloud migration 
summary: このドキュメントでは、 Azure NetApp Files で Azure 仮想マシンを利用して SQL Server Always On 可用性グループ（ AOAG ）をリアルタイムで導入する方法について説明します。 
---
= TR-4877 ：『 SQL Server on Azure NetApp Files - Real Deployment View 』
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ネットアップ、 Niyaz Mohamed

IT 組織は絶えず変化しています。Gartner のレポートでは、すべてのデータベースのほぼ 75% が 2022 年までにクラウドベースストレージが必要になると報告されています。Microsoft SQL Server は、業界をリードするリレーショナルデータベース管理システム（ RDBMS ）として、 Windows プラットフォームで設計されたアプリケーションや組織に最適です。エンタープライズリソースプランニング（ ERP ）から分析、コンテンツ管理まで、 SQL Server に依存します。SQL Server は、大規模なデータセットを管理する方法を変革し、アプリケーションを強化して、スキーマやクエリのパフォーマンスの要求に対応できるようにしました。

ほとんどの IT 組織は、クラウドファーストのアプローチを採用しています。変革フェーズにあるお客様は、現在の IT 環境を評価し、評価と調査の演習に基づいてデータベースワークロードをクラウドに移行します。柔軟性 / バースト性、データセンターの終了、データセンターの統合、サポート終了シナリオ、合併、合併など、お客様をクラウドへ移行させる要因には次のものがあります。 買収など。移行の理由は、組織ごとの優先事項と、それぞれのビジネスの優先事項によって異なります。クラウドに移行する際には、 SQL Server データベースクラウドの導入を有効に活用するために、適切なクラウドストレージを選択することが非常に重要です。



== ユースケース

SQL Server 環境を Azure に移行し、 SQL Server を Azure の膨大なプラットフォームサービス（ PaaS ）機能（ Azure Data Factory 、 Azure IoT Hub 、 Azure Machine Learning など）と統合することで、デジタル変革をサポートするための大きなビジネス価値が生まれます。また、クラウドを採用することで、各事業部門は、 CAPEX モデルや従来のプライベートクラウドモデルに頼らずに、生産性に重点を置き、新機能や拡張機能（ DevTest ユースケース）をより迅速に提供することができます。このドキュメントでは、 Azure NetApp Files で Azure 仮想マシンを利用して SQL Server Always On 可用性グループ（ AOAG ）をリアルタイムで導入する方法について説明します。

Azure NetApp Files は、継続的な可用性が確保されたファイル共有を備えたエンタープライズクラスのストレージを提供しますSQL Server の本番用データベースの SMB ファイル共有には、継続的可用性を備えた共有が必要です。これにより、コントローラのアップグレードや障害などのシステム停止を伴うシナリオにおいて、ノードは常にデータベースストレージにアクセスできます。継続的な可用性が確保されたファイル共有により、ストレージノード間でデータをレプリケートする必要がなくなります。Azure NetApp Files は、 SMB 3.0 のスケールアウト、永続的ハンドル、透過的なフェイルオーバー機能を使用して、計画的停止と計画外停止の間のノンストップオペレーション（ NDO ）をサポートします。これには、多くの管理タスクが含まれます。

クラウドへの移行を計画する場合は、常に最適な使用方法を評価する必要があります。アプリケーション移行で最も一般的かつ簡単なアプローチはリホスト（リフトアンドシフトとも呼ばれます）です。このドキュメントの例では、リホスト方法を使用しています。Azure NetApp Files を使用した Azure 仮想マシン上の SQL Server では、オンプレミスのハードウェアを管理しなくても、クラウド上で SQL Server のフルバージョンを使用できます。SQL Server 仮想マシン（ VM ）は、従量課金制でもライセンスコストを簡易化し、開発、テスト、環境の更新シナリオ向けに柔軟性とバースト性の高い機能を提供します。
