---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-firewall.html 
keywords: tcp, nfs, smb share, kerberos, active directory, dns 
summary: Cloud Volumes Service は、複数のTCPポートを公開してNFS共有とSMB共有を提供します。 
---
= ファイアウォール：
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-data-encryption-at-rest.html["Previous：保存データの暗号化。"]

[role="lead"]
Cloud Volumes Service は、複数のTCPポートを公開してNFS共有とSMB共有に対応します。

* https://["NFSアクセスに必要なポート"^]
* https://["SMBアクセスに必要なポート"^]


さらに、Kerberosを含むLDAPを使用するSMB、NFS、およびデュアルプロトコル構成では、Windows Active Directoryドメインへのアクセスが必要になります。Active Directory接続はである必要があります https://["を設定します"^] 地域単位で指定します。Active Directoryドメインコントローラ（DC）は、で識別できます https://["DNSベースのDC検出"^] 指定したDNSサーバを使用しています。返されるDCはすべて使用されます。対象となるDCのリストは、Active Directoryサイトを指定することによって制限できます。

Cloud Volumes Service は、に割り当てられているCIDR範囲のIPアドレスを使用して到達します `gcloud compute address` コマンドを実行中です https://["Cloud Volumes Service への参加"^]。このCIDRをソースアドレスとして使用して、Active Directoryドメインコントローラへのインバウンドファイアウォールを設定できます。

Active Directoryドメインコントローラは必須です https://["ここで説明したCloud Volumes Service CIDRsにポートを公開します"^]。

link:ncvs-gc-nas-protocols_overview.html["次：NASプロトコルの概要"]
