---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-overview.html 
keywords: 4918, tr4918, overview, introduction, scope, audience, abbreviation, definition 
summary: 特にストレージ管理者の管理権限がないクラウドでは、クラウドプロバイダが提供するサービスにデータを信頼することが何よりも重要です。このドキュメントでは、NetApp Cloud Volumes Service がGoogle Cloudで提供しているセキュリティサービスの概要について説明します。 
---
= TR-4918：『Security Overview - NetApp Cloud Volumes Service in Google Cloud』
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


ネットアップ、Oliver Krause、Justin Parisi



== 文書の範囲

特にストレージ管理者の管理権限がないクラウドでは、クラウドプロバイダが提供するサービスにデータを信頼することが何よりも重要です。本ドキュメントでは、ネットアップが提供するセキュリティソリューションの概要について説明します https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service はGoogle Cloudで提供されます"^]。



== 対象読者

このドキュメントの対象読者には、次の役割が含まれますが、これらに限定されません。

* クラウドプロバイダ
* ストレージ管理者
* ストレージアーキテクト
* フィールド用リソース
* ビジネス上の意思決定者


このテクニカルレポートの内容について不明な点がある場合は、を参照してください link:ncvs-gc-additional-information.html#contact-us["「お問い合わせください。」"]

|===
| 略語 | 定義（ Definition ） 


| CVS -ソフトウェア | Cloud Volumes Service 、サービスタイプCVS 


| CVS - パフォーマンス | Cloud Volume Service、サービスタイプCVS -パフォーマンス 


| PSA |  
|===
link:ncvs-gc-how-cloud-volumes-service-in-google-cloud-secures-your-data.html["次のステップ：Google CloudのCloud Volumes Service でデータを保護する方法をご紹介します。"]
