---
sidebar: sidebar 
permalink: ehc/azure/azure-native-overview.html 
keywords:  
summary:  
---
= ANFデータストアソリューションの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
成功を収めている組織は、変革と刷新の道を歩んでいます。このプロセスの一環として、企業は通常、既存のVMwareへの投資を活用しながら、クラウドのメリットを活用し、移行、バースト、拡張、ディザスタリカバリのプロセスを可能なかぎりシームレスに実行する方法を模索しています。クラウドに移行するお客様は、柔軟性とバースト性、データセンターの終了、データセンターの統合、サポート終了シナリオ、合併や買収などの問題を評価する必要があります。各組織が採用するアプローチは、それぞれのビジネスの優先順位に応じて異なります。クラウドベースの運用を選択する場合、適切なパフォーマンスと最小限の障害を持つ低コストモデルを選択することが重要な目標です。適切なプラットフォームを選択するとともに、クラウドの導入と柔軟性を最大限に活用するために、ストレージとワークフローのオーケストレーションが特に重要になります。



== ユースケース

Azure VMware解決策 はお客様に独自のハイブリッド機能を提供しますが、ネイティブストレージのオプションが限られているため、ストレージの負荷が高い組織での有用性が制限されています。ストレージはホストに直接関連付けられているため、ストレージを拡張する唯一の方法は、ホストを追加することです。これにより、ストレージを大量に消費するワークロードのコストを35～40%以上増加させることができます。このようなワークロードに必要なストレージ容量は追加ではなく、追加のホストに料金が発生します。

次のシナリオを考えてみましょう。お客様は6台のホストで馬力（vCPUとvMem）を求めていますが、ストレージの要件も大きくなっています。評価に基づいて、12台のホストがストレージ要件を満たしている必要があります。これにより、必要な容量をすべて追加購入するだけで、より多くのストレージが必要になるため、全体的なTCOが増加します。これは、移行、ディザスタリカバリ、バースト、開発/テストなど、あらゆるユースケースに当てはまります。 など。

Azure VMware解決策 のもう1つの一般的なユースケースは、ディザスタリカバリ（DR）です。ほとんどの組織には、裏付けのないDR戦略がないため、DR目的だけでゴーストデータセンターを運用する正当性を証明するのに苦労することがあります。管理者は、パイロットライトクラスタやオンデマンドクラスタを使用して、フットプリントゼロのDRオプションを検討できます。ホストを追加せずにストレージを拡張できるため、魅力的な選択肢となる可能性があります。

つまり、ユースケースは次の2つの方法で分類できます。

* ANFデータストアを使用したストレージ容量の拡張
* オンプレミスまたはAzureリージョン内のSoftware-Defined Storage（SDDC）間で、ANFデータストアをディザスタリカバリターゲットとして使用することで、コストを最適化したリカバリワークフローを実現できます。このガイドでは、Azure NetApp Files を使用してデータストアに最適化されたストレージを提供する方法を説明します（現時点ではパブリックプレビュー版です）。 Azure VMware解決策 の業界最高のデータ保護機能とDR機能を組み合わせることで、VSANストレージからストレージ容量をオフロードできます。



NOTE: Azure NetApp Files データストア機能は現在パブリックプレビュー版です。追加情報 の地域のネットアップまたはMicrosoft解決策 アーキテクトにお問い合わせください。



== AzureのVMware Cloudオプション



=== Azure VMware 解決策の略

Azure VMware解決策 （AVS）は、Microsoft Azureパブリッククラウド内でVMware SDSを完全に機能させるハイブリッドクラウドサービスです。AVSはMicrosoftが完全に管理およびサポートするファーストパーティの解決策 で、Azureインフラストラクチャを使用するVMwareにより検証されています。そのため、コンピューティング仮想化用のVMware ESXi、ハイパーコンバージドストレージ用のVSAN、ネットワークとセキュリティ用のNSXを、Microsoft Azureのグローバルプレゼンス、クラス最高レベルのデータセンター施設、ネイティブのAzureサービスとソリューションの豊富なエコシステムの近くで利用できます。Azure VMware解決策 SDDCとAzure NetApp Files を組み合わせることで、ネットワークレイテンシを最小限に抑えながら最高のパフォーマンスを実現できます。

VMware SDDCを導入する際、使用するクラウドに関係なく、最初のクラスタには次のコンポーネントが含まれます。

* コンピューティング仮想化用のVMware ESXiホストと、管理用のvCenterサーバアプライアンス
* 各ESXiホストの物理ストレージ資産を組み込んだVMware vSANハイパーコンバージドストレージ。
* 管理のためにNSX Managerクラスタを使用した仮想ネットワークとセキュリティのためのVMware NSX




== まとめ

Azure NetApp Files は、オールクラウドとハイブリッドクラウドのどちらをターゲットとしている場合でも、アプリケーションワークロードとファイルサービスを導入して管理するための優れたオプションを提供し、データ要件をアプリケーションレイヤとシームレスにすることでTCOを削減します。どのようなユースケースでも、クラウドのメリット、一貫したインフラ、オンプレミスと複数のクラウドにわたる運用、ワークロードの双方向性、エンタープライズクラスの容量とパフォーマンスを迅速に実現するには、Azure VMware解決策 とAzure NetApp Files を選択してください。ストレージの接続に使用される一般的なプロセスと手順は同じです。新しい名前とともに変更されたデータの位置にすぎません。ツールやプロセスはすべて変わらないので、Azure NetApp Files を使用すると導入全体を最適化できます。



== 重要なポイント

本ドキュメントの主な内容は次のとおりです。

* AVS SDDCのデータストアとしてAzure NetApp Files を使用できるようになりました。
* アプリケーションの応答時間を短縮し、可用性を高めて、必要なときに必要な場所でワークロードデータにアクセスできるようにします。
* シンプルで瞬時のサイズ変更機能により、VSANストレージの全体的な複雑さを緩和
* 動的な再構築機能でミッションクリティカルなワークロードのパフォーマンスを保証
* Azure VMware解決策 クラウドが移行先である場合、Azure NetApp Files は最適化された導入に最適なストレージ解決策 です。




== 追加情報の参照先

このドキュメントに記載されている情報の詳細については、次の Web サイトのリンクを参照してください。

* Azure VMware解決策 のドキュメント
+
https://docs.microsoft.com/en-us/azure/azure-vmware/["https://docs.microsoft.com/en-us/azure/azure-vmware/"^]

* Azure NetApp Files のドキュメント
+
https://docs.microsoft.com/en-us/azure/azure-netapp-files/["https://docs.microsoft.com/en-us/azure/azure-netapp-files/"^]

* Azure NetApp Files とAzure VMware解決策 を統合
+
https://docs.microsoft.com/en-us/azure/azure-vmware/netapp-files-with-azure-vmware-solution["https://docs.microsoft.com/en-us/azure/azure-vmware/netapp-files-with-azure-vmware-solution"^]


