---
sidebar: sidebar 
permalink: ehc/azure/azure-avs.html 
keywords: NetApp Solutions, hyperscalers, azure, avs, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Azure AVS 向けのネットアップの機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
ネットアップが Azure VMware 解決策（ AVS ）に提供する機能の詳細をご確認ください。ネットアップがゲスト接続ストレージデバイスまたはネイティブデータストアとして提供する機能から、ワークフローの移行、クラウドへの拡張 / バースト対応、バックアップ / リストア、ディザスタリカバリに至るまで、さまざまなメリットがあります。

次のオプションから選択して、目的のコンテンツのセクションに移動します。

* link:#config["Azure で AVS を設定する"]
* link:#datastore["AVS 向けのネットアップストレージオプション"]
* link:#solutions["ネットアップとVMwareのクラウドソリューション"]




== Azure で AVS を設定する

オンプレミスと同様に、 VM と移行を作成する本番環境に適したクラウドベースの仮想化環境を計画することが重要です。

このセクションでは、 Azure VMware 解決策をセットアップおよび管理する方法と、ネットアップストレージの接続に使用できるオプションについて説明します。


NOTE: Azure NetApp Files と Cloud Volumes ONTAP を Azure VMware 解決策に接続する方法としてサポートされているのは、ゲスト内ストレージだけです。

セットアッププロセスは、次の手順に分けることができます。

* リソースプロバイダを登録し、プライベートクラウドを作成
* 新しい ExpressRoute 仮想ネットワークゲートウェイまたは既存の ExpressRoute 仮想ネットワークゲートウェイに接続します
* ネットワーク接続を検証し、プライベートクラウドにアクセス


詳細を表示します link:azure-setup.html["AVSの設定手順"]。



== AVS 向けのネットアップストレージオプション

ネットアップストレージは、 Azure AVS 内で数通りの方法で利用できます。接続されているか、ネイティブデータストアとして利用できます。

にアクセスしてください link:ehc-support-configs.html["サポートされているネットアップストレージオプション"] を参照してください。

Azure は、以下の構成でネットアップストレージをサポートします。

* ゲスト接続ストレージとしての Azure NetApp Files （ ANF
* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* ネイティブデータストアとしてのAzure NetApp Files （ANF）^1 ^


詳細を表示します link:azure-guest.html["AVSのゲスト接続ストレージオプション"]。


NOTE: 1 - AVSのネイティブデータストアとしてのANFは、現時点ではパブリックプレビュー版です。詳細はこちら https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?branch=main&tabs=azure-portal["こちらをご覧ください"]。



== 解決策のユースケース

ネットアップと VMware のクラウドソリューションを使用すれば、多くのユースケースを Azure AVS で簡単に導入できます。SEケースは、VMwareが定義したクラウド領域ごとに定義されます。

* 保護（ディザスタリカバリとバックアップ/リストアの両方を含む）
* 拡張
* 移動


link:azure-solutions.html["Azure AVS 向けネットアップソリューションをご覧ください"]
