---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-cloud-backup-tools.html 
keywords: deployment, backup tools, snapcenter server, Veeam server, 
summary: アプリケーションVMとデータベースボリュームをAWSで実行されているVMware Cloud Volumeサービスにフェイルオーバーするには、SnapCenter サーバとVeeam Backup and Replication Serverの両方の実行中のインスタンスをインストールして設定する必要がありました。フェイルオーバーが完了したら、オンプレミスのデータセンターへのフェイルバックが計画されて実行されるまで、これらのツールで通常のバックアップ処理を再開するようにも設定する必要があります。 
---
= Cloud Backupツール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-compute.html["前へ：コンピューティング。"]

アプリケーションVMとデータベースボリュームをAWSで実行されているVMware Cloud Volumeサービスにフェイルオーバーするには、SnapCenter サーバとVeeam Backup and Replication Serverの両方の実行中のインスタンスをインストールして設定する必要がありました。フェイルオーバーが完了したら、オンプレミスのデータセンターへのフェイルバックが計画されて実行されるまで、これらのツールで通常のバックアップ処理を再開するようにも設定する必要があります。



== バックアップツールの導入

SnapCenter サーバとVeeam Backup & Replicationサーバは、VMware Cloud SDDCにインストールするか、VPC内のEC2インスタンスにインストールしてVMware Cloud環境にネットワーク接続できます。



=== SnapCenter サーバ

SnapCenter ソフトウェアはネットアップサポートサイトから入手でき、ドメインまたはワークグループ内にあるMicrosoft Windowsシステムにインストールできます。詳細な計画ガイドとインストール手順については、を参照してください link:https://docs.netapp.com/us-en/snapcenter/install/install_workflow.html["ネットアップドキュメントセンター"^]。

SnapCenter ソフトウェアは、から入手できます https://mysupport.netapp.com["リンクをクリックしてください"^]。



=== Veeam Backup & Replicationサーバ

Veeam Backup & Replicationサーバは、AWS上のVMware CloudまたはEC2インスタンス上のWindowsサーバにインストールできます。実装の詳細なガイダンスについては、を参照してください https://www.veeam.com/documentation-guides-datasheets.html["Veeam Help Centerテクニカルドキュメント"^]。



== バックアップツールと設定

インストールが完了したら、SnapCenter とVeeam Backup & Replicationを設定し、AWS上のVMware Cloudにデータをリストアするために必要なタスクを実行する必要があります。



=== SnapCenter 構成

FSX ONTAP にミラーリングされたアプリケーション・データをリストアするには'まずオンプレミスのSnapCenter データベースのフル・リストアを実行する必要がありますこのプロセスが完了すると、VMとの通信が再確立され、プライマリストレージとしてFSX ONTAP を使用してアプリケーションのバックアップを再開できるようになります。

AWSに配置されているSnapCenter サーバで実行する手順の一覧については、セクションを参照してください link:aws-guest-dr-cloud-backup-config.html#deploy-secondary-windows-snapcenter-server["セカンダリWindows SnapCenter サーバを展開します"]。



=== Veeam Backup & Replicationの設定

Amazon S3ストレージにバックアップされた仮想マシンをリストアするには、WindowsサーバにVeeamサーバをインストールし、元のバックアップリポジトリが格納されたVMware Cloud、FSX ONTAP 、およびS3バケットと通信できるように設定する必要があります。また、リストアされたVMの新しいバックアップを実行するために、FSX ONTAP に新しいバックアップリポジトリが設定されている必要があります。

アプリケーションVMのフェイルオーバーを完了するために必要な手順については、を参照してください link:aws-guest-dr-cloud-backup-config.html#deploy-secondary-veeam-backup-&-replication-server["セカンダリVeeam Backup & Replication Serverを導入します"]。

link:aws-guest-dr-snapcenter-overview.html["次の手順：概要-災害復旧。"]
