---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-conclusion.html 
keywords: conclusion 
summary: このドキュメントで紹介するユースケースでは、ネットアップとVMwareの統合に特化した、実績のあるディザスタリカバリテクノロジに焦点を当てています。ネットアップのONTAP ストレージシステムは、実績あるデータミラーリングテクノロジを提供します。このテクノロジを使用すると、業界をリードするクラウドプロバイダのオンプレミステクノロジとONTAP テクノロジにまたがるディザスタリカバリソリューションを設計できます。 
---
= まとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-failback.html["前の手順：フェイルバック。"]

このドキュメントで紹介するユースケースでは、ネットアップとVMwareの統合に特化した、実績のあるディザスタリカバリテクノロジに焦点を当てています。ネットアップのONTAP ストレージシステムは、実績あるデータミラーリングテクノロジを提供します。このテクノロジを使用すると、業界をリードするクラウドプロバイダのオンプレミステクノロジとONTAP テクノロジにまたがるディザスタリカバリソリューションを設計できます。

ONTAP on AWSは、アプリケーションデータをクラウドにレプリケートするためにSnapCenter やSyncMirror とシームレスに統合できる解決策 の1つです。Veeam Backup & Replicationも、ネットアップのONTAP ストレージシステムと緊密に統合され、vSphereネイティブストレージへのフェイルオーバーを可能にする、よく知られたテクノロジです。

この解決策 では、SQL ServerとOracleアプリケーションデータをホストしているONTAP システムから、ゲスト接続ストレージを使用してディザスタリカバリ解決策 を提供しています。SnapCenter とSnapMirrorを使用すると、ONTAP システム上のアプリケーションボリュームを保護し、それらをクラウド上のFSXまたはCVOにレプリケートするための管理しやすい解決策 が提供されます。SnapCenter は、DR対応の解決策 で、すべてのアプリケーションデータをAWS上のVMware Cloudにフェイルオーバーします。



== 追加情報の参照先

このドキュメントに記載されている情報の詳細については、以下のドキュメントや Web サイトを参照してください。

* 解決策 のドキュメントへのリンク
+
https://docs.netapp.com/us-en/netapp-solutions/ehc/index.html["VMwareソリューションを使用したネットアップのハイブリッドマルチクラウド"]

+
https://docs.netapp.com/us-en/netapp-solutions/index.html["ネットアップのソリューション"]


