---
sidebar: sidebar 
permalink: vmware/migrate-vms-to-ec2-fsxn.html 
keywords: netapp, vmware, amazon, ec2, fsxn, migration, iscsi, 
summary: このテクニカルレポートでは、Cirrus Migrate Cloud（CMC）のMigrateOps「data-mobility-as-code」機能を使用して、データディスクがFSx for ONTAP iSCSI LUNに配置されたオンプレミスのVMware vSphere VMをAmazon EC2インスタンスに移行する方法について説明します。 
---
= FSxNを使用したAmazon EC2へのVMの移行：概要
:allow-uri-read: 




== FSxNを使用したAmazon EC2へのVMの移行：概要

[role="lead"]
組織は、Amazon Elastic Compute Cloud（Amazon EC2）インスタンスやAmazon FSx for NetApp ONTAP（FSx for ONTAP）などのサービスを活用して、AWS上のクラウドコンピューティングソリューションへの移行を加速し、ITインフラの最新化、コスト削減、運用効率の向上を実現しようとしています。これらのAWSサービスは、消費量ベースの価格モデル、エンタープライズストレージ機能を通じて総所有コスト（TCO）を最適化する移行を可能にし、グローバルなビジネスニーズの進化に対応する柔軟性と拡張性を提供します。



== 概要

VMware vSphereに多額の投資を行っている企業にとって、現在の市場状況を考えると、AWSへの移行は対費用効果の高い選択肢であり、またとない機会となります。

AWSに移行するにあたり、特にストレージに関しては、使い慣れた機能セットを維持しながら、クラウドの即応性とコストのメリットを活用したいと考えています。ワークロードの移行やディザスタリカバリソリューションの設定では、使い慣れたストレージプロトコル（特にiSCSI）のプロセス、ツール、スキルセットを使用してシームレスな運用を維持することが非常に重要です。

AWSマネージドストレージサービスFSx for ONTAPを使用してエンタープライズストレージ機能を維持すると同時に、オンプレミスのサードパーティベンダーストレージも利用できるため、システム停止を最小限に抑え、将来の投資を最大限に活用しながら、AWSのパワーを最大限に引き出すことができます。

このテクニカルレポートでは、Cirrus Migrate Cloud（CMC）のMigrateOps「data-mobility-as-code」機能を使用して、データディスクがFSx for ONTAP iSCSI LUNに配置されたオンプレミスのVMware vSphere VMをAmazon EC2インスタンスに移行する方法について説明します。



== 解決策の要件

VMwareのお客様が現在解決しようとしている課題は多数あります。このような組織は、

. シンプロビジョニング、Storage Efficiencyテクノロジ、ゼロフットプリントのクローン、統合バックアップ、ブロックレベルのレプリケーション、 階層化：これにより、移行作業を最適化し、初日からAWSへの将来を見据えた導入を実現できます。
. FSx for ONTAPとそれが提供するコスト最適化機能を組み込むことで、Amazon EC2インスタンスを使用するAWS上の現在のストレージ環境を最適化します。
. 必要なIOPSとスループットのパラメータを満たすようにAmazon EC2インスタンスのサイズを適正化することで、ブロックストレージソリューションでAmazon EC2インスタンスを使用する場合の総所有コスト（TCO）を削減します。ブロックストレージでAmazon EC2のディスク処理には、帯域幅とI/O速度に制限があります。FSx for ONTAPを使用するファイルストレージでは、ネットワーク帯域幅を使用します。つまり、FSx for ONTAPにはVMレベルのI/Oの制限はありません。




== 技術コンポーネントの概要



=== FSx for ONTAPの概念

Amazon FSx for NetApp ONTAPは、NetApp®ONTAP®ファイルシステムに、AWS上で使い慣れたONTAPのデータ管理機能、パフォーマンス、APIをすべて備えたフルマネージドのAWSストレージサービスです。ハイパフォーマンスストレージは複数のプロトコル（NFS、SMB、iSCSI）をサポートし、Windows、Linux、macOS EC2インスタンスを使用してワークロードに単一のサービスを提供します。

FSx for ONTAPはONTAPファイルシステムであるため、SnapMirror®データレプリケーションテクノロジ、シンクローン、NetApp Snapshot™コピーなど、使い慣れたNetAppの多くの機能やサービスを利用できます。データ階層化を通じて低コストの大容量階層を活用することで、FSx for ONTAPの柔軟性が高まり、ほぼ無制限の拡張が可能になります。さらに、独自のNetApp Storage Efficiencyテクノロジにより、AWS上のストレージコストをさらに削減できます。詳細については、 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Amazon FSx for ONTAPの利用を開始する"]。



==== File System の略

FSx for ONTAPの中心的なリソースは、ソリッドステートドライブ（SSD）ストレージを基盤とするファイルシステムです。FSx for ONTAPファイルシステムをプロビジョニングする際、ユーザは必要なスループットとストレージ容量を入力し、ファイルシステムを配置するAmazon VPCを選択します。

また、ファイルシステムに組み込まれている2つの高可用性導入モデル（Multi-Availability Zone（AZ；マルチアベイラビリティゾーン）とシングルAZのどちらか）を選択できます。これらのオプションにはそれぞれ独自の耐久性と可用性があり、ユースケースのビジネス継続性要件に応じて選択できます。マルチAZ環境は、2つのAZ間でシームレスにレプリケートされるデュアルノードで構成されています。コストが最適化されたシングルAZ展開オプションを使用すると、ファイルシステムが2つのノードに分割され、2つの異なるフォールトドメインが1つのAZ内に存在するように構成されます。
Storage Virtual Machine
FSx for ONTAPファイルシステムのデータには、Storage Virtual Machine（SVM）と呼ばれる論理ストレージパーティションを介してアクセスされます。SVMは、データアクセスポイントと管理アクセスポイントを備えた独自のファイルサーバです。FSx for ONTAPファイルシステムでiSCSI LUNにアクセスする場合、Amazon EC2インスタンスはSVMのiSCSIエンドポイントのIPアドレスを使用してSVMと直接インターフェイスします。

クラスタ内に1つのSVMを維持できますが、1つのクラスタで複数のSVMを実行するオプションには、さまざまな用途とメリットがあります。お客様は、ワークロード分離の要件など、ビジネスニーズを考慮して、構成に最適なSVM数を決定できます。



==== 個のボリューム

FSx for ONTAP SVM内のデータは、仮想コンテナとして機能するボリュームと呼ばれる構造に格納され、編成されます。個 々 のボリュームは、単一または複数のLUNで構成できます。各ボリュームに格納されているデータは、ファイルシステムのストレージ容量を消費します。ただし、FSx for ONTAPではボリュームがシンプロビジョニングされるため、ボリュームがストレージ容量を消費するのは格納されているデータの量だけです。



=== Cirrus Migrate Cloud MigrateOpsの概念

CMCは、Cirrus Data Solutions, Inc.が提供するトランザクション可能なソフトウェアサービス（SaaS）であり、AWS Marketplaceから入手できます。MigrateOpsはCMCのData-Mobility-as-Code自動化機能で、YAMLのシンプルな操作構成を使用して大規模なデータ移動操作を宣言的に管理できます。MigrateOps設定は、データ移動タスクの実行方法を決定します。MigrateOpsの詳細については、を参照してください。 link:https://www.google.com/url?q=https://customer.cirrusdata.com/cdc/kb/articles/about-migrateops-hCCHcmhfbj&sa=D&source=docs&ust=1715480377722215&usg=AOvVaw033gzvuAlgxAWDT_kOYLg1["MigrateOpsについて"]。

MigrateOpsは、プロセス全体の合理化を目的とした自動化ファーストアプローチを採用し、運用を中断することなくクラウド規模のエンタープライズデータモビリティを実現します。CMCが自動化のために提供する機能豊富な機能に加えて、MigrateOpsはさらに、外部で管理される次のような他の自動化を追加します。

* OSノシユウフク
* アプリケーションのカットオーバーと承認のスケジュール設定
* ダウンタイムゼロのクラスタ移行
* パブリック/プライベートクラウドプラットフォームの統合
* 仮想化プラットフォームの統合
* エンタープライズストレージ管理の統合
* SAN（iSCSI）構成


上記のタスクは完全に自動化されており、オンプレミスのソースVMの準備（AWSのエージェントやツールの追加など）、デスティネーションFSx LUNの作成、AWSデスティネーションインスタンスでのiSCSIとマルチパス/ MPIOのセットアップなど、面倒な手順がすべて自動化されています。 また、YAMLファイルでパラメータを指定するだけで、アプリケーションサービスを停止/開始するすべてのタスクが排除されます。

FSx for ONTAPを使用すると、データLUNを提供してAmazon EC2インスタンスタイプを適切にサイジングできると同時に、これまで組織がオンプレミス環境で使用していたすべての機能を利用できます。CMCのMigrateOps機能を使用して、マッピングされたiSCSI LUNのプロビジョニングなど、関連するすべての手順を自動化し、予測可能な宣言的な操作にします。

*注*：CMCでは、ストレージソースストレージからFSx for ONTAPへのデータ転送を安全に行うために、ソースとデスティネーションの仮想マシンインスタンスに非常にシンエージェントをインストールする必要があります。



== EC2インスタンスでAmazon FSx for NetApp ONTAPを使用するメリット

Amazon EC2インスタンス向けFSx for ONTAPストレージには、次のようなメリットがあります。

* 非常に要件の厳しいワークロードに一貫した高パフォーマンスを提供する、高スループットと低レイテンシのストレージ
* インテリジェントなNVMeキャッシングでパフォーマンスを向上
* 容量、スループット、IOPSを調整可能。オンザフライで変更し、変化するストレージニーズにすばやく対応
* オンプレミスのONTAPストレージからAWSへのブロックベースのデータレプリケーション
* マルチプロトコルのアクセス性（オンプレミスのVMware環境で広く使用されているiSCSIなど）
* NetApp Snapshot™テクノロジとSnapMirrorによるDRオーケストレーションにより、データ損失を防ぎ、リカバリを高速化
* シンプロビジョニング、データ重複排除、圧縮、コンパクションなど、ストレージの設置面積とコストを削減するStorage Efficiency機能
* 効率的なレプリケーションにより、バックアップ作成にかかる時間が数時間からわずか数分に短縮され、RTOが最適化されます。
* NetApp SnapCenter®を使用したファイルのバックアップとリストアのきめ細かなオプション


Amazon EC2インスタンスとFSx ONTAPをiSCSIベースのストレージレイヤとして導入することで、ハイパフォーマンスでミッションクリティカルなデータ管理機能が実現し、コスト削減につながるStorage Efficiency機能がAWSへの導入を変革します。

Flash Cacheを実行し、複数のiSCSIセッションを実行し、ワーキングセットサイズ5%を活用するFSx for ONTAPでは約350、000 IOPSを実現し、最も負荷の高いワークロードにも対応できるパフォーマンスレベルを実現できます。

FSx for ONTAPにはネットワーク帯域幅の制限のみが適用され、ブロックストレージの帯域幅の制限は適用されないため、小規模なAmazon EC2インスタンスタイプを活用しながら、はるかに大規模なインスタンスタイプと同じパフォーマンスレートを実現できます。このような小規模なインスタンスタイプを使用すると、コンピューティングコストも低く抑えられ、TCOが最適化されます。

FSx for ONTAPで複数のプロトコルを処理できるというメリットもあります。1つのAWSストレージサービスを標準化して、既存のデータサービスとファイルサービスのさまざまな要件に対応できるというメリットもあります。
VMware vSphereに多額の投資を行っている企業にとって、現在の市場状況を考えると、AWSへの移行は対費用効果の高い選択肢であり、またとない機会となります。
