---
sidebar: sidebar 
permalink: vmware/vmw-vcf-protect-vmsc.html 
keywords: vmware, vcf, protect, vmsc, vsphere, metro, storage, cluster 
summary:  
---
= VMware vSphere Metro Storage Cluster（vMSC）による高可用性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware vSphere Metro Storage Cluster（vMSC）と統合されたNetApp ONTAP高可用性ソリューションは、VMware Cloud Foundation（VCF）の管理とVIワークロードドメインに堅牢なソリューションを提供します。

この組み合わせにより、地理的に分散したサイト全体で、継続的なデータ可用性、シームレスなフェイルオーバー、ディザスタリカバリが実現し、重要なワークロードの耐障害性と運用継続性が強化されます。SnapMirror Active Sync：サイト全体で障害が発生してもビジネスサービスの運用を継続できるため、アプリケーションをセカンダリコピーを使用して透過的にフェイルオーバーできます。SnapMirrorアクティブ同期でフェイルオーバーをトリガーするための手動操作やカスタムスクリプトは必要ありません。

詳細については、以下のソリューションを参照してください。

* link:vmw-vcf-vmsc-mgmt-smas.html["SnapMirrorアクティブ同期を使用した管理ドメイン用のストレッチクラスタ"]
* link:vmw-vcf-vmsc-mgmt-mcc.html["MetroClusterを使用した管理ドメイン用のストレッチクラスタ"]
* link:vmw-vcf-vmsc-viwld-smas.html["SnapMirrorアクティブ同期を使用したVIワークロードドメイン用のストレッチクラスタ"]
* link:vmw-vcf-vmsc-viwld-mcc.html["MetroClusterを使用したVIワークロードドメイン用のストレッチクラスタ"]

