---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-data-infrastructure-insights.html 
keywords: vmware, getting, started, overview, netapp, data, infrastructure, insights, dii 
summary:  
---
= Data Infrastructure Insights（DII）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Data Infrastructure Insightsは、インフラ全体を可視化できるクラウドインフラ監視ツールです。



== はじめに

Data Infrastructure Insightsを使用すると、パブリッククラウドやプライベートデータセンターを含む、すべてのリソースの監視、トラブルシューティング、最適化を実行できます。

Data Infrastructure Insightsの詳細については、を参照してくださいlink:https://docs.netapp.com/us-en/data-infrastructure-insights/index.html["Data Infrastructure Insightsドキュメント"]。



== データインフラの分析機能

* Data Infrastructure Insightsは、ハイブリッドマルチクラウドを監視し、インフラとワークロードのフルスタックのオブザーバビリティを提供します。
* Kubernetesを含む、異機種混在インフラとワークロード向けのデータコレクタ
* オープンなTelegrafコレクターとオープンAPIにより、統合が容易になります
* 包括的なアラートと通知
* インテリジェントなインサイトを得るための機械学習
* リソース利用率を最適化
* 高度なフィルタを備えた組み込みまたはカスタマイズ可能なダッシュボードにより、回答 の質問に対する表示ノイズを最小限に抑えることができます
* ONTAP ストレージの運用状態を検出できます 
* 最も重要なビジネス資産であるランサムウェア攻撃やデータ破壊攻撃からデータを保護

