---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-vm-data-collector.html 
keywords: vmware, getting, started, overview, netapp, vm, data, collector, vmdc 
summary:  
---
= VMデータコレクタ（VMDC）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
サイズを適正化し、最適化の可能性を予測するうえで重要な要素は、VMware環境の現在の状態を把握することです。



== はじめに

Virtual Machine Data Collector（VMDC）は、VMware環境向けの軽量でシンプルなGUIベースの無償ツールキットです。ユーザは、仮想マシン（VM）、ホスト、ストレージ、およびネットワークに関する詳細なインベントリ情報を収集できます。

Virtual Machine Data Collectorの詳細については、を参照してくださいlink:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmdc.html["Virtual Machine Data Collectorのマニュアル"]。



== VMDCの機能

VMDCは、VMwareコアライセンスとvCPUおよびRAMの最適化の可能性を予測するための統計を迅速かつ瞬時に収集するための足がかりにすぎません。AUSとデータコレクタのインストールが必要なNetAppデータインフラインサイトは、VMの詳細なトポロジを理解し、ワークロードのサイズを適正化し、将来のニーズにも対応できるように、アノテーションを使用したVMのグループ化を理解するための次のステップです。

VMDCで収集されたメトリックのサンプリング：

* VM情報
+
** VM name
** VMの電源状態
** VM CPU情報
** VMメモリ情報
** VMの場所
** VMネットワーク情報
** その他


* VMパフォーマンス
+
** 選択した間隔のVMのパフォーマンスデータ
** VM読み取り/書き込み情報
** VMのIOPS情報
** VMのレイテンシ
** その他


* ESXiホストノシヨウホウ
+
** ホストデータセンター情報
** ホストクラスタノシヨウホウ
** ホストモデル情報
** ホストCPU情報
** ホストメモリ情報
** その他



