---
sidebar: sidebar 
permalink: vmware/vmw-vcf-expand.html 
keywords: vmware, vcf, expand, supplemental, storage 
summary:  
---
= 補完的ストレージでVCF環境を拡張
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Cloud Foundation（VCF）は、VCF管理ドメインとVIワークロードドメイン上のストレージを拡張するための幅広い追加ストレージオプションをサポートしています。

NetAppのONTAP Tools for VMware vSphereは、NetAppストレージをVCF環境にシームレスに統合することで、この拡張のための効率的なソリューションを提供します。ONTAPツールを使用すると、データストアのセットアップと管理が簡易化され、管理者はvSphere Clientから直接ストレージのプロビジョニングと管理を行うことができます。スナップショット、クローニング、データ保護などのONTAPの高度な機能により、VCF環境内のストレージのパフォーマンス、効率性、拡張性が向上します。

VCF環境を拡張するための技術的な詳細については、以下のソリューションを参照してください。

* link:vmw-vcf-mgmt-supplemental-iscsi.html["iSCSIによる管理ドメイン"]
* link:vmw-vcf-mgmt-supplemental-fc.html["FCを使用する管理ドメイン"]
* link:vmw-vcf-viwld-supplemental-vvols.html["VVOLを使用する仮想インフラワークロードドメイン（iSCSI）"]
* link:vmw-vcf-viwld-supplemental-nfs-vvols.html["VVOL（NFS）を使用する仮想インフラワークロードドメイン"]
* link:vmw-vcf-viwld-supplemental-nvme.html["NVMe/TCPを使用した仮想インフラワークロードドメイン"]
* link:vmw-vcf-viwld-supplemental-fc.html["FCを使用する仮想インフラストラクチャワークロードドメイン"]

