---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-hybrid-multicloud.html 
keywords: vmware, getting, started, overview, netapp, hybrid, multicloud, multi, cloud 
summary:  
---
= ハイブリッドマルチクラウド
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetAppを使用したVMwareハイブリッドマルチクラウドアーキテクチャは、オンプレミスのインフラとパブリッククラウドサービスをシームレスに統合し、柔軟性と拡張性を提供します。



== はじめに

このアプローチにより、企業はワークロードを簡単に移行し、リソース使用率を最適化し、両方の環境で一貫した運用を維持できます。

VMwareとNetAppを使用したハイブリッドクラウドのシナリオの詳細については、を参照してくださいlink:https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-overview.html#vmware-cloud-options-in-public-cloud["VMwareを使用したネットアップのハイブリッドマルチクラウドの概要"]。



== NetAppを使用したVMwareの導入シナリオ

このセクションでは、オンプレミスとパブリッククラウドにわたるVMware環境のさまざまな導入オプションについて説明します。各クラウドプロバイダは、それぞれのパブリッククラウドサービス内で、VMware Software Defined Data Center（SDDC）やVMware Cloud Foundation（VCF）スタックをサポートしています。

* *オンプレミスのVMware *


VMwareとオンプレミスのNetAppストレージを併用することで、堅牢で拡張性と柔軟性に優れた仮想化環境が実現します。重複排除、圧縮、効率的なSnapshotなどのNetAppの高度なデータ管理機能と、ONTAPを搭載した適切なストレージシステムを組み合わせることで、お客様は自社に適したプラットフォームを選択できます。この組み合わせにより、仮想化されたワークロードの高いパフォーマンス、信頼性、シンプルな管理が実現し、データセンター全体の効率が向上します。

* * Azure VMwareソリューション*


Azure VMware 解決策は、 Microsoft Azure パブリッククラウド内で VMware データセンターを完全に機能させるハイブリッドクラウドサービスです。Azure VMware 解決策は、 Microsoft がフルマネージドでサポートし、 VMware が Azure インフラを活用して検証した、ファーストパーティ製解決策です。つまり、 Azure VMware 解決策を導入すると、お客様のコンピューティング仮想化向けに VMware の ESXi を、ハイパーコンバージドストレージ用に vSAN を、 さらに NSX は、ネットワークとセキュリティを実現するだけでなく、 Microsoft Azure のグローバルプレゼンス、クラスをリードするデータセンター施設を活用し、ネイティブの Azure サービスとソリューションの豊富なエコシステムに近接しています。

* * VMware Cloud on AWS *


VMware Cloud on AWS は、 VMware のエンタープライズクラスの SDDC ソフトウェアを AWS クラウドに提供し、ネイティブ AWS サービスへのアクセスを最適化します。VMware Cloud Foundation を基盤とする VMware Cloud on AWS は、 VMware のコンピューティング、ストレージ、ネットワーク仮想化製品（ VMware vSphere 、 VMware vSAN 、 VMware NSX ）と VMware vCenter Server の管理を統合し、専用の柔軟性の高いベアメタル AWS インフラストラクチャ上で実行できるように最適化されています。

* * Google Cloud VMware Engine *


Google Cloud VMware Engineは、Google Cloudのハイパフォーマンスな拡張性に優れたインフラとVMware Cloud Foundationスタック（VMware vSphere、vCenter、vSAN、NSX-T）上に構築されたインフラサービス（IaaS）です。このサービスにより、クラウドへの迅速な移行が可能になり、既存のVMwareワークロードをオンプレミス環境からGoogle Cloud Platformにシームレスに移行または拡張できます。VMware と緊密に連携して Google が販売およびサポートするサービスです。
