---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-security-ransomware.html 
keywords:  
summary:  
---
= VMwareワークロードのセキュリティとランサムウェアに対応
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ビジネスの継続的な運用を維持し、重要なアプリケーションの高可用性を確保し、データ損失から保護するためには、VMware環境内でシステム停止のリスクを軽減することが重要です。



== はじめに

NetApp ONTAPの高度な機能をVMware環境で活用することで、組織はデータの整合性、可用性、セキュリティを確保できます。

これらのテクノロジーがどのように連携して*セキュリティー*と*バックアップの利点*を提供するかについては、以下を参照してください。



== セキュリティとランサムウェア

セキュリティは仮想化環境における最重要課題であり、NetApp ONTAPは、VMwareインフラストラクチャ内のセキュリティを強化する堅牢な機能を提供します。ONTAPは保存中および転送中のデータを暗号化し、機密情報を不正アクセスから保護します。暗号化キーはセキュアに管理され、ONTAPはソフトウェアベースとハードウェアベースの両方の暗号化ソリューションをサポートしています。ONTAPは、vSphereの組み込みセキュリティ機能やサードパーティのセキュリティソリューションなど、VMwareのセキュリティツールと統合することで、安全でコンプライアンスに準拠した環境の構築を支援します。



== ランサムウェア対策

ランサムウェア攻撃は組織にとって重大な脅威であり、VMwareとONTAPの組み合わせは強力な防御メカニズムを提供します。ONTAPのSnapshotテクノロジを使用すると、ランサムウェアによる変更や削除ができない変更不可のSnapshotを作成できます。攻撃が発生した場合、これらのスナップショットを使用して、影響を受けるVMとデータストアを攻撃前の状態に迅速にリストアし、ダウンタイムとデータ損失を最小限に抑えることができます。さらに、ONTAPのセキュリティ情報およびイベント管理(SIEM)システムとの統合により、疑わしいアクティビティのプロアクティブな監視とアラートが可能になります。ONTAPでは、多要素認証（MFA）とロールベースアクセス制御（RBAC）もサポートしているため、セキュリティがさらに強化されます。



== ランサムウェアリカバリ保証

NetAppランサムウェア保証は、ランサムウェア攻撃から保護するための堅牢で信頼性の高いソリューションを組織に提供します。NetApp ONTAPの高度な機能を活用することで、組織はデータのセキュリティと可用性を確保できます。ランサムウェア攻撃が発生した場合、データを迅速かつ効果的にリストアし、ダウンタイム、データ損失、財務への影響を最小限に抑えることができるため、安心感が得られます。データセキュリティと耐障害性に対するこの取り組みにより、NetAppは、進化するサイバー脅威から重要な資産を保護したい組織にとって理想的なパートナーになります。



== 高度なセキュリティ機能

ONTAPには、マルチテナント環境でデータとリソースを分離するセキュアマルチテナンシーや、機密データへのアクセスを追跡してログに記録するコンプライアンス監査などの高度なセキュリティ機能が搭載されています。これらの機能により、データの安全性が確保され、組織は業界の規制や標準へのコンプライアンスを実証できます。



== 概要

ONTAPのセキュリティ機能（暗号化、変更不可のスナップショット、高度なアクセス制御など）とVMwareのツールを統合することで、ランサムウェアなどのサイバー脅威に対する堅牢な防御が可能になります。ONTAPでは、セキュアマルチテナンシーとコンプライアンス監査をサポートしているため、データ保護とコンプライアンスを確保できます。

NetApp ONTAPとVMwareは、仮想化環境を保護するための包括的なソリューションを提供し、組織がデータを保護し、ダウンタイムを最小限に抑え、ビジネス継続性を維持できるようにします。これらのテクノロジを実装することで、企業は最新のIT課題に対処し、進化するセキュリティ脅威から重要な資産を保護できます。
