---
sidebar: sidebar 
permalink: vmware/vmware_vcf_asa_prin_fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= FC上のVMFSをVCFプリンシパルデータストアとして使用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このシナリオでは、管理ドメインとワークロードドメイン用に、ファイバチャネル（FC）バックエンドを使用してVMFSデータストアを導入する方法を説明します。

作成者：Suresh Thoppay



== シナリオの概要

VCFプリンシパルストレージとは、VCFドメインセットアッププロセスの一部として導入、変換、またはインポートされるあらゆるタイプのストレージを指します。このドキュメントでは、次のシナリオについて説明します。

[cols="20% 20% 20% 20% 20%"]
|===
| ストレージ タイプ | 管理ドメイン-デフォルトクラスタ | 管理ドメイン-追加クラスタ | VIワークロードドメイン-デフォルトクラスタ | VIワークロードドメイン-追加クラスタ 


| FC上のVMFS | *インポートツール* | *インポートツール、SDDC API * | はい | はい 
|===


== 前提条件

このシナリオでは、次のコンポーネントと構成が必要です。

* FCポートがFCスイッチに接続されたONTAPストレージシステム。
* SVMをFC LIFで作成
* FC HBAをFCスイッチに接続したvSphere
* 単一のイニシエータとターゲットのゾーニングがFCスイッチに設定されます。
+

NOTE: ONTAPシステムの物理FCポートではなく、ゾーン構成でSVM FC論理インターフェイスを使用してください。



NetAppではFC LUNにマルチパスを推奨しています。



== 導入手順



=== 管理ドメイン-デフォルトクラスタ

初期クラスタのFCプリンシパルストレージは、VCFブラウンフィールドインポートツールでのみサポートされます。VCFがCloudbuilderツールを使用して導入されている場合（バージョン5.2.xまで）、VSANのみがサポートされます。詳細については、を参照してください https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["既存のvSphere環境から管理ドメインへの変換"]。



=== 管理ドメイン-追加クラスタ

管理ドメイン上の追加のvSphereクラスタは、次のオプションを使用して導入できます。* vSphere環境に追加のクラスタがあり、VCFブラウンフィールドインポートツールを使用してvSphere環境を管理ドメインに変換します。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["VMware vSphere向けONTAPツール"]を https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System ManagerまたはONTAP API"]使用して、VMFSデータストアをvSphereクラスタに導入できます。* SDDC APIを使用して、追加のクラスタを導入します。vSphereホストにVMFSデータストアが設定されている必要があります。vSphereホストにLUNを導入するために使用し https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System ManagerまたはONTAP API"]ます。* SDDC Manager UIを使用して、追加のクラスタを導入します。ただし、このオプションで作成されるのは、バージョン5.2.xまでのVSANデータストアのみです。



=== VIワークロードドメイン-デフォルトクラスタ

管理ドメインを起動して実行したら、SDDC Manager UIを使用してVI Workloadドメインを作成できます*。vSphereホストにVMFSデータストアが設定されている必要があります。System ManagerまたはONTAP APIを使用して、vSphereホストにLUNを導入します。*既存のvSphere環境を新しいVIワークロードドメインとしてインポートします。ONTAP Tools for VMware vSphere、System Manager、またはONTAP APIを使用して、VMFSデータストアをvSphereクラスタに導入できます。



=== VIワークロードドメイン-追加クラスタ

VIワークロードの運用が開始されたら、次のオプションを使用して、VMFSとともに追加のクラスタをFC LUNに導入できます。

* VCFブラウンフィールドインポートツールを使用してインポートされたvSphere環境の追加のクラスタ。ONTAP Tools for VMware vSphere、System Manager、またはONTAP APIを使用して、VMFSデータストアをvSphereクラスタに導入できます。
* SDDC ManagerのUIまたはAPIを使用して追加のクラスタを導入する。vSphereホストにVMFSデータストアが設定されている必要があります。System ManagerまたはONTAP APIを使用して、vSphereホストにLUNを導入します。




== 追加情報

ONTAPストレージシステムの構成については、センターを参照してlink:https://docs.netapp.com/us-en/ontap["ONTAP 9ドキュメント"]ください。

VCFの設定については、を参照してくださいlink:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware Cloud Foundationのドキュメント"]。
