---
sidebar: sidebar 
permalink: vmware/vmware-scv-overview.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= SnapCenter Plug-in for VMware vSphere
:allow-uri-read: 




== SnapCenter Plug-in for VMware vSphere

[role="lead"]
SnapCenter Plug-in for VMware vSphereは、仮想マシン（VM）、データストア、VMDKに対して、VMと整合性のあるバックアップおよびリストア処理を迅速かつ効率的に実行します。SnapCenter Serverと連携して動作するため、SnapCenterのアプリケーション固有のプラグインに対してアプリケーションベースのバックアップおよびリストア機能を有効にすることができます。



=== ドキュメントに関するリソース

詳細については、次のドキュメントリソースを参照してください。

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["SnapCenter Plug-in for VMware vSphere のドキュメント"]




=== 解決策のリソース

SnapCenter Plug-in for VMware vSphereとBlueXP VMのバックアップとリカバリを搭載した次の3-2-1バックアップ解決策を参照してください。

テクニカルレポート： link:../ehc/bxp-scv-hybrid-solution.html["3-2-1 SnapCenterプラグインとBlueXPによるVMのバックアップとリカバリによるVMwareのデータ保護"]

Tech OnTapブログ： link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180["3-2-1 SnapCenterプラグインとBlueXPによるVMのバックアップとリカバリによるVMwareのデータ保護"]



=== ビデオリソース

.VMware vSphere 解決策 用の SnapCenter プラグインの前提条件
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto]
.SnapCenter Plug-in for VMware vSphere - 導入
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto]
.SnapCenter Plug-in for VMware vSphere - バックアップワークフロー
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto]
.SnapCenter Plug-in for VMware vSphere - リストアワークフロー
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto]
.SnapCenter - SQL リストアワークフロー
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto]