---
sidebar: sidebar 
permalink: ai/a400-thinksystem-conclusion.html 
keywords: acknowledgements, additional information 
summary: このネットアップとLenovo解決策 は柔軟なスケールアウトアーキテクチャであり、ミッドレベルのエンタープライズAIへのエントリに最適です。ネットアップのストレージは、ローカルのSSDストレージと同等以上のパフォーマンスを提供し、データサイエンティスト、データエンジニア、IT意思決定者に次のようなメリットをもたらします。 
---
= まとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ネットアップとLenovo解決策 は、柔軟性に優れたスケールアウトアーキテクチャを採用しており、ミッドレベルのエンタープライズAI導入に最適です。

ネットアップのストレージは、ローカルのSSDストレージと同等以上のパフォーマンスを提供し、データサイエンティスト、データエンジニア、IT意思決定者に次のようなメリットをもたらします。

* AI システム、分析などの重要なビジネスシステム間でデータを容易に共有できます。このようなデータ共有により、インフラのオーバーヘッドを削減し、パフォーマンスを向上させ、企業全体のデータ管理を合理化できます。
* 個別に拡張可能なコンピューティングとストレージにより、コストを最小限に抑え、リソースの使用率を向上させます。
* 統合されたSnapshotとクローンを使用して開発と導入のワークフローを合理化し、ユーザのワークスペースを瞬時にスペース効率よく利用できるようにし、バージョン管理を統合し、導入を自動化します。
* ディザスタリカバリとビジネス継続性を実現するエンタープライズクラスのデータ保護




== 謝辞

* ネットアップテクニカルマーケティングエンジニアKarthikeyan Nagalingam氏
* Lenovo、AIラボシステム、管理者Jarrett Upton氏




== 詳細情報の入手方法

このドキュメントに記載されている情報の詳細については、以下のドキュメントや Web サイトを参照してください。

* NetApp All Flash Arraysの製品ページです
+
https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx["https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx"^]

* NetApp AFF A400のページです
+
https://docs.netapp.com/us-en/ontap-systems/a400/index.html["https://docs.netapp.com/us-en/ontap-systems/a400/index.html"]

* NetApp ONTAP データ管理ソフトウェアの製品紹介ページ
+
http://www.netapp.com/us/products/data-management-software/ontap.aspx["http://www.netapp.com/us/products/data-management-software/ontap.aspx"^]

* MLPerf
+
https://mlperf.org/["https://mlperf.org"^]

* TensorFlow ベンチマーク
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* NVIDIA SMI（NVIDIA - SMI）
+
https://developer.nvidia.com/nvidia-system-management-interface["https://developer.nvidia.com/nvidia-system-management-interface"]


