---
sidebar: sidebar 
permalink: ai/ai-edge-architecture-sizing-options.html 
keywords: architecture, sizing, computer server, shared storage 
summary: 検証に使用する設定は、他のユースケースに合わせて調整できます。 
---
= アーキテクチャのサイジングオプション
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
検証に使用する設定は、他のユースケースに合わせて調整できます。



== コンピューティングサーバ

SE350 でサポートされている最小レベルの CPU である Intel Xeon D-2123IT CPU を使用し、 4 つの物理コアと 60W TDP を使用しました。サーバは CPU の交換をサポートしていませんが、より強力な CPU で発注することもできます。サポートされている CPU の上位は、 16 コアを搭載した Intel Xeon D-2183IT 、 2.20GHz で動作する 100W です。これにより、 CPU の計算能力が大幅に向上します。CPU は推論ワークロード自体を実行するためのボトルネックではありませんでしたが、データ処理や推論に関連するその他のタスクに役立ちます。現時点では、 NVIDIA T4 がエッジで唯一の GPU です。そのため、 GPU のアップグレードやダウングレードは行えません。



== 共有ストレージ

テストと検証には、ストレージ容量が最大 50.5TB の NetApp AFF C190 システムが使用されています。シーケンシャルリードの場合は 4.4GBps のスループット、スモールランダムリードの場合は 230K の IOPS が、このドキュメントではエッジ推論ワークロードに適していることが実証されています。

ただし、ストレージ容量の拡張やネットワーク速度の高速化が必要な場合は、NetApp AFF A220またはNetApp AFF A250ストレージシステムを使用する必要があります。また、最大容量が 1.5PB の NetApp EF280 システムでは、この解決策検証に、帯域幅も 10Gbps 使用しました。より多くのストレージ容量と帯域幅を必要とする場合は、を https://www.netapp.com/pdf.html?item=/media/19339-DS-4082.pdf&v=2021691654["NetApp EF300"^] 使用できます。
