---
sidebar: sidebar 
permalink: ai/ai-edge-conclusion.html 
keywords: acknowledgements, version history, additional information 
summary: AI 主導の自動化とエッジコンピューティングは、ビジネス組織がデジタル変革を実現し、運用効率と安全性を最大限に高めるための、業界をリードするアプローチです。エッジコンピューティングでは、データセンターとの間を移動する必要がないため、データの処理速度が大幅に向上します。そのため、データセンターやクラウドへのデータの送受信に関連するコストが削減されます。 
---
= まとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-edge-architecture-sizing-options.html["前のバージョン：アーキテクチャのサイジングオプション"]

[role="lead"]
AI 主導の自動化とエッジコンピューティングは、ビジネス組織がデジタル変革を実現し、運用効率と安全性を最大限に高めるための、業界をリードするアプローチです。エッジコンピューティングでは、データセンターとの間を移動する必要がないため、データの処理速度が大幅に向上します。そのため、データセンターやクラウドへのデータの送受信に関連するコストが削減されます。エッジに導入された AI 推論モデルを使用してほぼリアルタイムで意思決定を行う必要がある場合は、レイテンシの低減とスピードの向上が効果的です。

ネットアップのストレージシステムは、ローカル SSD ストレージと同等以上のパフォーマンスを発揮し、データサイエンティスト、データエンジニア、 AI / ML 開発者、ビジネスや IT の意思決定者に次のようなメリットをもたらします。

* AI システム、分析などの重要なビジネスシステム間でデータを容易に共有できます。このようなデータ共有により、インフラのオーバーヘッドを削減し、パフォーマンスを向上させ、企業全体のデータ管理を合理化できます。
* 個別に拡張可能なコンピューティングとストレージにより、コストを最小限に抑え、リソース使用率を向上させます。
* 統合された Snapshot コピーとクローンを使用して開発と導入のワークフローを合理化し、ユーザのワークスペースを瞬時にスペース効率よく利用できるほか、バージョン管理機能も統合され、導入も自動化されています。
* ディザスタリカバリとビジネス継続性を実現するエンタープライズクラスのデータ保護本ドキュメントで紹介するネットアップと Lenovo の解決策は、柔軟性に優れたスケールアウトアーキテクチャを備えており、エッジでのエンタープライズクラスの AI 推論導入に最適です。




== 謝辞

* J. J. J.Falkanger 、 Sr.Lenovo 、 HPC & AI ソリューション担当マネージャー
* ネットアップ、テクニカルマーケティングエンジニア、 Dave Arnette 氏
* Joey Parnell 、 Tech Lead E シリーズ AI Solutions 、ネットアップ
* ネットアップ、 QA エンジニア、 Cody Harryman 氏




== 追加情報の参照先

このドキュメントに記載されている情報の詳細については、以下のドキュメントや Web サイトを参照してください。

* NetApp AFF A シリーズアレイの製品ページ
+
https://www.netapp.com/data-storage/aff-a-series/["https://www.netapp.com/data-storage/aff-a-series/"^]

* NetApp ONTAP データ管理ソフトウェア— ONTAP 9 情報ライブラリ
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* TR-4727 ：『 NetApp EF Series Introduction 』
+
https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf"^]

* NetApp E シリーズ SANtricity ソフトウェアのデータシート
+
https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf["https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf"^]

* コンテナ向け NetApp 永続的ストレージ— NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* MLPerf
+
** https://mlcommons.org/en/["https://mlcommons.org/en/"^]
** http://www.image-net.org/["http://www.image-net.org/"^]
** https://mlcommons.org/en/news/mlperf-inference-v11/["https://mlcommons.org/en/news/mlperf-inference-v11/"^]


* NetApp Cloud Sync の略
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* TensorFlow ベンチマーク
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* Lenovo ThinkSystem SE350 Edge Server
+
https://lenovopress.com/lp1168["https://lenovopress.com/lp1168"^]

* Lenovo ThinkSystem DM5100F ユニファイドフラッシュストレージアレイ
+
https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array^["https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array"^]





== バージョン履歴

|===
| バージョン | 日付 | ドキュメントのバージョン履歴 


| バージョン 1.0 以降 | 2021年3月 | 初版リリース 


| バージョン 2.0 以降 | 2021年10月 | EF および MLPerf Inference v1.1 で更新 
|===