---
sidebar: sidebar 
permalink: ai/ai-protopia-conclusion.html 
keywords: conclusion, ai inferencing, 
summary: データは保管中、転送中、コンピューティング中の3つの状態に存在します。AI推論サービスの重要な部分は、プロセス全体における脅威からのデータの保護である必要があります。推論の実行中にデータを保護することが重要です。これは、外部のお客様と推論サービスを提供するビジネスの両方の個人情報がこのプロセスによって公開される可能性があるためです。 
---
= まとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-protopia-obfuscation-speed.html["前のバージョン：難読化の速度。"]

[role="lead"]
データは、保管中、転送中、コンピューティング中の3つの状態に存在します。AI推論サービスの重要な部分は、プロセス全体における脅威からのデータの保護である必要があります。推論の実行中にデータを保護することが重要です。これは、外部のお客様と推論サービスを提供するビジネスの両方の個人情報がこのプロセスによって公開される可能性があるためです。Protopia AIは、今日の市場における機密性の高いAI推論を行うための、悪意のないソフトウェアのみの解決策 です。Protopiaを使用すると、AIには、AI / MLタスクを実行するために必要なデータレコードの変換された情報のみが渡されます。これ以外にも、データレコードには何も入力されません。この確率的変化はマスキングの形式ではなく、キュレーションされたノイズを使用してデータの表現を数学的に変更することに基づいています。

ONTAP 機能を備えたネットアップのストレージシステムは、ローカルSSDストレージと同等以上のパフォーマンスを提供します。また、NetApp DataOpsツールキットと組み合わせることで、データサイエンティスト、データエンジニア、AI / ML開発者、ビジネスまたはエンタープライズITの意思決定者に次のようなメリットをもたらします。

* AI システム、分析などの重要なビジネスシステム間でデータを容易に共有できます。このようなデータ共有により、インフラのオーバーヘッドを削減し、パフォーマンスを向上させ、企業全体のデータ管理を合理化できます。
* 個別に拡張可能なコンピューティングとストレージにより、コストを最小限に抑え、リソース使用率を向上させます。
* 統合された Snapshot コピーとクローンを使用して開発と導入のワークフローを合理化し、ユーザのワークスペースを瞬時にスペース効率よく利用できるほか、バージョン管理機能も統合され、導入も自動化されています。
* ディザスタリカバリ、ビジネス継続性、規制要件に対応するエンタープライズクラスのデータ保護とデータガバナンス。
* データ管理操作の簡単な呼び出し。データサイエンティストのワークスペースのSnapshotコピーを迅速に作成し、Jupyterノートブック内のNetApp DataOpsツールキットからバックアップとトレーサビリティを実現します。


ネットアップとProtopia解決策 は、エンタープライズクラスのAI推論環境に最適な、柔軟性に優れたスケールアウトアーキテクチャを提供します。データ保護を実現し、オンプレミス環境とハイブリッドクラウド環境の両方で、AI推論の機密要件を満たすことができる機密情報のプライバシーを提供します。

link:ai-protopia-where-to-find-additional-information,-acknowledgements,-and-version-history.html["Next：追加情報 、確認応答、およびバージョン履歴の参照先。"]
