---
sidebar: sidebar 
permalink: ai/ai-protopia-solution-areas.html 
keywords: environmental intelligence, edge device wearables, noncombatant evacuation operations, cloud migration of analytics 
summary: デジタル画像処理には多くの利点があり、多くの組織が視覚表現に関連するデータを最大限に活用できるようになっています。このネットアップとProtopia解決策 は、ML / DLのライフサイクル全体にわたってAI / MLデータを保護し、民営化するための、独自のAI推論設計を提供しています。お客様は機密データの所有権を維持し、プライバシーに関する懸念を解消して、拡張性と効率性を高めるためにパブリッククラウドまたはハイブリッドクラウドの導入モデルを使用できます。また、エッジでAI推論を導入することもできます。 
---
= 解決策エリア
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-protopia-overview.html["前へ：概要。"]

[role="lead"]
デジタル画像処理には多くの利点があり、多くの組織が視覚表現に関連するデータを最大限に活用できるようになっています。このネットアップとProtopia解決策 は、ML / DLのライフサイクル全体にわたってAI / MLデータを保護し、民営化するための、独自のAI推論設計を提供しています。お客様は機密データの所有権を維持し、プライバシーに関する懸念を解消して、拡張性と効率性を高めるためにパブリッククラウドまたはハイブリッドクラウドの導入モデルを使用できます。また、エッジでAI推論を導入することもできます。



== 環境インテリジェンス

業界は、環境上の危険がある領域で地理空間分析を活用する方法が数多くあります。政府や公共事業部は、公衆衛生や天候に関する実用的な洞察を得ることができ、パンデミックや野生火災などの自然災害時の国民へのアドバイスを向上させることができます。たとえば、空港や病院などの公共スペースで新型コロナウイルス感染症の患者を特定する際に、該当する個人のプライバシーを侵害することなく、必要な安全対策を講じるために各当局および近隣の公衆に警告を出すことができます。



== エッジデバイスのウェアラブル

軍事演習や戦場では、エッジでのAI推論をウェアラブルデバイスとして使用することで、兵士の健康状態を追跡し、運転者の行動を監視し、軍車に接近する際の安全および関連するリスクについて当局に警告しながら、兵士のプライバシーを守り、保護することができます。軍事の未来は、Internet of Battlefield Things（IOBT）とInternet of Military Things（IANMT）でハイテク化を進めています。この製品は、兵士が敵を特定し、高速エッジコンピューティングを使用して戦闘でより良いパフォーマンスを発揮するのに役立ちます。ドローンやウェアラブル・ギアなどのエッジデバイスから収集した視覚的なデータを保護し、保護することは、ハッカーや敵をベイに維持するために不可欠です。



== 非燃焼型避難作業

非戦闘員避難行動（Neos）は、米国市民および国民、DoD民間人、および指定された人（HN）および第3国国民（TCN）の避難を支援するために、国防総省によって実施されます。所定の管理制御では、主に手動による退避対象者スクリーニングプロセスが使用されます。ただし、高度に自動化されたAI / MLツールとAI / MLビデオ難読化テクノロジを組み合わせることで、避難先の識別、退避対象の追跡、脅威スクリーニングの精度、セキュリティ、速度を向上させることができます。



== ヘルスケアおよび生物医学研究

画像処理は、CT（Computed Tomography）またはMRI（Magnetic Resonance Imaging）から取得した3D画像から外科的な計画を立てる際の病理を診断するために使用されます。HIPAAのプライバシールールは、すべての個人情報および写真などのデジタル画像に関して、組織がデータを収集、処理、消去する方法を規定しています。HIPAA Safe Harbor規制の下でデータが共有可能となるようにするには、フルフェイスの写真画像と、それに相当する画像を削除する必要があります。構造CT/MR画像から個人の顔の特徴を隠すために使用される匿名化アルゴリズムや頭蓋骨除去アルゴリズムなどの自動化技術は、生物医学研究機関のデータ共有プロセスの重要な要素となっています。



== AI / ML分析のクラウド移行

エンタープライズのお客様は従来、AI / MLモデルのトレーニングを受け、オンプレミスで導入してきました。スケールメリットと効率性の理由から、AI / ML機能をパブリッククラウド、ハイブリッドクラウド、マルチクラウド環境に移行するお客様が増えています。ただし、他のインフラにどのようなデータを公開できるかによって制限されます。ネットアップのソリューションは、に求められるあらゆるサイバーセキュリティの脅威に対処します https://["データ保護"^] また、セキュリティ評価を行い、Protopiaのデータ変換と組み合わせることで、画像処理AI / MLワークロードをクラウドに移行する際のリスクを最小限に抑えることができます。

他の業界のエッジコンピューティングとAI推論のその他のユースケースについては、を参照してください https://["TR-4886『エッジでのAI推論』"^] NetApp AIブログ、 https://["インテリジェンスとプライバシー"^]。

link:ai-protopia-technology-overview.html["次のステップ：テクノロジの概要"]
