---
sidebar: sidebar 
permalink: ai/ai-sent-deploying-support-center-sentiment-analysis.html 
keywords: deploy, NetApp DataOps Toolkit, NGC Configuration, NVIDIA RIVA Server, NVIDIA TAO Toolkit, Export TAO models to RIVA 
summary: このセクションでは、この解決策を導入するために必要な詳細な手順について説明します。 
---
= サポートセンターのセンチメント分析の導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-sent-design-considerations.html["前の手順：設計上の考慮事項。"]

[role="lead"]
解決策の導入には、次のコンポーネントが含まれます。

. NetApp DataOps ツールキット
. NGC の設定
. NVIDIA Rivea サーバ
. NVIDIA TAO ツールキット
. TAO モデルを Riva にエクスポートします


導入を実行するには、次の手順を実行します。



== NetApp DataOps ツールキット：センターのセンチメント分析をサポート

を使用します https://github.com/NetApp/netapp-dataops-toolkit["NetApp DataOps ツールキット"^]、次の手順を実行します。

. PIP でツールキットをインストールします。
+
....
python3 -m pip install netapp-dataops-traditional
....
. データ管理を設定
+
....
netapp_dataops_cli.py config
....




== NGC 構成：センターの感情分析をサポート

セットアップするには https://ngc.nvidia.com/setup/installers/cli["NVIDIA NGC"^]、次の手順を実行します。

. NGC をダウンロード
+
....
wget -O ngccli_linux.zip https://ngc.nvidia.com/downloads/ngccli_linux.zip && unzip -o ngccli_linux.zip && chmod u+x ngc
....
. 現在のディレクトリをパスに追加します。
+
....
echo "export PATH=\"\$PATH:$(pwd)\"" >> ~/.bash_profile && source ~/.bash_profile
....
. コマンドを実行できるように、 NGC CLI を設定する必要があります。次のコマンドを入力します。プロンプトが表示されたら、 API キーも入力します。
+
....
ngc config set
....


Linux ベースではないオペレーティングシステムについては、を参照してください https://ngc.nvidia.com/setup/installers/cli["こちらをご覧ください"^]。



== NVIDIA Rivea サーバ：センタ心理分析をサポートします

セットアップするには https://docs.nvidia.com/deeplearning/riva/user-guide/docs/quick-start-guide.html["NVIDIA RIVA"^]、次の手順を実行します。

. NGC から Riva ファイルをダウンロード
+
....
ngc registry resource download-version nvidia/riva/riva_quickstart:1.4.0-beta
....
. Riva セットアップを初期化します (`Riva_init.sh`)
. Riva サーバ (`Riva_start.sh`) を起動します
. Riva クライアント (`Riva_start_client.sh`) を起動します
. Riva クライアント内で、オーディオ処理ライブラリをインストールします（ https://ffmpeg.org/download.html["FFmpeg"^])
+
....
apt-get install ffmpeg
....
. を起動します https://jupyter-server.readthedocs.io/en/latest/["Jupyter"^] サーバ
. Riva Inference Pipeline Notebook を実行します。




== NVIDIA TAO Toolkit ：センターの感情分析をサポートします

NVIDIA TAO Toolkit をセットアップするには、次の手順を実行します。

. を準備してアクティブ化します https://docs.python.org/3/library/venv.html["仮想環境"^] TAO ツールキット用。
. をインストールします https://docs.nvidia.com/tao/tao-toolkit/text/tao_toolkit_quick_start_guide.html["必須パッケージ"^]。
. トレーニング中および微調整中に使用したイメージを手動で引き出します。
+
....
docker pull nvcr.io/nvidia/tao/tao-toolkit-pyt:v3.21.08-py3
....
. を起動します https://jupyter-server.readthedocs.io/en/latest/["Jupyter"^] サーバ
. TAO 微調整ノートブックを実行します。




== TAO モデルを Riva にエクスポート：センターの感情分析をサポートします

を使用してください https://docs.nvidia.com/tao/tao-toolkit/text/riva_tao_integration.html["Rivea の Tao ツールキットモデル"^]、次の手順を実行します。

. TAO 微調整ノートブックにモデルを保存します。
. TAO トレーニング済みモデルを Riva モデルディレクトリにコピーします。
. Riva サーバ (`Riva_start.sh`) を起動します




== 導入の障害です

独自の解決策を開発する際に留意すべき点をいくつかご紹介します。

* 最初に NetApp DataOps ツールキットをインストールし、データストレージシステムが最適に動作するようにします。
* NVIDIA NGC は、イメージとモデルのダウンロードを認証するため、それ以外のコンポーネントよりも先にインストールする必要があります。
* Rivea は、 TAO ツールキットの前にインストールする必要があります。Riva インストールでは、必要に応じてイメージをプルするように Docker デーモンが設定されます。
* DGX および Docker でモデルをダウンロードするには、インターネットアクセスが必要です。


link:ai-sent-validation-results.html["次の例は、検証結果です"]
