---
sidebar: sidebar 
permalink: ai/aicp_hardware_and_software_requirements.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: NetAppによるオープンソースMLOps -アーキテクチャ 
---
= アーキテクチャ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
この解決策は特定のハードウェアに依存しません。解決策は、 Trident でサポートされている、任意のネットアップ物理ストレージアプライアンス、ソフトウェア定義インスタンス、クラウドサービスと互換性があります。たとえば、NetApp AFFストレージシステム、Amazon FSx for NetApp ONTAP、Azure NetApp Files、NetApp Cloud Volumes ONTAPインスタンスなどです。さらに、使用しているKubernetesバージョンがKubeflowとNetApp Astra Tridentでサポートされていれば、解決策を任意のKubernetesクラスタに実装できます。Kubeflow でサポートされる Kubernetes バージョンの一覧については、を参照してください https://www.kubeflow.org/docs/started/getting-started/["Kubeflow の公式ドキュメント"^]。Trident でサポートされている Kubernetes のバージョンのリストについては、を参照してください https://docs.netapp.com/us-en/trident/index.html["Trident のドキュメント"^]。解決策の検証に使用した環境の詳細については、次の表を参照してください。

|===
| ソフトウェアコンポーネント | バージョン 


| Apache の通気 | 2.0.1 


| Apache Airflow Helm チャート | 8.0.8 


| クビフロー | 1.7、次の方法で導入 link:https://www.deploykf.org["deployKF"] 0.1.1 


| Kubernetes | 1.26 


| ネットアップアストラト Trident | 23.07 
|===


== サポート

NetAppは、Apache Airflow、Kubeflow、Kubernetesのエンタープライズサポートを提供していません。完全にサポートされているMLOpsプラットフォームに関心がある場合は、 link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["ネットアップにお問い合わせください"] NetAppがパートナーと共同で提供する、完全にサポートされたMLOpsソリューションについて説明します。
