---
sidebar: sidebar 
permalink: ai/aicp_example_trident_backends_for_ontap_ai_deployments.html 
keywords: ONTAP, Trident, AI, Deployment, 
summary: NetAppを使用したオープンソースMLOps - NetApp AIPod導入のTridentバックエンドの例 
---
= NetApp AIPod導入のTridentバックエンドの例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident を使用して Kubernetes クラスタ内のストレージリソースを動的にプロビジョニングするには、 Trident バックエンドを 1 つ以上作成する必要があります。次の例は、このソリューションのコンポーネントをに配置する場合に作成するバックエンドの種類を示してい link:aipod_nv_intro.html["NetApp AIPod"^]ます。バックエンドの詳細、および他のプラットフォーム/環境のバックエンドの例については、を参照してください link:https://docs.netapp.com/us-en/trident/index.html["Trident のドキュメント"^]。

. NetAppでは、AIPod用にFlexGroup対応のTridentバックエンドを作成することを推奨しています。
+
以降のコマンド例では、AIPod Storage Virtual Machine（SVM）用にFlexGroup対応のTridentバックエンドを作成しています。このバックエンドはストレージドライバを使用し `ontap-nas-flexgroup`ます。ONTAP では、 FlexVol と FlexGroup の 2 つの主要なデータボリュームタイプがサポートされます。FlexVol ボリュームのサイズは限られています（現時点では、最大サイズは環境によって異なります）。一方、 FlexGroup ボリュームは最大 20PB 、 4 、 000 億ファイルまでリニアに拡張でき、データ管理を大幅に簡易化する単一のネームスペースを提供します。そのため、 FlexGroup ボリュームは、大量のデータに依存する AI や ML のワークロードに最適です。

+
少量のデータを処理していて、FlexGroupボリュームの代わりにFlexVolボリュームを使用する場合は、ストレージドライバではなくストレージドライバを `ontap-nas-flexgroup`使用するTridentバックエンドを作成できます `ontap-nas`。

+
....
$ cat << EOF > ./trident-backend-aipod-flexgroups-iface1.json
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "backendName": "aipod-flexgroups-iface1",
    "managementLIF": "10.61.218.100",
    "dataLIF": "192.168.11.11",
    "svm": "ontapai_nfs",
    "username": "admin",
    "password": "ontapai"
}
EOF
$ tridentctl create backend -f ./trident-backend-aipod-flexgroups-iface1.json -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexgroups-iface1 | ontap-nas-flexgroup | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
$ tridentctl get backend -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexgroups-iface1 | ontap-nas-flexgroup | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
....
. NetAppでは、FlexVol対応のTridentバックエンドを作成することも推奨しています。FlexVolボリュームは、永続的アプリケーションのホスト、結果の格納、出力、デバッグ情報などに使用できます。FlexVol ボリュームを使用する場合は、 FlexVol 対応の Trident バックエンドを 1 つ以上作成する必要があります。以降のコマンド例では、FlexVol対応のTridentバックエンドを1つ作成しています。


....
$ cat << EOF > ./trident-backend-aipod-flexvols.json
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "aipod-flexvols",
    "managementLIF": "10.61.218.100",
    "dataLIF": "192.168.11.11",
    "svm": "ontapai_nfs",
    "username": "admin",
    "password": "ontapai"
}
EOF
$ tridentctl create backend -f ./trident-backend-aipod-flexvols.json -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexvols          | ontap-nas           | 52bdb3b1-13a5-4513-a9c1-52a69657fabe | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
$ tridentctl get backend -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexvols          | ontap-nas           | 52bdb3b1-13a5-4513-a9c1-52a69657fabe | online |       0 |
| aipod-flexgroups-iface1 | ontap-nas-flexgroup | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
....