---
sidebar: sidebar 
permalink: ai/aicp_hardware_and_software_requirements.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: NetApp AI コントロールプレーン解決策は、このような特定のハードウェアには依存しません。 
---
= ハードウェアとソフトウェアの要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NetApp AI コントロールプレーン解決策は、このような特定のハードウェアには依存しません。解決策は、 Trident でサポートされている、任意のネットアップ物理ストレージアプライアンス、ソフトウェア定義インスタンス、クラウドサービスと互換性があります。例としては、ネットアップ AFF ストレージシステム、 Azure NetApp Files 、ネットアップ Cloud Volumes Service 、ネットアップ ONTAP Select ソフトウェアで定義されるストレージインスタンス、ネットアップ Cloud Volumes ONTAP インスタンスなどがあります。また、使用する Kubernetes のバージョンが Kubeflow および NetApp Trident でサポートされていれば、どの Kubernetes クラスタにも解決策を実装できます。Kubeflow でサポートされる Kubernetes バージョンの一覧については、を参照してください https://["Kubeflow の公式ドキュメント"^]。Trident でサポートされている Kubernetes のバージョンのリストについては、を参照してください https://["Trident のドキュメント"^]。解決策の検証に使用した環境の詳細については、次の表を参照してください。

|===
| インフラストラクチャコンポーネント | 数量 | 詳細 | オペレーティングシステム 


| 展開ジャンプホスト | 1. | VM | Ubuntu 20.04.2 LTS の場合は 


| Kubernetes マスターノード | 1. | VM | Ubuntu 20.04.2 LTS の場合は 


| Kubernetes ワーカーノード | 2. | VM | Ubuntu 20.04.2 LTS の場合は 


| Kubernetes GPU ワーカーノード | 2. | NVIDIA DGX-1 （ベアメタル） | NVIDIA DGX OS 4.0.5 （ Ubuntu 18.04.2 LTS に基づく） 


| ストレージ | 1 つの HA ペア | NetApp AFF A220 | NetApp ONTAP 9.7 P6 
|===
|===
| ソフトウェアコンポーネント | バージョン 


| Apache の通気 | 2.0.1 


| Apache Airflow Helm チャート | 8.0.8 


| Docker です | 19.03.12 


| クビフロー | 1/2 


| Kubernetes | 1.18.9 


| NetApp Trident | 21.01.2. 


| NVIDIA DeepOps のことです | コミット時点でマスターブランチから Trident 導入機能を利用できるようになりました link:https://github.com/NVIDIA/deepops/tree/61898cdfdaa0c59c07e9fabf3022945a905b148e/docs/k8s-cluster["61898cdfda"]; バージョン 21.03 の他のすべての機能 
|===


== サポート

ネットアップは、 Apache Airflow 、 Docker 、 Kubeflow 、 Kubernetes 、 NVIDIA DeepOps のエンタープライズサポートを提供していません。ネットアップの AI コントロールプレーン解決策と同様の機能を備えた、完全にサポートされている解決策に関心がある場合： link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["ネットアップにお問い合わせください"] ネットアップがパートナー様と共同で提供する、完全にサポートされている AI / ML ソリューションについて説明します。

link:aicp_kubernetes_deployment.html["次： Kubernetes の導入"]
