---
sidebar: sidebar 
permalink: ai/aicp_conclusion.html 
keywords: NetApp AI Machine Deep Learning 
summary:  
---
= まとめ
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


あらゆる規模の企業や組織が、あらゆる業界で、人工知能（ AI ）、機械学習（ ML ）、ディープラーニング（ DL ）を活用して、現実世界の問題を解決し、革新的な製品やサービスを提供し、競争が激化する市場で優位に立つことが求められています。AI 、 ML 、 DL の利用が増えるにつれ、ワークロードの拡張性やデータの可用性など、多くの課題に直面しています。これらの課題には、ネットアップのフルスタック AI データと実験管理解決策である NetApp AI コントロールプレーンを使用して対処できます。

この解決策を使用すると、データネームスペースのクローンを Git リポジトリと同様に迅速に作成できます。さらに、トレーサビリティとバージョン管理のためにデータやモデルベースラインをほぼ瞬時に作成する AI 、 ML 、 DL のトレーニングワークフローを定義して実装できます。この解決策を使用すると、すべてのモデルトレーニングを、モデルがトレーニングされ、検証されたデータセットに戻すことができます。最後に、この解決策を使用すると、 Jupyter Notebook ワークスペースをすばやくプロビジョニングし、大規模なデータセットにアクセスできます。

この解決策はデータサイエンティストやデータエンジニアを対象としているため、ネットアップや ONTAP に関する専門知識は不要です。この解決策を使用すると、シンプルで使い慣れたツールやインターフェイスを使用してデータ管理機能を実行できます。さらに、この解決策では、完全なオープンソースおよび無償のコンポーネントを使用しています。したがって、ネットアップストレージがすでにある環境では、この解決策を実装できます。この解決策でドライブをテストしたいが、ネットアップストレージはまだお持ちでない場合は、を参照してください http://cloud.netapp.com/["cloud.netapp.com"^]また、クラウドベースの NetApp Storage 解決策を使用すれば、いつでも稼働を開始できます。

link:aicp_acknowledgments.html["次：謝辞"]
