---
sidebar: sidebar 
permalink: ai/aicp_trigger_a_snapmirror_volume_replication_update.html 
keywords: Prerequisites, DAG definition, model training, SnapMirror, 
summary: このページで概説している DAG の例では、 NetApp SnapMirror データレプリケーションテクノロジを利用して、異なる ONTAP クラスタ間でボリュームの内容をレプリケートするワークフローを実装しています。 
---
= SnapMirror Volume Replication Update をトリガーする
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
このセクションで説明する DAG の例では、 NetApp SnapMirror のデータレプリケーションテクノロジを利用して複数の ONTAP クラスタ間でボリュームの内容をレプリケートするワークフローを実装しています。

このパイプラインを使用すると、異なるサイトやリージョンに配置されているデータや配置されていないデータを ONTAP クラスタ間でレプリケートできます。考えられるユースケースとしては、次のようなものがあります

* 新たに取得したセンサーデータをエッジで収集してコアデータセンターやクラウドにレプリケートし、 AI / ML モデルのトレーニングや再トレーニングに使用できます。
* トレーニングを受けた、または新しく更新されたモデルを、推論アプリケーションの一部として導入するコアデータセンターからエッジまたはクラウドにレプリケートします。




=== 前提条件

この DAG を正しく機能させるには、次の前提条件を満たしている必要があります。

* 「トレーサビリティとバージョン管理機能を備えたエンドツーエンドの AI トレーニングワークフローの実装」セクションの前提条件 #1 に記載されているように、 ONTAP システムの通気に接続を作成しておく必要があります。」
* 標準の設定手順に従って、ソースボリュームとデスティネーションボリュームの間で非同期 SnapMirror 関係を開始しておく必要があります。詳細については、を参照してください http://docs.netapp.com/["ネットアップの公式ドキュメント"^]。




=== DAG の定義

以下の Python コードの抜粋には、 DAG の例の定義が含まれています。ご使用の環境でこの DAG の例を実行する前に、「定義パラメータ」セクションのパラメータ値を変更して、ご使用の環境に合わせてください。

....
# Airflow DAG Definition: Replicate Data - SnapMirror
#
# Steps:
#   1. Trigger NetApp SnapMirror update
from airflow.utils.dates import days_ago
from airflow.secrets import get_connections
from airflow.models import DAG
from airflow.operators.python_operator import PythonOperator
##### DEFINE PARAMETERS: Modify parameter values in this section to match your environment #####
## Define default args for DAG
replicate_data_snapmirror_dag_default_args = {
    'owner': 'NetApp'
}
## Define DAG details
replicate_data_snapmirror_dag = DAG(
    dag_id='replicate_data_snapmirror',
    default_args=replicate_data_snapmirror_dag_default_args,
    schedule_interval=None,
    start_date=days_ago(2),
    tags=['data-movement']
)
## Define SnapMirror details (change values as necessary to match your environment)
# Destination ONTAP system details
airflowConnectionName = 'ontap_ai'  # Name of the Airflow connection that contains connection details for the destination ONTAP system's cluster admin account
verifySSLCert = False   # Denotes whether or not to verify the SSL cert when calling the ONTAP API
# SnapMirror relationship details (existing SnapMirroer relationship for which you want to trigger an update)
sourceSvm = "ailab"
sourceVolume = "sm"
destinationSvm = "ai221_data"
destinationVolume = "sm_dest"
################################################################################################
# Define function that triggers a NetApp SnapMirror update
def netappSnapMirrorUpdate(**kwargs) -> int :
    # Parse args
    for key, value in kwargs.items() :
        if key == 'sourceSvm' :
            sourceSvm = value
        elif key == 'sourceVolume' :
            sourceVolume = value
        elif key == 'destinationSvm' :
            destinationSvm = value
        elif key == 'destinationVolume' :
            destinationVolume = value
        elif key == 'verifySSLCert' :
            verifySSLCert = value
        elif key == 'airflowConnectionName' :
            airflowConnectionName = value
    # Install ansible package
    import sys, subprocess, os
    print("Installing required Python modules:\n")
    result = subprocess.check_output([sys.executable, '-m', 'pip', 'install', '--user', 'ansible', 'netapp-lib'])
    print(str(result).replace('\\n', '\n'))

    # Retrieve ONTAP cluster admin account details from Airflow connection
    connections = get_connections(conn_id = airflowConnectionName)
    ontapConnection = connections[0]    # Assumes that you only have one connection with the specified conn_id configured in Airflow
    ontapClusterAdminUsername = ontapConnection.login
    ontapClusterAdminPassword = ontapConnection.password
    ontapClusterMgmtHostname = ontapConnection.host

    # Define temporary Ansible playbook for triggering SnapMirror update
    snapMirrorPlaybookContent = """
---
- name: "Trigger SnapMirror Update"
  hosts: localhost
  tasks:
  - name: update snapmirror
    na_ontap_snapmirror:
      state: present
      source_path: '%s:%s'
      destination_path: '%s:%s'
      hostname: '%s'
      username: '%s'
      password: '%s'
      https: 'yes'
      validate_certs: '%s'""" % (sourceSvm, sourceVolume, destinationSvm, destinationVolume, ontapClusterMgmtHostname,
        ontapClusterAdminUsername, ontapClusterAdminPassword, str(verifySSLCert))
    print("Creating temporary Ansible playbook.\n")
    snapMirrorPlaybookFilepath = "/home/airflow/snapmirror-update.yaml"
    snapMirrorPlaybookFile = open(snapMirrorPlaybookFilepath, "w")
    snapMirrorPlaybookFile.write(snapMirrorPlaybookContent)
    snapMirrorPlaybookFile.close()
    # Trigger SnapMirror update
    print("Executing Ansible playbook to trigger SnapMirror update:\n")
    try :
        result = subprocess.check_output(['ansible-playbook', snapMirrorPlaybookFilepath])
        print(str(result).replace('\\n', '\n'))
    except Exception as e :
        print("Exception:", str(e).strip())
        print("Removing temporary Ansible playbook.")
        os.remove(snapMirrorPlaybookFilepath) # Remove temporary Ansible playbook before exiting
        raise
    # Remove temporary Ansible playbook before exiting
    print("Removing temporary Ansible playbook.\n")
    os.remove(snapMirrorPlaybookFilepath)
    # Return success code
    return 0
# Define DAG steps/workflow
with replicate_data_snapmirror_dag as dag :
    # Define step to trigger a NetApp SnapMirror update
    trigger_snapmirror = PythonOperator(
        task_id='trigger-snapmirror',
        python_callable=netappSnapMirrorUpdate,
        op_kwargs={
            'airflowConnectionName': airflowConnectionName,
            'verifySSLCert': verifySSLCert,
            'sourceSvm': sourceSvm,
            'sourceVolume': sourceVolume,
            'destinationSvm': destinationSvm,
            'destinationVolume': destinationVolume
        },
        dag=dag
    )
....
link:aicp_trigger_a_cloud_sync_replication_update.html["次の手順： Cloud Sync レプリケーションの更新をトリガーします"]
