---
sidebar: sidebar 
permalink: ai/aicp_where_to_find_additional_information.html 
keywords: Additional, Information, references 
summary: このドキュメントに記載されている情報の詳細については、このページに記載されているリソースを参照してください。 
---
= 追加情報の検索場所
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
このドキュメントに記載されている情報の詳細については、次のリソースを参照してください。

* NVIDIA DGX-1 サーバ：
+
** NVIDIA DGX-1 サーバ
+
https://www.nvidia.com/en-us/data-center/dgx-1/["https://www.nvidia.com/en-us/data-center/dgx-1/[""]"^]

** NVIDIA Tesla V100 Tensor コア GPU
+
https://www.nvidia.com/en-us/data-center/tesla-v100/["https://www.nvidia.com/en-us/data-center/tesla-v100/[""]"^]

** NVIDIA GPU Cloud （ NGC ）
+
https://www.nvidia.com/en-us/gpu-cloud/["https://www.nvidia.com/en-us/gpu-cloud/[""]"^]



* NetApp AFF システム：
+
** AFF データシート
+
https://www.netapp.com/us/media/ds-3582.pdf["https://www.netapp.com/us/media/ds-3582.pdf[""]"^]

** AFF 向け NetApp FlashAdvantage プログラム
+
https://www.netapp.com/us/media/ds-3733.pdf["https://www.netapp.com/us/media/ds-3733.pdf[""]"^]

** ONTAP 9.x のドキュメント
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[""]"^]

** NetApp FlexGroup テクニカルレポート
+
https://www.netapp.com/us/media/tr-4557.pdf["https://www.netapp.com/us/media/tr-4557.pdf[""]"^]



* コンテナ向けのネットアップの永続的ストレージ：
+
** NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/[""]"^]



* NetApp Interoperability Matrix を参照してください
+
** NetApp Interoperability Matrix Tool で確認できます
+
http://support.netapp.com/matrix["http://support.netapp.com/matrix[""]"^]



* ONTAP AI ネットワーク：
+
** Cisco Nexus 3232C スイッチ
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html["https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html[""]"^]

** Mellanox Spectrum 2000 シリーズスイッチ
+
http://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000["http://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000[""]"^]



* ML フレームワークとツール：
+
** 大理
+
https://github.com/NVIDIA/DALI["https://github.com/NVIDIA/DALI[""]"^]

** TensorFlow ：あらゆる環境に対応するオープンソースの機械学習フレームワーク
+
https://www.tensorflow.org/["https://www.tensorflow.org/[""]"^]

** Horovod ： Uber が開発したオープンソースの TensorFlow 用分散学習フレームワーク
+
https://eng.uber.com/horovod/["https://eng.uber.com/horovod/[""]"^]

** コンテナランタイムエコシステムでの GPU の有効化
+
https://devblogs.nvidia.com/gpu-containers-runtime/["https://devblogs.nvidia.com/gpu-containers-runtime/[""]"^]

** Docker です
+
https://docs.docker.com["https://docs.docker.com[""]"^]

** Kubernetes
+
https://kubernetes.io/docs/home/["https://kubernetes.io/docs/home/[""]"^]

** NVIDIA DeepOps のことです
+
https://github.com/NVIDIA/deepops["https://github.com/NVIDIA/deepops[""]"^]

** クビフロー
+
http://www.kubeflow.org/["http://www.kubeflow.org/[""]"^]

** Jupyter Notebook Server の 2 つのツールを使用
+
http://www.jupyter.org/["http://www.jupyter.org/[""]"^]



* データセットとベンチマーク：
+
** ImageNet
+
http://www.image-net.org/["http://www.image-net.org/[""]"^]

** ココ
+
http://cocodataset.org/["http://cocodataset.org/[""]"^]

** 都会の風景
+
https://www.cityscapes-dataset.com/["https://www.cityscapes-dataset.com/[""]"^]

** n シーン（ nuScenes
+
http://www.nuscenes.org["www.nuscenes.org"^]

** 第 2 に、内蔵の欠点を検出するモデルです
+
https://pdfs.semanticscholar.org/5125/a16039cabc6320c908a4764f32596e018ad3.pdf["https://pdfs.semanticscholar.org/5125/a16039cabc6320c908a4764f32596e018ad3.pdf[""]"^]

** TensorFlow ベンチマーク
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks[""]"^]




