---
sidebar: sidebar 
permalink: ai/aicp_hardware_and_software_requirements.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: NetAppによるオープンソースMLOps -アーキテクチャ 
---
= アーキテクチャ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
この解決策は特定のハードウェアに依存しません。このソリューションは、NetApp Tridentでサポートされている任意のNetApp物理ストレージアプライアンス、Software-Definedインスタンス、クラウドサービスと互換性があります。たとえば、NetApp AFFストレージシステム、Amazon FSx ONTAP、Azure NetApp Files、Google Cloud NetApp Volume、NetApp Cloud Volumes ONTAPインスタンスなどです。さらに、使用されているKubernetesのバージョンがNetApp Tridentおよび実装されているその他のソリューションコンポーネントでサポートされているかぎり、このソリューションは任意のKubernetesクラスタに実装できます。TridentでサポートされるKubernetesのバージョンのリストについては、を参照してください https://docs.netapp.com/us-en/trident/index.html["Trident のドキュメント"^]。このソリューションの各種コンポーネントの検証に使用した環境の詳細については、次の表を参照してください。



== Apacheエアフロー検証環境

|===
| ソフトウェアコンポーネント | バージョン 


| Apache の通気 | 2.0.1、8.0.8経由で導入 link:https://artifacthub.io/packages/helm/airflow-helm/airflow["Apache Airflow Helmチャート"^] 


| Kubernetes | 1.18 


| NetApp Trident | 21.01 
|===


== JupyterHub検証環境

|===
| ソフトウェアコンポーネント | バージョン 


| JupyterHub | 4.1.5、3.3.7経由で導入 link:https://hub.jupyter.org/helm-chart/["JupyterHub Helmチャート"^] 


| Kubernetes | 1.29 


| NetApp Trident | 24.02 
|===


== MLflow検証環境

|===
| ソフトウェアコンポーネント | バージョン 


| MLflow | 2.14.1（1.4.12経由で導入） link:https://artifacthub.io/packages/helm/bitnami/mlflow["MLflow Helmチャート"^] 


| Kubernetes | 1.29 


| NetApp Trident | 24.02 
|===


== Kubeflow検証環境

|===
| ソフトウェアコンポーネント | バージョン 


| クビフロー | 1.7、0.1.1を使用して導入 link:https://www.deploykf.org["deployKF"^] 


| Kubernetes | 1.26 


| NetApp Trident | 23.07 
|===


== サポート

NetAppは、Apache Airflow、JupyterHub、MLflow、Kubeflow、Kubernetesのエンタープライズサポートを提供していません。完全にサポートされたMLOpsプラットフォームに関心がある場合は link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["NetAppへのお問い合わせ"^] 、NetAppがパートナーと共同で提供する完全にサポートされたMLOpsソリューションについて説明します。
