---
sidebar: sidebar 
permalink: ai/aicp_kubernetes_deployment.html 
keywords: NVIDIA, GPU, Kubernetes, Control Plane, Trident 
summary: このページでは、 NetApp AI コントロールプレーン解決策を実装する Kubernetes クラスタを導入するために実行する必要があるタスクについて説明します。Kubernetes クラスタをすでにお持ちの場合は、 Kubeflow と NetApp Trident でサポートされるバージョンの Kubernetes を実行していれば、このセクションをスキップできます。 
---
= Kubernetes の導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
このセクションでは、 NetApp AI コントロールプレーン解決策を実装する Kubernetes クラスタを導入するために完了しておく必要があるタスクについて説明します。Kubernetes クラスタをすでにお持ちの場合は、 Kubeflow と NetApp Trident でサポートされるバージョンの Kubernetes を実行していれば、このセクションをスキップできます。Kubeflow でサポートされる Kubernetes バージョンの一覧については、を参照してください https://www.kubeflow.org/docs/started/getting-started/["Kubeflow の公式ドキュメント"^]。Trident でサポートされている Kubernetes のバージョンのリストについては、を参照してください https://netapp-trident.readthedocs.io/["Trident のドキュメント"^]。

NVIDIA GPU を搭載したベアメタルノードを統合したオンプレミスの Kubernetes 環境では、 NVIDIA の DeepOps Kubernetes 導入ツールの使用を推奨します。このセクションでは、 DeepOps を使用した Kubernetes クラスタの導入について説明します。



== 前提条件

このセクションで説明する導入の演習を行う前に、次の作業をすでに実行していることを前提としています。

. 標準的な構成手順に従って、ベアメタルの Kubernetes ノード（ ONTAP AI ポッドに含まれる NVIDIA DGX システムなど）を設定済みであること。
. すべての Kubernetes マスターノードとワーカーノード、および導入ジャンプホストに、サポートされているオペレーティングシステムをインストールしておきます。DeepOps でサポートされているオペレーティングシステムのリストについては、を参照してください https://github.com/NVIDIA/deepops["DeepOps GitHub サイト"^]。




== NVIDIA DeepOps を使用して Kubernetes をインストールおよび設定します

NVIDIA DeepOps で Kubernetes クラスタを導入および設定するには、導入ジャンプホストから次のタスクを実行します。

. の手順に従って、 NVIDIA DeepOps をダウンロードします https://github.com/NVIDIA/deepops/tree/master/docs["「はじめに」ページ"^] NVIDIA DeepOps GitHub サイトで入手できます。
. の手順に従って、クラスタに Kubernetes を導入します 。 https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster["Kubernetes 導入ガイドのページ"^] NVIDIA DeepOps GitHub サイトで入手できます。

