---
sidebar: sidebar 
permalink: ai/aicp_netapp_trident_deployment_and_configuration_overview.html 
keywords: Trident, Kubernetes, Storageclass 
summary: このページでは、 Kubernetes クラスタに NetApp Trident をインストールして設定するために必要な作業について説明します。 
---
= NetApp Trident の導入と設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
このセクションでは、 Kubernetes クラスタに NetApp Trident をインストールして設定するために必要な作業について説明します。



== 前提条件

このセクションで説明する導入の演習を行う前に、次の作業をすでに実行していることを前提としています。

. Kubernetes クラスタはすでに稼働しており、 Trident でサポートされるバージョンの Kubernetes を実行している。サポートされているバージョンの一覧については、を参照してください https://netapp-trident.readthedocs.io/["Trident のドキュメント"^]。
. すでに稼働しているネットアップストレージアプライアンス、ソフトウェア定義インスタンス、クラウドストレージサービスで、 Trident でサポートされているものを使用している。




== Trident をインストール

Kubernetes クラスタに NetApp Trident をインストールして設定するには、導入ジャンプホストから次のタスクを実行します。

. Trident は、次のいずれかの方法で導入できます。
+
** NVIDIA DeepOps を使用して Kubernetes クラスタを導入した場合は、 NVIDIA DeepOps を使用して Kubernetes クラスタに Trident を導入することもできます。Trident で DeepOps を導入する方法については、を参照してください https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster#netapp-trident["Trident の導入手順"] NVIDIA DeepOps GitHub サイトで入手できます。
** NVIDIA DeepOps を使用して Kubernetes クラスタを導入していない場合や Trident を手動で導入する場合は、次の手順で Trident を導入できます https://netapp-trident.readthedocs.io/["導入手順"^] Trident のドキュメントTrident バックエンドと Kubernetes StorageClass を少なくとも 1 つずつ作成してください。Backends と StorageClasses の詳細については、を参照してください https://netapp-trident.readthedocs.io/["Trident のドキュメント"^]。





NOTE: 解決策 AI ポッドにネットアップ AI コントロールプレーン ONTAP を導入する場合は、を参照してください link:aicp_example_trident_backends_for_ontap_ai_deployments.html["ONTAP AI 導入向け Trident バックエンドの例"] さまざまな Trident バックエンドの例を紹介します とを作成します link:aicp_example_kubernetes_storageclasses_for_ontap_ai_deployments.html["ONTAP AI 導入向けの Kubernetes StorageClasses の例"] を参照してください。

link:aicp_example_trident_backends_for_ontap_ai_deployments.html["次の例： ONTAP AI 導入向けの Trident バックエンド"]
