---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion_add_info.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: NVIDIA DGXシステムを搭載したNetApp AIPod -追加情報の入手先 
---
= NVA-1173 NVIDIA DGXシステム搭載NetApp AIPod -まとめと追加情報
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションでは、NVIDIA DGXシステムを搭載したNetApp AIPodの追加情報に関する参考資料を紹介します。



== まとめ

DGX BasePODアーキテクチャは、同等の高度なストレージ機能とデータ管理機能を必要とする次世代のディープラーニングプラットフォームです。DGX BasePODとNetApp AFFシステムを組み合わせることで、NetApp AIPodとDGXシステムのアーキテクチャをほぼあらゆる規模で実装できます。AFFは、NetApp ONTAPの優れたクラウド統合機能とソフトウェアで定義される機能を組み合わせることで、DLプロジェクトを成功させるために、エッジ、コア、クラウドにわたる幅広いデータパイプラインを実現します。



== 追加情報

このドキュメントに記載されている情報の詳細については、次のドキュメントやWebサイトを参照してください。

* NetApp ONTAP データ管理ソフトウェア—ONTAP 情報ライブラリ
+
https://docs.netapp.com/us-en/ontap-family/["https://docs.netapp.com/us-en/ontap-family/"^]

* NetApp AFF A90ストレージシステム-
+
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf"]

* NetApp ONTAP RDMA情報-
+
link:https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html["https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html"]

* NetApp DataOps ツールキット
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* NetApp Trident
+
link:../containers/rh-os-n_overview_trident.html["概要"]

* NetApp GPUDirectストレージに関するブログ-
+
https://www.netapp.com/blog/ontap-reaches-171-gpudirect-storage/["https://www.netapp.com/blog/ontap-reaches-171-gpudirect-storage/"]

* NVIDIA DGX BasePOD
+
https://www.nvidia.com/en-us/data-center/dgx-basepod/["https://www.nvidia.com/en-us/data-center/dgx-basepod/"^]

* NVIDIA DGX H100システム
+
https://www.nvidia.com/en-us/data-center/dgx-h100/["https://www.nvidia.com/en-us/data-center/dgx-h100/"^]

* NVIDIAネットワーク
+
https://www.nvidia.com/en-us/networking/["https://www.nvidia.com/en-us/networking/"^]

* NVIDIAマグナムIO&#8482;GPUDirect&#174;ストレージ
+
https://docs.nvidia.com/gpudirect-storage["https://docs.nvidia.com/gpudirect-storage"]

* NVIDIA Baseコマンド
+
https://www.nvidia.com/en-us/data-center/base-command/["https://www.nvidia.com/en-us/data-center/base-command/"]

* NVIDIA Baseコマンドマネージャ
+
https://www.nvidia.com/en-us/data-center/base-command/manager["https://www.nvidia.com/en-us/data-center/base-command/manager"]

* NVIDIA AIエンタープライズ
+
https://www.nvidia.com/en-us/data-center/products/ai-enterprise/["https://www.nvidia.com/en-us/data-center/products/ai-enterprise/"^]





== 謝辞

このドキュメントは、NetAppソリューションおよびONTAPエンジニアリングチーム（David Arnette、Olga Kornievskaia、Dustin Fischer、Srikanth Kaligotla、Mohit Kumar、Raghuram Sudhaakar）の作業です。また、NVIDIAとNVIDIA DGX BasePODエンジニアリングチームの継続的なサポートに感謝します。
