---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion_add_info.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: NVIDIA DGXシステムを搭載したNetApp AIPod -追加情報の入手先 
---
= NVIDIA DGXシステムを搭載したNetApp AIPod -まとめと追加情報
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aipod_nv_validation_sizing.html["以前：NVIDIA DGXシステムを使用したNetApp AIPod -解決策の検証とサイジングに関するガイダンス"]



== まとめ

DGX BasePODアーキテクチャは、同等の高度なストレージ機能とデータ管理機能を必要とする次世代のディープラーニングプラットフォームです。NetApp AIPodアーキテクチャは、DGX BasePODとNetApp AFFシステムを組み合わせることで、OEMサーバの単一のGPUとAFF A250ストレージシステムを組み合わせ、24ノードのAFF A900クラスタ上に最大48台のDGX H100システムを構築するなど、ほぼあらゆる規模で実装できます。AFFは、NetApp ONTAPの優れたクラウド統合機能とソフトウェアで定義される機能を組み合わせることで、DLプロジェクトを成功させるために、エッジ、コア、クラウドにわたる幅広いデータパイプラインを実現します。



== 追加情報

このドキュメントに記載されている情報の詳細については、次のドキュメントやWebサイトを参照してください。

* NetApp ONTAP データ管理ソフトウェア—ONTAP 情報ライブラリ
+
https://docs.netapp.com/us-en/ontap-family/["https://docs.netapp.com/us-en/ontap-family/"^]

* NetApp AFF A900ストレージシステム-
+
https://www.netapp.com/data-storage/aff-a-series/aff-a900/["https://www.netapp.com/data-storage/aff-a-series/aff-a900/"]

* NetApp ONTAP RDMA情報-
+
link:https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html["https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html"]

* NetApp DataOps ツールキット
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* ネットアップアストラト Trident
+
https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html["https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html"^]

* ONTAP AI - NVIDIA DGX A100システムを使用したNetApp検証済みアーキテクチャ
+
https://docs.netapp.com/us-en/netapp-solutions/ai/ontap-ai-overview.html["https://docs.netapp.com/us-en/netapp-solutions/ai/ontap-ai-overview.html"^]

* NVIDIA BasePOD
+
https://www.nvidia.com/en-us/data-center/dgx-basepod/["https://www.nvidia.com/en-us/data-center/dgx-basepod/"^]

* NVIDIA DGX A100システム
+
https://www.nvidia.com/en-us/data-center/dgx-a100/["https://www.nvidia.com/en-us/data-center/dgx-a100/"^]

* NVIDIAネットワーク
+
https://www.nvidia.com/en-us/networking/["https://www.nvidia.com/en-us/networking/"^]

* NVIDIA AIエンタープライズ
+
https://www.nvidia.com/en-us/data-center/products/ai-enterprise/["https://www.nvidia.com/en-us/data-center/products/ai-enterprise/"^]





== 謝辞

このドキュメントは、NetAppソリューションおよびONTAPエンジニアリングチーム（David Arnette、Olga Kornievskaia、Dustin Fischer、Srikanth Kaligotla、Mohit Kumar、Rajeev Badrinath）の作業です。また、NVIDIAとBasePODエンジニアリングチームの継続的なサポートにも感謝します。
