---
sidebar: sidebar 
permalink: ai/aks-anf_click-through_rate_prediction_use_case_summary.html 
keywords: use case, terabyte click log, random forest, training 
summary: このページでは、分散型または大規模なトレーニングにおける Azure NetApp Files の利点をまとめています。 
---
= クリックスルー率予測ユースケースの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このユースケースは、から公開されているデータセット https://ailab.criteo.com/["Crito AI Lab の略"^]に基づいて http://labs.criteo.com/2013/12/download-terabyte-click-logs/["[ ログ ] をクリックします"^]います。ML プラットフォームとアプリケーションの最近の進歩により、現在は大規模な学習が注目されています。クリックスルー率（ CTR ）は、オンライン広告インプレッション数 100 件あたりの平均クリックスルー数（パーセンテージ）と定義されています。デジタルマーケティング、小売、 E コマース、サービスプロバイダなど、さまざまな業界やユースケースで重要な指標として広く採用されています。CTR を潜在的な顧客トラフィックの重要な指標として使用する例を以下に示します。

* *デジタルマーケティング:*では https://support.google.com/google-ads/answer/2615875?hl=en["Google アナリティクス"^]、CTRを使用して、広告主またはマーチャントのキーワード、広告、および無料リストがどれだけうまく機能しているかを測定できます。クリック率が高いと、ユーザーは広告やリストを便利で関連性の高いものとして見つけることができます。CTRは、キーワードの期待されるCTRにも貢献します。これは、のコンポーネントです https://support.google.com/google-ads/answer/1752122?hl=en["広告ランク"^]。
* *電子商取引：*電子商取引バックエンドには、活用に加えて https://analytics.google.com/analytics/web/provision/#/provision["Google アナリティクス"^]、少なくとも一部の訪問者統計があります。これらの統計情報は一目見すると有用ではないように見えますが、通常は読みやすく、他の情報よりも正確な情報になる可能性があります。このような統計で構成されるファーストパーティデータセットは独占的なものであり、 E コマースの販売者、購買担当者、プラットフォームに最も関連性があります。これらのデータセットは、ベンチマークの設定に使用でき、過去 1 年と過去 1 日の間に結果を比較するために、さらに詳細な分析を行うための時系列を作成します。
* * 小売： * 実店舗の小売業者は、訪問者数と顧客数を CTR に関連付けることができます。お客様の数は、販売時点の履歴から確認できます。小売業者のウェブサイトや広告トラフィックの CTR が、前述の売上につながる可能性があります。ロイヤルティプログラムは、オンライン広告や他の Web サイトからリダイレクトされたお客様が報奨を獲得するために参加する可能性があるため、別のユースケースです。小売業者は、ロイヤルティプログラムを通じて顧客を獲得し、販売履歴から行動を記録することで、さまざまなカテゴリーで消費者の購買行動を予測するだけでなく、クーポンをパーソナライズし、チャーンを減らす推奨システムを構築できます。
* * 通信事業者とインターネット・サービス・プロバイダーは、豊富なデータを提供するファーストパーティのユーザー・テレメトリ・データを使用して、洞察に富んだ AI 、 ML 、分析のユースケースを実現しています。たとえば、携帯電話会社の Web 閲覧のトップレベルのドメイン履歴ログを毎日活用して、既存のモデルを微調整して最新のオーディエンスセグメンテーションを作成したり、顧客の行動を予測したり、リアルタイム広告を配置してオンライン体験を向上させることができます。このようなデータ主導のマーケティングワークフローでは、 CTR はコンバージョンを反映する重要な指標です。


デジタルマーケティングの文脈では、 http://labs.criteo.com/2013/12/download-terabyte-click-logs/["Crito Terabyte のログをクリックします"^]MLプラットフォームとアルゴリズムのスケーラビリティを評価する際の参照データセットです。広告主は、クリックスルーレートを予測することで、広告に対応する可能性が最も高い訪問者を選択し、閲覧履歴を分析し、ユーザーの関心に基づいて最も関連性の高い広告を表示できます。

このテクニカルレポートで紹介する解決策には、次のようなメリットがあります。

* 分散型または大規模なトレーニングにおける Azure NetApp Files の利点
* CUDA 対応のデータ処理（ cDF 、 cuPy など）と ML アルゴリズム（ cuML ）をラピッズで表示
* 分散型トレーニング用 Dask 並列コンピューティングフレームワーク


Rapids AI と Azure NetApp Files をベースに構築されたエンドツーエンドのワークフローでは、ランダムフォレストモデルのトレーニング時間が 2 桁単位で大幅に短縮されたことが示されています。この点は、構造化された表形式データが 45 GB （平均）の実世界のクリックログを毎日処理する場合の従来の Pandas アプローチと比べて大幅に改善されています。これは、約 20 億行を含む DataFrame に相当します。このテクニカルレポートでは、クラスタ環境のセットアップ、フレームワークとライブラリのインストール、データのロードと処理、従来型のトレーニングと分散型のトレーニング、可視化と監視について説明し、重要なエンドツーエンドのランタイム結果を比較します。
