---
sidebar: sidebar 
permalink: ai/cainvidia_executive_summary.html 
keywords: WP-7328, wp7328, 7328, Executive Summary, NVIDIA, Jarvis, 
summary:  
---
= WP-7328 ：『 NetApp Conversational AI Using NVIDIA Jarvis 』
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ネットアップ、 Rick Huang 、 Sung-Han Lin 、 NVIDIA 、 Davide Onofrio

[role="lead"]
NVIDIA DGX システムファミリーは、エンタープライズ AI に特化した世界初の人工知能（ AI ）ベースシステムで構成されます。NetApp AFF ストレージシステムは、卓越したパフォーマンスと業界をリードするハイブリッドクラウドデータ管理機能を提供します。ネットアップと NVIDIA は提携を通じて、 NetApp ONTAP AI リファレンスアーキテクチャを構築しました。このリファレンスアーキテクチャは、 AI と機械学習（ ML ）のワークロード向けのターンキー解決策であり、エンタープライズクラスのパフォーマンス、信頼性、サポートを提供します。

このホワイトペーパーでは、さまざまな業種のさまざまなユースケースに対応した会話型 AI システムを構築するお客様にガイダンスを提供します。これには、 NVIDIA Jarvis を使用したシステムの導入に関する情報が含まれています。テストは NVIDIA DGX ステーションと NetApp AFF A220 ストレージシステムを使用して実施しました。

解決策の対象となるグループは次のとおりです。

* AI 開発のためのソリューションを設計するエンタープライズアーキテクト などの会話型 AI のユースケースに適したモデルとソフトウェア バーチャル・リテール・アシスタント
* データサイエンティストは、言語モデリングを効率的に実現する方法を探しています 能力開発の目標
* テキストデータの保守と処理を担当するデータエンジニア お客様からの質問や会話の記録など
* エグゼクティブや IT の意思決定者、および関心のあるビジネスリーダー 会話型 AI のエクスペリエンスを変革し、最速の時間を実現できます AI への取り組みから市場に投入


link:cainvidia_solution_overview.html["次の手順：解決策の概要"]
