---
sidebar: sidebar 
permalink: ai/hcaios_where_to_find_additional_information.html 
keywords: NetApp Additional Information 
summary:  
---
= 追加情報の検索場所
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


このドキュメントに記載されている情報の詳細については、次のリソースを参照してください。

* Cnvrg.io （ https://cnvrg.io["https://cnvrg.io"^]）：
+
** Cnvrg コア（無償の ML プラットフォーム）
+
https://cnvrg.io/platform/core[]

** Cnvrg のドキュメント
+
https://app.cnvrg.io/docs["https://app.cnvrg.io/docs"^]



* NVIDIA DGX-1 サーバ：
+
** NVIDIA DGX-1 サーバ
+
https://www.nvidia.com/en-us/data-center/dgx-1/[]

** NVIDIA Tesla V100 Tensor コア GPU
+
https://www.nvidia.com/en-us/data-center/tesla-v100/[]

** NVIDIA GPU Cloud （ NGC ）
+
https://www.nvidia.com/en-us/gpu-cloud/[]



* NetApp AFF システム：
+
** AFF データシート
+
https://www.netapp.com/us/media/d-3582.pdf[]

** AFF 向け NetApp FlashAdvantage プログラム
+
https://www.netapp.com/us/media/ds-3733.pdf[]

** ONTAP 9.x のドキュメント
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[]

** NetApp FlexGroup テクニカルレポート
+
https://www.netapp.com/us/media/tr-4557.pdf[]



* コンテナ向けのネットアップの永続的ストレージ：
+
** NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/[]



* NetApp Interoperability Matrix を参照してください
+
** NetApp Interoperability Matrix Tool で確認できます
+
http://support.netapp.com/matrix[]



* ONTAP AI ネットワーク：
+
** Cisco Nexus 3232C スイッチ
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html[]

** Mellanox Spectrum 2000 シリーズスイッチ
+
http://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000[]



* ML フレームワークとツール：
+
** 大理
+
https://github.com/NVIDIA/DALI[]

** TensorFlow ：あらゆる環境に対応するオープンソースの機械学習フレームワーク
+
https://www.tensorflow.org/[]

** Horovod ： Uber が開発したオープンソースの TensorFlow 用分散学習フレームワーク
+
https://eng.uber.com/horovod/[]

** コンテナランタイムエコシステムでの GPU の有効化
+
https://devblogs.nvidia.com/gpu-containers-runtime/[]

** Docker です
+
https://docs.docker.com[]

** Kubernetes
+
https://kubernetes.io/docs/home/[]

** NVIDIA DeepOps のことです
+
https://github.com/NVIDIA/deepops[]

** クビフロー
+
http://www.kubeflow.org/[]

** Jupyter Notebook Server の 2 つのツールを使用
+
http://www.jupyter.org/[]



* データセットとベンチマーク：
+
** NIH 胸部 X 線データセット
+
https://nihcc.app.box.com/v/ChestXray-NIHCC[]

** Xiaosong Wang 、 Yifan Peng 、 Le Lu 、 Zhiyong Lu 、 Mohammadhadi Bagheri 、 ロナルド・サマーズ、 ChestX-Ray8 ：『 Hospital scale Chest X-ray Database and Benchmarks on weakly Supervised Classification and Localization of Common Thorax Diseases 、 IEEE CVR 、 pp3462-3471 、 2017TR-4841-0620



