---
sidebar: sidebar 
permalink: ai/hcaios_kubernetes_deployment.html 
keywords: Kubernetes, Deployment, NVIDIA, DeepOps 
summary:  
---
= Kubernetes の導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NVIDIA DeepOps で Kubernetes クラスタを導入および設定するには、導入ジャンプホストから次のタスクを実行します。

. NVIDIA DeepOps GitHubサイトのの手順に従って、NVIDIA DeepOpsをダウンロードし https://github.com/NVIDIA/deepops/blob/master/docs/getting-started.md["「はじめに」ページ"^]ます。
. NVIDIA DeepOps GitHubサイトのの手順に従って、クラスタにKubernetesを導入し https://github.com/NVIDIA/deepops/blob/master/docs/kubernetes-cluster.md["Kubernetes 導入ガイド"^]ます。



NOTE: DeepOps Kubernetes 環境を使用するには、 Kubernetes マスターノードとワーカーノードがすべて同じユーザである必要があります。

導入に失敗した場合は、での値をfalseに `deepops/config/group_vars/k8s-cluster.yml`変更し `kubectl_localhost`、手順2を繰り返します。 `Copy kubectl binary to ansible host`の値がtrueの場合にのみ実行されるタスクは `kubectl_localhost`、既知のメモリ使用量の問題があるfetch Ansibleモジュールに依存しています。このようなメモリ使用の問題により、原因がタスクを失敗させることがあります。メモリ問題が原因でタスクが失敗した場合は、以降の導入処理は正常に完了しません。

の値をに `false`変更したあとに導入が正常に完了した場合は `kubectl_localhost`、Kubernetesマスターノードから導入ジャンプホストにを手動でコピーする必要があります `kubectl binary`。特定のマスターノード上のの場所を確認する `kubectl binary`には、そのノードでコマンドを直接実行し `which kubectl`ます。
