---
sidebar: sidebar 
permalink: ai/hciai_edge_netapp_h615cmanual_deployment.html 
keywords:  
summary:  
---
= NetApp H615c の設定（手動導入）
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
この解決策では、 NetApp H615c コンピューティングノードが Kubernetes ワーカーノードとして構成されます。推論ワークロードはこれらのノードでホストされます。

コンピューティングノードを導入するには、次のタスクを実行します。

* Ubuntu 18.04.4 LTS をインストールします。
* データアクセスと管理アクセス用のネットワークを設定します。
* Kubernetes 環境用の Ubuntu インスタンスを準備します。




== Ubuntu 18.04.4 LTS をインストールします

H615c コンピューティングノードにオペレーティングシステムをインストールするには、次の高度な手順が必要です。

. から Ubuntu 18.04.4 LTS をダウンロードします http://cdimage.ubuntu.com/ubuntu/releases/18.04/release/["Ubuntu のリリース"^]。
. ブラウザを使用して、 H615c ノードの IPMI に接続して Remote Control を起動します。
. 仮想メディアウィザードを使用して Ubuntu ISO をマッピングし、インストールを開始します。
. プロンプトが表示されたら、 2 つの物理インターフェイスのうちの 1 つを「プライマリネットワークインターフェイス」として選択します。
+
DHCP ソースからの IP が使用可能な場合は割り当てられ、あとで手動 IP 設定に切り替えることができます。OS のインストールが完了すると、ネットワーク構成がボンドベースのセットアップに変更されます。

. ホスト名のあとにドメイン名を入力します。
. ユーザを作成し、パスワードを入力します。
. 必要に応じてディスクをパーティショニングします。
. Software Selection （ソフトウェアの選択）で、「 OpenSSH server 」（ OpenSSH サーバ）を選択し、 Continue （続行）をクリック
. ノードをリブートします。




== データおよび管理アクセス用のネットワークを設定します

Kubernetes ワーカーノードの 2 つの物理ネットワークインターフェイスが管理用とアプリケーション用にボンドインターフェイスと VLAN インターフェイスとして設定され、その上に NFS データトラフィックが作成されます。


NOTE: 推論アプリケーションと関連するコンテナは、接続にアプリケーションネットワークを使用します。

. root 権限を持つユーザとして Ubuntu インスタンスのコンソールに接続し、ターミナルセッションを起動します。
. /etc/netplan` に移動して '01-netcfg.yaml ファイルを開きます
. 環境内の管理、アプリケーション、および NFS トラフィックのネットワーク詳細に基づいて netplan ファイルを更新します。
+
この解決策では、 netplan ファイルの次のテンプレートを使用しました。

+
....
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp59s0f0: #Physical Interface 1
      match:
        macaddress: <<mac_address Physical Interface 1>>
      set-name: enp59s0f0
      mtu: 9000
    enp59s0f1: # Physical Interface 2
      match:
        macaddress: <<mac_address Physical Interface 2>>
      set-name: enp59s0f1
      mtu: 9000
  bonds:
      bond0:
        mtu: 9000
        dhcp4: false
        dhcp6: false
        interfaces: [ enp59s0f0, enp59s0f1 ]
        parameters:
          mode: 802.3ad
          mii-monitor-interval: 100
  vlans:
    vlan.3488: #Management VLAN
      id: 3488
      link: bond0
      dhcp4: false
      addresses: [ipv4_address/subnet]
      routes:
      - to: 0.0.0.0/0
        via: 172.21.232.111
        metric: 100
        table: 3488
      - to: x.x.x.x/x # Additional routes if any
        via: y.y.y.y
        metric: <<metric>>
        table: <<table #>>
      routing-policy:
      - from: 0.0.0.0/0
        priority: 32768#Higher Priority than table 3487
        table: 3488
      nameservers:
        addresses: [nameserver_ip]
        search: [ search_domain ]
      mtu: 1500
    vlan.3487:
      id: 3487
      link: bond0
      dhcp4: false
      addresses: [ipv4_address/subnet]
      routes:
      - to: 0.0.0.0/0
        via: 172.21.231.111
        metric: 101
        table: 3487
      - to: x.x.x.x/x
        via: y.y.y.y
        metric: <<metric>>
        table: <<table #>>
      routing-policy:
      - from: 0.0.0.0/0
        priority: 32769#Lower Priority
        table: 3487
      nameservers:
        addresses: [nameserver_ip]
        search: [ search_domain ]
      mtu: 1500    vlan.3491:
      id: 3491
      link: bond0
      dhcp4: false
      addresses: [ipv4_address/subnet]
      mtu: 9000
....
. ルーティングポリシーのプライオリティがメインテーブルおよびデフォルトテーブルのプライオリティよりも低いことを確認します。
. netplan を適用します。
+
....
sudo netplan -–debug apply
....
. エラーがないことを確認します。
. Network Manager が実行されている場合は、停止して無効にします。
+
....
systemctl stop NetworkManager
systemctl disable NetworkManager
....
. DNS でサーバのホストレコードを追加します。
. VI エディタを開き '/etc/iproute2/RT_tables' に 2 つのエントリを追加します
+
....
#
# reserved values
#
255     local
254     main
253     default
0       unspec
#
# local
#
#1      inr.ruhep
101     3488
102     3487
....
. テーブル番号を、 netplan で使用したものと一致させます。
. VI エディタを開き '/etc/sysctl.conf を開き ' 次のパラメータの値を設定します
+
....
net.ipv4.conf.default.rp_filter=0
net.ipv4.conf.all.rp_filter=0net.ipv4.ip_forward=1
....
. システムをアップデートします。
+
....
sudo apt-get update && sudo apt-get upgrade
....
. システムをリブートします
. 他の Ubuntu インスタンスについて、手順 1 ~ 13 を繰り返します。


link:hciai_edge_setp_the_deployment_jump__and_the_kubernetes_master_node_vms_manual_deployment.html["次のステップ：導入ジャンプのセットアップと Kubernetes マスターノード VM のセットアップ（手動導入）"]
