---
sidebar: sidebar 
permalink: ai/hciai_edge_deploy_the_client_for_triton_inference_server_automated_deployment.html 
keywords:  
summary:  
---
= Triton Inference Server のクライアントの導入（自動導入）
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Triton Inference Server のクライアントを導入するには、次の手順を実行します。

. VI エディタを開き 'Triton クライアントの配備を作成し ' ファイル Triton_client.yaml を呼び出します
+
....
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: triton-client
  name: triton-client
  namespace: triton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-client
      version: v1
  template:
    metadata:
      labels:
        app: triton-client
        version: v1
    spec:
      containers:
      - image: nvcr.io/nvidia/tritonserver:20.07- v1- py3-clientsdk
        imagePullPolicy: IfNotPresent
        name: triton-client
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi
....
. クライアントを展開します。
+
....
kubectl apply -f triton_client.yaml
....


link:hciai_edge_collect_inference_metrics_from_triton_inference_server.html["次に、 Triton Inference Server から推論指標を収集します"]
