---
sidebar: sidebar 
permalink: ai/hciai_edge_virtual_infrastructure_with_automated_deployment.html 
keywords:  
summary:  
---
= NDE を使用して NetApp HCI に VMware 仮想インフラストラクチャを導入する （導入の自動化）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== NDE 導入の前提条件

を参照してください https://library.netapp.com/ecm/ecm_download_file/ECMLP2798490["NetApp HCI 前提条件チェックリスト"^] 導入を開始する前に、 NetApp HCI の要件と推奨事項を確認してください。

. ネットワークおよびスイッチの要件と構成
. 必要な VLAN ID を準備します
. スイッチの設定
. NetApp HCI および VMware の IP アドレス要件
. DNS と時間管理の要件
. 最終準備




== NDE 実行

NDE を実行する前に、すべてのコンポーネントのラックとスタック、ネットワークスイッチの設定、およびすべての前提条件の確認を完了しておく必要があります。NDE ですべてのアドレスを自動的に設定できるようにする場合は、 1 つのストレージノードの管理アドレスに接続して NDE を実行できます。

NDE は、 HCI システムをオンラインにするために次のタスクを実行します。

. 少なくとも 2 つのストレージノードにストレージノード（ NetApp Element ソフトウェア）をインストールします。
. VMware ハイパーバイザーを少なくとも 2 つのコンピューティングノードにインストールします。
. NetApp HCI スタック全体を管理するために VMware vCenter をインストールします。
. ネットアップストレージ管理ノード（ mNode ）と NetApp Monitoring Agent をインストールして設定します。
+

NOTE: この検証では、 NDE を使用してすべてのアドレスが自動的に設定されます。環境で DHCP を設定したり、ストレージノードとコンピューティングノードごとに IP アドレスを手動で割り当てたりすることもできます。これらの手順については、このガイドでは説明していません。

+
前述したように、この検証ではコンピューティングノードにケーブルを 2 本使用する構成を使用します。

+
NDE の詳細な手順については、このドキュメントでは説明していません。

+
基本の NetApp HCI プラットフォームの導入を完了するための詳細な手順については、を参照してください http://docs.netapp.com/hci/topic/com.netapp.doc.hci-ude-180/home.html?cp=3_0["導入ガイド"^]。

. NDE が終了したら、 vCenter にログインし、 NetApp HCI およびアプリケーションで使用する NFS ネットワーク用の分散ポートグループ「 ONTAP Select VDS 01-NFS_Network 」を作成します。

