---
sidebar: sidebar 
permalink: ai/hciai_edge_use_cases.html 
keywords:  
summary:  
---
= ユースケース
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
今日のアプリケーションはどれも AI 主導ではありませんが、 AI の大きなメリットにアクセスできるように進化を続けています。AI の導入をサポートするには、アプリケーションに最適なレベルで機能し、継続的な進化をサポートするために必要なリソースを提供するインフラが必要です。

AI ベースのアプリケーションの場合、エッジの場所はデータの主要なソースとして機能します。利用可能なデータは、一定期間にわたって複数のエッジから収集したトレーニングに使用して、トレーニングデータセットを形成できます。その後、トレーニング済みモデルを、データが収集されたエッジに導入して戻すことで、本番環境のデータを専用の推論プラットフォームに繰り返し転送することなく高速な推論を実現できます。

ネットアップと NVIDIA は、 NVIDIA T4 GPU およびネットアップのクラウド対応ストレージシステムを搭載した NetApp H615c コンピューティングノードを基盤とする NetApp HCI AI 推論解決策を開発および検証しました。NetApp HCI は、あいまいさの範囲に対処し、設計の複雑さを排除し、推測に基づく作業を排除することで、エッジデータセンターでの AI 推論ソリューションの導入を簡易化します。この解決策は、 IT 組織に次のような規範的アーキテクチャを提供します。

* エッジデータセンターで AI 推論を実行できます
* GPU リソースの消費を最適化します
* Kubernetes ベースの推論プラットフォームを提供し、柔軟性と拡張性を実現します
* 設計の複雑さを解消


エッジデータセンターでは、生成ポイントに非常に近い場所でデータを管理および処理します。このように近接することで、効率が向上し、データの処理に関連するレイテンシが低減します。多くの業種では、エッジデータセンターのメリットが認識されており、この分散型アプローチを採用するデータ処理が多用されています。

次の表に、エッジの垂直市場とアプリケーションを示します。

|===
| 垂直（ Vertical ） | アプリケーション 


| 医療 | コンピュータ支援診断は、医療スタッフによる早期疾患検出を支援します 


| 石油およびガス | 遠隔地の生産施設、ビデオ、画像分析の自動検査 


| 航空 | エアトラフィック制御支援とリアルタイムビデオフィード分析 


| メディアとエンターテイメント | 音声 / ビデオコンテンツフィルタリングにより、家族向けのコンテンツを提供します 


| ビジネス分析 | テレビ番組のライブ配信イベントでブランドの外観を分析するためのブランド認知 


| E コマース | 理想的な商人およびを見つけるための供給のスマートなバンドル 倉庫の組み合わせ 


| 小売 | 自動チェックアウトにより、お客様がカートに入れたアイテムを認識します デジタル決済を促進します 


| スマートシティ | 交通の流れを改善し、駐車を最適化し、歩行者と自転車の安全性を高めます 


| 製造 | 品質管理、組み立てラインの監視、欠陥の識別 


| カスタマーサービス | カスタマーサービスの自動化による問い合わせの分析と優先順位付け（電話、 E メール、ソーシャルメディア） 


| 農業 | 肥料や除草剤の使用を最適化するための、農場の運用と活動計画のインテリジェント化 
|===


== 対象読者

解決策の対象となるグループは次のとおりです。

* データサイエンティスト
* IT アーキテクト
* フィールドコンサルタント
* プロフェッショナルサービス
* IT マネージャ
* IT のイノベーションをもたらすインフラを必要としている他のユーザ エッジに配置された堅牢なデータサービスとアプリケーションサービス


link:hciai_edge_architecture.html["次の例は、アーキテクチャです"]
