---
sidebar: sidebar 
permalink: ai/hciai_edge_inferencing.html 
keywords: NVA-1144, NVA1144, 1144, inferencing, AI, artificial intelligence, ML, machine learning, Triton, NVIDIA, Kubernetes, DeepOps, 
summary:  
---
= NVA-1144 ： H615c および NVIDIA T4 を搭載したエッジデータセンターでの NetApp HCI による AI 推論
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ネットアップ、 Arvind Ramakrinan 氏

このドキュメントでは、エッジデータセンターにある人工知能（ AI ）推論ワークロードをホストするための NetApp HCI の設計方法について説明します。この設計は、 NVIDIA T4 GPU 搭載 NetApp HCI コンピューティングノード、 NVIDIA Triton 推論サーバ、 NVIDIA DeepOps を使用して構築された Kubernetes インフラに基づいています。また、この設計では、コアデータセンターとエッジデータセンターの間にデータパイプラインを確立し、データライフサイクルパスを完成させるための実装を示します。

AI と機械学習（ ML ）が主導する最新のアプリケーションは、インターネットの限界を押し上げています。エンドユーザとデバイスは、場所や時間を問わず、最小限のレイテンシでアプリケーション、データ、サービスへのアクセスを要求します。こうしたニーズを満たすために、データセンターはユーザの近くに移動し、パフォーマンスの向上、データ転送量の削減、ユーザ要件を満たすコスト効率の高い方法を実現しています。

AI の文脈では、コアデータセンターは機械学習や分析などの一元的なサービスを提供するプラットフォームであり、エッジデータセンターはリアルタイムの本番データが推論の対象となる場所です。通常、これらのエッジデータセンターはコアデータセンターに接続されます。エンドユーザサービスを提供し、 IoT デバイスで生成されるデータのステージングレイヤとして機能します。このデータには追加の処理が必要であり、時間がかかりすぎて中央のコアに転送できません。このドキュメントでは、 NetApp HCI をベースプラットフォームとして使用する AI 推論のリファレンスアーキテクチャについて説明します。



== お客様にもたらされる価値

NetApp HCI は、この推論の解決策におけるハイパーコンバージド市場での差別化を提供します。これには次のような利点があります。

* 分離型アーキテクチャにより、コンピューティングとストレージを個別に拡張でき、独立した NetApp HCI ストレージノードの仮想化ライセンスコストとパフォーマンスへの負荷が削減されます。
* NetApp Element ストレージでは、各ストレージボリュームに Quality of Service （ QoS ；サービス品質）が提供され、 NetApp HCI のワークロードに対してストレージパフォーマンスが保証されます。したがって、隣接するワークロードは推論パフォーマンスに悪影響を与えません。
* ネットアップのデータファブリックを使用すると、コアデータセンターからエッジデータセンター、クラウドデータセンターにデータをレプリケートできるため、データをアプリケーションのニーズに近い場所に移動できます。
* ネットアップとネットアップの FlexCache ソフトウェアを搭載したデータファブリックを使用すると、 NetApp ONTAP AI をベースにトレーニングされた AI ディープラーニングモデルに、モデルをエクスポートしなくても NetApp HCI からアクセスできます。
* NetApp HCI では、パフォーマンスを低下させることなく、複数のワークロード（仮想マシン（ VM ）またはコンテナベース）を同時に使用して、同じインフラ上で推論サーバをホストできます。
* NetApp HCI は NVIDIA GPU Cloud （ NGC ）として認定されており、 NVIDIA AI によるコンテナ化アプリケーションに対応しています。
* NGC 対応とは、スタックが NVIDIA によって検証され、 AI 専用に構築されていること、 NGC Support Services でエンタープライズサポートを利用できることを意味します。
* ネットアップは幅広い AI ポートフォリオを提供し、エッジからコア、クラウドまで、幅広い AI ユースケースをサポートします。トレーニングと推論のための ONTAP AI 、クラウドでのトレーニングのための Cloud Volumes Service と Azure NetApp Files 、 NetApp HCI でのエッジでの推論などをサポートします。


link:hciai_edge_use_cases.html["次：ユースケース"]
