---
sidebar: sidebar 
permalink: ai/mlrun_where_to_find_additional_information.html 
keywords: NetApp Find Additional Information 
summary:  
---
= 追加情報の検索場所
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
このドキュメントに記載されている情報の詳細については、次のリソースを参照してください。

* NetApp AI コントロールプレーン：
+
** ネットアップの AI コントロールプレーンテクニカルレポートでご確認ください
+
https://["https://www.netapp.com/us/media/tr-4798.pdf"^]



* コンテナ向けのネットアップの永続的ストレージ：
+
** NetApp Trident
+
https://["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]



* ML フレームワークとツール：
+
** TensorFlow ：あらゆる環境に対応するオープンソースの機械学習フレームワーク https://["https://www.tensorflow.org/"^]
** Docker です
+
https://["https://docs.docker.com"^]

** Kubernetes
+
https://["https://kubernetes.io/docs/home/"^]

** クビフロー
+
http://["http://www.kubeflow.org/"^]

** Jupyter Notebook Server の 2 つのツールを使用
+
http://["http://www.jupyter.org/"^]



* Iguazio データサイエンスプラットフォーム
+
** Iguazio Data Science Platform のドキュメント
+
https://["https://www.iguazio.com/docs/"^]

** Nuclio サーバーレス関数
+
https://["https://nuclio.io/"^]

** MLRun オープンソースパイプラインオーケストレーションフレームワーク
+
https://["https://www.iguazio.com/open-source/mlrun/"^]



* NVIDIA DGX-1 システム
+
** NVIDIA DGX-1 システム
+
https://["https://www.nvidia.com/en-us/data-center/dgx-1/"^]

** NVIDIA Tesla V100 Tensor コア GPU
+
https://["https://www.nvidia.com/en-us/data-center/tesla-v100/"^]

** NVIDIA GPU Cloud
+
https://["https://www.nvidia.com/en-us/gpu-cloud/"^]



* NetApp AFF システム
+
** AFF データシート
+
https://["https://www.netapp.com/us/media/ds-3582.pdf"^]

** AFF 向けのネットアップのフラッシュソリューションの利点
+
https://["https://www.netapp.com/us/media/ds-3733.pdf"^]

** ONTAP 9.x のドキュメント
+
https://["https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

** NetApp FlexGroup テクニカルレポート
+
https://["https://www.netapp.com/us/media/tr-4557.pdf"^]



* NetApp ONTAP AI
+
** DGX-1 と Cisco Networking Design Guide による ONTAP AI
+
https://["https://www.netapp.com/us/media/nva-1121-design.pdf"^]

** DGX-1 と Cisco Networking Deployment Guide を使用した ONTAP AI
+
https://["https://www.netapp.com/us/media/nva-1121-deploy.pdf"^]

** DGX-1 と Mellanox のネットワーキング設計ガイドで構成される ONTAP AI
+
https://["https://www.netapp.com/us/media/nva-1138-design.pdf"^]



* ONTAP AI ネットワーク
+
** Cisco Nexus 3232C シリーズスイッチ
+
https://["https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html"^]

** Mellanox Scale-out SN2000 イーサネットスイッチシリーズ
+
https://["https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000"^]




