---
sidebar: sidebar 
permalink: ai/mlrun_where_to_find_additional_information.html 
keywords: NetApp Find Additional Information 
summary:  
---
= 詳細情報の入手方法
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このドキュメントに記載されている情報の詳細については、次のリソースを参照してください。

* コンテナ向けのネットアップの永続的ストレージ：
+
** NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]



* ML フレームワークとツール：
+
** TensorFlow：誰もが利用できるオープンソースの機械学習フレームワーク https://www.tensorflow.org/["https://www.tensorflow.org/"^]
** Docker
+
https://docs.docker.com["https://docs.docker.com"^]

** Kubernetes
+
https://kubernetes.io/docs/home/["https://kubernetes.io/docs/home/"^]

** クビフロー
+
http://www.kubeflow.org/["http://www.kubeflow.org/"^]

** Jupyter Notebook Server の 2 つのツールを使用
+
http://www.jupyter.org/["http://www.jupyter.org/"^]



* Iguazio データサイエンスプラットフォーム
+
** Iguazio Data Science Platform のドキュメント
+
https://www.iguazio.com/docs/["https://www.iguazio.com/docs/"^]

** Nuclio サーバーレス関数
+
https://nuclio.io/["https://nuclio.io/"^]

** MLRun オープンソースパイプラインオーケストレーションフレームワーク
+
https://www.iguazio.com/open-source/mlrun/["https://www.iguazio.com/open-source/mlrun/"^]



* NVIDIA DGX-1システム
+
** NVIDIA DGX-1システム
+
https://www.nvidia.com/en-us/data-center/dgx-1/["https://www.nvidia.com/en-us/data-center/dgx-1/"^]

** NVIDIA Tesla V100 Tensor コア GPU
+
https://www.nvidia.com/en-us/data-center/tesla-v100/["https://www.nvidia.com/en-us/data-center/tesla-v100/"^]

** NVIDIA GPU Cloud
+
https://www.nvidia.com/en-us/gpu-cloud/["https://www.nvidia.com/en-us/gpu-cloud/"^]



* NetApp AFF システム
+
** AFF 向けのネットアップのフラッシュソリューションの利点
+
https://www.netapp.com/pdf.html?item=/media/19894-ds-3733.pdf["https://www.netapp.com/us/media/ds-3733.pdf"^]

** ONTAP 9.xのドキュメント
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

** NetApp FlexGroup テクニカルレポート
+
https://www.netapp.com/pdf.html?item=/media/7337-tr4557pdf.pdf["https://www.netapp.com/us/media/tr-4557.pdf"^]



* NetApp ONTAP AI
+
** DGX-1 と Cisco Networking Design Guide による ONTAP AI
+
https://www.netapp.com/us/media/nva-1121-design.pdf["https://www.netapp.com/us/media/nva-1121-design.pdf"^]

** DGX-1 と Cisco Networking Deployment Guide を使用した ONTAP AI
+
https://www.netapp.com/pdf.html?item=/media/7677-nva1121designpdf.pdf["https://www.netapp.com/us/media/nva-1121-deploy.pdf"^]

** DGX-1 と Mellanox のネットワーキング設計ガイドで構成される ONTAP AI
+
https://www.netapp.com/pdf.html?item=/media/17122-nva1138designpdf.pdf["https://www.netapp.com/us/media/nva-1138-design.pdf"^]



* ONTAP AI ネットワーク
+
** Cisco Nexus 3232C シリーズスイッチ
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html["https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html"^]

** Mellanox Scale-out SN2000 イーサネットスイッチシリーズ
+
https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000["https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000"^]




