---
sidebar: sidebar 
permalink: ai/nvaie_technology_overview.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: NVIDIA AI Enterprise with NetApp and VMware -テクノロジの概要 
---
= テクノロジの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションでは、NetAppとVMwareを使用するNVIDIA AI Enterpriseのテクノロジの概要を説明します。



== NVIDIA AIエンタープライズ

NVIDIA AI Enterpriseは、NVIDIA認定システムを搭載したVMware vSphere上で動作するようにNVIDIAによって最適化、認定、サポートされている、AIとデータ分析のためのエンドツーエンドのクラウドネイティブスイートです。AIワークロードの導入、管理、拡張を簡易化し、最新のハイブリッドクラウド環境で容易に実行できます。



== NVIDIA GPU Cloud （ NGC ）

NVIDIA NGCは、AIソリューションの開発に従事するAI担当者向けに最適化されたGPUソフトウェアのカタログをホスティングします。また、モデルトレーニング用のNVIDIA Baseコマンド、モデルを導入および監視するためのNVIDIA Fleetコマンド、独自のAIソフトウェアに安全にアクセスして管理するためのNGC Private Registryなど、さまざまなAIサービスにアクセスできます。また、NVIDIA AI Enterpriseをご利用のお客様は、NGCポータルからサポートをリクエストできます。



== VMware vSphere

VMware vSphereは、データセンターをCPU、ストレージ、およびネットワークリソースを含む集約コンピューティングインフラストラクチャに変換するVMwareの仮想化プラットフォームです。vSphereは、これらのインフラストラクチャを統合運用環境として管理し、その環境に参加するデータセンターを管理するためのツールを管理者に提供します。

vSphereの中核となるコンポーネントは、ESXiとvCenter Serverの2つです。ESXiは、管理者が仮想マシンおよび仮想アプライアンスを作成および実行する仮想化プラットフォームです。vCenter Serverは、管理者がネットワークおよびプールホストリソースに接続された複数のホストを管理するためのサービスです。



== NetApp ONTAP

ネットアップが提供する最新世代のストレージ管理ソフトウェアONTAP 9を使用すれば、インフラを最新化し、クラウド対応のデータセンターに移行できます。ONTAP は、業界をリードするデータ管理機能を活用して、データの格納場所に関係なく、単一のツールセットでデータの管理と保護を実現します。エッジ、コア、クラウドなど、必要な場所に自由にデータを移動することもできます。ONTAP 9には、データ管理の簡易化、重要なデータの高速化と保護、ハイブリッドクラウドアーキテクチャ全体で次世代インフラ機能を実現する多数の機能が搭載されています。



=== データ管理を簡易化

データ管理は、AIアプリケーションの運用やAI / MLデータセットのトレーニングに適切なリソースを使用できるように、エンタープライズIT運用とデータサイエンティストにとって非常に重要です。以下に記載するネットアップテクノロジに関する追加情報 は、この検証の対象外ですが、導入環境によっては関連性がある場合もあります。

ONTAP データ管理ソフトウェアには、運用を合理化および簡易化し、総運用コストを削減するための次の機能が含まれています。

* インラインデータコンパクション、強化された重複排除：データコンパクションはストレージブロック内の無駄なスペースを削減し、重複排除は実効容量を大幅に増やします。この環境データはローカルに格納され、データはクラウドに階層化されます。
* 最小、最大、アダプティブのQuality of Service（AQoS）。きめ細かいサービス品質（QoS）管理機能により、高度に共有された環境で重要なアプリケーションのパフォーマンスレベルを維持できます。
* NetApp FabricPool の略。Amazon Web Services（AWS）、Azure、NetApp StorageGRID ストレージ解決策 など、パブリッククラウドとプライベートクラウドのストレージオプションへコールドデータを自動的に階層化します。FabricPoolの詳細については、を参照してください https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598：『FabricPool best bests』"^]。




=== データの高速化と保護

ONTAP は、卓越したパフォーマンスとデータ保護を実現し、以下の方法でこれらの機能を拡張します。

* パフォーマンスとレイテンシの低下：ONTAP は、可能なかぎり最小のレイテンシで最高のスループットを提供します。
* データ保護：ONTAP には、組み込みのデータ保護機能が用意されており、すべてのプラットフォームを共通の管理機能で管理できます。
* NetApp Volume Encryption（NVE）：ONTAP は、オンボードと外部キー管理の両方をサポートし、ボリュームレベルでのネイティブな暗号化を実現します。
* マルチテナンシーおよび多要素認証ONTAP を使用すると、最高レベルのセキュリティでインフラリソースを共有できます。




=== 将来のニーズにも対応できるインフラ

ONTAP は、次の機能を備えており、要件が厳しく、絶えず変化するビジネスニーズに対応できます。

* シームレスな拡張とノンストップオペレーションONTAP を使用すると、既存のコントローラとスケールアウトクラスタに無停止で容量を追加できます。NVMe や 32Gb FC などの最新テクノロジへのアップグレードも、コストのかかるデータ移行やシステム停止を行わずに実行できます。
* クラウドへの接続：ONTAPは、ほとんどのクラウドに対応したストレージ管理ソフトウェアで、すべてのパブリッククラウドでSoftware-Defined Storage（ONTAP Select）とクラウドネイティブインスタンス（Google Cloud NetApp Volumes）のオプションを選択できます。
* 新しいアプリケーションとの統合：ONTAP は、既存のエンタープライズアプリケーションをサポートするインフラを使用して、自律走行車、スマートシティ、インダストリー4.0などの次世代プラットフォームやアプリケーション向けにエンタープライズクラスのデータサービスを提供します。




== NetApp DataOps ツールキット

NetApp DataOpsツールキットは、高性能なスケールアウトネットアップストレージを基盤とする開発/トレーニング用ワークスペースと推論サーバの管理を簡易化するPythonベースのツールです。主な機能は次のとおりです。

* ハイパフォーマンスでスケールアウト可能なネットアップストレージを基盤とする、大容量のJupyterLabワークスペースを迅速にプロビジョニングできます。
* エンタープライズクラスのネットアップストレージを基盤とする新しいNVIDIA Triton Inference Serverインスタンスを迅速にプロビジョニング
* 実験的または迅速な反復を可能にするために、大容量のJupyterLabワークスペースをほぼインスタンス化してクローニングします。
* 大容量JupyterLabワークスペースのスナップショットをほぼインスタンスで保存し、バックアップやトレーサビリティ/ベースライン設定を実現します。
* ほぼインスタンス化することなく、大容量でハイパフォーマンスなデータボリュームをプロビジョニング、クローニング、およびSnapshot作成する。

