---
sidebar: sidebar 
permalink: ai/osrunai_netapp_ontap_ai_and_ai_control_plane.html 
keywords:  
summary:  
---
= NetApp ONTAP AI と AI のコントロールプレーン
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NVIDIA DGX システムとネットアップのクラウド対応ストレージシステムを基盤とする NetApp ONTAP AI アーキテクチャこのリファレンスアーキテクチャには、 IT 組織に次のようなメリットがあります。

* 設計の複雑さを解消
* コンピューティングとストレージを個別に拡張できます
* 小規模構成から始めて、シームレスに拡張できます
* さまざまなパフォーマンスとコストポイントに対応する幅広いストレージオプションを提供 NetApp ONTAP AI は、 DGX システムと NetApp AFF A800 ストレージシステムを最先端のネットワーク機能と緊密に統合します。NetApp ONTAP AI システムと DGX システムでは、設計の複雑さと推測に頼らず、 AI 導入を簡易化できます。お客様は小規模構成から始めて、システムを中断なく拡張できます。同時に、エッジ、コア、クラウドにわたってデータをインテリジェントに管理できます。


ネットアップの AI コントロールプレーンは、データサイエンティストとデータエンジニアを対象とした、フルスタックの AI 、 ML 、ディープラーニング（ DL ）のデータと実験管理解決策です。AI の利用が拡大するにつれて、ワークロードの拡張性やデータの可用性など、さまざまな課題が生じています。NetApp AI コントロールプレーンは、データネームスペースの迅速なクローニングなどの機能を通じて、これらの課題に対処します。たとえば、 Git リポジトリをはじめ、トレーサビリティとバージョン管理のためにデータやモデルのベースラインをほぼ瞬時に作成する AI トレーニングワークフローを定義および実装します。NetApp AI コントロールプレーンを使用すると、サイトやリージョン間でデータをシームレスにレプリケートし、 Jupyter Notebook ワークスペースをすばやくプロビジョニングして、大規模なデータセットにアクセスできます。

link:osrunai_run_ai_platform_for_ai_workload_orchestration.html["次のステップ： AI ワークロードのオーケストレーション向けの AI プラットフォームを実行"]。
