---
sidebar: sidebar 
permalink: ai/osrunai_executive_summary.html 
keywords:  
summary:  
---
= TR-4858 ：『 NetApp Orchestration Solution with Run:AI 』
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


ネットアップの Yaron Goldberg 、 Run ： AI 、 David Arnette 、 Sung-Han Lin

[role="lead"]
NetApp AFF ストレージシステムは、卓越したパフォーマンスと業界をリードするハイブリッドクラウドデータ管理機能を提供します。ネットアップと Run ： AI は、 NetApp ONTAP AI 解決策の独自の機能である人工知能（ AI ）と機械学習（ ML ）のワークロードに対応し、エンタープライズクラスのパフォーマンス、信頼性、サポートを提供していることを実証するために提携しました。実行： AI ワークロードの AI オーケストレーションにより、 Kubernetes ベースのスケジュールとリソース利用プラットフォームが追加され、研究者が GPU 利用率を管理、最適化できるようになります。ネットアップ、 NVIDIA 、 Run ： AI の解決策を組み合わせた NVIDIA DGX システムは、エンタープライズ AI ワークロードに特化したインフラスタックを提供します。このテクニカルレポートでは、さまざまなユースケースや業種に対応した会話型 AI システムを構築するお客様向けのガイダンスを提供します。Run の導入に関する情報、 AI と NetApp AFF A800 ストレージシステムが記載されています。 AI イニシアチブを短期間で成功に導くためのリファレンスアーキテクチャとして機能します。

解決策の対象となるグループは次のとおりです。

* AI 開発のためのソリューションを設計するエンタープライズアーキテクト コンテナ化などの Kubernetes ベースのユースケース向けのモデルとソフトウェア マイクロサービス
* データサイエンティストは、効率的なモデルを実現するための効率的な方法を探しています 複数のチームとで構成されるクラスタ環境における開発目標 プロジェクト
* 本番モデルの保守と実行を担当するデータエンジニア
* エグゼクティブや IT の意思決定者、ビジネスリーダー Kubernetes クラスタのリソース利用率を最適化する方法をご確認ください AI 導入の市場投入までの時間を短縮できます

