---
sidebar: sidebar 
permalink: ai/osrunai_software_requirements.html 
keywords:  
summary:  
---
= ソフトウェア要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
この解決策は、 Run ： AI オペレータがインストールされた基本的な Kubernetes 環境で検証されました。KubernetesはDeployment Engineを使用して導入され、本番環境に必要なすべてのコンポーネントが導入されました https://github.com/NVIDIA/deepops["NVIDIA DeepOps のことです"^]。Kubernetes環境との永続的ストレージ統合のためにDeepOpsが自動的に導入され https://netapp.io/persistent-storage-provisioner-for-kubernetes/["NetApp Trident"^]、コンテナがAFF A800ストレージシステムのストレージを利用するようにデフォルトのストレージクラスが作成されました。ONTAP AIでのTrident with Kubernetesの詳細については、を参照してください https://www.netapp.com/us/media/tr-4798.pdf["TR-4798"^]。

 The following table lists the software components that are required to implement the solution as tested.
|===
| ソフトウェア | バージョンまたはその他の情報 


| NetApp ONTAP データ管理ソフトウェア | 9.6p4 


| Cisco NX-OS スイッチのファームウェア | 7.0（3）I6（1） 


| NVIDIA DGX OS | 4.0.4 - Ubuntu 18.04 LTS 


| Kubernetes のバージョン | 1.17 


| Trident のバージョン | 20.04.0 


| AI CLI を実行 | v2.1.13 


| 実行： AI Orchestration Kubernetes Operator バージョン | 1.0.39 


| Docker コンテナプラットフォーム | 18.06.1-CE [e68fc7a] 
|===
Run：AIのその他のソフトウェア要件については、を参照してください https://docs.run.ai/Administrator/Cluster-Setup/Run-AI-GPU-Cluster-Prerequisites/["AI GPU クラスタの前提条件を実行します"^]。
