---
sidebar: sidebar 
permalink: ai/rag_introduction.html 
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: NVIDIA NemoとNetAppを使用したエンタープライズRAG -はじめに 
---
= NetAppを使用したエンタープライズ検索拡張世代（RAG）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ネットアップ、 Mike Oglesby
Sathish Thyagarajan、NetApp

[role="lead"]
ジェネレーティブAIは、エンタープライズ検索エクスペリエンスに変革をもたらしています。これにより、社内のデータユーザは、オンプレミスでもパブリッククラウドでも、どこにあってもデータ資産を検出できるようになります。開発者がジェネレーティブAIを使用して最新のWebアプリケーションを設計するコードを生成するかどうかにかかわらず、 また、現実世界の物理データとモーションデータを使用してアニメーションを作成するために、組織は生成AIと事前にトレーニングされた大規模言語モデル（LLM）を使用して、革新的なAIアプリケーションの構築、新製品機能の設計、エンジニアリングの生産性の向上、顧客体験の強化を行っています。

ただし、生成型AIやLLMだけではビジネスバリューを保証することはできません。具体的なビジネスインパクトを生み出すには、ジェネレーティブAIが厳選されたデータを活用して、質の高いビジネス成果を達成する必要があります。したがって、大企業は、Retrieval Augmented Generation（RAG）と呼ばれる新しい必須フレームワークに目を向けています。このソリューションでは、RAGパイプラインを構築したいと考えている組織向けのアーキテクチャを紹介します。この解決策は、プライベートRAGパイプラインを通じてコンテキスト情報を取得することで、プライベートデータから価値を引き出すのに役立ちます。
