---
sidebar: sidebar 
permalink: ai/rag_nemo_ingest_netapp_data.html 
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: NetAppを使用したエンタープライズRAG - Nemo Retrieverで既存のNetAppデータを取り込み 
---
= Nemo Retrieverによる既存のNetAppデータの取り込み
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NVIDIA Nemo Retrieverの一部であるNemo Embeddingマイクロサービスを使用して、RAGベクターストア/ナレッジベースにデータを取り込むことができます。このセクションでは、既存のNetAppデータソースからデータを取り込むために実行する必要があるタスクについて説明します。



== NVIDIAサンプルチャットボットを使用したデータの取り込み

NVIDIA Enterprise RAG LLM OperatorによってデプロイされたサンプルチャットボットWebアプリケーションを使用して、既存のファイルを取り込むことができます。チャットボットWebアプリケーションを使用して既存のファイルを取り込むプロセスの概要については、以下を参照してください。 link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f718b504-d89b-497e-bd25-b13400d0bfbf&start=57["デモビデオ。"]



== プログラムによるデータの取り込み

NVIDIA Enterprise RAG LLM Operatorによって導入されたRAGクエリサーバを使用して、プログラムによって大量のデータを取り込むことができます。

RAGクエリサーバのAPIは、次のコマンドの出力に示すように、Kubernetesサービスを介して自動的に公開されます。

[source]
----
$ kubectl -n rag-sample get service chain-server
NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
chain-server   ClusterIP   10.233.28.129   <none>        8081/TCP   59d
----
デフォルトのサービスタイプはClusterIPであるため、APIエンドポイントにはKubernetesクラスタ内からしかアクセスできません。サービスタイプは、 `query.service.type` helmパイプライン設定のフィールド（helmpipeline_app.yamlなど）。

APIサーバのswaggerスキーマには、次のURLからアクセスできます。 `<chain_server_url>:<chain_server_api_port>/docs``。
