---
sidebar: sidebar 
permalink: ai/runai-ld_executive_summary.html 
keywords: azure, lane, detection, training, solution, design 
summary: 2019 年 5 月より、 Microsoft は Azure ネイティブのファーストパーティポータルサービスを提供し、 NetApp ONTAP テクノロジを基盤とするエンタープライズ NFS および SMB ファイルサービスを提供しています。 
---
= TR-4886 ：『 Distributed training in Azure ： Lane detection - 解決策 design 』
:allow-uri-read: 


Muneer Ahmad 氏と Verron Martina 氏、ネットアップの Ronen Dar 、 RUN ： AAI

[role="lead"]
2019 年 5 月より、 Microsoft は Azure ネイティブのファーストパーティポータルサービスを提供し、 NetApp ONTAP テクノロジを基盤とするエンタープライズ NFS および SMB ファイルサービスを提供しています。この開発は、 Microsoft とネットアップの戦略的パートナーシップによって推進されており、ワールドクラスの ONTAP データサービスの Azure への対応範囲がさらに拡大しています。

業界をリードするクラウドデータサービスプロバイダであるネットアップは、 AI インフラを仮想化する企業である AI の運用を共同で開始し、 GPU 利用率を最大限に活用して AI の実験を高速化しました。このパートナーシップでは、多数の実験を並行して実行し、データへの高速アクセスを実現し、無限のコンピューティングリソースを活用することで、 AI を加速できます。Run ： AI は、リソースの割り当てを自動化することで GPU 利用率を最大限に高めます。実績のある Azure NetApp Files のアーキテクチャにより、データパイプラインに障害が生じることをなくし、あらゆる実験を最高の速度で実行できます。

ネットアップと RUN ： AI が力を合わせて、お客様に Azure で AI 導入を実現するための将来を見据えたプラットフォームを提供しています。分析やハイパフォーマンスコンピューティング（ HPC ）から自律判断（お客様は必要なときに必要なものだけを購入することで IT 投資を最適化できる）まで、ネットアップと RUN のアライアンスによって、 AI は Azure クラウドでの単一の統合エクスペリエンスを提供します。
