---
sidebar: sidebar 
permalink: ai/vector-database-solution-with-netapp.html 
keywords: vector database, milvus, usecases 
summary: これは、NetAppを使用したベクターデータベース解決策の抽象ページです。 
---
= Vector Database解決策with NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Karthikeyan NagalingamとRodrigo Nascimento、NetApp

[role="lead"]
このドキュメントでは、ネットアップのストレージソリューションを使用して、Milvusなどのベクターデータベースや、オープンソースのPostgreSQL拡張pgvectoの導入と管理について詳しく説明します。NetApp ONTAPとStorageGRIDオブジェクトストレージを使用するためのインフラガイドラインについて詳しく説明し、AWS FSx ONTAPでのMilvusデータベースの適用を検証します。このドキュメントでは、ネットアップのファイルオブジェクトの二重性と、ベクター埋め込みをサポートするベクターデータベースやアプリケーションに対するその有用性について説明しています。また、ベクトルデータベースのバックアップとリストア機能を提供し、データの整合性と可用性を確保する、ネットアップのエンタープライズ管理製品であるSnapCenterの機能を強調しています。このドキュメントでは、ネットアップのハイブリッドクラウド解決策についてさらに詳しく解説し、オンプレミス環境とクラウド環境にわたるデータレプリケーションと保護におけるネットアップの役割について解説します。また、NetApp ONTAP上のベクトルデータベースのパフォーマンス検証に関するインサイトも含まれています。最後に、生成型AIに関する2つの実用的なユースケース、LLMを使用したRAGと、ネットアップ社内のChatAIについて説明します。本ドキュメントは、ベクターデータベースの管理にネットアップのストレージソリューションを活用するための包括的なガイドです。

リファレンスアーキテクチャでは、次の点に重点を置いています。

. link:./vector-database-introduction.html["はじめに"]
. link:./vector-database-solution-overview.html["解決策の概要"]
. link:./vector-database-vector-database.html["ベクターデータベース"]
. link:./vector-database-technology-requirement.html["技術要件"]
. link:./vector-database-deployment-procedure.html["Deployment手順"]
. link:./vector-database-solution-verification-overview.html["解決策検証の概要"]
+
** link:./vector-database-milvus-cluster-setup.html["オンプレミスでのKubernetesを使用したMilvusクラスタセットアップ"]
** link：./vector-database-milvus-with-amazon-fsx ONTAP for NetApp - ONTAP .html [Milvus with Amazon FSx ONTAP for NetApp ONTAP–ファイルとオブジェクトの二重性]
** link:./vector-database-protection-using-snapcenter.html["NetApp SnapCenterを使用したベクターデータベース保護。"]
** link:./vector-database-disaster-recovery-using-netapp-snapmirror.html["NetApp SnapMirrorを使用したディザスタリカバリ"]
** link:./vector-database-performance-validation.html["パフォーマンスの検証"]


. link:./vector-database-instaclustr-with-pgvector.html["PostgreSQLを使用したInstaclustrを使用したベクターデータベース: pgvector"]
. link:./vector-database-use-cases.html["Vectorデータベースのユースケース"]
. link:./vector-database-conclusion.html["まとめ"]
. link:./vector-database-values-yaml.html["付録A：values.yaml"]
. link:./vector-database-prepare-data-netapp-new-py.html["付録B：prepare_data_netapp_new.py"]
. link:./vector-database-verify-data-netapp-py.html["付録C：verify_data_netapp.py"]
. link:./vector-database-docker-compose-xml.html["付録D：docker-compose.yml"]

