---
sidebar: sidebar 
permalink: ai/vector-database-introduction.html 
keywords: vector database 
summary: VECTOR DATABASE解決策for NetAppの概要 
---
= はじめに
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== はじめに

ベクトルデータベースは、大規模言語モデル(LLM)および生成人工知能(AI)における意味探索の複雑さを処理するように設計されている課題に効果的に対処します。従来のデータ管理システムとは異なり、ベクターデータベースは、画像、ビデオ、テキスト、オーディオ、 ラベルやタグではなく、データ自体のコンテンツを使用することで、他の形式の非構造化データを作成できます。

リレーショナルデータベース管理システム（RDBMS）の限界は十分に文書化されています。特に、AIアプリケーションで一般的に使用される高次元データ表現や非構造化データに関する課題が顕著です。RDBMSでは、多くの場合、データをより管理しやすい構造にフラット化するために時間がかかり、エラーが発生しやすいプロセスが必要となり、検索の遅延や非効率化につながります。しかし、ベクターデータベースはこれらの問題を回避するように設計されており、複雑で高次元のデータを管理および検索するためのより効率的で正確な解決策を提供し、AIアプリケーションの進歩を促進します。

本ドキュメントは、現在ベクターデータベースを使用している、または使用を計画しているお客様向けの包括的なガイドであり、NetApp ONTAP、NetApp StorageGRID、Amazon FSxN for NetApp ONTAP、SnapCenterなどのプラットフォームでベクターデータベースを使用するためのベストプラクティスについて詳しく説明しています。ここでは、次のようなさまざまなトピックについて説明します。

* NetAppストレージがNetApp ONTAPおよびStorageGRIDオブジェクトストレージを介して提供する、Milvusなどのベクターデータベースのインフラガイドライン。
* ファイルとオブジェクトストアを使用したAWS FSx for NetApp ONTAPでのMilvusデータベースの検証。
* ネットアップのファイルオブジェクトとオブジェクトの二重性を詳しく検証し、ベクターデータベースやその他のアプリケーションのデータに対するその有用性を実証します。
* ネットアップのデータ保護管理製品SnapCenterは、ベクターデータベースデータのバックアップとリストアの機能を提供します。
* ネットアップのハイブリッドクラウドは、オンプレミス環境とクラウド環境にわたってデータのレプリケーションと保護を提供します。
* NetApp ONTAP上のMilvusやpgvectorなどのベクターデータベースのパフォーマンス検証に関するインサイトを提供します。
* 2つの具体的なユースケース:大規模言語モデル(LLM)を使用したRetrieval Augmented Generation (RAG)とNetApp ITチームのChatAIで、概説された概念と実践の実践例を提供します。

