---
sidebar: sidebar 
permalink: ai/vector-database-conclusion.html 
keywords: vector database, conclusion 
summary: 結論-ベクターデータベース解決策for NetApp 
---
= まとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションでは、ベクターデータベース解決策for NetAppについて説明します。



== まとめ

結論として、このドキュメントでは、NetAppストレージソリューションへのMilvusやpgvectorなどのベクターデータベースの導入と管理の包括的な概要を説明します。NetApp ONTAPとStorageGRIDオブジェクトストレージを活用するためのインフラガイドラインについて話し合い、ファイルとオブジェクトストアを使用してAWS FSx ONTAPのMilvusデータベースを検証しました。

ネットアップのファイルオブジェクトとオブジェクトの二重性を検証し、ベクトルデータベース内のデータだけでなく、他のアプリケーションでもその有用性を実証しました。また、ネットアップのエンタープライズ管理製品であるSnapCenterが、ベクターデータベースデータのバックアップ、リストア、クローニングの機能を提供し、データの整合性と可用性を確保する方法についても説明しました。

また、ネットアップのハイブリッドクラウド解決策がオンプレミス環境とクラウド環境にわたってデータのレプリケーションと保護を提供し、シームレスでセキュアなデータ管理を実現する方法についても詳しく説明しています。NetApp ONTAP上のMilvusやpgvectoなどのベクターデータベースのパフォーマンス検証に関するインサイトを提供し、効率とスケーラビリティに関する貴重な情報を提供しました。

最後に、生成型AIの2つのユースケース、LLMを使用したRAGと、ネットアップ社内向けChatAIについて説明しました。これらの実用的な例は、このドキュメントで概説した概念と実践の実際の用途と利点を強調しています。本ドキュメントは、ベクトルデータベースの管理にネットアップの強力なストレージソリューションを活用したいと考えているすべての人を対象とした包括的なガイドです。



=== 謝辞

このホワイトペーパーをNetAppのお客様やNetAppの分野に役立てるために、以下の寄稿者、フィードバックやコメントを提供してくださった方 々 に心から感謝いたします。

. NetApp ONTAP AI & AnalyticsテクニカルマーケティングエンジニアSathish Thyagarajan氏
. ネットアップテクニカルマーケティングエンジニア、 Mike Oglesby 氏
. NetAppシニアディレクターAj Mahajan氏
. NetAppワークロードパフォーマンスエンジニアリングマネージャーJoe Scott氏
. NetApp製品管理FSxシニアディレクターPuneet Dhawan氏
. NetApp FSx製品チームシニアプロダクトマネージャーYuval Kalderon氏




=== 追加情報の参照先

このドキュメントに記載されている情報の詳細については、以下のドキュメントや Web サイトを参照してください。

* Milvusドキュメント- https://milvus.io/docs/overview.md[]
* Milvusスタンドアロンドキュメント- https://milvus.io/docs/v2.0.x/install_standalone-docker.md[]
* ネットアップの製品マニュアル
https://www.netapp.com/support-and-training/documentation/[]
* instaclustr - link:https://www.instaclustr.com/support/documentation/?_bt=&_bk=&_bm=&_bn=x&_bg=&utm_term=&utm_campaign=&utm_source=adwords&utm_medium=ppc&hsa_acc=1467100120&hsa_cam=20766399079&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAjw26KxBhBDEiwAu6KXtzOZhN0dl0H1smOMcj9nsC0qBQphdMqFR7IrVQqeG2Y4aHWydUMj2BoCdFwQAvD_BwE["Instalclustrノトキユメント"]




=== バージョン履歴

|===


| バージョン | 日付 | ドキュメントのバージョン履歴 


| バージョン 1.0 以降 | 2024年4月 | 初版リリース 
|===