---
sidebar: sidebar 
permalink: ai/wp-dgxc.html 
keywords: NetApp AI, AI, Artificial Intelligence, Data Management, Supercomputing 
summary: NVIDIA DGXクラウドとNetApp Cloud Volumes ONTAP / ANF 
---
= NVIDIA DGXクラウド向けNetAppクラウドデータサービス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Dave Arnette and Sathish Thyagarajan, NetApp

[role="lead"]
ワールドクラスのスーパーコンピューティング向けの高度なデータ管理



== はじめに

このドキュメントでは、NetApp Cloudボリューム/ ANFを使用してNVIDIA DGXクラウドと連携して高度なデータ管理機能を提供し、AIデータパイプラインの運用を最適化および合理化する方法について説明します。



=== パートナーシップ：NVIDIA、Microsoft、NetApp

DGX Cloudを使用すると、お客様はWebブラウザからAIスーパーコンピュータにすぐにアクセスできます。  DGX Cloudを使用すると、大規模なマルチノードAIトレーニングにアクセスして、複雑なモデル設計を高速化できます。企業がオンプレミスインフラへの拡張を選択した場合、NetApp BlueXP™とNVIDIA Base Command Platformを活用して、すべてのリソースを統合してハイブリッドクラウドを実現できます。これにより、開発者は一貫した単一コンソールビューを利用できます。



=== NVIDIA DGXクラウド

~NVIDIAは、ここに追加するコンテンツを提供してくれます



=== Microsoft Azure



=== NetApp BlueXP™



=== Azure NetApp Files®



=== NetAppファイルとオブジェクトの二重性



== アーキテクチャと構成



=== 解決策の設計/概要



=== アーキテクチャ図



=== CVO / ANFの導入

BlueXPの使用



=== ファイルとオブジェクトの二重性の設定

Ansibleで自動化？



=== DGXCへの接続



== まとめ
