---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-powershell-considerations.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: ONTAPベースのサイバーボールトを構成、強化、検証するためのNetApp ONTAPソリューション 
---
= その他の考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
ONTAPベースのサイバーボールトを設計および導入する際には、追加の考慮事項があります。



== 容量サイジングに関する考慮事項

ONTAPサイバーバックアップデスティネーションボリュームに必要なディスクスペースの量はさまざまな要因によって異なりますが、最も重要な要因はソースボリュームのデータの変更率です。デスティネーションボリュームでのバックアップスケジュールとSnapshotスケジュールはどちらもデスティネーションボリュームのディスク使用量に影響し、ソースボリュームでの変更率は一定ではない可能性があります。エンドユーザやアプリケーションの今後の動作の変化に対応するために必要な容量よりも多くのストレージ容量を確保することを推奨します。

ONTAPで保持期間1カ月の関係をサイジングするには、プライマリデータセットのサイズ、データ変更率（日次変更率）、重複排除と圧縮による削減量（該当する場合）など、いくつかの要因に基づいてストレージ要件を計算する必要があります。

ステップバイステップのアプローチは次のとおりです。

最初のステップは、サイバーヴォールトで保護するソースボリュームのサイズを確認することです。これは、サイバーヴォールトデスティネーションに最初にレプリケートされるデータの基本量です。次に、データセットの1日の変更率を見積もります。日 々 変化するデータの割合です。データの動的性について十分に理解しておくことが重要です。

例：

* プライマリデータセットのサイズ= 5TB
* 1日の変更率= 5%（0.05）
* 重複排除と圧縮による削減率= 50%（0.50）


では、計算を見ていきましょう。

* 日単位のデータ変更率を計算します。
+
`Changed data per day = 5000 * 5% = 250GB`

* 30日間の変更データの合計を計算します。
+
`Total changed data in 30 days = 250 GB * 14 = 3.5TB`

* 必要な総ストレージ容量を計算します。
+
`TOTAL = 5TB + 3.5TB = 8.5TB`

* 重複排除と圧縮による削減効果を適用します。
+
`EFFECTIVE = 8.5TB * 50% = 4.25TB`



*ストレージニーズの概要*

* 効率性がない場合：30日間分のサイバーヴォールトデータを保存するには* 8.5TB *が必要です。
* 50%の効率性で、重複排除と圧縮のあとに* 4.25TB *のストレージが必要になります。



NOTE: Snapshotコピーではメタデータによってオーバーヘッドが増える可能性がありますが、通常はこれはわずかです。


NOTE: 1日に複数のバックアップが作成される場合は、1日に作成されるSnapshotコピーの数で計算を調整します。


NOTE: 長期的なデータ増加を考慮して、サイジングが将来のニーズにも対応できるようにします。



== プライマリ/ソースへのパフォーマンスへの影響

データ転送はプル処理であるため、プライマリストレージのパフォーマンスへの影響は、ワークロード、データボリューム、バックアップの頻度によって異なります。ただし、データ転送はデータ保護とバックアップタスクをサイバーヴォールトストレージシステムにオフロードするように設計されているため、プライマリシステム全体のパフォーマンスへの影響は一般に中程度で管理可能です。関係の初期セットアップおよび初回のフルバックアップでは、大量のデータがプライマリシステムからサイバーバックアップシステム（SnapLock Complianceボリューム）に転送されます。これにより、プライマリシステムのネットワークトラフィックやI/O負荷が増加する可能性があります。初回のフルバックアップが完了すると、ONTAPは前回のバックアップ以降に変更されたブロックを追跡して転送するだけで済みます。これにより、最初のレプリケーションに比べてI/O負荷が大幅に軽減されます。差分更新は効率的で、プライマリストレージのパフォーマンスへの影響は最小限です。ボールトプロセスはバックグラウンドで実行されるため、プライマリシステムの本番ワークロードに干渉する可能性が低くなります。

* ストレージシステムに追加の負荷を処理するための十分なリソース（CPU、メモリ、IOPS）があることを確認すると、パフォーマンスへの影響が軽減されます。

