---
sidebar: sidebar 
permalink: automation/automation_introduction.html 
summary: ネットアップのソリューションを自動化すれば、多くの一般的なインフラタスクやアプリケーションタスクの導入、設定、実行を自動化できます。 
keywords: netapp, solutions, automation, ansible, terraform 
---
= NetApp 解決策の自動化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/


[role="lead"]
ネットアップのソリューションを自動化すれば、多くの一般的なインフラタスクやアプリケーションタスクの導入、設定、実行を自動化できます。



== はじめに

ネットアップは、今日のビジネス上の課題に対処するソリューションを提供するにあたり、次の目標を達成したソリューションを提供しています。

* 検証済みの導入と設定手順を提供し、
* 簡単に利用できるソリューションを提供する
* 予測可能な成果をもたらす解決策 環境を提供することは、お客様の企業全体で同じことを繰り返して容易に拡張することができます。


これらの目標を達成するためには、当社のソリューションを通じて提供されるインフラやアプリケーションの導入と構成を自動化によって簡易化することが何よりも重要です。ネットアップは、自動化を通じて解決策 消費を簡易化することに取り組んでいます。

ネットアップのソリューションには、Red Hat Ansible、H橋本、Microsoft PowerShellなどのオープンソースの自動化ツールが採用されており、アプリケーションの導入、クラウドのプロビジョニング、設定管理など、一般的なITタスクを自動化できます。ネットアップのソリューションは、一般に公開されている自動化アーティファクトを活用し、ネットアップが独自に開発した自動化機能を提供することで、解決策 の全体的な導入を簡易化します。

自動化機能が利用可能な場合は、特定の自動化ツールを使用して解決策 や解決策 の手順を自動化するプロセスを、解決策 の資料で順を追って説明します。
