---
sidebar: sidebar 
permalink: automation/setup_awx.html 
summary: ネットアップのソリューションを自動化すれば、多くの一般的なインフラタスクやアプリケーションタスクの導入、設定、実行を自動化できます。 
keywords: netapp, awx, tower, ansible tower, solutions, automation, ansible 
---
= NetApp 解決策の自動化
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/




=== 手順

このセクションでは、ネットアップの自動化ソリューションを使用する環境を準備する AWX/Ansible タワーのパラメータを設定する手順について説明します。

. インベントリを設定します
+
.. [ リソース ] → [ インベントリ ] → [ 追加 ] に移動し、 [ インベントリの追加 ] をクリックします。
.. 名前と組織の詳細を入力し、 [ 保存 ] をクリックします。
.. [ インベントリ ] ページで、作成されたインベントリをクリックします。
.. インベントリ変数がある場合は、その変数を変数フィールドに貼り付けます。
.. 「グループ」サブメニューに移動し、「追加」をクリックします。
.. グループの名前を入力し、グループ変数（ある場合）を貼り付けて、「保存」をクリックします。
.. 次に、作成したグループをクリックし、 [ ホスト ] サブメニューに移動して、 [ 新しいホストの追加 ] をクリックします。
.. ホストのホスト名 / IP アドレスを入力し、ホスト変数（ある場合）を貼り付けて「保存」をクリックします。


. クレデンシャルタイプの作成
+
.. ONTAP 、 Element 、 VMware 、またはその他の HTTPS ベースの転送接続を使用するソリューションでは、ユーザ名とパスワードのエントリに一致するクレデンシャルタイプを設定する必要があります。
.. 「 Administration （管理）」→「 Credential Types （資格情報タイプ）」に移動し、「 Add （追加）」をクリックします。
.. 名前と概要を指定してください
.. 「入力構成」に次の内容を貼り付けます。
+
[source, cli]
----
fields:
- id: username
type: string
label: Username
- id: password
type: string
label: Password
secret: true
----
.. 「インジェクタの設定」に次の内容を貼り付けます。
+
[source, cli]
----
extra_vars:
password: '{{ password }}'
username: '{{ username }}'
----


. クレデンシャルの設定
+
.. 「リソース」→「資格情報」に移動し、「追加」をクリックします。
.. 名前と組織の詳細を入力します
.. 正しいクレデンシャルタイプを選択します。標準の SSH ログインを使用する場合は、「 Machine 」を選択するか、作成したカスタムクレデンシャルタイプを選択します
.. 他の対応する詳細情報を入力し、「保存」をクリックします。


. プロジェクトを構成します
+
.. 「リソース」→「プロジェクト」に移動し、「追加」をクリックします。
.. 名前と組織の詳細を入力します
.. 「 Source Control Credential Type 」で「 Git 」を選択します。
.. ソース管理 URL （または git クローン URL ）を貼り付けます。 特定の解決策に対応します
.. 必要に応じて、 Git URL がアクセス制御されている場合は、対応するクレデンシャルを「 Source Control Credential 」で作成して接続します。
.. 「保存」をクリックします。


. ジョブテンプレートを設定します
+
.. [ リソース ] → [ テンプレート ] → [ 追加 ] に移動して、をクリックします ' ジョブテンプレートの追加 '
.. 名前と概要を入力します
.. ジョブタイプを選択します - 「実行」を選択すると、システムベースが設定されます プレイブックと「チェック」を使用すると、プレイブックが事前にチェックされます 実際にはシステムを設定しないでください
.. このプレイブックに対応するインベントリ、プロジェクト、クレデンシャルを選択します
.. 実行するプレイブックを選択します ジョブテンプレートの一部
.. 通常、変数は実行時に貼り付けられます。そのため、実行時に変数に値を入力するように求めるプロンプトを表示するには、「変数」フィールドに対応する「起動時にプロンプトを表示」チェックボックスにチェックマークを付けてください。
.. 必要に応じてその他の詳細情報を入力し、 [ 保存 ] をクリックします


. ジョブテンプレートを起動しています
+
.. 「リソース」→「テンプレート」に移動
.. 目的のテンプレートをクリックし、 [ 起動 ] をクリックします。
.. 起動時にプロンプトが表示されたら、すべての変数を入力してから、入力します 「 Launch （起動）」をもう一度クリックします



