---
sidebar: sidebar 
permalink: ehc/gcp/gcp-gcve.html 
keywords: NetApp Solutions, hyperscalers, google cloud, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Google Cloud Platform GCVE のネットアップ機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
ネットアップがGoogle Cloud Platform（GCP）Google Cloud Virtualization Engine（GCVE）に提供する機能の詳細については、ネットアップのゲスト接続ストレージデバイスまたはNFSデータストアから、ワークフローの移行、クラウドへの拡張/バースト対応、バックアップ/リストア、ディザスタリカバリに至るまで解説しています。

次のオプションから選択して、目的のコンテンツのセクションに移動します。

* link:#config["GCP での GCVE の設定"]
* link:#datastore["GCVE のネットアップストレージオプション"]
* link:#solutions["ネットアップとVMwareのクラウドソリューション"]




== GCP での GCVE の設定

オンプレミスと同様に、 VM と移行を作成する本番環境に適したクラウドベースの仮想化環境を計画することが重要です。

このセクションでは、 GCVE のセットアップと管理方法、およびネットアップストレージの接続に使用できるオプションとの組み合わせについて説明します。


NOTE: Cloud Volume と Cloud Volumes ONTAP サービスを GCVE に接続する方法としてサポートされているのは、ゲスト内ストレージだけです。

セットアッププロセスは、次の手順に分けることができます。

* GCVE を導入および設定します
* GCVE へのプライベートアクセスを有効にします


詳細を表示します link:gcp-setup.html["GCVEの設定手順"]。



== GCVE のネットアップストレージオプション

ネットアップストレージは、接続されている推測データストアまたはNFSデータストア補助的なGCP GCVE内のいくつかの方法で利用できます。

にアクセスしてください link:ehc-support-configs.html["サポートされているネットアップストレージオプション"] を参照してください。

Google Cloud は、次の構成でネットアップストレージをサポートします。

* Cloud Volumes ONTAP （ CVO ）をゲスト接続ストレージとして活用
* Cloud Volumes Service （ CVS ）をゲスト接続ストレージとして使用できるようになりました
* Cloud Volumes Service （CVS）をNFSデータストア^1^として追加で作成します


詳細を表示します link:gcp-guest.html["GCVEのゲスト接続ストレージオプション"]。

詳細については、をご覧ください link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/["Cloud Volumes Service （CVS）をNFSデータストア^1の補足情報として追加しました"^]。


NOTE: 1- 現在プライベートプレビュー中です



== 解決策のユースケース

ネットアップと VMware のクラウドソリューションを使用すれば、多くのユースケースを Azure AVS で簡単に導入できます。SEケースは、VMwareが定義したクラウド領域ごとに定義されます。

* 保護（ディザスタリカバリとバックアップ/リストアの両方を含む）
* 拡張
* 移動


link:gcp-solutions.html["ネットアップの Google Cloud GCVE ソリューションをご覧ください"]
